fastify.js, test/shorthand-post.js
=> Added content-type checks for POST

fastify.js, test/404s.js
=> Added default route

fastify.js, lib/schemas.json, package.json, test/get.test.js, test/input-validation.js, test/post.test.js, test/put.test.js
As titled, discussion in #12 .
Few links:
- [ajv](https://github.com/epoberezkin/ajv)
- [options](https://github.com/epoberezkin/ajv#options)
- [coercion](https://github.com/epoberezkin/ajv/blob/master/COERCION.md)
=> Body validation

fastify.js, test/get.test.js, test/input-validation.js
As titled.
Discussion in #12 and #13.
=> Querystring validation

fastify.js, test/get.test.js
=> Params validation

README.md, benchmarks/koa.js, example.js, package.json
=> Added a README

README.md, example.js, fastify.js, package.json, plugin.js, test/register.test.js
=> Plugin support

.gitignore, examples/example.js, fastify.js, test/delete.test.js, test/head.test.js, test/input-validation.js, test/patch.test.js
=> added delete, head and patch methods

fastify.js, lib/tier-node.js, lib/validation.js, test/helper.js, test/options.test.js
As titled.
In addition I've added OPTIONS method support (#9) and exposed some internals for future testing.
=> Moved tier-node logic to /lib

README.md, examples/example.js, examples/use-plugin.js, fastify.js, test/404s.test.js, test/delete.test.js, test/get.test.js, test/head.test.js, test/helper.js, test/input-validation.js, test/register.test.js, test/route.test.js
As titled.
I've exposed the `listen` method and the `server` object.
Should we test the `https` server creation?
=> Internal server proposal

lib/tier-node.js, lib/validation.js, package.json, test/internals/tier-node.test.js, test/internals/validation.test.js
As titled.
Any suggestion to improve the test?
=> Test internals

README.md
Added anchor on license it do not work properly.
=> Anchor on license not work

lib/tier-node.js, test/helper.js
=> Fixed content type check in case of charset is present

test/plugin.test.js
=> Add plugin test showing non-scoped plugins

docs/Plugins.md, fastify.js, package.json, test/plugin.test.js
Closes #60 #59 
https://greenkeeper.io/
=> fix(package): update avvio to version 0.6.1

lib/reply.js, test/get.test.js
This fixes the reason why #70 is failing on node v7.
=> Allow an empty payload in send()

docs/ContentTypeParser.md, docs/Routes.md, docs/Server-Methods.md, docs/Validation-And-Serialize.md, examples/example.js, fastify.js, lib/validation.js, test/input-validation.js, test/internals/tier-node.test.js, test/internals/validation.test.js, test/logger.test.js
As titled, see discussion in #76 and #77.
=> Exposed logger instance and renamed payload to body

docs/Getting-Started.md, fastify.js, lib/reply.js, package.json
With this PR [fastify-cli](https://github.com/fastify/fastify-cli) is directly shipped with Fastify, the docs has been updated as well.
=> CLI support

.travis.yml, package.json
The value is deducted from `.travis.yml` file
=> Specify node version

benchmarks/koa.js, fastify.js, test/reply-error.test.js
Do we need to log this?
Feedbacks?
Rel: #102
=> Handle client error

package.json
Closes #113 and https://github.com/fastify/fastify/issues/81
=> fix(package): update find-my-way to version 1.0.1

fastify.js, test/route-prefix.test.js
=> Fix for 129

fastify.js, test/route-prefix.test.js
=> Support prefix without a / at the beginning

fastify.js, test/route-prefix.test.js
=> Fix chaining routes with route prefix

README.md, docs/Plugins-Guide.md
The concept of plugins and how to built them is not immediate for a newcomer, so I tried to wrote and handy guide to help new users to learn how fastify works and how build plugins.
Currently is a work in progress, any feedback will be highly appreciated!
=> Plugins guide

docs/Reply.md, lib/reply.js, test/internals/reply.test.js
As titled :)
```js
fastify.get('/path', (req, reply) => {
reply.redirect('/somewhere')
})
```
=> Redirect support

lib/reply.js, package.json
Double the througput in some JSON-heavy cases.
@darahayes
=> Always flatten the string before sending it out

test/listen.test.js
Added a failing test.
Maybe it could be a bug in avvio as https://github.com/fastify/fastify/pull/168
cc @mcollina
=> Add failing test

docs/Validation-And-Serialize.md, lib/reply.js, lib/validation.js, package.json, test/internals/reply.test.js
Fixes https://github.com/fastify/fastify/issues/178
=> Do not use fast-safe-stringify in Reply.send to avoid perf issues

README.md
Decided to put it right under fastify-multipart since both plugins are related to parsing POST data!
=> Added fastify-formbody plugin to the README

.gitignore, examples/typescript-server.ts, fastify.d.ts, package.json, test/types/index.ts
Linked to #174. This allows TypeScript users to just install fastify and immediately get to work. It is possibly missing some server options so needs a review.
=> add typings.d file for typescript users

package.json
Runs the tests in parallel to make them faster. 
Reduces the time to run the test suite from ~22s to ~7s on my machine.
I'm not sure if we are ready to commit to having the entire test suite run in parallel?
=> Run tests in parallel

docs/Routes.md, fastify.js, test/internals/all.test.js, test/route.test.js, test/routes.test.js
As titled, see https://github.com/fastify/fastify/issues/216.
=> Support for multiple methods with the same handler

docs/Plugins.md, docs/Routes.md
=> Added warning about fastify-plugin and prefix

fastify.d.ts, test/types/index.ts
to match https://github.com/fastify/fastify/commit/c0fdcc368147cc3af8f001a9754122c37aa77ae4  
see https://github.com/fastify/fastify/blob/24c0461c6951a7acab2351c70440cb7ae8b43792/fastify.js#L392-L394
=> Typescript definitions: allow method option to accept an array of methods

docs/Logging.md
Fix https://github.com/fastify/fastify/issues/251 and https://github.com/fastify/fastify/issues/250
=> Remove pino-http. Add genReqId option

test/promises.test.js
See https://github.com/fastify/fastify/issues/249
=> Add one more test to cover when a promise rejects

test/listen.test.js
Fix https://github.com/fastify/fastify/issues/179
I don't know if the check `if (os.platform() !== 'win32')` is correct.
=> Add listen on socket test

docs/Reply.md, lib/reply.js, test/internals/handleRequest.test.js
=> Fixes #263

docs/Routes.md, fastify.js, lib/handleRequest.js, test/async-await.js, test/listen.test.js
=> Fixes for borked release 0.28

docs/Testing.md, fastify.js, test/inject.test.js
The implementation is not so good.
Any advice?
=> Promisify inject if needed

LICENSE, README.md, package.json
As titled.
I've added all of you in the README, as it should be:
@allevo 
@jsumners 
@lmammino 
@evanshortiss 
I hope all your details are correct, please verify and let me know.
=> Fixed credits

fastify.d.ts
s/decorateResponse/decorateRequest/ ;)
=> Fix incorrect type definition

docs/Getting-Started.md
This could be useful for newcomers and to explain the idea that is behind the project, as well as the techniques that we used to optimize the code.
=> Added slides and videos section

examples/example.js, fastify.js, package.json
=> implemented logger: false through abstract-logging

lib/decorate.js, lib/validation.js, test/405.test.js, test/beforeHandler.test.js, test/custom-parser.test.js, test/inject.test.js, test/internals/reply.test.js, test/logger.test.js, test/middleware.test.js, test/output-validation.test.js, test/route.test.js, test/throw.test.js
This PR aims to raise the code coverage (https://github.com/fastify/fastify/issues/289)
Some troubles occurred:
- [those tests](https://github.com/allevo/fastify/blob/e6c2b7882ac8b82c649ab1a7223eb6e45fe7f885/test/middleware.test.js#L484) should be reviewed and fixed before merging: the behaviour is unexpected.
- IMHO [this](https://github.com/allevo/fastify/blob/e6c2b7882ac8b82c649ab1a7223eb6e45fe7f885/test/throw.test.js#L124) and [this](https://github.com/allevo/fastify/blob/e6c2b7882ac8b82c649ab1a7223eb6e45fe7f885/test/throw.test.js#L139) are bugs
- I don't know where (in which test file) we should test [those lines](https://github.com/fastify/fastify/blob/master/lib/handleRequest.js#L48)
- I don't know how to test [this](https://github.com/fastify/fastify/blob/master/lib/handleRequest.j …
=> WIP: Improve coverage

fastify.d.ts
Sorry for second PR, I noticed the problem later and I did not wanted to change the first PR #338
=> Fix TypeScript typing

README.md
I added myself to the contributor's list.
=> Added contributor

docs/Getting-Started.md, docs/Plugins-Guide.md, docs/Plugins.md, docs/Server-Methods.md, package.json, test/async-await.js, test/internals/reply.test.js, test/listen.test.js, test/middleware.test.js, test/plugin.test.js, test/promises.test.js, test/route-prefix.test.js, test/route.test.js
=> Updated tests to support latest avvio

fastify.js, test/decorator.test.js
as title.
Added failing test.
How should we treat this?
=> decorateReply two different fastify instances fails

docs/Plugins.md
Fixed some grammatical errors and reworded some sentences to improve clarity.
=> Further grammatical updates to the docs

docs/Server-Methods.md
Loving this! I just noticed a small type while perusing the docs.
=> Updated typo for url

package.json
This is PR to bump find-my-way due to this bug: https://github.com/fastify/fastify/issues/375
=> bump find-my-way

README.md, docs/Ecosystem.md
Fastify seems like a really cool project so I grabbed a help-wanted issue.
This addresses issue #299. I just sorted based on wether the repo was under the fastify organization or not.
If this isn't what you had in mind let me know and I can re-work it.
=> Sort Plugins and Move to Docs

.gitignore, fastify.d.ts, test/types/index.ts
=> add support for passing https server cert and key

docs/Ecosystem.md
This PR adds the `fastify-session` plugin to the community section of the Ecosystem.md.
=> add fastify-session to Ecosystem.md

README.md, docs/HTTP2.md, examples/http2.js, fastify.js, package.json, test/async-await.test.js, test/http2/http2.test.js, test/http2/plain.js, test/http2/secure-with-fallback.js, test/http2/secure.js
This needs docs and some more work, but it's a start. We don't add any of the http2-specific APIs yet.
Fixes #181
=> Added basic HTTP2 support

lib/reply.js, test/hooks.test.js
=> fix: throws in onSend hook never come back

docs/Hooks.md, fastify.js, lib/handleRequest.js, lib/logger.js, lib/reply.js, test/hooks-async.js, test/hooks.test.js
add support for async hooks as mentioned in #247.
=> add support for async hooks

docs/Ecosystem.md
=> Add fastify-url-data to ecosystem list

docs/Ecosystem.md
=> Add `under-pressure` plugin to ecosystem list

.travis.yml, appveyor.yml
=> Added Node 9 and removed Node 7 from CI

README.md, docs/Benchmarking.md, package.json
- Support running multiple scripts on windows and linux via concurrently package.
- Use https://github.com/StarpTech/branch-comparer to run benchmarks in different branches
__*the frames of the gif were reduced because of file size.__
=> Improve benchmark experience

docs/Server-Methods.md, fastify.d.ts, fastify.js, test/logger.test.js, test/types/index.ts
As titled.
See https://github.com/fastify/fastify/pull/435
=> fastify.logger => fastify.log

test/async-await.js, test/context-config.test.js, test/hooks-async.js, test/hooks.test.js
As titled.
This make the tests more robust, see https://github.com/fastify/fastify/issues/372 if you want an example of why this is needed :P
=> Updated test to avoid mixed use of the Fastify instance

docs/Ecosystem.md
=> Add fastify-caching to ecosystem list

examples/typescript-server.ts, fastify.d.ts, test/types/index.ts
- `req` may be http2.Http2ServerRequest
- `res` may be http2.Http2ServerResponse
- `ServerOptions` may have the `http2` field
=> update type definitions for http2

docs/Benchmarking.md, docs/Hooks.md, docs/Plugins-Guide.md
This pull request is just a collection of couple fixes to the documentations. Thanks :)
=> Docs Fixes

fastify.js, test/404s.test.js
=> Fixes #451

docs/Reply.md, lib/reply.js, package.json, test/promises.test.js
=> Drop send promise support

docs/Ecosystem.md
=> Added fastify-compress to ecosystem list

lib/handleRequest.js, test/delete.test.js
As discussed in https://github.com/fastify/fastify/issues/485
=> Add body parsing support for DELETE method

docs/Hooks.md
As discussed in https://github.com/fastify/fastify/issues/487
=> Describe hooks scoping possibility in the hooks doc description part

fastify.js, test/listen.test.js
=> fastify.listen: Handle missing callback consistently.

docs/Server-Methods.md
Follow-up to #502 CC @mcollina
=> Document fastify.listen without callback.

docs/Getting-Started.md
As titled.
@dolphin278 is this more clear now? :)
=> Fixes #513

fastify.js, lib/pluginUtils.js, test/internals/plugin.test.js, test/plugin.test.js
First implementation of the plugins meta handling, this work is coordinated with https://github.com/fastify/fastify-plugin/pull/13.
Related: https://github.com/fastify/fastify/issues/456
=> WIP: Plugins meta

package.json
=> chore(package): update fastify-plugin to version 0.2.1

docs/Ecosystem.md
Mock Knexjs plugin for fastify added fot testing support
=> Add Fastify KnexJS Mock to Community plugins

docs/Ecosystem.md
Added a Url to a new fastify plugin for Firebase Authentication.
Pls give some feedback about it
=> Add fastify-firebase-auth to the fastify community

lib/bin.js, package.json
* Delete lib/bin.js.
* Remove the "bin" setting from package.json.
* Remove fastify-cli from dependencies in package.json.
Fixes #514
=> Stop depending on fastify-cli.

docs/Reply.md, test/handler-context.test.js
This PR adds documentation to resolve issue #257. A test is also added to guarantee the functionality going forward.
=> Add documenation for Reply.context (issue #257)

docs/Getting-Started.md, docs/Hooks.md, docs/Lifecycle.md, docs/Plugins-Guide.md, docs/Plugins.md, docs/Reply.md, docs/Request.md, docs/Routes.md
=> Convert all double spaces to <br> in the docs

docs/Getting-Started.md, docs/Plugins-Guide.md, docs/Server-Methods.md, fastify.js, package.json, test/ajv-options.test.js, test/decorator.test.js, test/listen.test.js, test/throw.test.js
Fixes https://github.com/fastify/fastify/issues/491
Fixes https://github.com/fastify/fastify/pull/560
=> Start loading the plugins only when calling .ready, .inject or .listen

docs/Decorators.md, docs/Reply.md, docs/Server-Methods.md
Finished the work started in https://github.com/fastify/fastify/pull/558.
=> Updated http error docs

README.md
=> Add myself to collaborators list

fastify.js
Passing around options isn't necessary since they're available on the Fastify instance.
This also prevents people from overriding things like `contentTypeParser` and `middie`, which doesn't seem like something people should be able to do.
=> Clean up route declaration functions

lib/reply.js, test/stream.test.js
- [x ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
=> Avoid 'uncaughtException' if response aborts

fastify.js, test/listen.test.js, test/logger.test.js
As suggested in https://github.com/fastify/fastify-cli/pull/27, I make this PR.
No doc changed: it is not needed
No Benchmark added: the changed code is not the hot one
=> Add log on listen

docs/Ecosystem.md
=> add fastify-bookshelf to community page

test/route-prefix.test.js
Added another check to verify the route prefix encapsulation.
Related: https://github.com/fastify/fastify/pull/615
=> Updated route prefix test

docs/Testing.md, fastify.d.ts, package.json, test/404s.test.js, test/405.test.js, test/500s.test.js, test/async-await.js, test/beforeHandler.test.js, test/error-in-post.js, test/hooks-async.js, test/hooks.test.js, test/inject.test.js, test/internals/all.test.js, test/internals/logger.test.js, test/logger.test.js, test/middleware.test.js, test/reply-error.test.js, test/route-prefix.test.js, test/route.test.js, test/stream.test.js, test/types/index.ts
As titled.
@evanshortiss we should update the types as well, would you mind to help? :)
cc @fastify/fastify 
related: https://github.com/fastify/light-my-request/releases/tag/v2.0.0
=> Update light my request

docs/Lifecycle.md
=> update Lifecycle after #639

docs/Ecosystem.md
=> Add fastify-error-page to docs

docs/Ecosystem.md
Hi, 
I would like to share with the community the new plugin fastify-dynamodb. It provides easy integration with AWS dynamoDB. 
This commit only changes documentation.
=> Add fastify-dynamodb plugin to Ecosystem.md

docs/Getting-Started.md, docs/HTTP2.md, docs/Logging.md, docs/Plugins-Guide.md, docs/Routes.md, docs/TypeScript.md
This makes it clear that `request` is Fastify's Request object and `req` is Node's IncomingRequest object.
=> Update docs to use `request` as the name for the Fastify Request object

docs/Validation-and-Serialization.md
This PR will improve the schema examples to underline where they belong.
=> improve examples

docs/Getting-Started.md
=> Improve Getting-Started docs regarding fastify-plugin

docs/Server-Methods.md, fastify.js, test/pretty-print.test.js
As titled :)
cc @fastify/fastify
=> Expose printRoutes

docs/Ecosystem.md
=> add fastify-blipp to the list of plugins

docs/Ecosystem.md
=> Add fastify-boom to community plugins list

README.md
=> The readme should specify the interface

docs/Getting-Started.md
Small hint to the reader about setting up their server for IPv6 and IPv4.
=> Tip about IPv4/IPv6 in listen()

package.json
=> updated autocannon to 1.0.0

docs/Ecosystem.md
=> Add fastify-oracle plugin to ecosystem

fastify.d.ts, test/types/index.ts
This PR updates the types for the `logger` option to support passing `true` as documented [here](https://www.fastify.io/docs/latest/Logging/)
=> Fix TypeScript types to support `{logger: true}`

fastify.d.ts, test/types/index.ts
=> ts: onResponse hook receive a http.ServerResponse

package.json, test/get.test.js, test/output-validation.test.js
=> Updated fast-json-stringify to 1.0.0.

.github/ISSUE_TEMPLATE.md, README.md
=> Added Fastify help repo

docs/Reply.md
=> Document reply.res

LICENSE
=> updated copyright year to 2018

docs/Ecosystem.md
[`fastify-jwt-authz`](https://github.com/Ethan-Arrowood/fastify-jwt-authz) JWT user scope verifier.
=> Add fastify-jwt-authz to Ecosystem.md

docs/HTTP2.md
=> Added imports for fs and path in http2 examples

docs/Getting-Started.md
=> Added 'Loading order of your plugins' section to Getting-Started.md

docs/Plugins.md
I thought this is not a bloated framework... 🤣
=> Typos: fatify

docs/Ecosystem.md
Plugin to make it easy to work with localhost HTTPS.
It is a wrapper around npm:tls-keygen, which itself is a wrapper around the arcane openssl incantations everyone always has to look up on StackOverflow.
=> fastify-tls-keygen plugin

lib/validation.js
=> Renaming variable

fastify.d.ts, test/types/index.ts
Most of the recently added options were missing and a few typings were incomplete.
@fastify/typescript
=> Add missing TypeScript type definitions

docs/Routes.md, fastify.d.ts, test/types/index.ts
Add `logLevel` and `config` properties.
Add typescript definition too with test
=> Add logLevel and config to Routes.md doc

docs/ContentTypeParser.md, examples/parser.js
=> Add custom content type parser example

fastify.js, lib/ContentTypeParser.js, lib/handleRequest.js, lib/hookRunner.js, lib/reply.js
*First commit: Rename into throwIfAlreadyStarted*
*Second commit: Consistency return statement*
=> Clean code

lib/reply.js
=> Simplify function handleError in reply.js

docs/ContentTypeParser.md
=> Add example code snippet for hasContentTypeParser

docs/Ecosystem.md
=> Add fastify-rob-config to community plugins list

docs/Ecosystem.md
Fixes https://github.com/fastify/fastify/issues/87
=> Added fastify-reply-from and fastify-http-proxy to the ecosystem

docs/Write-Plugin.md
Hi all!
This is the first draft of our suggestions on how build a good plugin for Fastify.
Please review it and write down your suggestions!
I don't want the document to be despotic, but we must be clear that a bad plugin will not be accepted.
Related: https://github.com/fastify/fastify/issues/294
=> Added 'Write-Plugin' documentation

docs/Ecosystem.md
Added [`fastify-circuit-breaker`](https://github.com/fastify/fastify-circuit-breaker) and [`fastify-rate-limit`](https://github.com/fastify/fastify-rate-limit).
=> Updated Ecosystem.md

.travis.yml, appveyor.yml
This makes it much easier to see which tests failed when looking at Travis/Appveyor logs.
=> ci: Improve format of output errors

package.json
=> Update dependencies (fixes #789)

docs/Ecosystem.md
We should remove `fastify-register-timeout` from our list because I don't want to maintain it.
=> Remove fastify-register-timeout add fastify-elasticsearch

docs/Getting-Started.md
~~Remove unnecessary log line from an example since the error handler will end up logging the error. Also `req` was spelled wrong and isn't a variable in the function.~~
Rewrite the handler in the example to be short and concise and to remove an incorrect line.
=> Small doc fix in Getting-Started.md

README.md
=> Updated benchmarks

docs/LTS.md
=> Update LTS release date

docs/Getting-Started.md, docs/Hooks.md, docs/Plugins-Guide.md, docs/Server-Methods.md
=> Minor corrections to documentation

docs/Routes.md, fastify.js, test/hooks.test.js, test/route.test.js, test/throw.test.js
=> Add support for handler in shorthand route options.

README.md
Ref https://github.com/fastify/website/issues/55
=> Added LTS in ToC

package.json, test/404s.test.js, test/405.test.js
=> Update to find my way 1.11.0

test/internals/reply.test.js
=> Add reply serialize test

docs/Ecosystem.md
=> Add fastify-sensible to ecosystem list

fastify.js, test/listen.test.js
This PR will fix https://github.com/fastify/fastify/issues/872
=> Promise error handling in "listen()"

fastify.d.ts, test/types/index.ts
Added content type parsing to TypeScript types.
Fixes #858.
=> Added content type parsing to TypeScript types. [#858]

fastify.d.ts, test/types/index.ts
=> typescript: support logger option as a boolean

test/async-await.js
=> remove and increase timeout

docs/Routes.md
Fix #723 
An error is already logged by https://github.com/fastify/fastify/pull/887
=> [ci skip] update doc

docs/Reply.md, lib/reply.js, test/internals/reply.test.js
=> add .removeHeader()

docs/Decorators.md
Added usage example on updating a decorated property of the Request object.
=> Update decorator docs with example

docs/Routes.md
=> Remove some 'you'

package.json, test/404s.test.js
=> Update light-my-request version

docs/Ecosystem.md
=> Adds fastify-language-parser to community list

lib/handleRequest.js
this pr:
```
$ autocannon -c 100 -d 5 -p 10 localhost:3000
Running 5s test @ http://localhost:3000
100 connections with 10 pipelining factor
Stat         Avg     Stdev   Max
Latency (ms) 3.62    11.76   291.03
Req/Sec      27051.2 1275.73 28229
Bytes/Sec    4.42 MB 233 kB  4.63 MB
135k requests in 5s, 22.2 MB read
```
master:
```
$ autocannon -c 100 -d 5 -p 10 localhost:3000
Running 5s test @ http://localhost:3000
100 connections with 10 pipelining factor
Stat         Avg    Stdev   Max
Latency (ms) 3.78   11.99   250.12
Req/Sec      25912  1670.52 27637
Bytes/Sec    4.3 MB 277 kB  4.53 MB
130k requests in 5s, 21.2 MB read
```
=> avoid creating a promise

docs/Server-Methods.md
=> Documentation of method After

docs/Hooks.md
=> Fix hooks count

package.json, test/shared-schemas.test.js
Just add another test case to cover #922.
cc @BastienAr
=> Test issue #922

fastify.d.ts, test/types/index.ts
Hi there,
Thanks for this project, while I try to use this with typescript, I found there's a missing typescript property definition on request. Here's a simple fix for that.
Thanks,
Vincent
=> [Typescript Definition] fix missing headers property on FastifyRequest

docs/Decorators.md, fastify.d.ts, fastify.js, lib/decorate.js, test/decorator.test.js, test/types/index.ts
=> Add fastify.hasRequestDecorator and fastify.hasReplyDecorator

docs/Ecosystem.md
Title says it all, this PR was requested by @delvedor in https://github.com/fastify/fastify-swagger/pull/75
- [N/A] run `npm run test` and `npm run benchmark`
- [N/A] tests and/or benchmarks are included
=> Added fastify-swaggergen plugin to docs/Ecosystem.md

docs/Factory.md, fastify.js, package.json, test/custom-http-server.test.js
~~This is a working progress, currently the test are not passing because the `uws` API is slightly different from the core http module.~~
We should find a way to create a compatibility layer (eg: enrich the server instance that we are returning) or try do contact the other modules maintainers.
Feedbacks?
Related: https://github.com/fastify/fastify/issues/365
=> WIP: Feature: Custom http server

README.md
As titled. I think this would be very nice to add.
=> Added security badge.

docs/Ecosystem.md
=> Added fastify-basic-auth plugin

test/https/custom-https-server.test.js
One more test case for https://github.com/fastify/fastify/pull/937
=> add custom https server tests

fastify.d.ts, test/types/index.ts
add ts definition for `addContentTypeParser` method.
=> add-content-type-parser-definition

package.json
=> chore(package): update fastify-plugin to version 1.1.3

.github/stale.yml
=> Added 'good first issue' to stale bot

docs/Ecosystem.md
Hi!
This doesn't fix https://github.com/fastify/fastify/issues/147 completely but at least we are able to integrate some OAuth2 providers.
=> Add fastify-oauth2 to Ecosystem

docs/Routes.md, fastify.js, lib/logger.js, package.json, test/versioned-routes.test.js
=>  Added support for versioned routes

docs/Ecosystem.md
Add `fastify-soap-client` plugin to Ecosystem
=> Add fastify-soap-client plugin in ecosystem

test/types/index.ts
See https://github.com/fastify/fastify/pull/986#pullrequestreview-130092388
=> Add type test for '.status()'

lib/decorate.js, test/decorator.test.js
=> Resolve issue #998

README.md
This PR fixes the problems of the documentation website described in https://github.com/fastify/website/issues/61 and https://github.com/fastify/website/issues/62.
Fixes https://github.com/fastify/website/issues/61, Fixes https://github.com/fastify/website/issues/62
=> Add missing documentation links

docs/Ecosystem.md
Related to https://github.com/fastify/fastify-websocket/issues/13
=> Add fastify-wamp-router plugin to docs/Ecosystem.md

test/beforeHandler.test.js
=> Resolves issue #1006

README.md
=> New instructions have been added for use with fastif-cli

test/internals/handleRequest.test.js
add testcase for [lib/request.js](https://github.com/fastify/fastify/blob/master/lib/request.js), mainly test for `Request.id`
=> test: add test case for request.id

package.json
=> Fixed homepage field

lib/logger.js, test/logger.test.js
=> feat: remove `req.id` in serializer

docs/Server-Methods.md
I found some small typos in the Server-Methods.md and fixed them.
=> Fix typos in Server-Methods.md

docs/Plugins-Guide.md
While doing the translation for documentation, we found that this order would be better in Plugins-Guide.md.
=> Change order of Plugins-Guide.md

docs/Ecosystem.md
=> Added fastify-vhost plugin

package.json
=> chore(package): update typescript-eslint-parser to version 18.0.0

docs/Ecosystem.md
As titled.
Related: https://github.com/fastify/fastify/issues/326
=> Added fastify-cors to ecosystem

docs/Ecosystem.md
Request for listing the **k-fastify-gateway** fastify plugin
=> add k-fastify-gateway plugin

docs/Factory.md, fastify.d.ts, fastify.js, lib/logger.js, package.json, test/trust-proxy.test.js
=> Trust proxy

test/trust-proxy.test.js
Confirmed that following branch is covered in coverage results:
https://github.com/fastify/fastify/blob/6bce249e04c60914280b5919efdb4ded6a745925/fastify.js#L220-L222
=> Add test for trust proxy with function

fastify.js
Fixes: https://github.com/fastify/fastify/issues/1099
=> Override address in listen instead of listenPromise

fastify.d.ts
=> Augment types available for https server options

test/trust-proxy.test.js
=> Refactor trust-proxy tests

test/trust-proxy.test.js
Confirmed that the following branch is covered in the coverage results:
https://github.com/fastify/fastify/blob/4bcc1f6508b16258a13b9b219e790ca8fcace7f3/fastify.js#L227-L230
=> Add test for trust proxy with number

test/trust-proxy.test.js
Confirmed that the following branch is covered in coverage results:
https://github.com/fastify/fastify/blob/da897351bf9e395e9777fc912e7bc17f52eae2f6/fastify.js#L231-L235
=> Add test for trust proxy with ip addresses

package.json
Fixes #1115.
@jsumners can you test this?
=> Added eslint-import-resolver-node

package.json, test/404s.test.js, test/bodyLimit.test.js, test/context-config.test.js, test/decorator.test.js, test/handler-context.test.js, test/hooks.test.js, test/input-validation.js, test/internals/reply.test.js, test/logger.test.js, test/route.test.js, test/shared-schemas.test.js, test/trust-proxy.test.js, test/types/index.ts
=> Updated standard to v12.

docs/Ecosystem.md
=> Updated ecosystem doc

.github/ISSUE_TEMPLATE.md
=> Correct typos in Github Issue Template

docs/Logging.md, docs/Server.md, fastify.js, lib/logger.js, lib/reqIdGenFactory.js, test/genReqId.test.js, test/logger.test.js
=> Separate logging and reqid options

fastify.js
=> Request id deprecation warning

test/genReqId.test.js
oops, forgot to update test name
=> Update genReqId test name

docs/Plugins-Guide.md
=> Correct typo in docs/Plugins-Guide.md

README.md
=> Add @cemremengu to contributors

lib/schemas.js, lib/validation.js, test/internals/validation.test.js
=> Complete support for Joi. Added test

docs/Ecosystem.md
=> added fastify-jwt-webapp

lib/contentTypeParser.js, test/internals/contentTypeParser.test.js
The benchmark result is not changed
=> Fix content length on utf8 charset

package.json
Fixes https://github.com/fastify/fastify/issues/629
=> Bumped avvio to 6.0.0.

test/internals/logger.test.js
=> Added unit test for multiple logger destinations

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/regression.md, .github/ISSUE_TEMPLATE/security.md
=> Pretty issue templates

docs/Logging.md
=> doc(logging): fix broken link

docs/Ecosystem.md
Link plugin which allows live babel transformation of JavaScript sources.
https://github.com/cfware/fastify-babel
=> Add `fastify-babel`

docs/Validation-and-Serialization.md
Update validation docs to include information about error handling
=> Update validation docs to include information about error handling

.travis.yml
=> Add additional build scripts for travis

lib/handleRequest.js, lib/reply.js, test/internals/contentTypeParser.test.js, test/internals/handleRequest.test.js, test/throw.test.js
Remove /* eslint-disable no-useless-return */
=> Remove eslint ignore comments

package.json
=> Bump typescript-eslint-parser

docs/Reply.md
Incorrect arguments for `.type` ?
=> Fix typo in README

README.md
Per #1263 . This question has come up multiple times so I think adding a note can be helpful.
=> Add listen notice for GCP

docs/LTS.md
@fastify/fastify please check this out, I've added some more wording to clarify what will be expected from us for v1.
=> clarification on LTS support

docs/Ecosystem.md
Hi all, I created this plugin to have in a quick way an healthcheck route (configurable), and even a script that can be executed to call that route.
Main goal for it is to use these features with Containers; in plugin sources there is a working example using Docker.
Hope it will be useful even to others.
Bye.
=> add fastify-healthcheck to comunity plugins

fastify.js, lib/reply.js
=> fix: some typos

lib/reply.js
=> refactor: remove unnecessary not null check

package.json
=> Backport ajv and autocannon updates

package.json
=> fix(package): update tiny-lru to version 4.0.1

docs/Decorators.md
=> docs(decorators): fix "view" typos

docs/Express-Compatibility.md, docs/Middlewares.md
Closes #1276 
Let me know if we can improve this.
=> Add express middleware compatibility notice

docs/Middlewares.md
cc @dougwilson (thanks I didn't notice!)
=> doc: remove res.end from middleware page

lib/reply.js, test/validation-error-handling.test.js
Fix for issue #1325 : Call onErrorHook if response serialization throw an error
My branch
```
┌─────────┬──────┬──────┬───────┬───────┬─────────┬──────────┬───────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev    │ Max       │
├─────────┼──────┼──────┼───────┼───────┼─────────┼──────────┼───────────┤
│ Latency │ 0 ms │ 0 ms │ 75 ms │ 81 ms │ 6.82 ms │ 21.98 ms │ 352.12 ms │
└─────────┴──────┴──────┴───────┴───────┴─────────┴──────────┴───────────┘
┌───────────┬─────────┬─────────┬────────┬─────────┬─────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%    │ 97.5%   │ Avg     │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼────────┼─────────┼─────────┼─────────┼─────────┤
│ Req/Sec   │ 10111   │ 10111   │ 13383  │ 17567   │ 14242.4 │ 2729.37 │ 10111 …
```
=> Handle response validation error

docs/Ecosystem.md
This PR adds [fastify-gql](https://github.com/mcollina/fastify-gql) to the Fastify ecosystem
=> docs(ecosystem): add fastify-gql

docs/HTTP2.md, fastify.js, lib/errors.js, package.json, test/http2/http2.test.js, test/http2/missing-http2-module.js
This feature spawned from a short discussion in #1335. Will be adding an appropriate unit test to this PR and documentation changes. It will slightly increase the overall code coverage as well.
=> Throw error for improper node js version using http2

lib/reply.js, test/internals/reply.test.js
…ttps://github.com/fastify/fastify/issues/1358)
Fixes: https://github.com/fastify/fastify/issues/1358
=> Fix setting multiple cookies as multiple 'Set-Cookie' headers. (fix #1358)

LICENSE
=> Update copyright year to 2019

docs/Testing.md, fastify.js, lib/reply.js, lib/schemas.js, test/emit-warning.test.js, test/inject.test.js, test/internals/contentTypeParser.test.js, test/internals/reply.test.js, test/route.test.js
Work in progress PR for #1335 
Contributions welcome! I'm also happy to mentor anyone looking to write some tests of their own.
=> [WIP] Improve Code Coverage to 99% or 100%

docs/Hooks.md, docs/Lifecycle.md, fastify.d.ts, fastify.js, lib/handleRequest.js, lib/hooks.js, test/hooks.test.js, test/internals/handleRequest.test.js, test/internals/hooks.test.js, test/types/index.ts
Fixes: https://github.com/fastify/help/issues/37
=> Added preParsing hook.

docs/Ecosystem.md
https://github.com/fastify/fastify-nextjs/pull/50
=> fastify-react->fastify-nextjs

fastify.d.ts, test/types/index.ts
This PR includes work started on #1380 and adds test. Goal of this PR is discussed in #1378 .
Closes #1378
=> Ts routeschema missing type + testing #1378

fastify.d.ts, test/types/index.ts
=> Improve typings with an overload for the close() method, which returns a promise

test/404s.test.js
Add extra test to improve coverage
=> Add test for misplaced callNotFound

lib/validation.js
Helps for coverage + some parts were unused I think
=> Simplify schemaErrorsText builder function

test/router-options.test.js
More tests to bump the coverage
=> Add preParsing tests for router opts

docs/Validation-and-Serialization.md
=> fix document of handle validation error

test/hooks.test.js, test/listen.test.js, test/stream.test.js
Trying to stabilize coveralls so we stay at 100% for good. We already announced it on twitter so can't go back now 😄
=> Add more tests

docs/Validation-and-Serialization.md, lib/schemas.js, lib/validation.js, test/shared-schemas.test.js
Hi, 
this is a backport of PR #1437 for issue #1410
=> Cherry-Pick: fix/addSchema to serialization

docs/Ecosystem.md
Added a link to a plugin i'm currently using on a couple of projects. 
I don't know if it satisfies quality standards, let me know if it's fine.  :)
=> Added link to fastify-google-cloud-storage plugin in doc/Ecosystem

fastify.js, test/http2/closing.js, test/http2/http2.test.js
- [ X] run `npm run test` and `npm run benchmark`
- [X ] tests and/or benchmarks are included
- [ X] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
=> Fix HTTP/2 request while closing

test/http2/closing.js
=> fixed flaky http2 closing test

fastify.js, test/http2/closing.js
=> maybe fixed flaky test

package.json
Adding my details to `package.json`
=> Add email for cemremengu

test/decorator.test.js
This PR is the porting in fastify v2 of a test in the PR #1462
=> test: cover issue #1456

CONTRIBUTING.md
=> Add onboarding section to CONTRIBUTING document

package.json
=> Add self to package.json

docs/LTS.md
=> Updated LTS.md

package.json
=> chore(package): update fast-json-stringify to version 1.11.2

docs/Ecosystem.md
Hi, I would like to add my plugin to the ecosystem
This plugin tries to solve issue #917
=> add fastify-405 plugin

lib/schemas.js, test/shared-schemas.test.js
=> fix: unused shared schema to serializer

README.md, package.json
Hi all, 
I'm really happy to have been invited to join the Fastify collaborators' team 🎉
=> add: @eomm as contributor

lib/validation.js, test/validation-error-handling.test.js
Backport #1513 for issue #1512
=> Cherry pick: fix/schema error text

examples/hooks.js
Tiny addition on hooks examples
Unsure if worth adds also a:
```
// CALL THE GET
// curl http://localhost:3000/
// CALL THE POST
// curl -X POST http://localhost:3000/ -H 'Content-Type: application/json' -d '{"hello": 123}'
```
=> added all the hooks in the example file

docs/Logging.md
Closes #1316 
Add `res` serializer to docs
=> Add res serializer to docs

docs/Ecosystem.md
Update ecosystem (fastify is officially supported by apollo-server since 2.4.2 version)
Close https://github.com/fastify/fastify/pull/1126 and possibly close https://github.com/fastify/fastify/pull/1156 (as far as I can tell `fastify-graphql` repo seems to lack of maintenance)
=> Add apollo-server-fastify to the ecosystem.

fastify.js, lib/contentTypeParser.js, lib/logger.js, lib/server.js, lib/symbols.js, test/http2/missing-http2-module.js, test/internals/logger.test.js
Hello team!
As all of you know, our entry point is a mess! 😱 
We worked really hard during the past year on adding new features and applied bugfixes, and we leave this file organization out in the cold.
This pr aims to start cleaning up this file. I can't do everything in this pr since it will be a massive change, furthermore, some work will be done in conjunction with https://github.com/fastify/fastify/issues/1503.
~~As you can see a test is failing, not sure how to fix it.~~
Related: https://github.com/fastify/fastify/issues/1475
=> Chore: refactor fastify.js

docs/Ecosystem.md
=> Adds fastify-flash to Ecosystem.md

.gitignore
=> chore: ignore tap file

fastify.js, lib/initialConfigValidation.js
Following this PR https://github.com/fastify/fastify/pull/1471.
This is a "raw" implementation of the management of default initialization options discussed here https://github.com/fastify/fastify/pull/1471#issuecomment-471196136.
I am opened to suggestions and I will be glad to proceed to any changes requested.
NB: there was a strange issue with the `caseSensitive` option, when I tried to set the default as a fallback if no `options.caseSensitive` is provided, `test/case-insensitive.test.js` failed 9 tests. So for now I removed the `caseSensitive` fallback and all tests are successfully passing again (I will dig into this strange behavior later).
PS: Sorry for the delay I am very busy since this Monday, but I will try to address any request as fast as I can ^^
=> Init options

.github/tests_checker.yml
With this pr we start testing a new bot, [test checker](https://github.com/infection/tests-checker).
If a pr changes the framework code but it does not contain test, the bot will automatically answer in the pr, requesting to add test.
=> Added test checker configuration

docs/Ecosystem.md
=> add fastify-http-client plugin

fastify.d.ts, test/types/index.ts
- [Y] run `npm run test` and `npm run benchmark`
- [Y] tests and/or benchmarks are included
- [Y] documentation is changed or added
- [Y] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
fixed #1538
=> Type this in RequestHandler

package.json
=> chore(package): update semver to version 6.0.0

lib/initialConfigValidation.js, test/internals/initialConfig.test.js
Fixes: https://github.com/fastify/fastify/issues/1560
=> Fix broken tests

docs/Server.md
=> Fix ignoreTrailingSlash example

docs/Ecosystem.md
=> doc add fastify-schema-constraint to ecosystem

docs/Reply.md
=> TOC added to Reply.md

docs/Server.md, fastify.js, lib/initialConfigValidation.js, lib/reqIdGenFactory.js, test/internals/initialConfig.test.js, test/logger.test.js
=> Resolve issue 1584

README.md, docs/Serverless.md
=> first serverless documentation for AWS Lambda

docs/Validation-and-Serialization.md
Notify our users that schemas should not be dynamic.
=> Warning notice for new Function

.travis.yml
Node6 has reached its life cycle.
=> chore(travis) add 12 & rm 6

docs/Validation-and-Serialization.md, examples/shared-schema.js
=> add: more example on how use the $ref keyword

docs/Server.md
This documents that `fastify.close()` will return a Promise if called without a callback.
=> improve docs of fastify.close()

fastify.d.ts
This adds the `disableRequestLogging` option to the typescript `ServerOptions`.
=> Add typings for disableRequestLogging option

CONTRIBUTING.md, README.md
Follow up of our internal discussion about the reorg.
Once we finalize this document, we should also update the website accordingly.
=> Updated docs to reflect internal reorg

docs/Validation-and-Serialization.md
=> Add links for Ajv i18n and custom errors

docs/Ecosystem.md
Fastify plugin that provides the set of TypeScript decorators 🙌
=> Added `fastify-decorators` to Ecosystem.md

CONTRIBUTING.md
=> offboarding steps

package.json
This update improved the performance of the lib
Closes #1652
=> chore(package): update flatstr to version 1.0.12

README.md
In order to give more visibility and attention on the example repo I would add it in the main readme.
=> add example repo link

fastify.js, test/route-hooks.test.js
=> Emit warning synchronously

.npmignore
=> Add .git folder to NPM ignore

fastify.d.ts, test/types/index.ts
Fixes https://github.com/fastify/fastify/issues/1667
This PR just adds defaults types, if no explicit type is passed.
=> Adds defaults to TS generics definitions

azure-pipelines.yml, build/azure-pipelines-npm-template.yml, build/azure-pipelines-yarn-template.yml
=> Updated azure pipelines configuration (#1639)

docs/Ecosystem.md
=> Add RBAC plugin

docs/Logging.md
=> docs(Logging): Update docs to fix req.body inside logger req

docs/Logging.md
=> docs: fix typos for logging

fastify.d.ts, test/types/index.ts
=> Added case sensitive option to definition file.

docs/Validation-and-Serialization.md, lib/validation.js, test/nullable-validation.test.js
=> allow nullable option for use cases like #1709

docs/Validation-and-Serialization.md
See https://github.com/fastify/help/issues/91
=> Clarify that user-provided data relates to the schemas

docs/Ecosystem.md
=> docs(Ecosystem): Add plugin community fastify-amqp

docs/Ecosystem.md
The package not found more. :cry:
=> docs(Ecosystem): Removed fastify-nuxt community package

README.md
=> docs: move Trivikram to past collaborators

docs/Ecosystem.md
- [ x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
=> docs(Ecosystem): Add plugin community fastify-reverse-routes

docs/Ecosystem.md
=> docs(Ecosystem): Add cls-rtracer community plugin

test/content-length.test.js
=> test: change describe for content-length.test.js

docs/Server.md, fastify.d.ts, fastify.js, lib/route.js, test/close-pipelining.test.js, test/close.test.js, test/http2/closing.js, test/types/index.ts
=> Avoid return 503 after closing fastify

docs/Reply.md
=> change code examples in Reply documentation

docs/Hooks.md
=> docs(Hooks): Fix typo

docs/Ecosystem.md
=> docs(Ecosystem): Add fastify-no-additional-properties community plugin

docs/Plugins.md
According to https://github.com/fastify/fastify/pull/1756 and the context, I changed `next` to `done`.
=> docs(Plugins): Fix typo

docs/Serverless.md
=> docs: simplify serverless usage

test/hooks.test.js
change hooks test cases from `next` to `done`
=> test: change hooks test cases from next to done

docs/Serverless.md
=> Added Google Cloud Run docs

docs/Serverless.md
=> docs(Serverless): add missing punctuation marks

docs/Hooks.md
=> docs(Hooks): Add each Hook to a title

docs/Ecosystem.md
plugin for autogenerate crud route, it's use mongoose model
=> plugin for autogenerate crud route

docs/Ecosystem.md
Hope it matches overall community plugins paradigm. Please check: [fastify-mongoose-api](https://github.com/jeka-kiselyov/fastify-mongoose-api) - Plugin to expose REST API for Mongoose MongoDB connection.
=> Plugin to expose Mongo REST API

docs/Getting-Started.md
- Corrected some simple grammatical mistakes
- Rewrote some passages for improved clarity
- Added `npm install fastify-plugin` in section on *plugins*
=> Improving Getting Started documentation

docs/Server.md, fastify.js, lib/pluginUtils.js, lib/symbols.js, test/plugin.test.js
=> feat - Implement pluginName

README.md
It's been far too long since I've made any meaningful contributions. I think it's time for me to bow out. I'll still try to help out in the `help` repo when I can.
=> Move Nathan Woltman to Past Collaborators

.github/workflows/ci.yml, .github/workflows/package-manager-ci.yml, package.json
=> possible fixes

.github/workflows/package-manager-ci.yml
=> install yarn and pnpm in the host env

docs/Reply.md, docs/Routes.md, lib/reply.js, test/async-await.js, test/internals/reply.test.js, test/promises.test.js
Fixes https://github.com/fastify/fastify/issues/1864
=> Make reply a thenable

README.md, package.json
=> Add SerayaEryn to team list

package.json
Greenkeeper should not update lolex
=> greenkeeper do not update lolex

README.md
=> Add missing fluent schema link

docs/Ecosystem.md
=> Updates fastify-multer repository in ecosystem

.github/workflows/ci.yml, build/azure-pipelines-npm-template.yml, build/azure-pipelines-yarn-template.yml
=> Add Node v13 to CI

docs/Ecosystem.md
=> adds community plugin to ecosystem fastify-https-redirect

docs/Hooks.md, docs/Plugins.md, docs/Routes.md, fastify.d.ts, fastify.js, lib/context.js, lib/route.js, lib/symbols.js, test/hooks.test.js, test/logger.test.js
Ref #1845 
Obs: I do not create a description (on docs) for it yet. Can you help me to explain more this feature?
=> Add log serializer

docs/Ecosystem.md
=> Added fastify-qs plugin

fastify.js, package.json, test/404s.test.js
As titled.
Should we document this somewhere?
Fixes: #1884
=> Handle invalid url components

.github/workflows/ci.yml
=> Update Actions to use latest versions of all OS's

.github/workflows/ci.yml
Inspired from https://github.com/coverallsapp/github-action/issues/13
Should Fix #1870
=> less coverage messages

fastify.d.ts, test/types/index.ts
=> Fix/1932 Add version field to the route options

lib/logger.js, package.json
=> Update abstract-logging to v2

docs/Ecosystem.md
Hi!
I've created this little plugin that installs error handlers capable of returning additional properties in error response and generic error handling.
Hope this helps!
=> Add fastify-errors-properties plugin to Ecosystem

README.md
Original blog post:
https://openjsf.org/blog/2019/11/20/web-framework-fastify-joins-openjs-foundation-as-an-incubating-project/
Congrats everyone!
=> Added note about OpenJS Foundation

docs/Hooks.md
Fixing my mistake on request changes #1956
=> docs(Hooks.md): adjust example onRoute with preSerialization

docs/Hooks.md
=> Fix Docs adjust note about request body null

docs/Ecosystem.md
Added https://github.com/mcollina/fastify-secure-session to community plugins. 
No idea why this wasn't already in the list. Could've sworn it was there already at some point.
=> Added mcollina's plugin "fastify-secure-session" & fixed a typo

docs/Validation-and-Serialization.md
Updated example which show how to make some of query string variables mandatory.
=> Update validation docs

docs/Plugins-Guide.md, docs/Plugins.md
1. fix anchors (error-handling -> esm-support)
1. fix heading level
1. add ESM-support to content
=> doc: fix esm-support anchor

docs/Fluent-Schema.md
Link to fluent-schema repo don't work (see [docs](https://www.fastify.io/docs/latest/Fluent-Schema/)).
=> Docs(Fluent-Schema.md): fix fluent schema repo link

README.md, docs/Recommendations.md
This PR adds a document where we can add best practices and recommendations. To start, I have added a recommendation for issues #1996, https://github.com/fastify/help/issues/127, https://github.com/fastify/help/issues/98 and other issues like them.
=> Add a recommendations doc

docs/Recommendations.md
=> Fix TOC typo in recommendations

docs/TypeScript.md
=> docs(Typescript): typo

docs/Testing.md, package.json
Follow up https://github.com/fastify/light-my-request/pull/72
Updating light my request, we can use two new snippet:
- cookies
- `res.json()`
=> update inject features

LICENSE
=> Update Copyright Year to 2020

docs/Routes.md
Moving the comment to the next line improved the layout of <https://www.fastify.io/docs/latest/Routes/>.
=> Shorten longest line (docs)

test/types/route.test-d.ts, types/reply.d.ts
It covers the issue #2030 for the v3.
=> Add generic parameter for Reply send method

CODE_OF_CONDUCT.md
✔ Adopt the OpenJS Foundation Code of Conduct
✔ Update project CoC reporting methods to include OpenJS Foundation escalation path
Ref: https://github.com/openjs-foundation/project-onboarding/issues/35
=> OpenJS CoC

README.md, docs/Ecosystem.md, docs/Fluent-Schema.md, docs/Hooks.md, docs/Recommendations.md, docs/Routes.md, docs/TypeScript.md
=> Cherrypick from master

README.md
=> Drop azure badge

docs/Ecosystem.md
=> Added fastify-response-validation to ecosystem

docs/Serverless.md
Changes `Fastfiy` to `Fastify`
=> Fixed documentation typo

test/emit-warning.test.js, test/internals/handleRequest.test.js, test/internals/reply.test.js
=> Do not show warnings in tests

docs/Validation-and-Serialization.md
=> add comma to queryStringJsonSchema

package.json
=> chore: greenkeeper ignore semver

package.json, test/register.test.js
Updated, and it still shows some bugs in Avvio.
=> Bumped avvio to 7.0.0-alpha.1

fastify.d.ts, test/types/index.ts
=> Use light-my-request types instead of duplicating typings. fixes #2098

.github/workflows/ci.yml
I  would add these little improvements to the ci script as security check since many user install fastify without running the scripts
=> Improve ci.yml

test/decorator.test.js
We need to change this test because of this issue before fixing avvio/master
Ref https://github.com/mcollina/avvio/issues/99
=> fix test ready-start order

package.json
=> chore(package): update @typescript-eslint/parser to version 2.24.0

test/schema-feature.test.js
Adding more strict checks to verify the correctness of `ValidatorSelector` optimization
https://github.com/fastify/fastify/blob/b9a6a041d1dfc341600abe16f6ec309f0386c402/lib/schema-compilers.js#L6
Ref #2144
=> add more checks for schema compiler pool

docs/Ecosystem.md
=> Add to fastify-qrcode into Ecosystem

docs/Validation-and-Serialization.md, test/schemas.test.js
=> docs: use direct references in the "Schema Resolver" example

docs/Routes.md
(only extra closing parentheses)
=> typo in routes doc

package.json
=> Update fast-json-stringify and avvio

test/types/fastify.test-d.ts, types/instance.d.ts
=> Add missing type for builder-style injection

fastify.d.ts, test/types/index.ts
=> Support builder-style injection

docs/Ecosystem.md
=> docs: add i18next-http-middleware

docs/Ecosystem.md
=> Add fastify-etag to ecosystem

test/types/route.test-d.ts, types/reply.d.ts
=> fix: adds statusCode to FastifyReply type

docs/TypeScript.md
=> update typescript docs to exit node process with 1 in case of error

package.json, test/register.test.js
=> Fixed chainable .register() and added test for it

docs/Migration-Guide-V3.md
=> Add missing breaking change

docs/Serverless.md
Updated serverless docs page as described in fastify/fastify#2211.
=> Fix docs: Zeit Now -> Vercel

docs/Ecosystem.md
There were 2 community plugins in the core plugins list
=> fix core plugins

docs/TypeScript.md
=> doc: Fix error 

fastify.js, test/inject.test.js
=> Fix builder-style injection in v3

docs/Ecosystem.md
=> Add fastify-sse-v2 to community plugins

docs/Recommendations.md
=> Tweak haproxy config for issue #2036

README.md
=> docs: Fix absolute paths on main README.md

docs/Server.md
=> Remove duplicated sections in server options

fastify.js, test/schema-feature.test.js
* updated getSchema() test.
close #2279
=> fix: getSchema() should return schema added in inner/plugin instance

fastify.d.ts, test/types/fastify.test-d.ts
=> TypeScript: onProtoPoisoning typo

test/types/instance.test-d.ts, test/types/schema.test-d.ts, types/instance.d.ts, types/schema.d.ts
=> TypeScript: FastifySchema: add missing 'response'

docs/Ecosystem.md
Add fastify-piscina to the community plugins list
(https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
=> Add fastify-piscina to the community plugins list

docs/Reply.md
=> docs: Fix Reply.md to throw statusCode object

docs/Getting-Started.md
=> Fix spelling mistake

docs/Decorators.md
=> Fix spelling mistake in Decorators.md

docs/Errors.md
=> Fix spelling mistake in Errors.md

docs/Server.md, fastify.js, test/request-error.test.js
=> Bind error handler to instance (v3)

lib/reply.js, test/internals/reply.test.js
PR regarding https://github.com/fastify/fastify/issues/2307.
=> Fix hateoas json support

lib/reply.js, test/internals/reply.test.js
PR regarding https://github.com/fastify/fastify/issues/2307 and https://github.com/fastify/fastify/pull/2309 (2.x).
=> Fix custom JSON support at 3.x

docs/Server.md
I'm submitting a change proposal to documentation in regards to issue #2319 I'm open to suggestions for a better explanatory note if any
=> docs: added note about disableRequestLogging onResponse hook error log

docs/Ecosystem.md
Add https://github.com/fastify/fastify-request-context to the list of official 
fix #2298
=> docs: Add fastify-request-context to the plugin list

docs/Ecosystem.md
=> Add fastify-peekaboo plugin on doc ecosystem

docs/Hooks.md, fastify.js, lib/hooks.js, lib/symbols.js, package.json, test/hooks.on-ready.async.js, test/hooks.on-ready.test.js, test/logger.test.js
Backport of #2166 
Related #2123
=> On ready backport

test/types/hooks.test-d.ts, test/types/instance.test-d.ts, test/types/route.test-d.ts, types/error.d.ts, types/hooks.d.ts, types/instance.d.ts
=> fix: add code to FastifyError typing

docs/Ecosystem.md
=> List fastify-tokenize on the ecosystem doc page

docs/Ecosystem.md
As titled
Ref https://github.com/fastify/help/issues/158
Close https://github.com/fastify/fastify/issues/707
=> add fastify-raw-body to Ecosystem

docs/TypeScript.md
=> Add missing parameter `done` in typescript example

docs/Serverless.md
=> feat(Serverless): Add netlify-lambda guide

docs/Hooks.md
Short links did not work with camel case notation. Source they are leading to is all lower case.
=> Fix short links

docs/Serverless.md
Related PR: #2359 
On #2359 i forgot to add link to headers
=> docs(Serverless): add missing netlify-lambda link

docs/Ecosystem.md
Removed old Google Datastore package that we abandoned, removed our old fastify-firestore plugin in favor of our new fastify-firebase all-in-one plugin. fastify-firebase includes firebase-admin SDK including auth, firestore, storage, machineLearning, and more
=> updated docs/ecosystem

docs/Ecosystem.md
=> add fastify-prettier to ecosystem

package.json, test/async-await.test.js
See https://github.com/fastify/fastify/issues/2374
=> await app must resolve to the app

package.json, test/plugin.test.js
See: https://github.com/fastify/fastify/issues/2406
=> Bump avvio to 7.1.1 and add a regression test

fastify.js, package.json, test/hooks.on-ready.test.js
Fix #2343 
Missing encapsulation checks
=> fix ready returns

README.md
Hello everyone,
My sincere apologies for not being able to contribute for a long time and not communicating this earlier. Moving forward, it is best for me to step aside as Fastify welcomes more active contributors. It was a fantastic experience and I learned a lot from this project so thank you so much for giving me the chance and taking your time.
I hope everyone is doing well in these uncertain times. Stay safe an keep up the great work!
=> Move cemremengu to past contributors

README.md
Now Collaborators list gets fixed order
=> docs(readme): add my name and fix order

lib/request.js
=> Removed warnings introduced in #2418

package.json
=> Add new contributor

fastify.js, lib/pluginOverride.js
Task plugin overload logic out of fastify.js for easier read code.
=> Refactor overload

package.json, test/plugin.test.js
=> Fix broken tests due to fastify-plugin@2.1.0

README.md
=> We have a discord!

CONTRIBUTING.md
=> Added a section on what to do to became a collaborator

test/close-pipelining.test.js
This is a workaround for #2470 but the issue is still there.
=> increase timeout

lib/logger.js, test/logger.test.js
Fixs https://github.com/fastify/fastify/issues/2455
=> support unWritable props in the logger option

.github/workflows/ci.yml
Avoid using unnecessary use of the CI for non used ressources.
EDIT: GHA not working as intended. Working on a fix.
=> ci: avoid unnecessary runs

README.md
fix #2488 
To make this badge works, this procedure need to be done : https://vimeo.com/364220040
=> doc: add discord badge

docs/Plugins-Guide.md, docs/TypeScript.md
This PR follows these discussions:
- https://github.com/fastify/fastify/pull/2480
- https://github.com/fastify/fastify/issues/2404
=> Adds new section that better explains ESM context and TypeScript exports

PROJECT_CHARTER.md
I followed [this template](https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_CHARTER_TEMPLATE.md)
I think we should write down a process on the `Section 4.2: Decision-making, Voting, and/or Elections` since there is not a written standard right now in our CONTRIBUTING.md.
Ref https://github.com/openjs-foundation/project-onboarding/issues/35
=> add PROJECT_CHARTER

PROJECT_CHARTER.md
This PR is the follow up for #2045 and will add the changes after the OJSF feedback 
=> docs: follow up PROJECT_CHARTED

docs/Ecosystem.md
Add fastify-xray to ecosystem.
=> Add fastify-xray to ecosystem

docs/Ecosystem.md
=> docs: added fastify-socket.io to Ecosystem section

CONTRIBUTING.md, GOVERNANCE.md, PROJECT_CHARTER.md, README.md
PR to fix the charter after the feedback https://github.com/openjs-foundation/cross-project-council/issues/617
Notable changes:
- included how to self-apply ( from [CONTRIBUTING.md](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md#i-want-to-be-a-collaborator) )
- "how to became lead maintainers"
Maybe I should improve the description of the plugin's projects per this feedback:
> This looks great, congrats! I bet this is the result of a lot of hard work. I'm new, does the project charter need to be the same across projects?
since we have only this sentence `+ Official plugins for common user requirements`
=> add decision making paragraph

docs/Ecosystem.md
We recently open-sourced our fastify-opentelemetry plugin and thought it might be a useful addition to the Fastify ecosystem.
- #2097 
=> Add fastify-opentelemetry to ecosystem doc.

CODE_OF_CONDUCT.md
=> Fix link to OpenJS Foundation CoC

README.md, package.json
=> Adds Maksim to the core team

README.md
https://github.com/openjs-foundation/cross-project-council/pull/626
=> Growth stage!

docs/Ecosystem.md
=> Add fastify-dynareg to ecosystem doc.

docs/Ecosystem.md
=> add fastify-guard to ecosystem

fastify.js, test/404s.test.js
fixes: #2531 
I don't sure about the documentation of it
=> fix(setNotFoundHandler): return this on function call

lib/request.js
Was stumbling upon improving code coverage and this branch is unreachable:
https://github.com/fastify/fastify/blob/master/lib/request.js#L33
Because of this condition:
https://github.com/fastify/fastify/blob/master/lib/request.js#L37
So it makes sense to replace `.compile(tp || [] )` with `compile(tp)`
=> fix: delete unreachable branch

lib/fourOhFour.js, lib/handleRequest.js, test/url-rewriting.test.js
Increase a little coverage of unit tests.
Ref: #2486 
=> Test coverage increase

test/internals/request.test.js
Add uncovered branch in `internals/request.test.js`
Ref: #2381 
=> test: 100% coverage on lib/request.js

package.json, test/types/fastify.test-d.ts, test/types/hooks.test-d.ts, test/types/instance.test-d.ts, test/types/logger.test-d.ts, test/types/plugin.test-d.ts, test/types/reply.test-d.ts, test/types/request.test-d.ts, test/types/route.test-d.ts, types/.eslintrc.json, types/hooks.d.ts, types/tsconfig.json
fix #2515 
Also added some overrides rules related to test files. Also it's a bit slower now because of `createDefaultProgram` attribute but ain't find a solution yet. ref: https://github.com/typescript-eslint/typescript-eslint/issues/967
=> Bring eslint back

README.md, package.json
As i'm now a contributor, just edited the Readme :)
=> doc: add Zekth as contributor

types/.eslintrc.json
Fixing the eslint config to not pollute the CI with false positives
=> fix: eslint config

docs/TypeScript.md, fastify.d.ts
Refs: https://github.com/fastify/help/issues/251
=> docs: fix TS plugin documentation

docs/Reply.md
fix https://github.com/fastify/fastify/issues/2372
Added some doc to explain the issue of using `Reply.raw`
=> doc: improve reply raw explaination

docs/Decorators.md
=> Improve wording of field decoration documentation

docs/Ecosystem.md, test/listen.test.js
=> Adding test case for handling pipe

test/types/instance.test-d.ts, types/instance.d.ts
refs: #2533 
I'm not sure about the best practices to test the function chaining on tsd. What do you recommend?
=> fix(types): update types to setErrorHandler and setNotFoundHandler

lib/route.js, test/route.test.js
Fixes https://github.com/fastify/fastify/issues/2567
=> Clones opts object on route management

test/types/schema.test-d.ts, types/schema.d.ts
=> fix: FastifySchemaCompiler signature incompatible with AJV

lib/request.js, types/request.d.ts
Following https://github.com/fastify/fastify/issues/2580
Here is a first PR to improve typings. Also encapsulated `id` property as it's not meant to be mutated.
Regarding `raw` do we also want to encapsulate it or not? not sure.
=> Typescript: Improve FastifyRequest typing

docs/Validation-and-Serialization.md
Docs: link points to missing anchor #2588
Fixed broken link
=> Fixed broken link Signed-off-by: Bart Kalanski <bkalanski@gmail.com>

docs/Validation-and-Serialization.md
=> Updated example for queryStringJsonSchema

test/types/instance.test-d.ts, types/instance.d.ts
=> Added ipc types support

test/types/logger.test-d.ts, types/logger.d.ts
=> bug #2578 fix

fastify.js, lib/pluginUtils.js, test/internals/version.test.js
fix the issue introduced with #2605 
=> fix: conditionnal version load

docs/Ecosystem.md
=> Move fastify-csrf to core plugins

lib/errors.js, lib/fourOhFour.js, lib/reply.js, lib/wrapThenable.js
=> fixing for enum definition

CONTRIBUTING.md
This PR fixes a couple of issues in `CONTRIBUTING.md`
* Fix typo
* Use "move to" instead of "move in"
=> CONTRIBUTING.md: improve language

docs/Ecosystem.md
Changed the description due to mercurius not only does caching now, but also many more features.
=> update fastify-gql to mercurius

test/nullable-validation.test.js
Test the 2 possible variants for nullable body:
- type: ['object', 'null']
- type: 'object', nullable: true
See: https://github.com/fastify/fastify/issues/2618.
=> Test nullable body

docs/Ecosystem.md
=> Add `fastify-totp`

docs/Ecosystem.md
👋 Hello everyone
Can I add a suggestion for https://github.com/gquittet/graceful-server?
- Graceful Server is keeping track of all open connections and signaling them that the server is shutting down.
- Graceful Server is listening system events to safely close your API on interruption to avoid to keep opened ghost connections on your data sources.
- It is coming with the Kubernetes liveness and readiness out of the box.
- It support all NodeJS frameworks.
- Very simple to use.
- It is a complete solution.
- It is dependency free.
- It has a KISS code base.
- You can customize what you want.
- It is very lightweight.
- It is in active development.
---
Graceful Server is a free and open-source project (MIT license) and it is used by 2 companies and get more downloads each days.
and the …
=> Add @gquittet/graceful-server to Ecosystem

.dependabot/config.yml
The config update tells dependabot to merge the PRs automatically without requiring an approval (once the CI is green)
Just need to make sure the below config is turned on in dependabot settings page.
=> chore: auto-merge dependabot updates

.dependabot/config.yml, .github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
This PR contains config updates from https://github.com/fastify/fastify/pull/2672 as well as a new workflow that automatically merges dependabot PRs after CI goes green.
=> chore: fix dependabot config

docs/Ecosystem.md
include fastify-casbin and fastify-casbin-rest plugins
=> docs: include casbin plugins

docs/Routes.md, package.json, test/pretty-print.test.js, test/versioned-routes.test.js
=> Added security notice to route versioning docs

fastify.js, test/listen.test.js
https://github.com/fastify/fastify/issues/2381
=> test: add some coverage

docs/Ecosystem.md
=> docs: added link to fastify-postgraphile in ecosystem

.github/workflows/ci.yml
=> chore: use automerge actions

docs/Ecosystem.md
Related to #2619 
Include [fastify-get-head](https://github.com/MetCoder95/fastify-get-head) in `docs/Ecosystem.md`
=> docs: Add fastify-get-head to ecosystem

docs/Ecosystem.md
=> docs: added fastify-envalid to ecosystem

docs/Ecosystem.md
Hello, 
In my company we use Fastify for micorservices and want to run custom functions and check the status of the service (e.g . connection with mongodb, redis). So I created this plugin for exposing a health check route that asserts on those functions. The are some plugins that are similar but don't do the exact same thing, so I think it's worth sharing.
Thanks 
=> Add fastify-custom-healthcheck to ecosystem

docs/Decorators.md
replace `decorareRequest` with `decorateRequest`
=> Fix spelling error

README.md
=> chore: update plugins team

test/types/schema.test-d.ts, types/instance.d.ts, types/route.d.ts, types/schema.d.ts
=> fix: setSerializerCompiler types (#2722)

docs/Ecosystem.md
=> Added fastify-minify

docs/Fluent-Schema.md, lib/schemas.js, package.json, test/fluent-schema.test.js
Related to https://github.com/fastify/fluent-schema/issues/87 
TODO:
- `fluent-json-schema` 2.0 not yet published
=> Rename fluent-schema to fluent-json-schema

README.md
These changes make all commands on the command line look the same, namely `sh`
=> docs(readme): normalize all necessary code snippets to sh

lib/reqIdGenFactory.js
=> Add comment explaining the role of SMI

docs/Ecosystem.md
Hi 👋🏻 , do you think it could be useful to include [this plugin](https://github.com/dnlup/fastify-traps) in the ecosystem?
=> docs(ecosystem): add fastify-traps

docs/Ecosystem.md
=> docs(ecosystem): add fastify-disablecache plugin

SECURITY.md, docs/Middleware.md, docs/Server.md, docs/Write-Plugin.md
A handful of grammar and spelling corrections.
Also includes replacements for recommendations in https://github.com/fastify/fastify/blob/master/docs/Write-Plugin.md:
- Recommended CircleCI or Github Actions over Travis CI for continuous integration due to [Travis CI no longer being free for open source and moving to a trial period plan as of 2020-11-02](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).
- Recommended Dependabot or Snyk over Greenkeeper due to Greenkeeper no longer operating
=> Grammar and spelling corrections in documentation

docs/Ecosystem.md
=> docs(ecosystem): add fastify-autoload to core list

docs/Serverless.md
=> doc(serverless) Fix typo

.github/dependabot.yml
Dependabot can be used to keep GitHub Actions used in `.github/workflows` up to date [as well](https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions).
=> ci(dependabot): auto update github actions

.github/workflows/ci.yml
`flag-name` input param is required to generate coverage in parallel jobs, see [documentation here](https://github.com/coverallsapp/github-action#inputs).
Without this flag enabled parallel jobs do not generate separate coverage reports to then be aggregated into a coverage score, only one report will be generated.
As an example, compare the number of jobs in this [report](https://coveralls.io/builds/36403079 ) of a build of Fastify with a [report](https://coveralls.io/builds/36527508) for a build of one of my repos where the `flag-name` input param has been enabled and the coverage score has been aggregated.
=> ci: define `flag-name` input param for coveralls action

README.md, package.json
=> Adds Ayoub El Khattabi to collaborators list

docs/Ecosystem.md
=> docs(ecosystem): add fastify-nuxtjs plugin

docs/Hooks.md
=> Update docs to include all lifecycle hooks as route level hooks
