docs/TypeScript.md

Fastify automatically converts them to lowercase and the examples don't work as expected.

Convert header names to lowercase

---

README.md

🥳 Let me know if this is amiss!

Add me to the contributors and plugins teams

---

docs/TypeScript.md

fix error
```
docker/src/api on  master [?] is 📦 v1.0.0 via ⬢ v15.3.0 
❯ npx typescript --init
npm ERR! could not determine executable to run
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ethan/.npm/_logs/2021-01-16T00_00_47_925Z-debug.log
docker/src/api on  master [?] is 📦 v1.0.0 via ⬢ v15.3.0 
❯ npx tsc --init
message TS6071: Successfully created a tsconfig.json file.
```

docs: update installation guide for typescript

---

docs/Server.md

fix: Removing genReqId from the doc docs/Server.md

---

docs/Serverless.md

Update serverless Vercel configuration

---

README.md

Use discord vanity URL

---

docs/TypeScript.md

Document use of JSDoc to enable Intellisense.
Part of #2829

Document use of JSDoc to enable Intellisense

---

lib/request.js
package.json
test/internals/request.test.js

Fixes https://github.com/fastify/fastify/issues/2761

Use forked proxy-addr

---

docs/Validation-and-Serialization.md

Ref: https://github.com/fastify/fastify/issues/2841

docs(Validation-and-Serialization): add section about coerceType array

---

docs/TypeScript.md

Use example code recommended by @voxpelli in https://github.com/fastify/fastify/issues/2829#issuecomment-778821727

Update JSDoc TypeScript example

---

docs/Ecosystem.md

Add @coobaha/typed-fastify to Ecosystem.md

---

test/route.test.js

Removed console.log

---

docs/Errors.md

I didn't change this in https://github.com/fastify/fastify/pull/2865 because changing the error code seemed like a breaking change. It turns out, however, that https://github.com/fastify/fastify/pull/2628 already changed the error code, but did not update the documentation. In other words, the currently documented error code is not the code that fastify actually uses. Therefore, this PR is just a documentation fix and not a breaking change by itself.

Fix FST_ERR_PROMISE_NOT_FULFILLED

---

docs/Ecosystem.md

docs: add diagnostics-channel plugin to core list

---

docs/Benchmarking.md
docs/Decorators.md
docs/Encapsulation.md
docs/Getting-Started.md
docs/HTTP2.md
docs/LTS.md
docs/Lifecycle.md
docs/Logging.md
docs/Middleware.md
docs/Migration-Guide-V3.md
docs/Plugins-Guide.md
docs/Plugins.md
docs/Recommendations.md
docs/Serverless.md
docs/Testing.md
docs/Write-Plugin.md

Minor tweaks to the shorter documentation files to increase readability.
Plan on taking a pass at the bigger files at some point.

docs: grammar and sentence structure fixes

---

docs/Ecosystem.md

docs(ecosystem): sort community plugin list alphabetically ascending

---

docs/TypeScript.md

https://github.com/fastify/fastify/issues/2887

Docs: Sample code is invalid in fastify.RequestGenericInterface (TypeScript Docs)

---

docs/Serverless.md

We officially support AWS Lamdba with [aws-lambda-fastify](https://github.com/fastify/aws-lambda-fastify) (which is in the org), and we have some good support for the other environments following this guide.
I've softened the warning text.

Mark serverless environments as supported

---

docs/Ecosystem.md

docs: add fastify-schema-to-typescript to ecosystem

---

lib/route.js

Update on comments inside prepareRoute function

---

docs/Serverless.md

Updated Serverless docs

---

lib/contentTypeParser.js

See
https://github.com/fastify/fastify/issues/2356#issuecomment-675202766
https://github.com/fastify/fastify/discussions/2907

Fix lru require for webpack builds

---

lib/contentTypeParser.js

Added a comment about lru.default

---

test/types/schema.test-d.ts
types/instance.d.ts
types/route.d.ts
types/schema.d.ts

fix: adjust schema compiler type

---

docs/Style-Guide.md

Fixes some minor issue i missed, and one i caused back in #2873 😠 

docs(style-guide): minor fixes

---

README.md

chore: link badges

---

.github/labeler.yml

chore: auto plugins label

---

CONTRIBUTING.md
docs/Migration-Guide-V3.md
docs/Server.md
docs/Style-Guide.md
fastify.js

Minor improvements to docs and a comment

---

README.md

chore(readme): add @Fdawgs to plugins team list

---

CONTRIBUTING.md

Also replaced reference to Greenkeeper (RIP) with Dependabot

docs(contributing): minor sentence restructuring to increase readability

---

CONTRIBUTING.md

docs(contributing): clarify sort order

---

docs/TypeScript.md

I added some docs to the TypeScript section.
I used the module json-schema-to-ts in sometimes and found it also helpful in combination with fastify.
Perhaps this is also a first step into making inline schema on routes possible.

docs: added Typescript docs for json-schema-to-ts

---

docs/Ecosystem.md

docs(ecosystem): add a few community plugins

---

docs/Logging.md

works: https://www.fastify.io/docs/latest/Server/#genreqid
doesn't works: https://www.fastify.io/docs/latest/Server/#gen-request-id

docs: fix link

---

docs/HTTP2.md

Minor typo fix

---

docs/Ecosystem.md

Added two of my fastify plugins to community

docs(ecosystem): add nstats and fastify-good-sessions to community plugins

---

test/route.test.js

Add test to assert that route option `onSend` accepts both a function directly OR an array of functions.
Raises coverage of [headRoute.js](lib/headRoute.js) to 100%.

Test: route onSend accepts function or array of functions

---

.github/labeler.yml

chore: auto label test

---

lib/errors.js
test/hooks-async.test.js
test/hooks.test.js

Fix error message for FST_ERR_SEND_UNDEFINED_ERR

---

test/internals/handleRequest.test.js
test/schema-special-usage.test.js

test: fix typos in test messages

---

docs/Hooks.md

Fixes little typo in the Hooks Docs

fix typo in comment

---

lib/reply.js
package.json

dropped flatstrt

---

docs/Ecosystem.md

feat(plugins): community plugin oas-fastify

---

.github/workflows/ci.yml
.github/workflows/package-manager-ci.yml

style(ci): use shorter syntax for node matrix

---

README.md

Add white outline to a fastify logo so it's visible in the dark mode. Should be merged after https://github.com/fastify/graphics/pull/8
Demo:
https://github.com/laSinteZ/fastify
https://www.npmjs.com/package/lasintez-fastify-but-i-just-test-readme

Use outlined logo, visible at dark

---

docs/LTS.md

See [supported-runner-and-hardware-resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), current CI workflows are using `macos-latest`, `ubuntu-latest`, and `windows-latest`.

docs(lts): update list of ci operating systems

---

docs/Benchmarking.md
docs/ContentTypeParser.md
docs/Decorators.md
docs/Ecosystem.md
docs/Encapsulation.md
docs/Errors.md
docs/Fluent-Schema.md
docs/Getting-Started.md
docs/HTTP2.md
docs/Hooks.md
docs/LTS.md
docs/Lifecycle.md
docs/Logging.md
docs/Middleware.md
docs/Migration-Guide-V3.md
docs/Plugins-Guide.md
docs/Plugins.md
docs/Recommendations.md
docs/Reply.md
docs/Routes.md
docs/Server.md
docs/Serverless.md
docs/Style-Guide.md
docs/Testing.md
docs/Validation-and-Serialization.md
docs/Write-Plugin.md

This is a second pass on some of the shorter documents (that were updated in https://github.com/fastify/fastify/pull/2871), and a first pass on the larger documents.
Hit every one apart from the TypeScript one as that one is.... long.

docs: grammar, spelling, and readability fixes

---

.github/workflows/package-manager-ci.yml
docs/LTS.md

`ubuntu-16.04` will be removed as a runner this year: [see GitHub Blog here](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/).

ci(package-manager-ci): update ubuntu environment

---

package.json
test/types/fastify.test-d.ts

Update @types/node to 15.3.0 and fix type definition

---

docs/Ecosystem.md

Add new packages for the fastify ecosystem

---

fastify.d.ts
package.json

Use ajv options from ajv-compiler

---

docs/Serverless.md

The old name is affecting Google search results. It is best to update the name so that the search results will eventually update 😄 

Replace ZEIT to Vercel

---

docs/TypeScript.md

fix: #229 TypeScript page, CONTRIBUTING.md anchor tag broken link

---

lib/route.js
test/versioned-routes.test.js

Fixes #3105 
Hi @climba03003  / @mcollina! how does this look?
Thank you!

[Fix] Change warning message when version appears in route declaration

---

docs/Server.md

Notes for augmenting default 404 handler

---

docs/Ecosystem.md

docs(ecosystem): add fastify-seaweedfs to community plugins

---

docs/TypeScript.md

- Fixed `preHandler` from being stuck when requested 
Reproduce steps 
- Added `async` alternative in `preValidation` example because handler function is using `async`

Fixed `preHandler` from being stuck when requested

---

GOVERNANCE.md

Correct link in GOVERNANCE.md

---

docs/Routes.md

This PR is for #3135. Also, feedbacks to edit or improve this new line are all welcome.

docs: add notice of early response in hooks (#3135)

---

docs/Errors.md

Update to show where to configure, this was not showing on docs when searching for the error code and description.

Update FST_ERR_CTP_BODY_TOO_LARGE description

---

fastify.d.ts
test/types/fastify.test-d.ts

`http2SessionTimeout` is used in both secure and non-secure context:
https://github.com/fastify/fastify/blob/f298676c95046daf68aa8c3b279efeb8a5ebd2a2/lib/server.js#L17-L20
https://github.com/fastify/fastify/blob/f298676c95046daf68aa8c3b279efeb8a5ebd2a2/lib/server.js#L25-L27

Update TypeScript definitions: http2SessionTimeout

---

docs/Ecosystem.md

Add `fastify-early-hints` to ecosystem page.
https://github.com/zekth/fastify-early-hints

doc: add fastify early hints

---

docs/Ecosystem.md

Fixes https://github.com/fastify/website/issues/264

Fixes formatting error (and consequent build fail for website)

---

package.json

Removed the engines field in package.json

---

docs/Ecosystem.md

Added the 'fastify-route-group plugin'

fastify-route-group

---

README.md
docs/LTS.md

Clarified LTS sentence about the supported Node.js releases

---

docs/Ecosystem.md

docs: add heply/fastify-bcrypt

---

package.json

Use Fastify fork of pre-commit

---

test/close.test.js

This aimes to fix flakiness on windows noticed by @jsumners .
Not sure if it's the best implementation. Let's make several runs of CI to see if it passes.
edit: DO NOT MERGE.

WIP: fix: windows flakiness

---

docs/Ecosystem.md
docs/Validation-and-Serialization.md

docs: fix broken links

---

docs/Routes.md

Fixes some examples provided in the documentation.

Fix constrainted route definition

---

package.json
test/types/logger.test-d.ts

Bumped tsd to v0.17.0

---

docs/Server.md

Server.md fix default value of onConstructorPoisoning

---

docs/Ecosystem.md

- Add sequelize-fastify to ecosystem docs.

Add sequelize-fastify to ecosystem docs

---

lib/logger.js
lib/route.js

fix: pino deps warning

---

docs/Ecosystem.md

docs: add fastify-recaptcha

---

test/types/logger.test-d.ts
types/logger.d.ts

fix: add file option in FastifyLoggerOptions interface

---

docs/Ecosystem.md

Fixed dead link for @fastify/session

---

docs/Server.md
docs/Validation-and-Serialization.md
package.json

docs: how to use ajv8 within fastify3

---

docs/Lifecycle.md

The http status code is 400 when the validation fails

docs: fix http status on validation

---

docs/Server.md

docs: fix syntax

---

types/schema.d.ts

- Add a link to the schema documentation that the comment currently mentions but doesn't provide

Fix Schema Documentation Link

---

test/schema-feature.test.js

fixes #3296 
relaxed error message check

chore: fix error message check

---

docs/Recommendations.md

add nginx to Recommendations

---

package.json
test/schema-feature.test.js

Update to pino rc4

---

docs/Ecosystem.md

Just a small nit found in the ecosystem page, fastify-websocket uses `ws` since v1.0.0

docs: update fastify-websocket description

---

test/types/plugin.test-d.ts
types/instance.d.ts

close() returns a Promise, not a PromiseLike

---

docs/Validation-and-Serialization.md
test/schema-validation.test.js

Added doc and tests for #3262 

Doc - Schema validators per validation types

---

docs/Request.md

Close #2538 
- ~[ ] run `npm run test` and `npm run benchmark`~
- ~[ ] tests and/or benchmarks are included~
Hello @mcollina, I just try to change documentation based on the issue, I don't know the words suit yet or not. Could you help me to review it?
Thanks!

docs: try to fit the doc with the code

---

lib/pluginUtils.js
test/decorator.test.js
test/internals/plugin.test.js

Fixes https://github.com/fastify/fastify/issues/3332

fix decorator checks in plugin definitions

---

lib/decorate.js
test/decorator.test.js

Only null and undefined are valid values for same shape optimization

---

docs/Request.md
docs/Server.md

This is a minor docs change, fixing some broken links.

Fix links to querystringParser

---

.npmignore

`.git` and `.DS_Store` are [ignored by default](https://docs.npmjs.com/cli/v7/using-npm/developers#keeping-files-out-of-your-package), so do not need to be added.
`.dependabot` config is no longer needed either as that now resides in `.github/dependabot.yml` 😄 

chore(.npmignore): remove default ignored files/paths

---

lib/reply.js
lib/symbols.js
test/internals/reply.test.js

make getResponseTime deterministic

---

docs/Getting-Started.md
docs/Request.md

docs: clarify on `request.body` content and usage

---

docs/Hooks.md
docs/Routes.md
test/route-hooks.test.js

there were some hooks not tested as route options

test: add hook tests

---

docs/Ecosystem.md

docs: add fastify-polyglot plugin to the ecosystem

---

examples/typescript-server.ts

docs(examples): fix ts-server exit code of error

---

docs/Ecosystem.md

docs: add fastify-crud-generator plugin

---

lib/logger.js
test/logger.test.js

fix: logger req serializers

---

docs/Logging.md

add section of code to show how to setup logger for development

docs: add code sample for development logger config

---

docs/Reply.md

Rejiggs section added in #3470 

docs(reply): grammar and readability fixes for `set-cookie` section

---

lib/context.js
lib/fourOhFour.js
lib/route.js

related issues https://github.com/fastify/fastify/issues/3481

fix: Refactor Context constructor and avoid positional arguments

---

docs/Validation-and-Serialization.md

fix the sentence of `serializerCompiler`

---

docs/Logging.md

It looks like the request object has changed over time and the docs have not yet reflected that. This PR brings them up to date. 

Update logger options to correct properties

---

docs/Guides/Fluent-Schema.md
docs/Reference/ContentTypeParser.md
docs/Reference/Decorators.md
docs/Reference/Errors.md
docs/Reference/HTTP2.md
docs/Reference/Hooks.md
docs/Reference/LTS.md
docs/Reference/Lifecycle.md
docs/Reference/Logging.md
docs/Reference/Middleware.md
docs/Reference/Plugins.md
docs/Reference/Reply.md
docs/Reference/Request.md
docs/Reference/Routes.md
docs/Reference/Server.md
docs/Reference/TypeScript.md
docs/Reference/Validation-and-Serialization.md
docs/Reference/index.md
docs/index.md

This PR finishes the `docs/Reference/index.md` file. It also applies hard line wrapping to each of the reference documents. 

Implement full TOC for `docs/Reference`

---

README.md
package.json

Add Luis Orbaiceta as a contributor

---

.github/workflows/ci.yml

chore: upgrade github-action-merge-dependabot to v3

---

docs/index.md

Hello Fastify Team,
I found a typo in the docs, specifically this [page](https://www.fastify.io/docs/latest/) which corresponds to `/docs/latest`, and I thought of making a quick PR to correct it.
Regards,
Noor.

Fix typo in `/docs/index.md`

---

docs/Guides/Ecosystem.md

https://github.com/spa5k/fastify-file-routes

added fastify-file-routes

---

lib/decorate.js
test/decorator.test.js

Fixes regressions for function decorators on Request and Reply

---

.github/workflows/website.yml

Add release trigger for website build

---

lib/warnings.js
package.json

Move from fastify-warning to process-warning

---

docs/Reference/Validation-and-Serialization.md
package.json
test/schema-feature.test.js

feat: ajv default array coercion

---

.github/workflows/website.yml

This PR makes the current `website.yml` workflow to take into account all pushes to main that change documentation (*nested or not*).

Fix website workflow not triggering

---

fastify.d.ts
test/types/fastify.test-d.ts

Hi, maintainers,
I couldn't work with ajv plugins options as described in documentation [Server:ajv](https://www.fastify.io/docs/latest/Reference/Server/#ajv) in a typescript file, so I realized that types were incomplete.
I add the necessary types and their tests.

Fix types to support Ajv plugins with options

---

docs/Guides/Prototype-Poisoning.md

doc(Guides): fix grammar issue in the Prototype Poisoning file

---

package.json

Bump `ajv-compiler` to use `fast-uri`

feat: bump ajv-compiler

---

docs/Reference/Server.md

I have added the `removeContentTypeParser`, `removeAllContentTypeParsers` and `hasContentTypeParser` methods to the server docs.

update Server docs

---

fastify.js
lib/server.js
test/custom-http-server.test.js
test/https/custom-https-server.test.js
test/listen.test.js
test/logger.test.js

Tests should pass on a host with only a single network interface

---

lib/errors.js

- [N] run `npm run test` and `npm run benchmark`
- [N] tests and/or benchmarks are included
- [N] documentation is changed or added
- [N] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
This commit just changed the docs reference when a middleware is not registered.

Update middleware docs link

---

package.json

fixes #3709 
ref: https://github.com/fastify/fastify/runs/5259969308?check_suite_focus=true
```
➜  fastify git:(fix-pnpm) ✗ pnpm run test:ci
> fastify@4.0.0-alpha.1 test:ci /Users/mspigolon/workspace/fastify
> npm run unit -- -R terse --cov --coverage-report=lcovonly && npm run test:typescript
> fastify@4.0.0-alpha.1 unit
> tap -J test/*.test.js test/*/*.test.js "-R" "terse" "--cov" "--coverage-report=lcovonly"
Suites:   ​101 passed​, ​101 of 101 completed​
Asserts:  ​​​5709 passed​, ​of 5709​
> fastify@4.0.0-alpha.1 test:typescript
> tsc test/types/import.ts && tsd
```

fix: add ajv dep as dev

---

.github/workflows/ci.yml
README.md
package.json

Remove Coveralls (closes #3720)

---

docs/Reference/Server.md
fastify.js
test/internals/initialConfig.test.js

Fix avvio plugin timeout for 0

---

docs/Guides/Ecosystem.md

https://twitter.com/matteocollina/status/1503321984968675329?s=20&t=AWcu5t1EBHmff6iGfCG7jg

docs: aws-lambda-fastify in the ecosystem

---

docs/Guides/Ecosystem.md

`fastify-impressions` is a plugin used to track impressions on the routes.

Update Ecosystem.md - Add fastify-impressions to the list

---

lib/validation.js

chore: code beauty

---

examples/parser.js

I have extended the content type parser example. It now also shows the use of the `addContentTypeParser` API with a RegEx content type and the usage of the `removeContentTypeParser` and `removeAllContentTypeParsers` APIs.  
Furthermore, the `querystring` module is now used instead of the `qs` module. This way no additional package has to be installed to run the example.

Improve parser example

---

lib/server.js
test/listen.test.js

ref: https://github.com/fastify/fastify/issues/3783

fix: #3783

---

docs/Guides/Ecosystem.md

docs: add fastify-webpack-hot (fixes #3792)

---

build/build-validation.js
docs/Reference/Server.md
fastify.js
lib/configValidator.js
package.json
test/allowUnsafeRegex.test.js
test/internals/initialConfig.test.js
test/types/instance.test-d.ts
types/instance.d.ts

feat: allowUnsafeRegex in options

---

test/types/request.test-d.ts

Fix `tsd` failure due to https://github.com/pinojs/pino/tree/160db55e97f21b29e02913b0babd10e407bf4e3b

test: fix latest pino type change error

---

README.md

As titled, updated as of today.

Updated benchmarks to v4 and Node v16

---

docs/Type-Providers.md

Just fixed the package names of the type provider packages. Also changed the type provider naming convention to `@fastify/type-provider-{provider-name}`.

fix type providers package names

---

docs/Guides/Delay-Accepting-Requests.md
docs/Guides/Index.md

This PR adds a guide on how to delay serving specific requests with Fastify using Decorators, Plugins and Hooks. It's meant to be educational and tries to assume the reader knows as little as possible (or at least that was the intention, but one can always be biased in that regard).
Closes https://github.com/fastify/fastify/issues/2500

chore: add guide on delaying serving specific requests

---

docs/Guides/Database.md
docs/Guides/Ecosystem.md
docs/Guides/Getting-Started.md
docs/Guides/Migration-Guide-V3.md
docs/Guides/Plugins-Guide.md
docs/Guides/Write-Plugin.md
docs/Migration-Guide-V4.md
docs/Reference/Encapsulation.md
docs/Reference/Hooks.md
docs/Reference/Middleware.md
docs/Reference/Reply.md
docs/Reference/TypeScript.md

See https://github.com/fastify/fastify/issues/3733#issuecomment-1111188683.
The following plugins have not yet been migrated, so have not updated mentions of them:
- `aws-lambda-fastify`
- `fastify-awilix`
- `fastify-csrf`
- `fastify-schedule`
- `middie`
- `point-of-view`
- `under-pressure`

docs: reference new `@fastify/*` modules

---

.github/stale.yml

Use case example: https://github.com/fastify/fastify/issues/3482

chore: add never stale as exempt

---

docs/Guides/Benchmarking.md
docs/Guides/Database.md
docs/Guides/Delay-Accepting-Requests.md
docs/Guides/Getting-Started.md
docs/Guides/Index.md
docs/Guides/Migration-Guide-V3.md
docs/Guides/Plugins-Guide.md
docs/Guides/Recommendations.md
docs/Guides/Serverless.md
docs/Guides/Style-Guide.md
docs/Guides/Write-Plugin.md

Been over a year since I did a pass on the docs, so thought i'd revisit them.
As guides are meant to be informal i've opened this as a separate PR.
Will open another PR for changes to the reference docs.

docs(guides): grammar fixes

---

README.md
docs/Guides/Contributing.md
docs/Guides/Database.md
docs/Guides/Getting-Started.md
docs/Guides/Serverless.md
docs/Guides/Testing.md
docs/Reference/TypeScript.md
docs/Type-Providers.md

This PR changes the following:
- Replaces `npm install` with `npm i` alias, as there was a mishmash of both being used throughout docs, so thought it better to be consistent and go with the shorter alias
- Replaces `--save-dev` npm arg with `-D` alias, as there was also a mishmash of both being used throughout docs
- Removes `--save` npm arg, which is legacy and hasn't been needed since pre-npm 5.x
- Replaces legacy `--only=production` npm arg with `--production`, as it was deprecated in npm 6.x

docs: standardize npm cli commands and args

---

fastify.js

chore: fix typo

---

.github/workflows/ci.yml
README.md
docs/Guides/Write-Plugin.md

closes #3883
After merging this, someone with permissions will need to remove Snyk hook from https://github.com/fastify/fastify/settings/hooks

ci: add dependency-review job

---

docs/Reference/Plugins.md

fixed a typo in the definition of the abbreviation DAG

---

docs/Guides/Ecosystem.md

- Removed `fastify-bankai` as it is archived and no longer maintained
- Renamed `fastify-csrf` to `@fastify/csrf-protection` and updated links
- Added missing `@fastify/hotwire`

docs(ecosystem): update core list

---

docs/Migration-Guide-V4.md

docs: update the link address of `hooks`

---

docs/Reference/Routes.md
fastify.js
lib/route.js
lib/server.js
test/internals/server.test.js
test/unsupported-httpversion.test.js

feat: http version check

---

docs/Reference/Server.md

docs: explain defaultRoute

---

docs/Reference/Server.md

ref: https://github.com/fastify/fastify/issues/3872

docs: update genReqId docs

---

docs/Reference/Server.md
test/constrained-routes.test.js
test/internals/initialConfig.test.js
test/versioned-routes.test.js

Removed unused del and empty methods from constraint strategy storage. They were never used in the find-my-way and were removed by https://github.com/delvedor/find-my-way/pull/246. I left them in types definitions, to prevent typescript errors.

docs: remove unused constraint methods

---

package.json

chore: update @fastify/fast-json-stringify-compiler

---

docs/Guides/Ecosystem.md

docs(guides/ecosystem): add `any-schema-you-like`; sort alphabetically

---

docs/Guides/Ecosystem.md

Signed-off-by: Paweł Kuffel <pawel@kuffel.io>
This PR adds [fastify-amqp-async](https://github.com/kffl/fastify-amqp-async) plugin to the ecosystem docs. The plugin itself wraps [amqplib-as-promised](https://github.com/twawszczak/amqplib-as-promised) exposing its Promise-based API for operations on both regular AMQP channels (fire-and-forget) as well as channels w/ publisher confirms.

docs(ecosystem): add fastify-amqp-async

---

build/build-validation.js
docs/Reference/Routes.md
docs/Reference/Server.md
fastify.d.ts
fastify.js
lib/configValidator.js
lib/route.js
package.json
test/internals/initialConfig.test.js
test/route-prefix.test.js
test/router-options.test.js
test/types/fastify.test-d.ts
test/types/instance.test-d.ts
types/instance.d.ts

The `ignoreDuplicateSlashes` option removes all duplicated slashes from the pathname. Please pay attention on how `ignoreTrailingSlash`, `ignoreDuplicateSlashes` and `prefixTrailingSlash` will work with each other. There shouldn't be any breaking change. I hope, I didn't miss any case.
PR in the find-my-way: https://github.com/delvedor/find-my-way/pull/270

feat: add ignoreDuplicateSlashes option

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/coverage-nix.yml
.github/workflows/coverage-win.yml
.github/workflows/package-manager-ci.yml

See option description at https://github.com/actions/checkout#usage.
We don't use git in any `run` commands after checking out the repo in any of the workflow jobs, so best to remove the git credentials for security sake.
The credentials are already being removed in `benckmark.yml`:
https://github.com/fastify/fastify/blob/39830f8d3ffdf8f2059d076eaff3d90b962fdd33/.github/workflows/benchmark.yml#L26

ci: remove git credentials after checkout

---

docs/Guides/Ecosystem.md

I add community tool [fast-maker](https://github.com/imjuni/fast-maker).
fast-maker auto generate route.ts file using by directory structure like Next.js.
Thank you!

docs(ecosystem): add fast-maker

---

docs/Reference/TypeScript.md

docs: fix ambiguous sentence

---

docs/Guides/Ecosystem.md

This PR adds [fastify-kafkajs](https://github.com/kffl/fastify-kafkajs) plugin to the ecosystem docs. The plugin wraps [KafkaJS](https://github.com/tulios/kafkajs) and decorates the Fastify instance with a KafkaJS client instance, a single, pre-connected KafkaJS producer and an array of consumers declared in plugin config. 

docs(ecosystem): add fastify-kafkajs

---

docs/Reference/Server.md
fastify.js
test/plugin.test.js

Ref: https://github.com/fastify/fastify/issues/3942

Make the root pluginName 'fastify'

---

lib/request.js
test/decorator.test.js

fix: preserve chain of proptotypes in multiple nested plugins

---

docs/Guides/Ecosystem.md

This PR adds an authentication plugin for Fastify, powered by [NextAuth.js](https://next-auth.js.org/).
Thank you!

docs(ecosystem): add fastify-next-auth

---

docs/Reference/TypeScript.md

This PR updates the link to tsconfig.
https://medium.com/@fastifyjs/announcing-fastify-v4-release-candidate-2b6be6edf196
> We now support only Node.js v14+

docs: update a link to tsconfig

---

types/schema.d.ts

I found broken link and this is because just folder structure is changed.
So I quickly fixed it up.

docs: fix broken link

---

package.json
test/output-validation.test.js

update fast-json-stringify to v4

---

lib/validation.js
test/schema-serialization.test.js

2XX is a supported status code for the response

---

README.md
docs/Guides/Prototype-Poisoning.md
docs/Guides/Recommendations.md
docs/Reference/Routes.md

docs: update http links to https

---

docs/Guides/Ecosystem.md
docs/Guides/Migration-Guide-V3.md
docs/Guides/Plugins-Guide.md
docs/Guides/Serverless.md
docs/Guides/Write-Plugin.md
docs/Migration-Guide-V4.md
docs/Reference/Middleware.md

All plugins now published under `@fastify` org.

docs: update core plugin names

---

docs/Migration-Guide-V4.md

Great release, nothing to complain, just came to fix the typo.

chore(docs): fix typo

---

docs/Migration-Guide-V4.md

Add info on migrating to Aja's strict schema

Solves #3984

---

docs/Reference/Request.md

The conflict message is added in docs when merging `main` into `next`.

docs: fix merge error

---

docs/Guides/Migration-Guide-V4.md

Fixes broken link for hooks page in migration to v4 guide

docs: Update to correct link for hooks page

---

docs/Guides/Ecosystem.md

Adding [fastify-mongodb-sanitizer](https://github.com/KlemenKozelj/fastify-mongodb-sanitizer) plugin to the community ecosystem docs.
Plugin sanitizes client requests (parameters, query strings and body) to the server by removing all objects or strings prefixed with "$" in order to minimize possibility of database injection attacks to the MongoDB database.
Plugin is written in plain JavaScript and has only fastify-plugin as dependency.

docs(ecosystem): add fastify-mongodb-sanitizer

---

README.md

@next will still grab the release candidate, and now that 4.0 stable is out, folks should use that instead.
Note, https://github.com/fastify/fastify/blob/main/docs/Reference/LTS.md#schedule looks out-of-date too, but I didn't update that here.

docs: update install instructions to remove `@next`

---

docs/Guides/Database.md

This pull request is related to the issue #4036. I fix descriptions of port settings in the database guide documement.

Fix port settings for deprecation warnings.

---

.eslintrc

Fixes https://github.com/fastify/fastify/issues/4031
See https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy

chore(.eslintrc): limit eslint config to project

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-ssr-vite to community plugins

---

.github/workflows/links-check.yml

PR from forks are failing due to lack of comments permissions. 

Remove comments from links check action

---

docs/Guides/Ecosystem.md

Add lightweight cache plugin to fastify ecosystem

---

.github/workflows/integration.yml
integration/server.js
integration/test.sh

Fix https://github.com/fastify/fastify/issues/4006

Adds integration CI step

---

docs/Guides/Ecosystem.md

Add typeorm-fastify-plugin in alphabetic order to community plugins. This plugin is similar to fastify-typeorm-plugin but uses DataSource and specifically calls initialize method instead of the deprecated createConnection. Also supports creating multiple instances/namespaces.
- [x ] run `npm run test` and `npm run benchmark`
- [x ] tests and/or benchmarks are included
- [x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)

Add typeorm-fastify-plugin in Alphabetic order

---

lib/reply.js
test/stream.test.js

Handle aborted requests (#215)

---

package.json
test/schema-validation.test.js

closes https://github.com/fastify/fastify/issues/4107

fix: no store compiled schema ids

---

docs/Guides/Ecosystem.md

* Update docs/Guides/Ecosystem.md

docs(ecosystem): add simple-tjscli (#4112)

---

test/types/instance.test-d.ts
types/.eslintrc.json
types/instance.d.ts

Fixes https://github.com/fastify/fastify/issues/4110

Re-add typed decorators

---

docs/Guides/Ecosystem.md

[Plugin](https://github.com/ZigaStrgar/fastify-bugsnag) provides a way to send errors and crash reports to Bugsnag. I'll work on supporting the `Fastify V4` before merging this one off.

docs(ecosystem): Add fastify-bugsnag as community plugin

---

docs/Reference/Reply.md

For folks who copy&paste this code snippet, it would be beneficial to
include an accurate and working example which imports the `promisify()`
function.

docs: update code snippet for accurate use

---

test/types/reply.test-d.ts
test/types/request.test-d.ts
types/reply.d.ts

The PR attempts to properly add tests for the new Types of the recently added `serialization` and `validation` APIs.
Not 100% if this is the best approach, so wide open to feedback if there's a need to change the types to make it more user-friendly.

types: adjust and add testing

---

docs/Guides/Ecosystem.md

Add the **Fastify-Lyra** community plugin.

docs(ecosystem): add fastify-lyra

---

docs/Guides/Ecosystem.md

Add links to type providers

---

docs/Guides/Ecosystem.md

Hi, I created a fastify plugin for working with keycloak server, it could help developer implement the auth mechanism more easily.

docs(ecosystem): add fastify-keycloak-adapter

---

docs/Guides/Ecosystem.md

Add fastify-osm

---

docs/Guides/Ecosystem.md

Add fastify-https-always to Ecosystem doc.

---

docs/Guides/Ecosystem.md

ecosystem.md: move fastify-secure-session and fastify-soap-client to core plugins

---

package.json
test/async-await.test.js

fix: inject hangs with undefined promise resolve

---

types/instance.d.ts
types/route.d.ts

Fixes #4221
The error says "This type parameter might need an `extends FastifySchema` constraint.", so I added them.

chore: add support for TypeScript 4.8

---

types/hooks.d.ts
types/instance.d.ts
types/logger.d.ts
types/plugin.d.ts
types/reply.d.ts
types/request.d.ts
types/route.d.ts

chore: replace deprecated FastifyLoggerInstance occurences in typings with FastifyBaseLogger

---

docs/Guides/Write-Plugin.md

chore: update dependabot link

---

docs/Reference/Server.md

Hey folks, just a small suggestion here!
I was confused for a little while by `setDefaultRoute` also applying the default handler **outside** the scope of the plugin instance it was being called on, so figured it might be worth clarifying in the docs.

docs: clarify setDefaultRoute scope

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-aws-timestream and fastify-aws-sns

---

.github/workflows/lock-threads.yml

Reverts fastify/fastify#4244
Refs https://github.com/dependabot/dependabot-core/issues/5556
Wrong version bump by dependabot.

Revert "build(deps): bump jsumners/lock-threads from b27edac0ac998d42b2815e122b6c24b32b568321 to 3"

---

docs/Guides/Ecosystem.md

docs: add pubsub-http-handler

---

docs/Reference/TypeScript.md

add note in typescript doc to prevent ts(2349) warning 
https://github.com/fastify/fastify/issues/4241

docs(typescript): fix fastify/fastify#4241

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-sqlite

---

docs/Guides/Ecosystem.md

Add RavenDB to community plugins

---

docs/Guides/Ecosystem.md

Fixes https://github.com/fastify/fastify/pull/4293

docs(ecosystem): capitalization fixes

---

lib/context.js

Fixed the typo in the comment to Context object ([lib/context.js](https://github.com/fastify/fastify/blob/main/lib/context.js#L18))

Fix typo in the comment to Context object (lib/context.js)

---

docs/Guides/Ecosystem.md

Correct github url for fastify-qs package

---

docs/Guides/Ecosystem.md

docs(ecosystem): replace heply -> beliven due to rebranding

---

test/logger.test.js
test/types/logger.test-d.ts
test/types/request.test-d.ts
types/hooks.d.ts
types/instance.d.ts
types/logger.d.ts
types/plugin.d.ts
types/reply.d.ts
types/request.d.ts
types/route.d.ts

fix(logger): lost setBindings type in FastifyBaseLogger

---

test/input-validation.js

This rule is on its way into the latest Standard ☺️ 
ref: https://github.com/standard/eslint-config-standard/pull/253
- [n/a] run `npm run test` and `npm run benchmark` (`npm test` failed with unrelated typescript error 🤔)
- [n/a] tests and/or benchmarks are included
- [n/a] documentation is changed or added

chore: remove leading empty lines

---

docs/Reference/TypeScript.md

Fix typo - 'sever' to 'server'

---

README.md

Add platformatic to the Acknowledgements

---

README.md

docs: add Simone Busoli to plugin maintainers

---

docs/Guides/Recommendations.md

docs(recommendations): grammar fixes

---

docs/Reference/Routes.md
fastify.js
test/route-shorthand.test.js
test/types/route.test-d.ts
types/instance.d.ts

add missing route shorthands

---

docs/Reference/Server.md

docs: fix removeAdditional refer

---

docs/Guides/Ecosystem.md

`fastify-constraints` is added to community plugins's list

Add fastify-constraints to community plugins

---

test/types/logger.test-d.ts
types/logger.d.ts

add silent option to LogLevel

---

docs/Reference/Server.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1832StDKE2RDa46BaX6cLPEhiQ5tzjRGw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ZbgldvY)
Incorrect example in default text parser docs
https://github.com/fastify/fastify/issues/4446

Incorrect example in default text parser docs

---

README.md

❤️ I've been inactive long enough on issues/prs/discussions so I think its appropriate I move myself to past collaborators.
Love and appreciate the entire fastify crew. Know that I'll always be around as apart of the Fastify community 🚀

Move @Ethan-Arrowood to Past Collaborator section

---

docs/Guides/Ecosystem.md

This PR renames the `fastify-lyra` plugin name from `@mateonunez/fastify-lyra` to `fastify-lyra`.

chore(ecosystem): rename fastify-lyra plugin

---

docs/Guides/Ecosystem.md

Add the **fastify-at-mysql** community plugin.

docs(ecosystem): add fastify-at-mysql plugin

---

fastify.d.ts

Well, the typings tests seem to run through... 
@fastify/typescript 

nodenext compatibility

---

docs/Guides/Migration-Guide-V4.md

docs: upgrade migration guide for v4

---

LICENSE

chore(license): update licensing year

---

docs/Guides/Ecosystem.md

As a result of #4499, I came up with a small plugin for customizing the inferring for the request-id given a set of predefined Request headers + the custom ones that can be added while using the plugin.
- [fastify-ip](https://github.com/metcoder95/fastify-ip)

docs(Ecosystem): add metcoder95/fastify-ip

---

test/close.test.js
test/maxRequestsPerSocket.test.js
test/skip-reply-send.test.js
test/unsupported-httpversion.test.js

Prepare for up-coming changes.
Refs https://github.com/nodejs/node/pull/45597

test: add host header for net connection

---

lib/error-handler.js
lib/schemas.js
test/hooks.test.js

https://github.com/fastify/fastify/issues/4528

fix: getSchemaSerializer contentType check

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-web-response

---

docs/Guides/Migration-Guide-V4.md

docs: update await fastify.register docs

---

docs/Guides/Ecosystem.md

Linked Topic https://github.com/fastify/fastify/issues/4316

docs: update Ecosystem.md

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-204

---

docs/Guides/Ecosystem.md

docs(ecosystem): add @clerk/fastify plugin

---

docs/Guides/Contributing.md

While following the instructions for Setting Up Your Environment using Visual Studio Code, I was prompted with 3 settings options when the docs imply that just one option would be presented. I think the docs need to be updated to include info on the 3 different options and link to the VSCode docs for the user to identify and select which one would work best for their use case. See https://github.com/fastify/fastify/issues/4593 
Update Contribution Guide doc to include info on the 3 different options available now for VSCode Settings. Add link to VSCode doc for the user to identify and select which one would work best for their use case. 
```
» npm run test
> fastify@4.13.0 test
> npm run lint && npm run unit && npm run test:typescript
> fastify@4.13.0 lint
> npm run lint:standard && npm …
```

Improve Contribution Guide's VSCode setup instructions 

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-flux tool

---

docs/Reference/Server.md

docs: consistency fix on note and example for frameworkErrors

---

README.md
package.json

Add @metcoder95 as Collaborator

docs: add metcoder95 as collaborator

---

docs/Reference/Server.md
test/pretty-print.test.js
test/types/instance.test-d.ts
types/instance.d.ts

feat: expose prettyPrint method param

---

package.json

Bump version of fast-json-stringify-compiler

---

docs/Guides/Database.md

As `@fastify/mongodb` updated to mongodb 5, callbacks are not supported anymore and we need to switch to promises https://github.com/fastify/fastify-mongodb/pull/212

docs(mongodb): update to mongodb 5

---

docs/Guides/Ecosystem.md

Include [`fastify-koa`](https://github.com/rozzilla/fastify-koa) plugin into the `Ecosystem > Community` section.

Add `fastify-koa` plugin

---

.github/workflows/labeler.yml

Fixes #4661
For more reference check [this issue](https://github.com/actions/labeler/issues/442)

Prevent labeler from removing existing labels

---

docs/Guides/Ecosystem.md

This PR renames the old `fastify-lyra` plugin name to `fastify-orama`. (same plugin, same maintainer)

chore(ecosystem): rename to fastify-orama plugin

---

.github/labeler.yml

chore: add `github actions` label automatically

---

docs/Guides/Ecosystem.md

Just a simple update. I have changed from @cobraz to @simenandre 

chore(docs): update from cobraz to simenandre

---

docs/Reference/Hooks.md

Link from Hooks onRoute to routeOptions definition

Documentation: link from Hooks onRoute to routeOptions definition

---

docs/Guides/Ecosystem.md

This PR adds [`fastify-type-provider-effect-schema`](https://github.com/daotl/fastify-type-provider-effect-schema)
Fastify [type provider](https://www.fastify.io/docs/latest/Reference/Type-Providers/) for [@effect/schema](https://github.com/effect-ts/schema) to Ecosystem.md.

doc: add fastify-type-provider-effect-schema

---

docs/Guides/Ecosystem.md

Include [fastify-redis-session](https://github.com/mohammadraufzahed/fastify-redis-session) plugin into the Ecosystem > Community section.
Checklist

Add fastify-redis-session plugin

---

README.md

Ref: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter

chore: fix badge link

---

docs/Guides/Ecosystem.md

This PR adds the [fastify-opaque-apake](https://github.com/squirrelchat/fastify-opaque-apake) plugin in the Community section

docs: add fastify-opaque-apake to Ecosystem.md

---

README.md

docs(readme): move table of contents

---

.github/workflows/website.yml

Update to v2 of the CircleCI api
This PR can only be merged once the Personal api token is created in the CircleCI website and added to the Github secrets of this repo.
Closes #4732

Chore(Workflow): Update website.yml

---

docs/Reference/Reply.md
lib/reply.js
test/internals/reply.test.js

Changes:
- Implemented TypedArray support in the Reply.send method
- Updated the relevant documentation to reflect the new feature
- Added unit tests to ensure proper functionality

support send typedarray objects (#4715)

---

README.md

Typo correction from extendible to extensible

---

docs/Reference/Errors.md
lib/errors.js
lib/route.js
test/route.test.js

Allow lowercase methods when registering routes

---

examples/benchmark/body.json
package.json

The script fails here:
- https://github.com/fastify/fastify/actions/runs/4984207675/jobs/8922234496?pr=4752
- https://github.com/fastify/fastify/pull/4752

fix: benchmark:parser script

---

package.json

hotfix https://github.com/fastify/fastify/issues/4769
our test are red because of ts ❤️

chore: pin json-schema-to-ts

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-evervault plugin

---

package.json

Revert #4770 
Bump fixed version

revert: hotfix dev dep

---

docs/Reference/Request.md

docs(request): fix typo in compileValidationSchema function name

---

.github/workflows/sync-next.yml

as discussed here a proposal for a workflow to sync the next branch with main regularly.
I tested it in my github user scope.
see 
https://github.com/Uzlopak/test-auto-sync
and successful run 
https://github.com/Uzlopak/test-auto-sync/actions/runs/5214380428
I needed to activate "Allow GitHub Actions to create and approve pull requests", but I guess this is already active in this repo.

add sync-next workflow

---

.github/workflows/ci.yml
.github/workflows/coverage-nix.yml
.github/workflows/coverage-win.yml
package.json

Fix broken CI

---

docs/Guides/Serverless.md

Add Platformatic to deploy strategies

---

docs/Guides/Ecosystem.md

A fastify plugin for better-sqlite3

docs(ecosystem): add fastify-better-sqlite3

---

docs/Reference/Routes.md

docs(Routes.md): added short description for constraints option

---

docs/Reference/Principles.md

These principles are what @delvedor and myself wrote down a long time ago and presented at multiple conferences and events.

Added "Principles" to explain the key technical principles behind Fastify

---

fastify.js

Do not leak memory if .listen()` is not called

---

docs/Guides/Serverless.md

docs: fix platformatic-cloud anchor id

---

docs/Guides/Prototype-Poisoning.md

docs: adjust line for linter

---

docs/Reference/Logging.md

docs(logging): fix typo

---

fastify.js
test/fastify-instance.test.js

Support IPv6 ::1 in listeningOrigin

---

package.json
test/stream.test.js

Do we really need pump, if we have pipeline?

chore: remove pump devDependency

---

package.json

ci: create artifacts in coverage workflows

---

docs/Reference/Server.md

fix: requestIdHeader docs

---

README.md

[readme] add CII Best Practices Badge

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-hashids

---

docs/Guides/Ecosystem.md

docs: early hints plugin is fastify plugin

---

.github/dependabot.yml
.github/workflows/pull-request-title.yml

chore: add pull request title check

---

docs/Reference/Validation-and-Serialization.md

Small fix/correction for https://github.com/fastify/website/issues/140

docs: fix removeAdditional comment

---

test/custom-http-server.test.js
test/https/custom-https-server.test.js

chore: make tests pass on ipv4 only machine

---

docs/Guides/Ecosystem.md

docs(ecosystem): add `@fastify/throttle` to core list

---

docs/Guides/Ecosystem.md
docs/Guides/Serverless.md
docs/Reference/Errors.md
docs/Reference/HTTP2.md
docs/Reference/Hooks.md
docs/Reference/Server.md
lib/contentTypeParser.js
lib/handleRequest.js
lib/hooks.js
lib/logger.js
lib/reply.js
lib/request.js
lib/schemas.js
lib/server.js
lib/validation.js
test/build/error-serializer.test.js

fix: typos

---

examples/asyncawait.js
examples/http2.js
examples/https.js
examples/parser.js
examples/shared-schema.js
examples/simple-stream.js
examples/simple.js
examples/typescript-server.ts
examples/use-plugin.js

Added curly braces to conditions for better readability and less error-prone

chore(examples): added curly braces to conditions for consistency

---

docs/Reference/Principles.md

I just noticed that it was a small typo

docs(typo): mistype of monkeypatch

---

package.json

chore: change website to .dev instead of .io

---

README.md
package.json

@gurgunday 
Is your data correct?

chore: add gurgunday and uzlopak as contributors

---

package.json

chore: add a citgm command to customize what we run in CITGM

---

docs/Reference/Request.md
lib/warnings.js

fix: correct warnings for request.routerPath and request.routerMethod

---

test/types/request.test-d.ts
types/request.d.ts

fix: add routeOptions.schema to types

---

.github/dependabot.yml

See https://github.com/fastify/fastify/pull/5043#issuecomment-1723545635

build(dependabot): ignore tap major updates

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-prisma

---

test/input-validation.js

Fixing the test CI
Caused by:
https://github.com/jquense/yup/issues/2111

test: fix ci due yup breaking

---

CONTRIBUTING.md
README.md

Just wanted to be of help fixing a couple simple typos I found while looking at the docs :)

docs: Fixing a couple typos

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-event-bus

---

docs/Reference/TypeScript.md
types/plugin.d.ts

docs: update docs for FastifyPlugin

---

docs/Reference/Reply.md

.hijack isn't showing correctly so update it.

docs: Update for .hijack heading

---

lib/route.js
test/head.test.js

fix: HEAD route reseting

---

package.json

fix: timeout on citgm tests

---

examples/use-plugin.js
integration/server.js
test/buffer.test.js
test/bundler/esbuild/src/fail-plugin-version.js
test/bundler/esbuild/src/index.js
test/bundler/webpack/src/fail-plugin-version.js
test/bundler/webpack/src/index.js
test/bundler/webpack/webpack.config.js

chore: add missing `use strict` directives

---

README.md

Congrats to @jsumners and @Eomm :).

fix: add @eomm and @jsumners as lead maintainers

---

lib/reply.js
test/internals/reply.test.js

- test: false positive Uint8Array view length
- fix(reply.send): support Uint8Array payloads
This issue fixes https://github.com/fastify/fastify/issues/5118 according to the
agreed upon [comment](https://github.com/fastify/fastify/issues/5118#issuecomment-1778897189).

fix: reply.send supports Uint8Array payload

---

docs/Reference/Index.md
docs/Reference/Warnings.md
lib/warnings.js

docs: added documentation about warnings

---

lib/hooks.js
test/types/request.test-d.ts

See https://github.com/fastify/fastify-helmet/issues/236

refactor(lib/hooks): replace `typeof` undefined check

---

docs/Reference/TypeScript.md

- [ x] run `npm run test` and `npm run benchmark`
- [x ] tests and/or benchmarks are included
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
add small fix to the typescript docs

docs: Fix small typo in Typescript docs

---

docs/Reference/ContentTypeParser.md

docs: mention about multipart support

---

docs/Reference/Hooks.md

docs(reference/hooks): add information about prehandler

---

test/types/logger.test-d.ts
types/instance.d.ts
types/route.d.ts

fix: type FastifyInstance['route'] and RouteShorthandMethod

---

docs/Reference/Request.md

docs (reference): Fix small typo in Request

---

docs/Guides/Ecosystem.md

Adds [Apitally](https://github.com/apitally/nodejs-client) to the Ecosystem page in the documentation.
Apitally is a simple API monitoring and API key management solution that supports Fastify.

docs(ecosystem): Add Apitally

---

lib/warnings.js

https://github.com/fastify/fastify/issues/5151#issuecomment-1832213051

fix: Update reply.context deprecation warning

---

docs/Guides/Ecosystem.md

This PR adds a new plugin to the community plugins list. This plugin is made for the purpose to help cache API responses using AWS DynamoDB as a caching storage, so you are able to run multiple API instances on serverless functions and still have access to the same cached responses.
Link to the plugin (Github): https://github.com/blastorg/fastify-aws-dynamodb-cache
```ts
import Fastify from "fastify";
import { dynamodbCache } from "@blastorg/fastify-aws-dynamodb-cache";
const fastify = Fastify().register(dynamodbCache, {
dynamoDbRegion: "", // AWS region of your choice.
dynamoDbAddress: "http://localhost:8000", // Optional! If you are hosting your own instance of Dynamo (locally or cloud), then specify the ip address of the database here.
tableName: "fastify-dynamodb-cache", // DynamoDB …
```

docs(ecosystem): adds @blastorg/fastify/aws-dynamodb-cache to community plugins list

---

docs/Guides/Ecosystem.md

Add http-wizard in the community ecosystem.
More information here:
https://http-wizard.vercel.app

docs(ecosystem): add http-wizard

---

fastify.js
lib/decorate.js
lib/pluginUtils.js
lib/reply.js
lib/request.js
lib/route.js
lib/server.js
lib/validation.js
lib/warnings.js
package.json
test/decorator.test.js
test/default-route.test.js
test/internals/reply.test.js
test/route.7.test.js
test/schema-feature.test.js
test/versioned-routes.test.js

chore: update process-warning

---

docs/Guides/Ecosystem.md

* added in fastify-hl7
* updated description of fastify-rabbitmq

docs(ecosystem): update fastify-rabbitmq // add fastify-hl7 to ecosystem.md

---

.github/workflows/labeler.yml

Remove invalid option
https://github.com/actions/labeler/releases/tag/v5.0.0

chore: update actions/labeler@5

---

types/instance.d.ts

Fixes https://github.com/fastify/fastify-rate-limit/issues/355

fix: remove unused promise warning in setNotFoundHandler with preHandler

---

docs/Guides/Ecosystem.md

docs: Add missing punctuation in Ecosystem

---

fastify.d.ts

chore(types): Remove unused type imports

---

docs/Reference/Errors.md

chore(docs): Add clarification about `fastify.setErrorHandler()`

---

docs/Reference/Server.md
fastify.js
lib/context.js
lib/fourOhFour.js
lib/reqIdGenFactory.js
lib/route.js
lib/symbols.js
test/genReqId.test.js
test/types/instance.test-d.ts
types/instance.d.ts

fixes: https://github.com/fastify/fastify/issues/5170

feat: expose method for setGenReqId on FastifyInstance

---

docs/Reference/Errors.md

docs: re-word clarification about `setErrorHandler()`

---

docs/Guides/Ecosystem.md

Apollo [dropped Fastify integration with v4](https://github.com/apollographql/apollo-server/blob/1140fce881c1dde340b9d1c55ce149a7c4dd82dd/packages/server/CHANGELOG.md#removed-web-framework-integrations), so the link was dead.

docs(ecosystem): remove unsupported package

---

lib/error-serializer.js

Just run
```
npm run build:validation
```
Generated by:
- https://github.com/fastify/fast-json-stringify/pull/670

chore: sync generated code

---

docs/Reference/Warnings.md

This PR is in response to issues such as https://github.com/fastify/help/issues/992. Such issues are not helpful because they do not include information that will help us provide a solution. But we can't really complain about them because we haven't told people how to get the information we would need. This should help solve that problem.

chore: add docs for tracing warnings

---

build/build-validation.js
docs/Guides/Migration-Guide-V5.md
docs/Reference/Server.md
lib/configValidator.js
test/internals/initialConfig.test.js
test/useSemicolonDelimiter.test.js

closes: https://github.com/fastify/fastify/issues/5319

feat: set useSemicolonDefault default option to false

---

test/types/fastify.test-d.ts

types: fix test failure

---

docs/Reference/Request.md

Proposal:
- Updated the `routerMethod` and `routerPath` methods because they are deprecated ( see screenshot ) on `Reference` section  in the `Request` page.

docs(request): update request page

---

docs/Guides/Ecosystem.md

By making a contribution to this project, I certify that:
* (a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
* (b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
* (c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
* (d) I understand and agree that this project and the contribution
are …

docs(ecosystem): update x-ray community plugin link

---

docs/Guides/Ecosystem.md

add fastify-msgraph-change-notifications-webhook to community plugins

docs(ecosystem): add fastify-msgraph-change-notifications-webhook to community plugins

---

docs/Reference/Errors.md

docs: fix errors table layout

---

docs/Reference/TypeScript.md

Proposal:
- Update `"Generic Constraints"` link, because the link redirects to a deprecated page in the `Typescript´ documentation (see screenshot).

docs(typescript): update generic constraints link

---

test/types/type-provider.test-d.ts
types/reply.d.ts

Closes https://github.com/fastify/fastify/issues/5378

types: narrow code reply type based on schema

---

docs/Reference/TypeScript.md

and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_COND
UCT.md)
Proposal:
A small correction in this code snippet ( see screenshot, marked in red )

docs(typescript): update snippet code

---

SPONSORS.md

Thanks to our new sponsor! @mercedes-benz

chore: add mercedes-benz as new sponsor

---

docs/Guides/Ecosystem.md

chore(ecosystem): Add Fastify asyncforge plugin

---

README.md
package.json

🎉
Side note: `gurgun.dayioglu@icloud.com` is no longer in use and will be deactivated shortly

chore: add @gurgunday to the Core Team

---

docs/Reference/TypeScript.md

The proposed changes are as a result of this [issue](https://github.com/fastify/website/issues/212) from the fastify/fastify repo

docs(ref/typescript): support Docusaurus v3

---

.github/labeler.yml
.github/workflows/labeler.yml

It is not working, no errors tho
- https://github.com/fastify/fastify/pull/5461
- https://github.com/fastify/fastify/actions/runs/9050598552/job/24866171348

fix: ci labeler

---

docs/Reference/Type-Providers.md

Proposal:
- Two minor corrections on import indentation, so that the code in the snippets appears neater with the rest of the page

docs: update indentation on type providers section

---

docs/Reference/Routes.md

Proposal:
Some minor updates in the code indentation  in `routes` section

docs: update indentation and code snippet in the routes section

---

test/close-pipelining.test.js

Refs https://github.com/nodejs/node/releases/tag/v18.20.3

test: fix closing - pipelining

---

docs/Guides/Ecosystem.md

docs(ecosystem): Add fastify-kysely plugin

---

.npmignore

Relates to https://github.com/fastify/fastify/issues/5536

fix(v5): update .npmignore

---

SPONSORS.md

If someone from Val Town would like to submit a better link or a logo to add it to the website, I will be more than happy to deploy it!

chore(sponsor): add valtown

---

types/type-provider.d.ts

chore: fix lint

---

lib/reply.js
test/stream-serializers.test.js

fix: res serializer not given reply (#5556)

---

docs/Reference/Request.md
docs/Reference/Warnings.md
lib/request.js
lib/warnings.js
test/internals/request.test.js

chore: remove deprecation 005

---

lib/server.js
test/listen.1.test.js

fix: nullish host

---

docs/Reference/Reply.md

Proposal:
- Small corrections to update in code snippets in `Reply` section

docs(reply): standardize import style in examples

---

docs/Reference/TypeScript.md

See https://github.com/fastify/fastify/issues/5585

docs(typescript): update example fastify version

---

docs/Reference/Warnings.md
lib/reply.js
lib/warnings.js
test/internals/reply.test.js
test/skip-reply-send.test.js

Remove the setter of `request.sent`.

refactor: remove `FSTDEP010`

---

docs/Reference/Warnings.md
lib/reply.js
lib/warnings.js
test/internals/reply.test.js
test/types/reply.test-d.ts
types/reply.d.ts

refactor: remove `FSTDEP021`

---

docs/Reference/Server.md

(Very small Docs PR, this could've saved my sleep-deprived brain some time going back and forth through code and docs)

docs: add default value for maxParamLength

---

README.md

This is something I should have done a year ago, but I forgot. Currently, my free time is too limited, so I don't have the capacity to keep working on it. Keep shaping it up!

docs: move RafaelGSS to past collaborators

---

docs/Reference/Type-Providers.md

Fixed typo in Scoped Type-Provider section

docs(type-providers): fix typos

---

docs/Guides/Migration-Guide-V4.md

closes #5574 creating codemods for fastify v4.

feat: add fastify v4 codemods

---

package.json

chore: bump ajv-compiler to v4.0.0

---

package.json

chore: Bumped light-my-request to v6.0.0

---

package.json

chore: Bumped avvio to v9.0.0

---

package.json
test/types/instance.test-d.ts

chore: bump fast-json-stringify-compiler to v5.0.0

---

README.md

add @dancastillo to Fastify Plugins team

docs: add dancastillo to Fastify Plugins team

---

README.md

Sorry, I missed that onboarding step, thanks @gurgunday for noticing me.

docs: join plugin team

---

lib/warnings.js

chore: list the next deprecation code

---

docs/Guides/Migration-Guide-V5.md
docs/Reference/LTS.md

docs: add v5 guide

---

docs/Guides/Migration-Guide-V4.md

- Added links to provide extra context for codemods
- Switched existing links to Dub links to avoid potential 404s in the future
- Minor wording adjustments

docs: update v4 codemods

---

docs/Guides/Getting-Started.md

While going through the guide, I ran into an issue with the sample code. This is a trivial documentation change to address it.

docs: Add required .js extension to relative ESM imports

---

docs/Guides/Migration-Guide-V5.md

Add the contributors for the release.

chore: Update Migration-Guide-V5.md

---

test/internals/reply-serialize.test.js

Changes 4 occurrences of `properites` into `properties`.

chore: fix typo in reply-serialize.test.js

---

docs/Reference/Routes.md

docs: fix schema

---

docs/Reference/Errors.md

docs: correct errors fragment

---

fastify.js
test/internals/initialConfig.test.js

fix: make shallow copy of fastify options before mutations

---

test/types/instance.test-d.ts

Looks like those tests could be uncommented since https://github.com/tsdjs/tsd/pull/220 has landed ? 🙂

chore(tests): uncomment server.decorate test case

---

lib/pluginUtils.js

instead of creating an extra array, we just stop the split early

chore: getFuncPreview limit split size

---

lib/contentTypeParser.js
lib/context.js
lib/reply.js
lib/request.js
lib/route.js

refactor: change var instances to const or let

---

lib/request.js

leftover from the last PR changes

perf: pause split early on hostname

---

test/allowUnsafeRegex.test.js
test/async_hooks.test.js
test/buffer.test.js
test/case-insensitive.test.js
test/chainable.test.js
test/check.test.js
test/childLoggerFactory.test.js
test/client-timeout.test.js

test: move allowUnsafeRegex to node test runner

---

test/route.4.test.js
test/route.5.test.js
test/route.7.test.js

Ported some test cases to node test runner

feat(test runner node): route 4

---

test/route.1.test.js
test/route.2.test.js

Ported `route.1.test` to test runner

test: migrate route.1.test to node test runner

---

test/route.3.test.js

Ported to the node test runner: `route.3.test.js`

test: ported route 3 test

---

test/keep-alive-timeout.test.js
test/keepAliveTimeout.test.js

Proposal:
- migrated `keepAliveTimeout.test.js` file from `tap` to `node:test` 🔥

test: migrated keep-alive-timeout.test.js from tap to node:test

---

test/noop-set.test.js

Proposal:
- migrated `noop-set.test.js` file from `tap` to `node:test` 🔥

test: migrated noop-set.test.js from tap to node:test

---

test/connectionTimeout.test.js
test/route.6.test.js

Small porting of some test to node test runners

feat(test runner node): test porting 

---

.github/workflows/benchmark-parser.yml
.github/workflows/benchmark.yml
.github/workflows/md-lint.yml
CONTRIBUTING.md
EXPENSE_POLICY.md
docs/Guides/Database.md
docs/Guides/Detecting-When-Clients-Abort.md
docs/Guides/Ecosystem.md
docs/Guides/Index.md
docs/Guides/Migration-Guide-V4.md
docs/Guides/Migration-Guide-V5.md
docs/Guides/Plugins-Guide.md
docs/Guides/Prototype-Poisoning.md
docs/Guides/Recommendations.md
docs/Guides/Serverless.md
docs/Guides/Testing.md
docs/Guides/Write-Plugin.md
docs/Guides/Write-Type-Provider.md
docs/Reference/Decorators.md
docs/Reference/Errors.md
docs/Reference/Hooks.md
docs/Reference/Reply.md
docs/Reference/Request.md
docs/Reference/Routes.md
docs/Reference/Server.md
docs/Reference/TypeScript.md
lib/error-serializer.js
test/bundler/README.md

style: remove trailing whitespace

---

CONTRIBUTING.md

Ref:
- https://github.com/orgs/fastify/discussions/45#discussioncomment-11165540

docs(CONTRIBUTING.md): read the announcements

---

test/listen.5.test.js

Proposal:
- migrated `listen.5.test.js` file from tap to node:test 🔥

test: migrated listen.5.test.js from tap to node:test

---

docs/Reference/Reply.md
docs/Reference/Server.md

docs: smaller documentation fixes

---

test/schema-examples.test.js

Proposal:
- migrated `schema-examples.test.js`  from `tap` to `node:test` 🔥

test: migrated schema-examples.test.js from tap to node:test

---

docs/Guides/Ecosystem.md

docs: Added fastify-passkit-webservice to community plugins

---

docs/Reference/Logging.md

docs: fix example for supplying own logger instance

---

lib/errors.js
lib/hooks.js
test/hooks.on-ready.test.js
test/internals/errors.test.js

feat: Add hook name within timeout error message

---

docs/Reference/Validation-and-Serialization.md

docs: make whitespace consistent

---

test/fastify-instance.test.js

Proposal:
- migrated `fastify-instance.js` from `tap` to `node:test` 🔥

test: migrated fastify-instance.test.js from tap to node:test

---

test/find-route.test.js

Proposals:
- migrated `find-route.test.js` file from `tap` to `node:test` 🔥

test: migrated find-route.test.js from tap to node:test

---

README.md

chore: sponsor link

---

README.md

This is a very simple addition: `pnpm` install script

chore: readme lighter install script

---

CONTRIBUTING.md

docs(CONTRIBUTING.md): added v4 to version branches

---

lib/error-handler.js

fix(errorHandler.js): linting problems in pipeline

---

types/request.d.ts

types: remove connection property in FastifyRequest

---

package.json

chore: bump dev fastify-plugin

---

README.md
docs/Reference/Request.md
lib/request.js

This PR:
- Corrects the sort order of members in the readme, changed by https://github.com/fastify/fastify/pull/5898
- Corrects grammar and spelling in request documentation introduced by https://github.com/fastify/fastify/pull/5892

docs(request): clarify request host functionality

---

README.md
package.json

Thanks for promoting me as the Leads Maintainer of fastify.

docs: add climba03003 to team

---

docs/Reference/Request.md

docs: fix typo

---

CONTRIBUTING.md
PROJECT_CHARTER.md
README.md

Minor grammar and spelling fixes to core pieces of documentation.
I will take a look at the references and guides, but will put them in their own PRs.

docs: grammar and spelling fixes

---

docs/Guides/Benchmarking.md
docs/Guides/Contributing.md
docs/Guides/Database.md
docs/Guides/Delay-Accepting-Requests.md
docs/Guides/Fluent-Schema.md
docs/Guides/Getting-Started.md
docs/Guides/Index.md
docs/Guides/Migration-Guide-V4.md
docs/Guides/Plugins-Guide.md
docs/Guides/Serverless.md
docs/Guides/Style-Guide.md
docs/Guides/Write-Plugin.md

docs(guides): grammar and spelling fixes

---

docs/Guides/Getting-Started.md

closes #5911 
The tool is under a new header so we can't make it any clearer this is separate from a normal server setup.

docs(getting-started): clarify fastify-cli is separate

---

docs/Reference/Validation-and-Serialization.md

Just a small typo fix `application-json` &rarr; `application/json`

docs(validation-and-serialization): fix typo

---

docs/Reference/LTS.md

Update broken link to N|Solid

---

docs/Reference/ContentTypeParser.md
docs/Reference/Encapsulation.md
docs/Reference/HTTP2.md
docs/Reference/LTS.md
docs/Reference/Lifecycle.md
docs/Reference/Middleware.md
docs/Reference/Principles.md
docs/Reference/Warnings.md

As these are all small files i've grouped them into one PR.
When i review the biguns like Review, those will be in their own PRs.

docs(reference): even more conciseness

---

docs/Guides/Ecosystem.md

docs(ecosystem): add `@fastify/otel` to core list

---

SPONSORS.md

chore(sponsor): Add Lokalise sponsorship reference

---

docs/Guides/Ecosystem.md

docs(ecosystem): add fastify-enforce-routes-pattern

---

SPONSORS.md

Adding the new sponsor (9th Jen):
Restoring the declared order:
> All active sponsors of Fastify are listed here, in order of contribution!
If we wanna change it, I would do in a separate PR with a quick automation check.

chore(sponsor): add Jspreadsheet

---

docs/Reference/Decorators.md
docs/Reference/Plugins.md
docs/Reference/Routes.md

docs(reference/routes): conciseness improvements

---

.github/workflows/ci.yml
.github/workflows/integration-alternative-runtimes.yml
.github/workflows/integration.yml
.github/workflows/lint-ecosystem-order.yml
.github/workflows/md-lint.yml
docs/Reference/TypeScript.md
docs/Reference/Validation-and-Serialization.md

See https://github.com/fastify/fastify/issues/5354. This is a batch PR, so may have some issues. Please review changes.

ci: remove master branch support

---

docs/Guides/Serverless.md

docs: Drop platformatic cloud reference in serverless.md

---

docs/Guides/Serverless.md

docs: add a Genezio step by step guide

---

docs/Guides/Getting-Started.md
docs/Reference/Server.md

docs: Update documentation for listening to `0.0.0.0`

---

docs/Guides/Serverless.md

Follow up to #5980.
As Genezio has a dedicated guide for deploying a Fastify application on their platform, we should simply reference it. This way, if Genezio updates their documentation, we won't need to update this page.
Other serverless platforms/deployment methods are documented here more extensively because they lack their own pages. If they did have their own, we'd do the same thing.

docs(serverless): cut down genezio example

---

README.md

See https://github.com/fastify/website/issues/275.

docs: add link to official demo

---

docs/Reference/Server.md

Related to https://github.com/fastify/fastify/pull/5993.

docs: update example to use correct parser

---

test/bundler/esbuild/package.json

Bumped to mitigate https://github.com/advisories/GHSA-67mh-4wv8-2f99

build(test/bundler/esbuild): bump esbuild

---

docs/Guides/Ecosystem.md

docs(guides/ecosystem): update broken link to scalar

---

test/upgrade.test.js

[context.skip()](https://nodejs.org/api/test.html#class-suitecontext) is not defined.

test: fix skip in upgrade test

---

test/custom-parser.4.test.js

Migrated the tests in custom-parser.4.test.js to node:test.
Assisting in completing #5555 !

chore: migrate custom-parser.4.test.js to node:test

---

test/logger/options.test.js

test: migrate logger options to node test runner

---

test/logger/logging.test.js
test/toolkit.js

test: migrate logger logging to node test runner

---

test/custom-querystring-parser.test.js

test: custom querystring parser

---

test/stream.4.test.js

test: migrate stream 4 to node test runner

---

test/logger/request.test.js
test/toolkit.js

test: migrate request logger to node test runner

---

test/custom-parser.0.test.js

test: migrate custom parser 0 to node test runner

---

test/logger/instantiation.test.js
test/toolkit.js

test: migrate logger instantiation to node test runner

---

docs/Guides/Serverless.md

👋 Now that Vercel supports server-like concurrency with Fluid, I updated this section to add more details, as well as linking to a template folks can get started with.

docs: update Vercel section

---

docs/Guides/Ecosystem.md

This pull request adds a description for the community plugin `@inaiat/fastify-papr` to the `Ecosystem.md` documentation file. This helps users understand the purpose of the plugin when browsing the list of community contributions.

docs(ecosystem): add fastify-papr plugin

---

test/helper.js
test/input-validation.js
test/options.error-handler.test.js
test/options.test.js
test/patch.error-handler.test.js
test/patch.test.js
test/put.error-handler.test.js
test/put.test.js

test: migrated helper and input validation to node test runner

---

test/stream.1.test.js
test/stream.2.test.js
test/stream.3.test.js

test: migrate stream tests to node test runner

---

test/logger/response.test.js
test/toolkit.js

test: logger response

---

test/schema-validation.test.js

fix: Added more cases for JSON schema validation

---

test/plugin.1.test.js

test: migrated plugin 1 to node test runner

---

.github/workflows/ci.yml

ci: fix branch pattern

---

docs/Guides/Ecosystem.md

docs: added Jeasx to Ecosystem.md

---

test/promises.test.js

This PR is an alternative to https://github.com/fastify/fastify/pull/6057
I think we should be very conservatives regarding tests suites as it's much harder to have feedback when we introduce regressions at that level.

test: mv promises from tap

---

docs/Guides/Ecosystem.md

Following private team discussion.

docs: add community plugins disclaimer

---

README.md
package.json

docs: join core team

---

test/custom-parser-async.test.js

chore: remove simple-get from custom parser async

---

test/http-methods/mkcol.test.js

chore: removed simple-get from mkcol tests

---

test/proto-poisoning.test.js

chore: removed simple-get from proto-poisoning test

---

test/als.test.js

chore: removed simple-get from als test

---

test/listen.4.test.js

chore: remove simple-get from listen 4

---

test/output-validation.test.js

chore: removed simple-get from output-validation tests

---

.github/workflows/citgm.yml

as titled, removing archived deps

chore(ci): cleanup citgm.yml

---

test/https/https.test.js

chore: removed simple-get from https tests

---

test/http-methods/lock.test.js

chore: removed simple-get from lock test

---

docs/Guides/Delay-Accepting-Requests.md

annoyingly there was a linting issue in the docs.

docs: fix markdown linting issue

---

test/versioned-routes.test.js

chore: removed simple-get from versioned-routes tests

---

test/hooks.test.js

chore: removed simple-get from hooks tests

---

test/https/custom-https-server.test.js

chore: removed simple-get from custom-https-server tests

---

test/custom-parser.5.test.js

chore: remove simple-get from custom parser 5

---

test/http-methods/head.test.js

chore: removed simple-get from head tests

---

test/request-id.test.js

chore: removed simple-get from request id tests

---

test/custom-parser.2.test.js

chore: remove simple-get from custom parser 2

---

test/custom-parser.4.test.js

chore: remove simple-get from custom parser 4

---

test/promises.test.js

chore: removed simple-get from promises test

---

test/custom-querystring-parser.test.js

chore: remove simple-get from custom querystring parser

---

test/check.test.js

chore: removed simple-get from check test

---

test/async_hooks.test.js

chore: removed simple-get from async hooks test

---

test/http2/secure-with-fallback.test.js

fix: close fastify instance

---

test/plugin.1.test.js

chore: removed simple-get from plugin-1 test

---

test/plugin.3.test.js

chore: removed simple-get from plugin-3 test

---

test/internals/reply.test.js

chore: remove simple get from reply test

---

docs/Guides/Ecosystem.md

This PR adds `fastify-route-preset` to the community plugins.

docs(ecosystem): add fastify-route-preset plugin

---

test/route-shorthand.test.js

chore: remove simple get from route shorthand

---

docs/Guides/Migration-Guide-V5.md
package.json
test/helper.js
test/input-validation.js

chore: finally remove simple get

---

test/schema-validation.test.js

Well, I guess we are currently refactoring some tests ;)

chore: remove undici from schema-validation.test.js

---

docs/Reference/Request.md

chore: fix docs Request.md

---

SECURITY.md

ref: https://github.com/openjs-foundation/cross-project-council/pull/1588

docs(security): add security escalation policy

---

SPONSORS.md

chore(sponsor): add lambdatest

---

lib/content-type-parser.js
test/content-parser.test.js
test/schema-validation.test.js

fix: accept htab ows

---

fastify.js
lib/route.js
lib/server.js

Read #6329 
A new `processOptions` function is now responsible for validating and normalizing options.  
This reduces noise in the `fastify()` factory and clarifies responsibilities.
We can continue splitting complexity into focused modules.
Suggestions:
- **Plugins**: merge `plugin-override` and `plugin-utils` into a single module with a new `initAvvio` function  
- **Inject**: move into its own file  
- **Hooks**: move `addHook` into `hooks.js`  
- etc.
Changes can be incremental.

refactor: delegate options processing to a dedicated function

---

docs/Reference/Server.md

See: #6284 
Before we decide if we should change the implementation, let's document the current behavior.

docs: mention that addHttpMethod override existing methods

---

test/promises.test.js

chore: remove reference to simple-get
