fastify/fastify

- fastify.d.ts
- test/types/instance.test-d.ts
- types/instance.d.ts
Added types for the ``printRoutes`` method.
> Add types for printRoutes

- docs/Reply.md
- docs/Server.md
* removed reference to pump, since it seems like pump is not used internally in request handling (its a dev dependency and can only be found in tests)
* added some description why the current default http2SessionTimeout was chosen (DoS mitigation)
> doc: removed reference to pump and added description on http2SessionTimeout

- lib/route.js
- test/route.test.js
Fixes https://github.com/fastify/fastify-swagger/issues/425
Problem: when checking if a scoped GET route's matching HEAD route already exists, Fastify looks it up by method and path, omitting the scope's prefix. When `exposeHeadRoutes` is true, this results is a false negative and an error when it tries to create a HEAD route that already exists.
Solution: look up the route by method and full path/url
> afterRouteAdded: fixed `headRouteExists` lookup argument

- test/types/reply.test-d.ts
- test/types/request.test-d.ts
- types/reply.d.ts
- types/request.d.ts
Closes #3202 
Update typescript type definitions for the `request` and `reply` object to include the new `server` property introduced in #3102.
> Update type defs to include new `server` req/rep property

- docs/Decorators.md
- test/types/instance.test-d.ts
- types/instance.d.ts
Just added the correct type for the ``this`` binding in the decorator functions. Additionally I added a note in the documentation that an arrow function in the ``decorate`` function would break the this binding.
> Add this types to decorator functions

- lib/reply.js
- test/async-await.test.js
Resolves #3209 
Make setErrorHandler consistent in handling return values, like in lib/handleRequest.js https://github.com/fastify/fastify/blob/7db55d47a80607f97c4fd8e3e54c649abcd78f2f/lib/handleRequest.js#L136-L142
> Fix request hanging when synchronously returning a value in setErrorHandler

- lib/contentTypeParser.js
- lib/handleRequest.js
- lib/hooks.js
- lib/reply.js
- lib/route.js
- test/content-parser.test.js
- test/reply-error.test.js
This is the first in line of PRs that will address issues outlined in https://github.com/fastify/fastify/issues/2860.
Firstly, I modified how kReplyIsError is tracked. The property is automatically set to false when reply.send() is used. This way there's no way that the reply would be considered an error longer than needed.
Secondly, I went through the code base and properly marked all replies as errors where appropriate. In the current version of Fastify there are huge inconsistencies of how non Errors are handled when thrown. Javascript supports throwing anything, so Fastify must take such cases into consideration. 
This PR ensures that you can safely throw anything in hooks or handlers …
> Deem everything thrown as an error

- docs/Getting-Started.md
With current example from Getting-started.md, I get this error and server doesn't resolve anything.
"name":"FastifyError"
"code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500}
"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"
Because "result" return undefined with an empty dataset and check only for null values doesn't avoid the exception.
> feat: update Getting-Started.md

- docs/ContentTypeParser.md
- fastify.js
- lib/contentTypeParser.js
- test/content-parser.test.js
- test/custom-parser.test.js
- test/types/content-type-parser.test-d.ts
- types/content-type-parser.d.ts
- types/instance.d.ts
Closes #2994. This PR adds the 2 methods `resetContentTypeParsers` and `removeContentTypeParser` to the Fastify instance. With `resetContentTypeParsers` all current content type parser can be deleted (including the both built-in content type parsers). This is especially useful if you want to implement a catch-all content type parser that should be called even if the content type is `application/json`. With `removeContentTypeParser` a single or an array of content type parsers can be removed. Both APIs support encapsulation.
```javascript
const app = fastify()
app.removeContentTypeParser('application/json')
app.resetContentTypeParsers()
```
> Extend content type parser

- fastify.d.ts
- test/types/fastify.test-d.ts
Since `find-my-way` version 4.1 it is possible to specify a generic type for the value of a constraint. The default type of this generic parameter is `string`. This makes it impossible to register constraints that have a value type other than string. The following example produces the error `Type 'ConstraintStrategy<HTTPVersion.V1, number>' is not assignable to type 'ConstraintStrategy<HTTPVersion.V1, string>'. Type 'number' is not assignable to type 'string'.`.
```typescript
import fastify from 'fastify'
import { ConstraintStrategy, HTTPVersion, Req, Handler} from 'find-my-way'
const constraintStrategy: ConstraintStrategy<HTTPVersion.V1, number> = {
deriveConstraint<Context>(req: Req<HTTPVersion.V1>, ctx: Context | undefined): number {
return 0
},
mustMatchWhenDerived: false,
name: …
```
> fix generic constraint type

- docs/TypeScript.md
Used was `Response` but it should be `Reply`. `Response` is not found in `RouteGenericInterface` but `Reply` is.
https://github.com/fastify/fastify/blob/main/types/reply.d.ts#L9
https://github.com/fastify/fastify/blob/main/types/reply.d.ts#L32
> docs: fix interface in route generic example

- package.json
PR #3221 causes an error if not at least find-my-version `4.1` is installed. To prevent this, the minimum installed version should be `4.1`.
> upgrade minimum find-my-way version

- docs/Reply.md
- docs/Server.md
> docs: update all nodejs doc links to point to v14.x documentation

- docs/Ecosystem.md
https://github.com/Unbuttun/fastify-slonik
> docs: Added fastify-slonik plugin reference in fastify-ecosystem page.

- docs/TypeScript.md
The third point in "Using Generics" says
"The shorthand route methods (i.e. .get) accept a generic object `RequestGenericInterface`".
But the route methods actually accept the generic object `RouteGenericInterface` which consists of `RequestGenericInterface` and `ReplyGenericInterface`. The `ReplyGenericInterface` adds the `Reply` interface to the list of interfaces.
> docs: add info about Reply generic interface

- docs/Ecosystem.md
Because `fastify-session` has been move to core plugin as `@fastify/session`, updating the documentation to redirect people to the new repository.
> doc: update status of session

- docs/Getting-Started.md
While reading the Getting Started guide, I was confused because I couldn't find where we "used the `decorate` API" until I understood that it's actually the MongoDB plugin that does use it.
I quickly investigated to find out that the code [used to actually call `fastify.decorate()`](https://github.com/fastify/fastify/commit/7788b90c3b84c229c44ffcb1e383183a7cc3f18f#diff-64f23e13f625e03181dae1a2c0162c0a047e09450e07dafd8569dc6afb6f813fL162) but it's not the case anymore thanks to the plugin. 
> Clarify getting started

- docs/TypeScript.md
Not solving #3244 , but correct the wrong statement.
> docs: fix import wrong statement

- docs/Ecosystem.md
> Add Fastify-allow plugin reference

- fastify.js
- test/request-error.test.js
1. Added check for writable state of the socket before trying to end request gracefully
2. Node.js updated their official documentation, so I changed link to the issue with a link to their official documentation
Fixes #3251
> Fixed socket leakage in TLS connection

- docs/Ecosystem.md
A fastify plugin for interacting with Appwrite backend server
> Add fastify-appwrite plugin

- README.md
- docs/Getting-Started.md
Adding ESM syntax to examples, as its the modern way to write JS these days.
This covers the main readme and the getting started example. Not sure if the whole documentation needs a patch
> Docs: esm syntax

- .github/workflows/ci.yml
We should not merge major into the project if the ci is green because a module may drop a Node.js supported by fastify
examples:
https://github.com/fastify/fastify/pull/3263
https://github.com/fastify/light-my-request/pull/132
> ci: automerge only minor semver

- CONTRIBUTING.md
- README.md
- docs/Guides/Contributing.md
- docs/Guides/Index.md
This pull request starts an informal guides section within the documentation by adding a new "contributing" guide. As discussed in  https://github.com/fastify/fastify/pull/2574#discussion_r494284789, we should started a concerted effort to separate our reference documentation from our informal guides. I see this PR as the first step in that process.
Additionally, I recently learned that it is possible to isolate VSCode instances such that each instance can have its own settings and set of extensions. Thus, this PR includes a guide on setting up such an instance specifically for working with Fastify. The idea being, that people can use a Fastify specific instance of VSCode so that their normal workflow does not conflict with our standards. 
Note: I modeled this guide after …
> Add contributing guide

- docs/ContentTypeParser.md
noticed this error this morning when reading docs about content type parsers.
> fixes minor typo in ContentTypeParser.md

- test/types/instance.test-d.ts
- types/instance.d.ts
adding missing type declaration for https://www.fastify.io/docs/latest/Server/#routing
> adding type for fastify.routing

- lib/route.js
- test/route.test.js
Fixes a bug where incorrect error messages were produced when using the `path` option instead of the `url` option for the route declaration with `route`method.
So
```javascript
fastify.route({
method: 'GET',
path: '/test'
})
```
would produce the error message: `Missing handler function for GET:undefined route.`
> fix error messages

- docs/ContentTypeParser.md
- docs/Routes.md
- lib/route.js
- test/route.test.js
- test/schema-examples.test.js
- test/schema-feature.test.js
Closes #3266. An error is now thrown if a body validation schema is specified for `GET` or `HEAD` routes. The docs also explain now that the request body validation is only available for `POST, PUT, PATCH, DELETE and OPTION` requests. The content-type parser documentation also now provides a more detailed explanation of when the request payload is parsed and when it is not.
> Payload validation

- docs/Ecosystem.md
Add my plugin `fastify-bree` to the Ecosystem. It is a plugin which provide scheduling of jobs using `bree`.
Any comments for improvement are welcome.
> docs: add fastify-bree

- lib/reply.js
- test/reply-error.test.js
> fixed unresponsive server  #3283

- lib/contentTypeParser.js
- test/custom-parser.test.js
Fixes an issue where it was not possible to add content type parsers after calling [`removeAllContentTypeParsers`](https://github.com/fastify/fastify/blob/main/docs/ContentTypeParser.md#removeallcontenttypeparsers).
Example
```javascript
fastify.removeAllContentTypeParsers()
fastify.addContentTypeParser('text/xml', function (request, payload, done) {
xmlParser(payload, function (err, body) {
done(err, body)
})
})
```
Documentation
- https://github.com/fastify/fastify/blob/main/docs/ContentTypeParser.md#removeallcontenttypeparsers
> fix: add content type parsers after removeAllContentTypeParsers

- test/types/request.test-d.ts
- types/request.d.ts
Fixing types declaration for `request.headers` - its no longer a readonly property following #2817 which added the ability to set custom headers
> fix headers no longer readonly

- build/build-validation.js
- docs/Server.md
- lib/configValidator.js
- test/internals/initialConfig.test.js
- test/request-error.test.js
Fixes https://github.com/fastify/fastify/issues/3282
I picked 72 seconds because bad things happen when two timeouts are the same on different machines. In this way things would work correctly on all platforms.
> Increase http2SessionTimeout and keepAliveTimeout to 72 seconds

- lib/reply.js
- test/schema-serialization.test.js
If a custom serializator returns something that is not a string, the request starve till the timeout (if set).
With this fix the response flow will continue as usual with Fastify's controlled error
> fix: check serialized payload

- test/types/instance.test-d.ts
- types/.eslintrc.json
- types/instance.d.ts
As far as I can tell, error handlers that return Promises are already handled: https://github.com/fastify/fastify/blob/0109643d76c578e389cf173c87402d7df30cd62a/lib/reply.js#L550-L557
> `FastifyInstance#setErrorHandler` supports async handlers

- .github/workflows/benchmark.yml
We are using `master` branch, however, the repository has changed it to `main` branch, and to prevent further bugs, I'm tagging to the latest major release.
> chore(benchmark): use tagged version to comment PR

- lib/reply.js
- test/stream.test.js
Replication scenario: https://github.com/fastify/fastify-static/issues/232
> fix: reply object not marked as sent for stream payloads

- README.md
I've clicked the logo so many times expecting the website to open instead of the image url.
Very common in other repositories so I can't be the only one 😄
> docs: link logo to the website

- lib/decorate.js
- test/decorator.test.js
- test/same-shape.test.js
Fixes: #3323 
When we `decorate` something that is not truthy, e.g. `null`. It will fall into `<k>.props` but not the `prototype`.
Currently, both `checkRequestExistence` and `checkReplyExistence` only check for `prototype` but not checking the new `<k>.props`.
Why I do not change `checkExistence` because it will fail the test for `instance` decoration.
> fix: check existence

- docs/Request.md
- docs/Server.md
A simple addition to `Request.md` now neatly mentions what specifies the format of the query property of a request (Fixes #3314).
A more complex addition to `Server.md` now better documents how users can modify query string handling and make query strings case insensitive (Fixes #2644). 
I decided to add this after stumbling upon all the conversations about query string case insensitivity (and the result agreed upon in #2647).
The related issues can be closed, as well as still open pull requests (namely #3235).
> Docs: Add and clarify query string handling tips

- lib/decorate.js
- lib/reply.js
- lib/request.js
- test/decorator.test.js
This is another followup from #3334.
This PR restore the optimization for all set values and remove a breaking change that was introduced in #3334, the coercion between `undefined` and `null`.
> Do not coerce undefined to null, always set it to decorated value.

- docs/Ecosystem.md
Add `fastify-supabase` plugin to fastify community ecosystem. (resolves https://github.com/fastify/fastify/issues/3286)
thank you @ruanmartinelli :)
> docs: add `fastify-supabase` to fastify ecosystem

- docs/Recommendations.md
I've added comments to potentially close #3300. I've mostly added what the directives and options mean in NGINX, and some basic recommendations. I assumed that the target audience does not necessarily know NGINX that well, and more advanced configurations/explanations are out of scope of the sample config.
I've rearranged some of the SSL configs so it's obvious what is needed and what is optional (OCSP stapling for example).
The proxy_pass directive does not need a port if you are using an upstream group. NGINX will also tell you that it's an error.
> Update NGINX section with comments and fixes

- lib/request.js
- test/internals/request.test.js
Adds a check on the existence of the request `socket` before accessing the attributes.
It should fix #3419
```
Suites:   96 passed, 96 of 96 completed
Asserts:  5497 passed, 2 skip, of 5499
Time:     28s
-----------------------------|---------|----------|---------|---------|-------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------|---------|----------|---------|---------|-------------------
All files                    |     100 |      100 |     100 |     100 |                   
fastify                     |     100 |      100 |     100 |     100 |                   
fastify.js                 |     100 |      100 …
```
> fix: verify request socket before access attributes

- fastify.js
- lib/schema-controller.js
- test/schema-feature.test.js
As stated in #3121, during the development of the plugin I noticed that when setting up a custom `SchemaController` on the second level of encapsulation (root -> instance), the custom Validator is not correctly inheriting the schemas defined on the root layer of encapsulation. Causing the following error:
`Failed building the validation schema for POST: /, due to error can't resolve reference some# from id #`
**Full Reproduction in the test case added**.
> fix: setSchemaController not inheriting Schemas from root parent

- lib/logger.js
- test/internals/logger.test.js
Adds a check on the existence of the request socket before accessing the attributes, in a previous commit was missed a check.
It should fix #3419
```
Suites:   96 passed, 96 of 96 completed
Asserts:  5498 passed, 2 skip, of 5500
Time:     31s
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |     100 |      100 |     100 |     100 |                   
fastify           |     100 |      100 |     100 |     100 |                   
fastify.js       |     100 |      100 |     100 |     100 | …
```
> fix: socket null in logger

- build/sync-version.js
- fastify.js
- lib/pluginUtils.js
- package.json
- test/bundler/webpack/bundler-test.js
- test/internals/version.test.js
- types/instance.d.ts
This change makes the "version" a reliable field, instead of
one that might be "undefined". Some issues with bundlers such
as "a wild package.json appears" are resolved as well.
Maintainers would have to ensure that versions in fastify.js
and package.json are in sync. That would be relatively trivial,
compared to the benefits, when it comes to such an essential
package.
To avoid errors and reduce maintenance burden, a test has been
added to ensure that the versions are in sync. It is configured
to run before publish.
Refs: #3110, #3113, #3155, #3185, #3191
Signed-off-by: Jesse Chan \<jc@linux.com>
> feat: make version field deterministic and reliable

- docs/Type-Providers.md
Hi,
the following PR closes https://github.com/fastify/fastify/issues/3421 and adds additional documentation how to use TypeBox with fastify v4.
> docs: Extend TypeBox documentation

- lib/server.js
- test/requestTimeout.test.js
> fix: server.requestTimeout miss when https

- docs/Serverless.md
Added Google Cloud Functions example to use Fastify as requests handler. (Related to https://github.com/fastify/fastify/issues/3382)
> docs: add Google Cloud Functions example to Serverless Documentation

- test/types/instance.test-d.ts
- types/instance.d.ts
> fix(typescript): define instance listen callback error nullable

- docs/Plugins.md
This PR replaces "sons" with "descendants" to avoid the default male in the language.
Would it be more accurate to use "children" instead of "descendants", or is "descendants" the more accurate term here?
> docs: replace "sons" with "descendants"

- lib/server.js
- test/maxRequestsPerSocket.test.js
server.maxRequestsPerSocket is missing when https.I change the logic of the condition of http2,https and http to avoid server's property missing after now.Because this is my second time to fix thing like this..Do you agree that
> fix: server.maxRequestsPerSocket miss

- docs/Getting-Started.md
Updates first route example to showcase use of `request.body` object. For context see https://github.com/fastify/fastify/discussions/3388#discussioncomment-1519333
> docs: add post example to intro

- fastify.js
- test/schema-feature.test.js
While still working on #3121 noticed when adding Schemas to child instances, these schemas were lost in the middle, causing any nested validation schema to fail the compilation step due to missing the schema(s) reference.
**Note**:
- This only happens when registering plugins (for instance not creating a new context)
- I'm not 100% why of the decision of using the parent of the SchemaController on each new registration instead of the one that belongs to the current instance, so please feel free to correct me if the approach is wrong or you think that can cause any side effect that I'm not considering within this PR 🙂 
> fix: use current instance schema controller

- docs/Reply.md
- This PR fixes issue [#3409](https://github.com/fastify/fastify/issues/3409) by adding documentation about  `set-cookie` header
> docs: add set-cookie special case

- lib/error-handler.js
- lib/reply.js
- test/stream.test.js
This PR adjusts some of the already merged PRs, so they are in line with the new way that reply.sent is handled (introduced in https://github.com/fastify/fastify/pull/3072).
https://github.com/fastify/fastify/pull/3261 & https://github.com/fastify/fastify/pull/3285: kReplySent does not exist anymore. We can simply delete those lines since they don't have any effect.
https://github.com/fastify/fastify/pull/3318: With the new way that the reply is handled, we do not have to do anything manually any more. Only the test had to be adjusted because of the reasoning explained in https://github.com/fastify/fastify/pull/3132.
> Adjust existing PRs for the new reply.sent handing

- fastify.js
- lib/context.js
- lib/decorate.js
- lib/pluginOverride.js
- lib/reply.js
- lib/request.js
- lib/route.js
- lib/symbols.js
- test/500s.test.js
- test/decorator.test.js
- test/helper.js
- test/request-error.test.js
This is an optimization that drops the encapsulation if decorateRequest and decorateReply has not been called. In common scenarios where most of the decorations happen top-level it can guarantee an improvement of 10% of throughput.
Fixes #3341
> Skip encapsulation of Request and Reply when not needed

- docs/Errors.md
- docs/Guides/Getting-Started.md
- docs/Hooks.md
- docs/LTS.md
- docs/Middleware.md
- docs/Plugins-Guide.md
- docs/Plugins.md
- docs/Reference/Encapsulation.md
- docs/Reference/Server.md
- docs/Reply.md
- docs/Routes.md
- docs/Validation-and-Serialization.md
No new line above Markdown headings is considered invalid in some compilers, including Docusaurus. This PR simply moves the `<a>` tags below the headers, which was already the format used in some files (such as `Decorators.md`).
EDIT: I also fixed an `<a>` link which could have been written as a Markdown (`[text](url)`) link in `Server.md`.
> Fix positioning of <a> tags relative to headers

- docs/ContentTypeParser.md
- docs/Decorators.md
- docs/Errors.md
- docs/Fluent-Schema.md
- docs/Guides/Contributing.md
- docs/Guides/Getting-Started.md
- docs/Guides/Index.md
- docs/Hooks.md
- docs/LTS.md
- docs/Lifecycle.md
- docs/Logging.md
- docs/Middleware.md
- docs/Migration-Guide-V3.md
- docs/Plugins-Guide.md
- docs/Plugins.md
- docs/Recommendations.md
- docs/Reference/Encapsulation.md
- docs/Reference/Server.md
- docs/Reply.md
- docs/Request.md
- docs/Routes.md
- docs/Serverless.md
- docs/Style-Guide.md
- docs/TypeScript.md
- docs/Validation-and-Serialization.md
- docs/Write-Plugin.md
- docs/index.md
This is a preparation commit before I start moving files into the Guide/Reference folders. I've manually removed any of the Docusaurus-specific changes for now so that the docs can still build against the current compiler (Metalsmith).
- All .md files are now connected via relative links (e.g. Request.md -> ./Request.md)
- Added absolute paths to previously broken links (e.g. ../examples/parser.js -> https://github.com/fastify/fastify/blob/main/examples/parser.js)
- Changed `<a>` tag property from `name` to `id` for consistency
- Updated tables of contents automatically with [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
- Replaced `<br>` and `<br/>` with newline (this is closer to the Markdown specification)
and the [Code of …
> Improve relative links and broken links on docs-reorg

- test/types/instance.test-d.ts
- types/instance.d.ts
Change `FastifyInstance.setErrorHandler` types on the handler to use `RouteGeneric` for the type of the promise return value, matching the typing of `RouteHandler`. This also makes sending a response via returning a value from an async function typecheck properly. The added tests mirror those from #2530.
P.S. This is basically a 1-year-late attempt at properly closing out #2466/#2467 :)
> fix(typescript): use RouteGeneric for setErrorHandler types

- docs/Ecosystem.md
> docs(ecosystem): add `middie` to core section

- .github/workflows/ci.yml
- package.json
- test/custom-parser.test.js
- test/handler-context.test.js
- test/http2/closing.test.js
- test/listen.test.js
- test/request-error.test.js
- test/router-options.test.js
- test/stream.test.js
- test/trust-proxy.test.js
superseded #3381 
Closes #3456
> add node 17

- docs/Ecosystem.md
Hey 👋  
We recently released [this plugin](https://github.com/immobiliare/fastify-metrics) which we use internally to collect usage/process metrics and send them to [statsd daemon](https://github.com/statsd/statsd)! We thought it could be useful for the community and wanted to share it, do you think it can be added to the ecosystem?
> docs(ecosystem): adds @immobiliarelabs/fastify-metrics

- package.json
- test/404s.test.js
- test/custom-parser.test.js
- test/hooks.test.js
- test/route.test.js
- test/router-options.test.js
This pull request resolves https://github.com/fastify/fastify/issues/3399
> chore: bump find-my-way to 5.1.0

- lib/decorate.js
- test/decorator.test.js
Address: https://github.com/fastify/fastify/issues/3517
That issue was added by: #3317 
> fix: use hasKey to check request dependencies

- docs/Guides/Benchmarking.md
- docs/Guides/Contributing.md
- docs/Guides/Ecosystem.md
- docs/Guides/Fluent-Schema.md
- docs/Guides/Getting-Started.md
- docs/Guides/Index.md
- docs/Guides/Migration-Guide-V3.md
- docs/Guides/Plugins-Guide.md
- docs/Guides/Recommendations.md
- docs/Guides/Serverless.md
- docs/Guides/Style-Guide.md
- docs/Guides/Testing.md
- docs/Guides/Write-Plugin.md
- docs/Reference/TypeScript.md
- docs/Reference/index.md
- docs/index.md
As with #3525 this PR implements the table of contents for the `docs/Guides`. It also applies hard line wrapping to each of the guides, and fixes some bad line wrapping in the `TypeScript.md` document (introduced by https://github.com/stkb/Rewrap/issues/93).
> Guides toc

- package.json
- test/types/type-provider.test-d.ts
- types/reply.d.ts
- types/request.d.ts
- types/route.d.ts
- types/type-provider.d.ts
This PR implements `Reply` type inference using the Type Provider mechanism submitted on PR https://github.com/fastify/fastify/pull/3398.
The current implementation involves specifying a union type for each expected status code
```typescript
server.get<{
Reply: string | number | boolean // varying reply type
}>('/', {
schema: {
response: { 
200: { type: 'string' },
400: { type: 'number' },
500: { type: 'boolean' },
}
} as const
}, (_, res) => {
res.send('hello')
res.send(42)
res.send(false)
})
```
The proposed implementation infers this union directly from the response schemas.
```typescript
server.withTypeProvider<JsonSchemaToTsProvider>().get('/', {
schema: {
response: {  // infer as string | …
```
> Type Provider Reply Types

- lib/route.js
- test/constrained-routes.test.js
047429eb832d7a631531a559231cfeacc1d682e7 introduced a handy new call to the router when new routes are defined to check if a HEAD route exists already before automatically registering one. This new call to the router didn't pass the newer third argument that .find expects for the derived constraint values. Most routes aren't constrained and thus never checked the derived constraints, so the undefined value was fine most of the time. But, for those using constraints, an error like this would be thrown when checking for the head route:
```
TypeError: Cannot read property 'host' of undefined
at Node.eval [as _getHandlerMatchingConstraints] (eval at Node._compileGetHandlerMatchingConstraints (/Users/airhorns/Code/fastify/node_modules/find-my-way/node.js:320:41), <anonymous>:9:32)
at …
```
> Pass constraint values to the router when checking for a preexisting HEAD route

- README.md
Fixes the broken documentation links. See https://github.com/fastify/website/issues/308
> docs: fix broken documentation links

- package.json
- test/http2/constraint.test.js
Add tests for secure http2 server routes with **host constraints**. This is part of the fix to the `find-my-way` package as discussed in #3408
Depends on delvedor/find-my-way#214
> Tests for http2 host constraint server

- docs/Guides/Fluent-Schema.md
- docs/Guides/Serverless.md
- docs/Guides/Style-Guide.md
- docs/Reference/ContentTypeParser.md
- docs/Reference/Decorators.md
- docs/Reference/Errors.md
- docs/Reference/Index.md
- docs/Reference/Plugins.md
- docs/Reference/Reply.md
- docs/Reference/Routes.md
- docs/Reference/Server.md
- docs/Reference/Validation-and-Serialization.md
Due to some reports about broken links, I'm opening this PR to fix all missing or old links.
> Fix docs broken links

- docs/Reference/Hooks.md
- types/hooks.d.ts
- types/instance.d.ts
Tests and implementation were already included for async onClose hooks, but documentation and TypeScript types were missing.
> Add missing types & docs for async onClose hook

- docs/Guides/Testing.md
- docs/Reference/TypeScript.md
> docs: Small improvements in the documentation

- lib/contentTypeParser.js
- test/als.test.js
- test/types/import.js
> Fix context tracking with als run

- docs/Reference/Plugins.md
>This is a change I disagreed with. I will likely revert all such declarations to full function declarations as I update the documentation. In this specific case, it is clearly wrong. A PR to fix this one would be quite welcome. - @jsumners 
Replace arrow functions with function expressions in the `Plugins` documentation.
> Documentation: replace `fastify.decorate` arrow functions with function expressions

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/package-manager-ci.yml
- docs/LTS.md
- test/esm/index.test.js
- test/http2/closing.test.js
Solves one of the issues in https://github.com/fastify/fastify/issues/3482 to prepare for v4 release
> build: drop node 12 support

- lib/reply.js
- test/internals/handleRequest.test.js
- test/internals/reply.test.js
Closes https://github.com/fastify/fastify/issues/3589. I decided to remove those tests since testing that fallbacks for writableEnded don't exist would be kinda useless.
> Remove .writableEnded fallbacks for node12

- fastify.js
the removed lines are already executed during the `add` call:
https://github.com/fastify/fastify/blob/bc40f5b54b6ce5b9d27ccea97661b6d03630d7ad/lib/hooks.js#L57
> chore: remove duplicated line

- docs/Reference/TypeScript.md
> docs(reference-typescript): fix formatting

- lib/pluginUtils.js
- test/plugin.name.display.js
- test/plugin.test.js
This PR gives to the user the ability to set the plugin name in encapsulated context.
It is useful for debugging purposes when using `fastify-autoload` that is now using the absolute file path as `pluginName` only.
Ref https://github.com/Eomm/fastify-overview/pull/23
> feat: manage display-name meta plugin

- docs/Guides/Index.md
- docs/Guides/Prototype-Poisoning.md
- docs/Reference/Server.md
Resolves issue #3003.
cc: @hueniverse
> Add prototype poisoning doc

- .github/workflows/ci.yml
- test/bundler/esbuild/bundler-test.js
- test/bundler/esbuild/package.json
- test/bundler/esbuild/src/fail-plugin-version.js
- test/bundler/esbuild/src/index.js
- test/bundler/webpack/bundler-test.js
- test/bundler/webpack/src/fail-plugin-version.js
- test/bundler/webpack/src/index.js
This PR fixes #3377: It includes esbuild tests to the package pipeline.
> Adding esbuild bundler to the pipeline

- .github/workflows/ci.yml
- package.json
Hello.
This PR aims to :
- Run the code linting once when a CI run is triggered (It will fail fast if linting needs to be fixed). (close https://github.com/fastify/fastify/issues/3621)
> chore (ci): run lint only once

- docs/Reference/Request.md
- fastify.js
- lib/route.js
- lib/symbols.js
- test/versioned-routes.test.js
Fixes #3625 
I think as a fast solution and not falling into the `version` constraint check in `find-my-way`. We can use a symbol to temporary store the header and revert it after `find-my-way` pick up the route. 
> fix: accept-version on default route

- test/404s.test.js
- test/types/hooks.test-d.ts
- types/hooks.d.ts
Hello.
This PR aims to :
- change typescript definitions of `this`to `FastifyInstance` (fix https://github.com/fastify/fastify/issues/3620)
- add a typescript test to avoid regressions
- fix a flaky `404s.test.js` test randomly timing out
> fix (types): `this` is `FastifyInstance`

- docs/Reference/Server.md
> docs: fix link to forceCloseConnections option

- docs/Guides/Prototype-Poisoning.md
> docs(Prototype-Poisoning): invalid content link

- .github/dependabot.yml
Dependabot's CI check didn't flag the config change in https://github.com/fastify/fastify/pull/3659 as an issue [until after it was merged into the main branch](https://github.com/fastify/fastify/runs/4952267835).
This PR resolves that by only providing one config object for NPM updates, at a weekly interval.
> build: correct dependabot config

- docs/Type-Providers.md
Address: https://github.com/fastify/fastify-type-provider-typebox/issues/2
> docs: add type provider encapsulation

- lib/reply.js
- test/schema-serialization.test.js
I have found that fastify sometimes can throw errors not caught by `errorHandler` and it's difficult to understand where it comes from.
Reduced Example you can find in the committed test:
Response schema with required field throws an error from `fast-json-stringify` when a required field is not found.
```
fastify.get('/', {
schema: {
response: {
200: {
type: 'object',
properties: {
name: { type: 'string' }
},
required: ['name']
}
}
}
}, function (req, reply) {
reply.code(200).send({ no: 'thing' })
})
```
So I decided that it will be ok idea to send the captured error to `errorHandler` like validation error, and add a sign that the error comes from serialization.
But here I need your advice on how to envelop error propely.
and the [Code of …
> Serialization errors will be send to errorHandler

- docs/Reference/Server.md
- fastify.js
- lib/server.js
- lib/symbols.js
- package.json
- test/custom-http-server.test.js
- test/helper.js
- test/https/custom-https-server.test.js
- test/internals/initialConfig.test.js
- test/internals/server.test.js
- test/listen.test.js
- test/logger.test.js
- test/stream.test.js
- test/versioned-routes.test.js
Supersedes https://github.com/fastify/fastify/pull/3546
Opening draft PR to close #3536 
1. Should the extra host binding block the Fastify application if an error is thrown?
- The actual implementation ignores all the extra hosts' errors if the OS default interface has started successfully.
2. Should the Fastify application be considered started when the default host and the extra ones are listening?
- The actual implementation consider the application started when all the `listen` calls are completed. The default host must be successful.
3. Should I remove all the `unref` calls in tests or the custom `emit` event is fine?
Todo:
Fixes https://github.com/fastify/fastify/issues/3027
> localhost binds to ipv4 and ipv6

- test/types/instance.test-d.ts
- types/instance.d.ts
- types/schema.d.ts
related to [#3366](https://github.com/fastify/fastify/issues/3366)
I'm Really happy to contribute! if something is wrong/ tests are bad feel I will  make it right as fast as I can
> Add Documentation and TS Types missed for FastifyInstance#setSchemaController

- .github/workflows/lock-threads.yml
This PR adds a new GitHub Action that will run once per day and lock any issue or pull requests that have not had any activity in the prior 90 days. I opted for 90 days here out of an abundance of caution. We added this same action to Pino with a 30 day window. I'm not opposed to the 30 day window here.
The docs for the action can be found at -- https://github.com/dessant/lock-threads
This action will take a several days to process the current history due to -- https://github.com/dessant/lock-threads#why-are-only-some-issues-and-pull-requests-processed
We _will_ see a lot of notifications that things have been locked. There's no way around that. We can speed up the initial processing by manually running the action through the [Actions](https://github.com/fastify/fastify/actions) tab.
and …
> Add action to lock threads

- fastify.d.ts
- test/types/fastify.test-d.ts
As pointed [in this issue](https://github.com/fastify/fastify/issues/3680), declaring jsonShorthand in Fastify options raise an error. This PR aims to include jsonShortand as boolean inside the available options.
> fix: added jsonShorthand in FastifyServerOptions

- .github/workflows/package-manager-ci.yml
> ci(package-manager): run `test:ci` instead of `test`

- .github/labeler.yml
> chore: fix plugin labeler

- docs/Reference/ContentTypeParser.md
- docs/Reference/Validation-and-Serialization.md
As `application-json` is not a default content-type for fetch- it's a foreseeably common error for new users to experience. And googling FST_ERR_CTP_INVALID_MEDIA_TYPE is not especially helpful. This PR adds a reference to the error to the relevant page, and to the concept of ContentTypeParser in the validation page.
>  Add reference to FST_ERR_CTP_INVALID_MEDIA_TYPE error in the docs for validation & content type parser

- test/types/hooks.test-d.ts
- types/hooks.d.ts
- types/register.d.ts
This fix the `onRegister` hook handler’s Typescript signature with an `options` parameters, as demonstrated in the [`onRegister` hook documentation](https://github.com/fastify/fastify/blob/main/docs/Reference/Hooks.md?plain=1#L480-L489).
I run into the issue as I was working on a (Typescript) plugin. I needed to hook on register to involve some logic with encapsulated contexts. This hook handler had to access the options the register function was given, but the type definition given after the `FastifyInstance` was a `HookHandlerDoneFunction`. 
Given the documentation and the tests I’ve conducted before making this pull request, I’m fairly confident this `options` parameter was mistakenly omitted in the `onRegister` hook handler signature.
- Export `RegisterOptions` interface in …
> fix(types): add opts param to onRegister hook handler signature

- .github/workflows/ci.yml
- .github/workflows/coverage-nix.yml
- .github/workflows/coverage-win.yml
- .taprc
- package.json
Currently, our CI code coverage reporting depends upon the unit tests succeeding. Which means if a unit run fails, no coverage report is uploaded to Coveralls for that suite. When the suite fails due to missing coverage, we have no easy way of seeing what coverage loss generated the error. In particular, non-Windows people cannot see the coverage report in https://github.com/fastify/fastify/runs/5259373178?check_suite_focus=true
This pull request adds a new step to our CI that generates coverage reports subsequent to linting and _prior_ to unit testing. The result of this coverage report will be attached to the Actions panel for the CI run as a zip file. This zip file can be downloaded and explored with a web browser.
I think this step could also be used to generate an `lcov` file to …
> Add coverage reporting per OS type

- docs/Guides/Database.md
Adds a guide's page for database integration. It focuses on officially maintained plugins (MySQL, Postgres, MongoDB, Redis, LevelDB).
> docs: add database guide page

- docs/Guides/Contributing.md
[vscode-eslint](https://github.com/microsoft/vscode-eslint) uses the Fastify local install of ESLint by default, as mentioned at the beginning of their [README.md](https://github.com/microsoft/vscode-eslint/blob/main/README.md):
> The extension uses the ESLint library installed in the opened workspace folder. If the folder doesn't provide one the extension looks for a global install version.
Also, the command: `ESLint: Manage library execution` [has been removed](https://github.com/microsoft/vscode-eslint/issues/1419) from vscode-eslint. This means, we can safely remove the last step from our CONTRIBUTING.md:
> Finally, we need to tell the eslint plugin to use the Fastify local install of eslint.
Press `cmd+shift+p` to bring up the VSCode command input, type `eslint: manage
library …
> Remove reference to 'ESLint: manage library execution' command

- .github/workflows/ci.yml
- types/.eslintrc.json
Alternative to https://github.com/fastify/fastify/pull/3737.
I looked at the actual problem and the typescript rule has a serious bug.
Apparently it cannot figure out anymore that https://github.com/fastify/fastify/blob/b2ce3d56021d98710cc879514b574547249fd8a2/test/types/hooks.test-d.ts#L142-L146 should lint against the async overload we had.
Given this is correct code and we should get the CI green again, I'll land this as soon as it pass. If somebody can open an issue against the typescript-eslint project, that would be awesome.
> Drop @typescript-eslint/no-misused-promises

- test/types/instance.test-d.ts
- types/instance.d.ts
Hello.
This PR aims to :
- add complete `fastify.listen()` typescript definitions (cf.: https://github.com/fastify/fastify/pull/3712#issuecomment-1058015854)
- add deprecations on typescript side to promote the use of the object options
(same PR as https://github.com/fastify/fastify/pull/3746 - automatically closed when the branch was deleted here https://github.com/fastify/fastify/pull/3712)
> feat (types): add complete `fastify.listen()` typescript definitions

- test/types/reply.test-d.ts
- types/reply.d.ts
Added response type of `ArrayBuffer` and `Buffer` to the serialize method in FastifyReply interface.
> Fix: response type of serialize method in FastifyReply interface

- docs/Reference/Server.md
Refs: https://github.com/fastify/fastify/pull/3712
> Fix typo in reference documentation for listen()

- .github/workflows/ci.yml
It’s important that we automerge major updates as they are the only ones that will be opened in most of our repos because we do not use lockfiles.
Let’s trust our tests to detect any potential breakage.
> Automerge major updates

- test/types/hooks.test-d.ts
- types/hooks.d.ts
By now, hooks use default Context Config for the `request` property. This PR implies using a custom Context Config for `request` in a hook if it was sent (repeats the same logic as for `reply`).
> Allow custom Context Config types for hooks' `request` properties

- test/types/hooks.test-d.ts
- types/hooks.d.ts
**This PR is based on #3786 for v3.x.**
By now, hooks use default Context Config for the `request` property. This PR implies using a custom Context Config for `request` in a hook if it was sent (repeats the same logic as for `reply`).
> (v3.x) Allow custom Context Config types for hooks' `request` properties

- docs/Reference/Reply.md
- lib/reply.js
- test/internals/reply.test.js
ref: https://github.com/fastify/fastify/issues/3788
> fix: set reply's default charset to utf8

- test/types/hooks.test-d.ts
- test/types/request.test-d.ts
- types/hooks.d.ts
- types/instance.d.ts
- types/request.d.ts
- types/route.d.ts
Initiated by this bug: https://github.com/fastify/fastify/issues/3775
I created a PR to fix the typings for the routeHandlers by using the `FastifyRequest` with a generic logger type.
As in the docs mentioned: https://www.fastify.io/docs/latest/Reference/Logging/#logging
> You can also supply your own logger instance. Instead of passing configuration options, pass the instance. The logger you supply must conform to the Pino interface; that is, it must have the following methods: info, error, debug, fatal, warn, trace, child.
However with the implemented type definitions it is not possible to use a custom LoggerInstance as the log property was only restricted to be of type `FastifyLoggerInstance` …
> add generic logger to route handler & FastifyRequest

- docs/Reference/Reply.md
- lib/errors.js
- lib/reply.js
- lib/symbols.js
- test/internals/reply.test.js
- test/reply-trailers.test.js
Closes #630
Some question
1. Is it fine for the `payload` as `null` when `stream` is sent?
2. Is `payload.on('end')` correct for `stream` handling and add trailers?
3. Is it fine for `trailer` only support sync function?
> feat: reply trailers support

- lib/reply.js
Optimized from last pr: https://github.com/fastify/fastify/issues/3789
> chore: change lastindexOf to endsWith

- lib/fourOhFour.js
- test/404s.test.js
- test/logger.test.js
Backport #3128 to `v3` branch and some new changes as requested.
After revisit the code, I think it should not break people but provide a better experience to the developer.
> (v3.x) fix: handle invalid url

- lib/fourOhFour.js
- test/404s.test.js
- test/logger.test.js
It is a follup PR for #3806. It provide the same behavior as `v3`.
> refactor: update 404 onBadUrl behavior

- lib/reply.js
- test/reply-trailers.test.js
> A sender MUST NOT send a Content-Length header field in any message that contains a Transfer-Encoding header field.
Due to https://tools.ietf.org/html/rfc7230#section-3.3.2
> reply: remove content-length when Transfer-Encoding is added

- test/404s.test.js
`test/404s.test.js` required `http-errors` twice.
- [na] tests and/or benchmarks are included
- [na] documentation is changed or added
> fix: remove duplicate require(http-errors)

- docs/Reference/Reply.md
- lib/errors.js
- lib/reply.js
- lib/symbols.js
- test/internals/reply.test.js
- test/reply-trailers.test.js
Backport #3794 and #3814 to `v3` branch.
I think the setting of backport CI has some problem. It received 403 when it try to push the commit.
https://github.com/fastify/fastify/runs/5710246658?check_suite_focus=true
> (v3.x) feat: reply trailers support

- .github/workflows/benchmark.yml
- .github/workflows/labeler.yml
- Fixes benchmark workflow failing to run
- Fixes labeller workflow failing to run
- permissions explicitly set in https://github.com/fastify/fastify/pull/3828 should negate security concerns of `pull_request_target`, as noted in the warning section in the [GitHub Actions docs here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
- Removes Git credentials and auth token after checkout in the benchmark workflow's benchmark job, to further negate security concerns of `pull_request_target`; credentials aren't used for anything else after the checkout
> ci: revert to using `pull_request_target`

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- docs/Reference/LTS.md
- lib/fourOhFour.js
- package.json
- test/listen.test.js
> chore: add node 18 to ci and benchmark

- lib/contentTypeParser.js
- package.json
- test/content-parser.test.js
Due to https://github.com/fastify/fastify-error/pull/69/. When content-type is empty, it will return :
```js
{
statusCode: 415,
code: 'FST_ERR_CTP_INVALID_MEDIA_TYPE',
error: 'Unsupported Media Type',
message: 'Unsupported Media Type: '
}
```
after change:
```js
{
statusCode: 415,
code: 'FST_ERR_CTP_INVALID_MEDIA_TYPE',
error: 'Unsupported Media Type',
message: 'Unsupported Media Type: undefined'
}
```
> content-type: return undefined when content-type is ''

- .github/workflows/backport.yml
Top level permissions and only running on merged PRs should negate security issues with `pull_request_target`:
https://github.com/fastify/fastify/blob/e29518145230ea54715685cfde4f8f213d5b14c7/.github/workflows/backport.yml#L16
> ci: allow backport to be run on fork prs

- docs/Guides/Ecosystem.md
- docs/Guides/Getting-Started.md
- docs/Guides/Migration-Guide-V3.md
- docs/Guides/Plugins-Guide.md
- docs/Guides/Write-Plugin.md
- docs/Reference/Encapsulation.md
- docs/Reference/Hooks.md
- docs/Reference/Middleware.md
- docs/Reference/Reply.md
- docs/Reference/TypeScript.md
Backported to v3, as requested in https://github.com/fastify/fastify/pull/3855
> docs: reference new `@fastify/*` modules

- docs/Reference/ContentTypeParser.md
- docs/Reference/Encapsulation.md
- docs/Reference/Hooks.md
- docs/Reference/Middleware.md
- docs/Reference/Plugins.md
- docs/Reference/Reply.md
- docs/Reference/Routes.md
- docs/Reference/Server.md
- docs/Reference/Validation-and-Serialization.md
Reference counterpart to #3876
> docs(reference): grammar and conciseness changes

- lib/pluginUtils.js
Added fastifyRc const and replaced conditional.
🌈 SUMMARY RESULTS 🌈  
SKIP ​ test/stream.test.js 1 skip of 75 435.886ms
~ should support send module 200 and 404
Suites:   ​104 passed​, ​104 of 104 completed​
Asserts:  ​​​5812 passed​, ​1 skip​, ​of 5813​
Time:​   ​28s​
-----------------------------|---------|----------|---------|---------|-------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------|---------|----------|---------|---------|-------------------
All files                    |     100 |      100 |     100 |     100 |                   
fastify                     |     100 |      100 |     100 |     100 |                   
fastify.js                 |     100 |      100 |     100 |     100 | …
> replaced semver check code per recommendation

- README.md
It seems hat the openjs foundation extracted the logo from the council repo to a special artworks repo.
> Fix link to OpenJS Foundation Image in Readme.md

- README.md
Previous link does not work anymore.
> Redirect Security Responsible Disclosure Badge in Readme.md to SECURITY.md

- test/listen.test.js
This PR prepare for the upcoming changes for https://github.com/nodejs/node/pull/43054
We can handle both `number` and `string` network interfaces and should not be failed even the local node is fall between `18.0.0-18.2.0` (assume that fix will released in `18.3.0`).
> test: prepare for network interfaces family change

- lib/hooks.js
- lib/route.js
- test/hooks.test.js
Maybe this behavior is expected, but "preParsing" and "onSend" hooks don't handle undefined/null errors when other hooks do.
> fix: all hooks should handle undefined error

- fastify.js
- lib/route.js
- package.json
Moved querystring parsing to the find-my-way router, where it parsed more efficiently. https://github.com/delvedor/find-my-way/pull/284
> Move querystring parsing to the router

- docs/Reference/Server.md
- fastify.js
- lib/route.js
- package.json
- test/constrained-routes.test.js
- test/types/instance.test-d.ts
- types/instance.d.ts
The motivation of this PR was described here https://github.com/delvedor/find-my-way/issues/272 by @matthyk. The main idea is to add an option to add a custom constraint strategy outside the Fastify constructor, in order to define strategies inside plugins. There is a PR that implements this option https://github.com/delvedor/find-my-way/pull/279.
Before merging it, I want to know your opinion:
- Is it option desirable?
- Are there some trouble spots in Fastify with it?
This PR isn't ready. I didn't add tests, docs, types, etc. I want to know if this option is needed before.
> Add constraint strategies outside Fastify constructor

- test/types/instance.test-d.ts
- types/instance.d.ts
getDefaultRoute is currently declared as a field, this PR changes it into a method. Fixes #3919.
> Fix getDefaultRoute type

- docs/Guides/Getting-Started.md
- docs/Reference/Errors.md
In the Getting Started guide, it is suggested that we should use `make-promises-safe`, but after clicking through and reading a bit, it became clear that it doesn't apply if you're already on the latest Node version.
In the first version of this PR I added a bit of text explaining that you only need this module if you use Node <=14. After some feedback in the comments it was suggested that any mention of `make-promises-safe` could be removed.
---
> Remove mentions of `make-promises-safe` because it is only needed with Node <=14

- docs/Guides/Testing.md
- docs/Reference/Logging.md
Passing prettyPrint: true/false/{} at the top level to pino configuration is deprecated.
Update docs to configure pino-pretty as a transport when in development, as suggested here — https://github.com/pinojs/pino-pretty#programmatic-integration
> docs(Reference/Logging): update suggested pino-pretty configuration

- README.md
In order to complete a few releases in some plugins (https://github.com/fastify/fastify/issues/3733) without bothering you all, I need to be invited to the Plugins team :smile:
> doc: add RafaelGSS to Plugins team

- test/types/route.test-d.ts
- types/route.d.ts
- types/type-provider.d.ts
Fix: https://github.com/fastify/fastify/issues/3923
This PR fixes the problem when returning the `Reply` parameter on the `Handler`.
The current implementation allow us to return the `Replay` parameter only on async `Handlers`.
```typescript
const routeHandler: RouteHandlerMethod = async (request, reply) => {
return reply.send();
}
```
But it is not the same for sync `Handlers`.
Add the `Reply` parameter type on the `Handlers` return types, to both (async and sync) have the same behavior.
```typescript
const routeHandler: RouteHandlerMethod = (request, reply) => {
return reply.send();
}
```
> fix: handler return reply type

- docs/Guides/Index.md
Back ticks meant the guide was not appearing on the website:
> docs(guides): fix page name style

- test/types/logger.test-d.ts
- types/logger.d.ts
Update Logger types to add options to the child function.
ChildLoggerOptions and redactOptions interface was copied from the pino library types.
logger test runs.
> Child log level in bindings is deprecated

- test/types/logger.test-d.ts
- types/logger.d.ts
> chore: Fix types for child loggers

- build/build-validation.js
- docs/Reference/Server.md
- fastify.d.ts
- fastify.js
- lib/configValidator.js
- lib/errors.js
- lib/route.js
- test/close-pipelining.test.js
- test/close.test.js
- test/custom-http-server.test.js
- test/internals/initialConfig.test.js
This PR aims to leverage the new Node.js 18.2.0 APIs if available and changes the `forceCloseConnection` option as follows:
* `forceCloseConnection=false` - No connection handling is done
* `forceCloseConnection=true` - Use `closeAllConnections` if available, otherwise the fastify connection handling.
* `forceCloseConnection="idle"` - Use `closeIdleConnections` if available, otherwise throws an error.
The option defaults to `"idle"` if the server supports `closeIdleConnections`, otherwise to `false`.
Fixes #3924.
> feat: Use new Node.js' connection closing API if available

- .github/workflows/backport.yml
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency, this allows a subsequently queued workflow run to interrupt previous runs in PRs.
As an example: You open a PR and the CI workflow starts running. You commit another change to that PR, however you have to wait for the CI workflow running on that initial PR commit to finish before it will test your new commit.
With `concurrency` it will cancel that already running workflow and start up the new one.
This should save time when making PRs with multiple commits.
> ci(ci): use concurrency in pull requests

- docs/Reference/Validation-and-Serialization.md
- lib/schemas.js
- lib/validation.js
- test/schema-serialization.test.js
Fixes https://github.com/fastify/fastify-swagger/issues/611
allow passing `default` as status code and treat it as the last fallback.
> feat: allow default as status code

- .github/workflows/backport.yml
- .github/workflows/ci.yml
Put it in the wrong workflow in https://github.com/fastify/fastify/pull/3973 😞 
> ci: move `concurrency` to correct workflow

- docs/Reference/Routes.md
I added the example code to show how to access to path params.
> added path parameters examples to URL BUILDING section

- lib/pluginUtils.js
- test/plugin.test.js
This PR addresses my comment at https://github.com/fastify/fastify/pull/3879/files#r865519397
The result is that a Fastify release candidate will load any existing plugins as if they target the RC. This should reduce the noise during the RC phase (e.g. reduce the amount of issue people file about a new plugin version not loading).
Notice that the first commit is a failing test and the second commit adds the code needed to implement the feature.
> Support prior version plugins during the release candidate phase

- build/build-error-serializer.js
- package.json
- test/build/error-serializer.test.js
- test/build/version.test.js
Follow Up #3996 
I decide to use `standard` to check the code syntax.
And we should check if the `error-serializer.js` out-dated before release.
We don't identify the breaking from `fast-json-stringify` because we never validate if it is the latest code.
> test: error serializer

- lib/reply.js
- test/reply-error.test.js
600 is not a valid HTTP status code, but `reply.code()` currently allows it, likely due to an off-by-one error in its validation.
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
https://datatracker.ietf.org/doc/html/rfc2616#section-10
> fix: disallow reply status code 600

- lib/server.js
- test/listen.test.js
> fix: Fastify.listen({path: '...'}) should not also listen on a port

- test/stream.test.js
I increased the timeout. CI fails sometimes.
https://github.com/fastify/fastify/runs/6907766958?check_suite_focus=true
https://github.com/fastify/fastify/runs/6907546308?check_suite_focus=true
> test: fix request terminated should not crash fastify test

- test/types/plugin.test-d.ts
- test/types/register.test-d.ts
- types/register.d.ts
> fix: propagate generics from FastifyRegister to plugin type

- lib/reply.js
- test/404s.test.js
- test/internals/reply.test.js
Fixes https://github.com/fastify/fastify/issues/3994
> feat: make reply.redirect() and reply.callNotFound() return reply

- docs/Reference/Server.md
- fastify.d.ts
- test/types/instance.test-d.ts
- types/schema.d.ts
Fixes https://github.com/fastify/fastify/issues/4002
The `schemaController` bucket interface from [here](https://github.com/fastify/fastify/blob/main/lib/schema-controller.js#L54) uses `add` not `addSchema`. This PR ensures that the docs + types reflect the correct name.
> fix: fix schema controller types

- docs/Reference/Type-Providers.md
wrong imported name in json schema to ts type provider example which will lead to `no exported member named` error, if anyone trying to just copy-paste the example
- [*] documentation is changed or added
- [*] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
> Docs(Reference): remove "Type" from imported name

- docs/Guides/Migration-Guide-V4.md
Adding two notes from an application update of mine where I needed to make the following changes:
```diff
-      reply.res.setHeader('Content-Type', 'image/png');
-      qrcode.toFileStream(reply.res, dest.url);
+      reply.raw.setHeader('Content-Type', 'image/png');
+      qrcode.toFileStream(reply.raw, dest.url);
+
+      return reply;
```
> docs(guides): add two v4 breaking changes

- docs/Guides/Migration-Guide-V4.md
> docs(guides): breaking change exposeHeadRoutes

- test/build/error-serializer.test.js
Related #4049 
When targeting branch to `github`, it may install the repo using `CRLF` as line break.
The line break should not be the cause for test failure.
This PR fixes the false negative signal based on line break.
> test: fix flaky test

- fastify.js
- lib/route.js
> refactor: use object as internal route args

- docs/Reference/Validation-and-Serialization.md
- lib/handleRequest.js
- lib/validation.js
- test/reply-error.test.js
- test/schema-feature.test.js
- test/validation-error-handling.test.js
As part of the error handling refactoring of #3261, we should
not be setting a custom status code for validation routes.
We should rely only on the error.statusCode property instead and
leave the user full customization capabilities. Unfortunately
a change was missed.
Fixes: https://github.com/fastify/fastify/issues/4048
Ref: https://github.com/fastify/fastify/pull/3261
> feat: make sure all validation errors have a statusCode set

- lib/error-serializer.js
- package.json
- test/schema-feature.test.js
This PR shows that all Fastify tests work with https://github.com/fastify/fast-json-stringify-compiler/pull/14 and https://github.com/fastify/fast-json-stringify/pull/462 changes.
> fix: use ajv for schema ref resolving

- docs/Guides/Ecosystem.md
> Add plugin lcache by alphabetic order

- lib/context.js
- lib/route.js
- lib/symbols.js
- test/hooks.test.js
- test/pretty-print.test.js
Fixes #4044 
I don't think we should fix #4044, but I submit this PR for others to determine. 
> fix: onRoute hook should not be called when it registered after route

- test/types/request.test-d.ts
- types/type-provider.d.ts
Fixes #4063 
Based off of https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types.
I believe this still satisfies the initial reason these `keyof`s were here. As a previous comment on `ResolveFastifyRequestContext` (the previous generation of this) said:
```ts
/**
* This type handles request context resolution either via generic arguments
* or type provider. If the user specifies both generic arguments as well as
* a type provider, this type will override the type provider and use the
* generic arguments. This enables users to override undesirable inference
* behaviours in the type provider.
*/
```
> Use a union-aware keyof operator

- docs/Reference/TypeScript.md
Docs #4073 Update TypeScript docs regarding typebox to use the new type provider.
> docs: Update TypeScript docs regarding typebox #4073

- test/types/request.test-d.ts
- test/types/type-provider.test-d.ts
- types/route.d.ts
Fixes https://github.com/fastify/fastify/issues/4088
> Make type provider-provided return types be enforced

- docs/Reference/Hooks.md
This is a very common practice that new users have to guess (specially on TypeScript is
not obvious how to do it at a first sight), so I'm improving the docs as suggested by @mcollina
and to meant to close https://github.com/fastify/help/issues/551 on the help repo.
> docs: explain common usage for injection into request instances

- .github/workflows/integration.yml
- .github/workflows/links-check.yml
Using `main` is asking for trouble, if a broken commit is made to an action's branch then we will immediately feel it.
It is considered the least secure method of referencing GitHub Actions.
If we want to be as secure as possible then we should be referencing them using the full length commit SHAs.
Sources:
- [GitHub Docs - Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
- [GitHub Security Lab - Keeping your GitHub Actions and workflows secure Part 3: How to trust your building blocks](https://securitylab.github.com/research/github-actions-building-blocks/)
- [OSSF - Security Scorecards](https://github.com/ossf/scorecard/blob/main/docs/checks.md) (Recommended by GitHub)
and the [Code of …
> ci: reference actions using tags

- docs/Reference/Type-Providers.md
TypeBox no longer requires the `kind` and `modifier` keywords to be added to Ajv (since v0.24.0).
See:
- https://github.com/sinclairzx81/typebox/blob/master/changelog.md#0240
- https://github.com/fastify/fastify-type-provider-typebox/issues/19
> Remove redundant docs on TypeBox properties

- .github/scripts/lint-ecosystem.js
- .github/workflows/lint-ecosystem-order.yml
- docs/Guides/Ecosystem.md
This PR adds a new workflow to lint the "Community" section of the ecosystem doc in order to verify that the items are in alphabetical order. We can see the result in this run -- https://github.com/fastify/fastify/runs/7123293753?check_suite_focus=true#step:3:11
Notice that there are some items in the doc that are currently out of order.
> Add ecosystem linting

- test/types/fastify.test-d.ts
- test/validation-error-handling.test.js
- types/schema.d.ts
> fix: `FastifySchemaValidationError` type insufficient

- test/types/instance.test-d.ts
- types/instance.d.ts
For issue #3942, the changes are tested via unit tests.
> fix: Add types to server properties

- docs/Reference/TypeScript.md
> docs(TypeScript): Fix a few typos

- README.md
I know this is an stupid PR but clicking any relative link from `https://github.com/fastify/fastify` README.md preview will take you to the desired href but not scroll you into view of the specified header in the link. Once you are already inside `https://github.com/fastify/fastify/blob/main/README.md` relative links will correctly scroll you into the header.
> docs: fix links on README

- docs/Guides/Plugins-Guide.md
Added a reminder note when using decorateReply and decorateRequest to use functions defined using the `function` keyword instead of *arrow function expressions*.
> docs(Guides/Plugins-Guide.md) : add reminder

- types/instance.d.ts
The options interface for `FastifyInstance.listen` was duplicated, which could potentially lead to type signature and documentation differences between the two instances. To solve this, I have made a new interface to unify the two, so there's only one source of truth for both overloads.
I also added `export` to it because I found it useful - I maintain a library that uses Fastify and it allows users to configure it by passing an object with all the options, which is one of the supported (and non-deprecated) overloads of the `listen` function. Currently, we would need a [very hacky type](https://github.com/microsoft/TypeScript/issues/32164#issuecomment-811608386) to get said options from the overloads.
<details>
<summary>Click to see the code</summary>
```typescript
import type { …
```
> refactor(types): deduplicate `listen` options and export it

- docs/Guides/Database.md
> sample usage code fixed

- package.json
- test/build/error-serializer.test.js
Otherwise CI will _always_ be red after a new release of fast-json-stringify is issued. This is quite annoying.
> run error serializer check only before release

- test/types/instance.test-d.ts
- types/.eslintrc.json
- types/instance.d.ts
This reverts commit 20263a1bf8c8195d4692c634ecba86baa918b2d5.
I don't think we can land this change. Moreover I don't think the change is correct.
After applying that change, I did not find a way to make https://github.com/fastify/fastify-passport/blob/4b912074ad2273172b65eb44e52201e37583226e/src/CreateInitializePlugin.ts#L9-L13 compile.
> Revert "Re-add typed decorators (#4111)"

- lib/contentTypeParser.js
- test/content-parser.test.js
Well I think it is nicer to have the caching only happening if we dont have a direct match.
> dont cache unnecessary content types

- fastify.js
- test/request-error.test.js
When fastify server receives request with invalid url
in a reused connection, it closes the connection
instead of 400 Bad Request reply.
The closed connection is then propagated by load balancer (ALB)
as 502 error. This turns client errors into closely monitored
server errors.
`socket.bytesWritten` is never going to be 0 on reused connection.
> fix: default clientError replies on reused connection (#4101)

- docs/Guides/Ecosystem.md
> docs(ecosystem): add electron-server

- fastify.d.ts
- test/types/import.ts
Follow-up to #4013, I missed that the exports in each file were manual and not `export *`'d as I'm used to, sorry for that 😅
This patch allows developers to import `FastifyListenOptions` from `fastify` instead of `fastify/types/instance`.
> types: re-export `FastifyListenOptions` in top-level types

- docs/Reference/HTTP2.md
> docs: remove http2 experimental status (#4142)

- test/types/hooks.test-d.ts
- test/types/request.test-d.ts
- test/types/type-provider.test-d.ts
- types/hooks.d.ts
- types/instance.d.ts
- types/reply.d.ts
- types/request.d.ts
- types/route.d.ts
- types/type-provider.d.ts
This PR provides a potential fix for https://github.com/fastify/fastify/issues/4120. It carries out a number of refactorings to defer inference of the `FastifyRequestType` until inside the `FastifyRequest`. By deferring, it enables varying types to be inferred at multiple call sites (typically external hook/handler functions).
These updates permit the following usage
```typescript
// -------------------------------------------------------------------
// Handlers: Inline
// -------------------------------------------------------------------
interface InlineHandlerProvider extends FastifyTypeProvider { output: 'handler-inline' }
// Inline handlers should infer for the request parameters (non-shared) …
```
> Fix #4120: Defer resolution of FastifyRequestType until FastifyRequest

- types/request.d.ts
**Note**: Thanks to @conioX for the heads up.
The PR fixes a bad naming of the function `validateInput` in the TS Types.
> fix(types): bad naming of `validateInput`

- docs/Reference/Logging.md
- test/types/logger.test-d.ts
- test/types/request.test-d.ts
- types/logger.d.ts
Using pino.BaseLogger allows to use an own logger implementation in fastify.
The interface describes only base properties unlike pino.Logger that requires
to implement all properties of pino.
Closes #4148
> feat(logger): use pino.BaseLogger as main interface for fastify logger

- docs/Reference/Server.md
fixed typo in docs/reference/Server.md
The Markdown for an inline link is []() .
> fix typo in docs/reference/Server.md

- test/types/reply.test-d.ts
- test/types/type-provider.test-d.ts
- types/type-provider.d.ts
Along with #4076, fixed a problem that when union type passed as Reply to RouteGeneric.
This fix revealed that the test added in #4089, and includes fix for that.
> Make ResolveFastifyReplyType union-aware

- docs/Reference/Hooks.md
- docs/Reference/Server.md
Integrated docs for `setErrorHandler` and `onResponse` hook.
Related to Issue #4173 
> Docs: onResponse hook error logging

- docs/Reference/Routes.md
Async example didn't do anything async and never returned a payload, so converted to sync.
> docs(reference/routes): fix `onSend` example

- lib/server.js
- test/upgrade.test.js
Fixes https://github.com/fastify/fastify-websocket/issues/207
> Forward upgrade from secondary server to primary

- test/schema-examples.test.js
We have ajv-formats in devDependencies but dont use it anywhere. In order to check if ajv-formats does work in regards to https://github.com/fastify/help/issues/732 I wrote the test to ensure that it should work.
> add unit test for ajv-formats

- docs/Reference/Validation-and-Serialization.md
In query string coercion example, query param passed is `ids`. Thus, the resulting curl response should have `ids` param instead of `hello`.
> docs(validation-and-serialization): Fix example on query string coercion

- lib/context.js
- test/hooks-async.test.js
Fixes https://github.com/fastify/fastify-static/issues/334
> make sure preSerialization hooks are null by default

- CONTRIBUTING.md
v3 was missing, so a table seems more readable
> chore: fastify branch list

- fastify.d.ts
- test/types/fastify.test-d.ts
The [docs](https://www.fastify.io/docs/latest/Reference/Server/#https) say that `fastify.https` can be set as `null` for not making the socket be configured for TLS. This PR updates the types to reflect that, since it currently only allows it to be `https.ServerOptions`
> fix(types): allow `fastify.https` to be `null`

- docs/Reference/TypeScript.md
in reading docs I found a typo issue to change.
it seems 'server' not 'fastify'.
```typescript
const server = fastify()
// stuffs...
server().register(plugin, {}) // Error - options object is missing required properties
server().register(plugin, { option1: '', option2: true }) // OK - options object contains required properties
```
> chore: fix typo in docs for typescript chapter

- fastify.js
- test/request-error.test.js
this PR is a back-port of the work done in [this](https://github.com/fastify/fastify/pull/4133) PR to the 3.x branch
> fix: backport reused connection fix

- docs/Guides/Migration-Guide-V4.md
This PR improves the migration guide to explicit how to define routes when `onRoute` is also used.
> docs: improved migration guide for onRoute

- docs/Guides/Migration-Guide-V4.md
This changes the following:
- General tidy and restructure of sentences to improve clarity; removes waffle
- Adds section regarding deprecation of variadic `fastify.listen()` method under the non-breaking changes header
- Renames **"Deprecation of `app.use()`"** section to **"Removed `app.use()`"** to reflect that the function has been fully removed and not just deprecated
- Updated example handlers to be inline with style used in "Getting-Started" guide
What the guide is still missing:
> docs(guides/migration-guide-v4): update content

- docs/Reference/Type-Providers.md
Remove Ajv configuration from example code in the Type Providers documentation.
As described in https://github.com/fastify/fastify/pull/4095, TypeBox no longer requires explicitly configuring Ajv to recognize the `kind` and `modifier` keywords.
> docs: Remove Ajv configuration from TypeBox Type Provider examples

- lib/schemas.js
- test/schema-special-usage.test.js
Fix https://stackoverflow.com/questions/73549034/error-with-route-validation-after-upgrading-fastify
> fix: visit schemas with custom prototype

- docs/Reference/Server.md
- fastify.js
- lib/route.js
- test/has-route.test.js
- test/types/route.test-d.ts
- types/instance.d.ts
> feat: add hasRoute

- docs/Reference/Server.md
Fixing #schema-validator url at https://www.fastify.io/docs/latest/Reference/Server/#ajv
> Docs: Fixing #schema-validator url at ./Reference/Server/#ajv

- docs/Guides/Ecosystem.md
> chore(doc): fix format

- fastify.d.ts
- test/types/fastify.test-d.ts
This is a very small change just to re-export RouteGenericInterface which is needed by typescript 4.8.x for implementations of RouteHandlerMethod
I created an issue for this https://github.com/fastify/fastify/issues/4235 that will be solved by this PR.
> chore: export RouteGenericInterface

- .github/scripts/lint-ecosystem.js
Improve ecosystem linting script by returning an error in case of an improperly added module name pattern (i.e., not enclosed with backticks)
Resolves #4256 
> chore: improve `Ecosystem.md` linter to check for improper module name patterns

- test/unsupported-httpversion.test.js
This behaviour has changed on v18.9. It's now validating and returning `400 Bad Request`.
For further information, see: https://github.com/nodejs/node/pull/44344
> test: remove assert to invalid HTTP version

- .github/scripts/lint-ecosystem.js
- docs/Guides/Ecosystem.md
Extend the ecosystem linter functionality (module name validation + ordering) to all `Ecosystem.md` sections (`Core`, `Community`, `Community Tools`) instead of `Community` only.
Relevant Issues/PRs: #4256 #4257
> chore: improve `Ecosystem.md` linter to lint all sections

- examples/typescript-server.ts
Fixing #4259
Hi, Actually this's my first contribution to this great framework, and hopefully not the last one. 
Let me know if anything is missing or could be improved. 
I've checked the changes proposed at https://github.com/fastify/fastify/pull/3274, and updated the example accordingly. 
Signed-off-by: iifawzi <iifawzie@gmail.com>
> Fixing #4259 - Updating typescript example according to the validation changes

- lib/server.js
- test/listen.deprecated.test.js
resolves: https://github.com/fastify/fastify/issues/4267
At the moment when using  the variadic signature of `listen` and passing the `port` as a `string`, the `port` is converted to `0`  even though the signature allows `string` as type.
With this PR it is possible to convert the `port` from `string` to `number`, and only in case the `string` cannot be parsed to a valid integer it converts it to `0`.
> Variadic listen signature allows string port

- docs/Reference/TypeScript.md
Remove Ajv configuration from the example code in the Type Providers documentation.
As described in https://github.com/fastify/fastify/pull/4249, TypeBox no longer requires explicitly configuring Ajv to recognize the kind and modifier keywords. I got confused while reading the docs and noticed that `ajvTypeBoxPlugin` is not available in `@fastify/type-provider-typebox`. A few searches through the different repos and commits got me to realise that this part of the doc wasn't updated and also the merged PR #4249 is not yet reflected in the documentation.
> doc: Remove Ajv configuration for TypeBox in TS examples

- docs/Guides/Ecosystem.md
This commit/PR adds the following plugins to the community section of the plugins' list:
- [`@ethicdevs/fastify-custom-session`](https://github.com/EthicDevs/fastify-custom-session)
- [`@ethicdevs/fastify-git-server`](https://github.com/EthicDevs/fastify-git-server)
Hope you'll like them 😛
> docs(ecosystem): add 2 new fastify v3.x+ plugins

- lib/route.js
- test/route.test.js
> fix: prevent reuse mutated route option for head

- .github/workflows/ci.yml
Right now we run the test for the coverage check.
We could run them only after the linting
> ci: reduce ci test when linting fails

- lib/contentTypeParser.js
- test/404s.test.js
> Check if route exist before checking Content-Type of body

- lib/contentTypeParser.js
- lib/reply.js
- lib/server.js
- test/internals/reply-serialize.test.js
Here is a small benchmark for `Number(value)` vs `parseInt(value)`
Number: 67.073ms
parseInt: 206.781ms
```javascript
var { time, timeEnd } = console
var I = 1e8;
var y;
time("Number")
for (var i = 0; i < I; i++) y = Number(i)
timeEnd("Number")
time("parseInt")
for (var i = 0; i < I; i++) y = parseInt(i)
timeEnd("parseInt")
```
```
➜  fastify git:(perf/reply) npx concurrently -k -s first "node ./examples/simple.js" "npx autocannon -c 100 -d 10 -p 10 localhost:3000/"
[1] Running 10s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1]
[1]
[1] ┌─────────┬──────┬──────┬───────┬───────┬─────────┬─────────┬────────┐
[1] │ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev   │ Max    │
[1] ├─────────┼──────┼──────┼───────┼───────┼─────────┼─────────┼────────┤
[1] …
```
> Replace parseInt with Number at get 6% boost

- .github/workflows/lint-ecosystem-order.yml
- .github/workflows/md-lint.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- docs/Guides/Plugins-Guide.md
Add an example to the plugin guide how the onRoute hook can be used #4282 .
> docs: onRoute hooks in plugins

- .github/scripts/lint-ecosystem.js
- .github/workflows/lint-ecosystem-order.yml
- docs/Guides/Ecosystem.md
Added annotations + summary output for the Linting GHA. See examples of outputs below:
- Success: [https://github.com/zrosenbauer/example-annotations-for-fastify/pull/3](https://github.com/zrosenbauer/example-annotations-for-fastify/pull/3)
- Failure: [https://github.com/zrosenbauer/example-annotations-for-fastify/pull/2](https://github.com/zrosenbauer/example-annotations-for-fastify/pull/2)
**Summary Sample**
<details>
</details>
**Annotations Sample**
<details>
</details>
> chore: Lint eco system error

- docs/Guides/Ecosystem.md
Added `@fastify/one-line-logger` to the ecosystem core plugins.
I thought this interesting module is worth adding to the ecosystem plugins page, so that the community is more aware of it.
> docs(ecosystem): Add `@fastify/one-line-logger`

- docs/Guides/Ecosystem.md
> docs(ecosystem): add slow down plugin

- lib/route.js
- lib/schema-controller.js
- lib/validation.js
- test/internals/validation.test.js
- test/schema-feature.test.js
- test/schema-validation.test.js
We should not take any assumption that `object` is something we want and mutate the `headers` schema.
Instead, whenever the `user` pass custom validator. All the responsibility should be given to the user and that library to handle.
Fixes https://github.com/fastify/fastify-type-provider-typebox/issues/42
- [] documentation is changed or added
> fix: custom validator should not mutate headers schema

- docs/Reference/Routes.md
- lib/handleRequest.js
- test/search.test.js
Trying to migrate to fastify over from express, one of the bigger blockers we had is how we treat the SEARCH request. Basically handle it as a GET request with a body, which after digging into your codebase realized SEARCH body was not being parsed at all. The [webDAV SEARCH specs](https://www.rfc-editor.org/rfc/rfc5323#section-2.2.2) specifically mention that SEARCH can have a body so not sure why this wasn't allowed in https://github.com/fastify/fastify/pull/3836 . Also noticed the tests were pretty non existent for the search methods, modified them to hopefully catch any accidental breakage in the future.
> feat: parse request body for http SEARCH requests

- docs/Reference/Type-Providers.md
Type `FastifyLoggerInstance` has been marked as deprecated in favor of `FastifyBaseLogger`. 
https://github.com/fastify/fastify/blob/450416e834838b85d9189de8091a243b854ad6a3/types/logger.d.ts#L27-L30
This commit replaces it with the correct type in the [example snippet](https://github.com/samialdury/fastify/blob/450416e834838b85d9189de8091a243b854ad6a3/docs/Reference/Type-Providers.md#type-definition-of-fastifyinstance--typeprovider).
> docs(type-providers): replace FastifyLoggerInstance with FastifyBaseLogger

- CONTRIBUTING.md
> docs(contributing): clarify teams for joiners

- lib/server.js
- test/reply-code.test.js
- test/server.test.js
> test: add number coersion related tests

- docs/Reference/Type-Providers.md
> fix: Fix typo in docs/Reference/Type-Providers.md

- docs/Guides/Testing.md
> docs: add test examples with undici and fetch

- docs/Reference/Hooks.md
Closes #4319. 
I have added @Uzlopak [solution](https://github.com/fastify/fastify/issues/4319#issuecomment-1266184728) to the documentation as a recommended approach.
> update onRoute hook docs

- docs/Reference/Errors.md
- docs/Reference/Routes.md
- docs/Reference/Server.md
- fastify.js
- lib/errors.js
- lib/route.js
- package.json
- test/constrained-routes.test.js
- test/router-options.test.js
Add support for async constraints
> feat: support async constraint

- lib/error-handler.js
- test/content-type.test.js
> fix: error handler content-type guessing

- lib/schema-controller.js
- test/schema-special-usage.test.js
fixes https://github.com/fastify/fastify/discussions/4339
Let the user remove totally the default compilers.
> fix: should now call default schema compilers

- docs/Guides/Ecosystem.md
> docs(ecosystem): add @fastify-userland plugins and tools

- docs/Reference/Reply.md
…pecified manually when sending back streams.
> docs(reply): specify streams content-type

- docs/Reference/Errors.md
- docs/Reference/Hooks.md
- docs/Reference/Routes.md
Updates document changes introduced in #4322 and #4323.
> docs(reference): grammar and structure fixes

- docs/Reference/Decorators.md
This PR adds example of how decorators dependency works. Related with issue #4147 
> docs: example how decorators dependencies works

- lib/route.js
- test/hooks.test.js
Unfortunately https://github.com/fastify/fastify/pull/4332 was too restrictive and it broke quite a few of our modules, e.g. https://github.com/fastify/fastify-http-proxy/blob/72703f28db516652fdd0fd08f17e269f8947b6b3/index.js#L221 has the value as `undefined`. This makes it _less_ restrictive by allowing `undefined` as a value for single-level hooks.
Given that the case mentioned in https://github.com/fastify/fastify/issues/4320 was about arrays I think it's ok to land this.
> Undefined is a valid value for if set as a single hook

- test/types/request.test-d.ts
- types/context.d.ts
- types/request.d.ts
> types: Add missing context types

- test/logger.test.js
- test/types/logger.test-d.ts
- test/types/request.test-d.ts
- types/hooks.d.ts
- types/instance.d.ts
- types/logger.d.ts
- types/plugin.d.ts
- types/reply.d.ts
- types/request.d.ts
- types/route.d.ts
Reverts fastify/fastify#4346
Fixes #4354 https://github.com/fastify/fastify-websocket/issues/226
Pretty sad that it is too breaking for now.
> Revert "fix(logger): lost setBindings type in FastifyBaseLogger"

- docs/Reference/Reply.md
Missed these whilst looking at #4264 
> docs(reference/reply): spelling fixes

- test/types/type-provider.test-d.ts
- types/type-provider.d.ts
At first, I really appreciate for #4264 (feat: Supporting different content-type responses).
I tried this feature with typescript, and realized type of response payload became unknown when using  different content-type schema. 
So I would suggest to update `ResolveReplyFromSchemaCompiler` to recognize diffrent content-types schema.
Thank you.
> Support different content-type typed reply with TypeProvider

- test/types/logger.test-d.ts
pino v8 dropped the `prettyPrint` option but it didn't drop it from its types. It did it in v8.7.0.
> fix types after pino 8.7.0 change

- .github/workflows/ci.yml
- fastify.js
- lib/contentTypeParser.js
- lib/route.js
- test/close-pipelining.test.js
- test/close.test.js
This PR makes all our tests pass on Node v19.
There is a significant behavior change in https://github.com/nodejs/node/pull/43522 which makes our `forceCloseConnection: false` behavior redundant as it will always be at least `'idle'` in v19. I've updated the tests to reflect this change.
This PR also fixes a bug in our codebase that was highlighted by the new keep-alive behavior:
we did not close the socket in case of a body was too large. 
> Node.js V19 support

- fastify.js
- lib/errors.js
- test/hooks-async.test.js
- test/hooks.on-ready.test.js
- test/hooks.test.js
While reviewing #4359 we noticed that Fastify was not properly checking for values that indicates emptiness (`null` or `undefined`) when adding a new hook using `Fastify#addHook`, this caused the following error:
```txt
/Users/metcoder/Documents/Workspace/MetCoder/Fastify/fastify.js:577
if (fn.constructor.name === 'AsyncFunction' && fn.length === 3) {
^
TypeError: Cannot read properties of null (reading 'constructor')
at Object.addHook (/Users/metcoder/Documents/Workspace/MetCoder/Fastify/fastify.js:577:14)
at Object.<anonymous> (/Users/metcoder/Documents/Workspace/MetCoder/Fastify/playground.js:4:9)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load …
```
> fix: no check on `null` or `undefined` values passed as fn

- docs/Reference/Reply.md
- docs/Reference/Server.md
> docs(server): config is lost when reply.call not found() is called

- docs/Guides/Write-Type-Provider.md
- test/types/type-provider.test-d.ts
Closes #4342 by changing narrowing checks inside `TypeProvider` interfaces to only reduce to `unknown` instead of `never`.
Note that this pull request serves as a way to coordinate proposed changes across all type-provider repos.
Constituent PRs which mirror the fix in each type provider package:
> fix(type-providers): assignability of instance with enabled type provider

- docs/Reference/Reply.md
- lib/reply.js
- lib/warnings.js
- test/reply-trailers.test.js
> feat: support async trailer

- lib/reply.js
- test/reply-trailers.test.js
Quick fix for the last PR #4380 
I spot the race-condition when using a single variables and `res.end`.
I use `process.nextTick` to allow all trailers function called and check the `handled` value later.
The next part is the `res.end` will call faster than `res.addTrailers`.
I move it inside the `sendTrailers` function.
> fix: trailers async race condition

- docs/Guides/Ecosystem.md
Added **fastify-list-routes** to the ecosystem core plugins.
I thought this interesting module is worth adding to the ecosystem plugins page, so that the community is more aware of it.
> docs(ecosystem): Add fastify-list-routes

- lib/hooks.js
- lib/route.js
- test/hooks.test.js
- test/internals/hooks.test.js
> [ Fix ] Improve error message for hooks check

- lib/contentTypeParser.js
- package.json
Fix the usage on `tiny-lru`.
The `.has` method do not means to be public use and it does not respect the `ttl` field.
Refs https://github.com/avoidwork/tiny-lru/pull/56
Closes #4389
> fix: tiny-lru usage

- docs/Guides/Plugins-Guide.md
As of today, you can import the named Fastify import in the ESM context with no issues.
Namely, this works as expected:
```
import { fastify } from "fastify";
const app = fastify({
logger: true,
});
await app.listen({ port: 3000 });
```
> Removes old note about named imports in ESM

- docs/Guides/Recommendations.md
fixes https://github.com/fastify/help/issues/780
> docs: Add section about capacity planning

- docs/Reference/Decorators.md
I believe the current docs are a typo/broken example, unless that's an undocumented syntax.  This change replaces the existing example with two examples for both returning the value since we're using async/await, along with still using `reply.send()` and then `await`ing `reply`.
> fix example using db decorator on fastify instance

- test/server.test.js
With https://github.com/nodejs/node/pull/45135 the output for validating a port changed and landed in node 19.1.0.
> fix node 19.1.0 port validation test

- test/types/register.test-d.ts
- types/plugin.d.ts
- types/register.d.ts
Fixes #4435.
To maintain backwards compatibility I added the new generic at the end of the list, it should have gone before TypeProvider.
> fix: use generic for Logger to register plugins when using a custom logger (#4435)

- test/close-pipelining.test.js
- test/close.test.js
These tests are intended to be skipped on any node version >= 19.0.0, however due to using `semver.satisfies()` without the `includePrerelease` option this means that prereleases of nodejs will never match. In order to simplify this and get the appropriate behavior in prereleases of node, I simplified the semver check to use `gte` which is what we really want here.
> chore: fix test skips for nodejs prereleases

- test/types/logger.test-d.ts
- types/logger.d.ts
> fix: make res.statusCode optional

- lib/contentTypeParser.js
With this PR we should improve the performance of the compareRegExpContentType method, as the indexOf is only done once and not on every run of compareRegExpContentType.
> perf: precompute isEssence for RegExp of content-type-parser method compareRegExpContentType

- docs/Reference/Server.md
- lib/route.js
- lib/warnings.js
- test/default-route.test.js
Attempt to fix https://github.com/fastify/fastify/issues/3977
> lib: deprecate the default route and improve its documentation

- docs/Reference/Reply.md
- package.json
…y object to signal fastify wait for your further response.
> docs(reference/reply): When using async-await, need return

- lib/wrapThenable.js
- test/reply-error.test.js
When using `async route handler` with `sync custom error handler`. Re-thrown inside the `custom error handler` would crash the problem.
The edge-case discovered in https://github.com/fastify/fastify/pull/4484#issuecomment-1367301750
> fix: re-thrown error crash

- docs/Reference/Errors.md
The example in document will make fastify never send a response if handle throw a error which is not expected error. For example if a handle `throw new Error(...)`. Original document is not clear about this and example doesn't handle it.
Original document make me confused, I assumed that rest of errors will be handled automatically without returning them, but turns out it doesn't.  I'm not sure if "error handler return unhanded error and pop them to parent handler" it expected behavior, but looks like it is, so I create this pr to fix them example. And if it's, I hope the document of `setErrorHandler` could be updated to o, so users can know they can pop error to default error handler. …
> improve `setErrorHandler` example

- lib/contentTypeParser.js
> (v3.x) perf: only check for isEssence once in RegExp for  content-type-parser (#4481)

- lib/contentTypeParser.js
- package.json
I implemented:
https://github.com/fastify/fast-content-type-parse
Here the benchmarks of fast-content-type-parse:
```sh
Benchmarking: "application/json"
util#MIMEType x 1,988,420 ops/sec ±0.41% (92 runs sampled)
fast-content-type-parse#parse x 18,283,119 ops/sec ±1.01% (86 runs sampled)
fast-content-type-parse#safeParse x 19,182,581 ops/sec ±1.29% (93 runs sampled)
content-type#parse x 12,852,355 ops/sec ±1.56% (93 runs sampled)
busboy#parseContentType x 15,001,593 ops/sec ±0.54% (95 runs sampled)
Fastest is fast-content-type-parse#safeParse
Benchmarking: "  application/json"
util#MIMEType x 1,999,209 ops/sec ±0.62% (89 runs sampled)
fast-content-type-parse#parse x 9,796,196 ops/sec ±0.84% (89 runs sampled)
fast-content-type-parse#safeParse x 10,228,216 ops/sec ±0.83% (92 runs sampled) …
```
> replace content-type with fast-content-type-parse

- docs/Guides/Ecosystem.md
Add [`fastify-postgres-dot-js`]() plugin to ecosystem docs.
> Add fastify-postgres-dot-js plugin to ecosystem docs.

- test/types/instance.test-d.ts
- types/instance.d.ts
This pull request intend to solve #4523 by adding types for `fastifyInstance.addresses()` in `fastify.d.ts`
> #4523 Add types for fastifyInstance.addresses()

- docs/Guides/Detecting-When-Clients-Abort.md
- docs/Guides/Index.md
**Summary**
There have been multiple issues posted asking how to detect when a client aborts a connection. I put together this guide that outlines my initial attempt to solve the issue. I would like to get some eyes on it to verify my assumptions. Please let me know your thoughts.
**Reported issues**
[issues/577](https://github.com/fastify/help/issues/577)
[issues/773](https://github.com/fastify/help/issues/773)
> Docs: Add guide about detecting client abort

- test/types/instance.test-d.ts
- types/instance.d.ts
This PR add typing to the fastify instance hasPlugin method.
**Checklist**
> fix: add type support for instance has plugin

- docs/Guides/Detecting-When-Clients-Abort.md
This PR includes suggested updates that were not merged in with: https://github.com/fastify/fastify/pull/4518. These include updated terminology, formatting, missing links to more details, and general cleanup.
> Docs: Update guide about detecting client abort

- docs/Reference/Validation-and-Serialization.md
Our docs was not up-to-date with the latest configuration in https://github.com/fastify/ajv-compiler#ajv-configuration.
> Bring docs in line with ajv-serializer defaults

- lib/contentTypeParser.js
- test/content-parser.test.js
It's not clear whether this behavior is desired for the current version, but threw together a quick PR in case it is.
Closes https://github.com/fastify/fastify/issues/4482
> ContentTypeParser remove(): Return false when content type parser was not present for removal

- docs/Guides/Ecosystem.md
The plugin that implement https://github.com/fastify/fastify/issues/2500 using `p-queue`.
The test is flaky, I have no idea why `macOS` failed. 
But the implementation should be good enough for production use.
> docs: add fastify-delay-request

- docs/Guides/Ecosystem.md
Whilst the public sector is always around 10 years behind the private sector, public sector suppliers are 20 years behind the private sector.
Had to build this because certain suppliers couldn't consume JSON, only XML. 😬 
> docs(ecosystem): add fastify-json-to-xml plugin

- lib/hooks.js
- test/hooks.on-ready.test.js
> Fix crash when onReady hook throws

- fastify.d.ts
- test/types/fastify.test-d.ts
- types/instance.d.ts
- types/route.d.ts
- types/schema.d.ts
Along with the type change in `FastifyError['validationContext']`, type of schemaErrorFormatter should be changed; there are three places to specify them (in `FastifyServerOptions['schemaErrorFormatter']`, `FastifyInstance[setSchemaErrorFormatter']`, and `RouteShorthandOptions['schemaErrorFormatter']`), so I also refactored them.
The type of argument `dataVar` is derived from [the actual invocation](https://github.com/fastify/fastify/blob/main/lib/validation.js#L103-L136). The type in original code of `FastifyError['validationContext']` mismatched from the implementation, so I changed them.
I could not figure out where any test for this change is located (maybe not tested?).
> Schema error formatter type

- fastify.d.ts
- package.json
- test/types/schema.test-d.ts
- types/schema.d.ts
should resolve https://github.com/fastify/ajv-compiler/issues/95
> Fix typescript integration bug with ajv-compiler

- .github/workflows/package-manager-ci.yml
- docs/Reference/LTS.md
closes #4590 by updating the OS used from `ubuntu-18.04` to `ubuntu-latest` (20.04), which also brings it into line with the OSes used by the other CI workflows.
> ci(package-manager): update ubuntu os to latest

- lib/route.js
- test/route.test.js
If you add a lot of routes using `fastify.all` AFTER registering a `/*` route, then each new route addition will need more and more time. This will bring the server boot time to the infinite.
A simple way to reproduce this is to run the following code:
```
const fastify = require('fastify')
const server = fastify()
function addRoute(server, path) {
console.time(path)
server.all(path, (req, reply) => {
return reply.json({ ok: true })
})
console.timeEnd(path)
}
server.get('/*', async (req, reply) => {
return reply.json({ ok: true })
})
for (let i = 0; i < 10; i++) {
addRoute(server, `/${i}`)
}
```
If you execute it, you should will see a result similar to this:
```
/0: 2.95ms
/1: 4.868ms
/2: 7.092ms
/3: 9.411ms
/4: 9.99ms
/5: 10.978ms
/6: 12.333ms
/7: 14.461ms
/8: 15.892ms
/9: 12.501ms
``` …
> fix: Only remove implicit HEAD routes.

- .github/workflows/package-manager-ci.yml
- package.json
- test/logger.test.js
For some obscure reason, an innoucuos test that passes locally like clockwork is failing in CI.
I identified the problem and fixed it. Originally I thought the problem was on pnpm, but it's like something on the CI env.
> Fix tests in Node.js v16

- lib/symbols.js
Fixes missed symbol reportad at #4511
> fix: add missed symbol

- docs/Reference/Hooks.md
- lib/route.js
- test/hooks.test.js
This PR shows that:
- the handler is executed (ref: https://twitter.com/kibertoad/status/1631687720769658882 )
- the onError hook is called if the handler is resolved after the request is aborted
- the onSend hook is called
> fix: onRequestAbort hook request pending

- lib/context.js
- lib/reply.js
- lib/request.js
- lib/symbols.js
- test/internals/context.test.js
- test/internals/reply-serialize.test.js
- test/internals/reply.test.js
- test/internals/request-validate.test.js
- test/internals/request.test.js
This PR just attempts to remove the duplicated Symbol as a result of #4608.
I'm trying to see if there's a way to avoid this from happening in the future, as I'm quite surprised I missed this and the linter didn't notify about the property being undefined within the Symbol exported object (though it might have some sense due to the scope of the lint rule).
I started thinking about testing the symbols against a JSON schema with AVJ to verify all the essential properties exist. Though not sure is the right approach nor the value that can add.
Looking forward to your thoughts and ideas about it 🙂 
> refactor: cleanup duplicated symbols

- package.json
- test/pretty-print.test.js
It's not ready: need to expose a new pretty print param: `method`.
Now you can see pretty print tests updates.
> feat: use internal trees for prettyPrint

- lib/validation.js
- test/schema-feature.test.js
this snippet works and I think it should not as it hides the wrong setup and missing schemas
```
const fastify = require('./fastify')({ logger: true })
fastify.post('/', {
schema: {
body: undefined
}
}, async (request, reply) => {
return request.body
})
fastify.ready()
.then(() => {
console.log('ready')
})
```
> fix: check if validation schema is undefined

- lib/contentTypeParser.js
- test/content-parser.test.js
@Uzlopak 
We do found a bug throughout the conversation on #4477 
I would fix this case first, but left the leading and trailing space support implementation.
It would be a heavy works for supporting it, since it means we need to do a parsing of input anywhere.
> fix: content-type mis-handling for invalid non-essence content-type

- lib/validation.js
- lib/warnings.js
- test/schema-feature.test.js
Emit `FSTWRN001` warning message on the schema validation.
Fix #4634.
> Emit a warning when validating undefined schemas

- .github/workflows/benchmark-parser.yml
- examples/benchmark/parser.js
- package.json
We have a gap in our benchmarking right now, as we only execute GET requests in existing benchmark.
This adds another workflow for hitting the execution path, which relies on using content parsers.
> Add workflow for benchmarking POST with custom parsers

- docs/Reference/Hooks.md
- test/route-hooks.test.js
- test/types/hooks.test-d.ts
- test/types/route.test-d.ts
- test/types/type-provider.test-d.ts
- types/route.d.ts
Adds the correct TS types for hooks on route level, including async hooks.
Based on PR #4628 with signature fixed
Closes #4376
> Adds async hooks signature on route level

- docs/Reference/Hooks.md
Fixed incorrect example for `onRequestAbort` hook. According to code, [tests](https://github.com/fastify/fastify/blob/662706bdca4c385616f3f3d1806c4b94a2a97b8a/test/hooks-async.test.js#L592) and [this comment](https://github.com/fastify/fastify/pull/4582#issuecomment-1430451820) the `reply` object is not passed to the hook handler.
The previous example caused this error:
```
FastifyError [Error]: Async function has too many arguments. Async hooks should not use the 'done' argument.
at Object.addHook (/Users/tim/IdeaProjects/affluent/packages/app-agency-api/node_modules/fastify/fastify.js:593:15) {
code: 'FST_ERR_HOOK_INVALID_ASYNC_HANDLER',
statusCode: 500
}
```
> docs: incorrect example for 'onRequestAbort' hook

- docs/Guides/Migration-Guide-V4.md
- docs/Reference/Routes.md
> docs: add optional URL param to upgrade guide and route docs (#4637)

- test/types/hooks.test-d.ts
- types/route.d.ts
Addresses https://github.com/fastify/fastify/issues/4705
Seems the change in https://github.com/fastify/fastify/pull/4655, made it so that all parameters were needed in the function to properly have types, for instance
```javascript
fastify.get('/', { onError: (request, reply, error, done) => {} }, async () => {})
```
would work fine, but would still require the `done` param with an async hook, which is certainly confusing
```javascript
// does not work
fastify.get('/', { onError: async (request, reply, error) => {} }, async () => {})
// works
fastify.get('/', { onError: async (request, reply, error, done) => {} }, async () => {})
```
Reverting back to how the route types were defined before, …
> fix: revert changes made to route hook types

- .github/workflows/integration.yml
- .github/workflows/package-manager-ci.yml
We can test using pnpm 8 whilst continuing to test on node 14 (with pnpm 7) by moving it to a separate job using `include`, see https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
> ci: test using pnpm 8

- .github/workflows/integration.yml
Missed this in https://github.com/fastify/fastify/pull/4714
> ci(integration): only trigger on pushes to main branches

- lib/schemas.js
- test/internals/validation.test.js
If a schema has a custom prototype (like when using a Zod schema), normalization will be skipped. Currently this does not work in the case where there are only response schemas.
This PR accounts for that case and adds a test.
> Maintain custom response schema

- docs/Reference/Logging.md
- test/types/logger.test-d.ts
- types/logger.d.ts
closes #4706
- Updated the logging documentation to clarify that `reply` is not guaranteed to be a fully-formed reply object in the `res` log serializer. also added a link out to pino's docs about the `serializers` option + mentioned serializers should never throw
- Updated the types to reflect the same
> Updates to docs and types regarding the `res` serializer

- .github/workflows/test-compare.yml
Whenever we add the label `test-compare` to a PR it will revert all the changes made outside of `test/` folder and run the tests again. The objective is pretty simple, guarantee the PR is testing the right thing.
Example: https://github.com/RafaelGSS/testing-the-right-thing/pull/2
> chore: add test-compare action

- README.md
I'm currently overwhelmed by notifications from different repositories and given the fact I'm not actively contributing to the fastify plugins, I prefer to remove myself from this team.
Note: I'm still at fastify core.
> doc: remove RafaelGSS from plugins team

- test/types/route.test-d.ts
- types/utils.d.ts
Added the missing types for the lowercasde HTTP methods added with #4750 
> Fix lowercase HTTP methods type

- lib/contentTypeParser.js
- test/hooks-async.test.js
- test/route-hooks.test.js
> body reader to use statusCode from stream error, if available (#4785)

- docs/Reference/Server.md
- lib/server.js
- test/close-pipelining.test.js
- test/close.test.js
Fixes #4774
The PR attempts to fix an unexpected behaviour when secondary binding servers were not in sync with the lifecycle hooks of the application.
> fix(#4774): close bindings through the hook system

- docs/Guides/Ecosystem.md
Add fastify-cacheman plugin.  
Small and efficient cache provider for Fastify with In-memory, File and Redis.
> docs(ecosystem): add fastify cacheman

- fastify.js
- test/header-overflow.test.js
~~This PR improves error response if URI is too long. The status code should ideally be 414 to better align response with other http servers and return a more meaningful error message to the client.~~
~~EDIT: Since it is not possible to determine if error was caused by too long URI or too large headers we can't change the status code as it could be rather misleading. This PR now just improves the error message if maximum allowed header size was exceeded.~~
EDIT2: As discussed it might be better to just return a 431 for now in both cases (request header fields are too large and URI is too long) to be more concise about the error (400 is too generic) and to be in line with default Node's default response (https://github.com/nodejs/node/pull/25605).
The error code is set by http parser : …
> fix: return 431 status code on HTTP header overflow error

- lib/reply.js
- lib/schema-controller.js
- lib/schemas.js
> minor jsdoc fixes

- docs/Reference/TypeScript.md
Fixes a minor typo in docs referencing a non-existent `compileOptions` property in a tsConfig.json example.
> docs(typescript): fix typo

- docs/Guides/Testing.md
- docs/Guides/Write-Plugin.md
This PR adds documentation for testing a plugin in Fastify (https://github.com/fastify/fastify/issues/4687)
> docs(testing): add plugin testing guide

- test/types/reply.test-d.ts
- types/reply.d.ts
An instance where the Reply generic was defined without HttpCodes as keys, would break type inference when .code().send were being chained. For example:
```typescript
fastify.get<{ Reply: string }>('/path', (req, reply) => {
reply.code(123).send(23); // <-- this was not showing an error, when it should've
})
```
Fixed and added a test.
> Fixed type inference on .code().send()

- docs/Guides/Delay-Accepting-Requests.md
- docs/Reference/Decorators.md
- test/types/instance.test-d.ts
- types/instance.d.ts
Follow up to #4874
Preferred to use `decorate('name')` , `decorateRequest('name')`, `decorateReply('name')` variants instead
Deprecation prior to dropping is not feasible because of https://github.com/microsoft/TypeScript/issues/54872
> Next: Disallow `decorate('name', null)` in the types

- SECURITY.md
This PR updates the security document to make it clear that CI/CD reports ***should not*** use our repositories as proofs of concept.
> docs(security): update policy on ci/cd reports

- .github/workflows/ci.yml
- .github/workflows/coverage-nix.yml
- .github/workflows/coverage-win.yml
Using now caching by setup-node, which is ensuring, that we cache properly. E.g. currently caching on windows machines was not happening, because the npm cache is not on ~/npm on windows. 
Split some jobs like linter and typescript tests, as they only need to run once and it is enough that they run on lts of node. 
automerge is running after package tests succeeded.
> ci: enable caching; split jobs

- docs/Reference/Plugins.md
This PR adds documentation for a side effect of using `await` when registering a plugin in Fastify (#3863)
> docs(plugins): note side-effect when using `await` in `fastify.register()`

- docs/Reference/Errors.md
"FST_ERR_ASYNC_CONSTRAINT" was set to a heading size that gave it a section title and was inconsistent with the rest of the docs on this page, quick and easy 1 character fix
> fix wrong header size in docs

- docs/Reference/Errors.md
- lib/errors.js
- test/internals/errors.test.js
I saw first some issues on the Errors documentation on fastify.dev, like so:
So I started fixing them manually. But then I realized, that I am a lazy guy. So I wrote unit tests, to ensure that the documentation is regarding Errors complete. 
Then I realized, that some of those Errors should be TypeErrors, so I also fixed that. 
> fix: rework FastifyErrors, ensure documentation completeness

- test/types/instance.test-d.ts
- types/instance.d.ts
Closes: https://github.com/fastify/fastify/issues/4896
Here is a screenshot of the new test failing on `main`.
> Fix setNotFoundHandler handler type

- docs/Guides/Detecting-When-Clients-Abort.md
[request.aborted](https://nodejs.org/docs/latest-v16.x/api/http.html#requestaborted) has been deprecated since node 16.
It seems like [request.destroyed](https://nodejs.org/docs/latest-v16.x/api/http.html#requestdestroyed) should be used instead
> docs(client-aborted): remove deprecated function

- docs/Guides/Detecting-When-Clients-Abort.md
This reverts commit cc347d7c0b4266097b61b126158b797878668353.
The author on #4898 do not test if `request.aborted` is really identical to `request.destoryed`. 
Instead, they are two completely different property and the meaning is different.
For `request.destoryed`, Node.js document is telling us to `Check` but not `Use` as replacement.
From the below example, a properly closed connection would also triggered when using `request.destroyed`.
So, it is not meaning request abort.
```js
test('onRequestAbort should not be called when using destroyed', t => {
const fastify = Fastify()
t.plan(3)
t.teardown(() => fastify.close())
fastify.addHook('onRequestAbort', async function (req) {
process.nextTick(() => t.fail())
})
fastify.route({
method: 'GET',
path: '/',
async handler (request, reply) { …
```
> Revert "docs(client-aborted): remove deprecated function (#4898)"

- lib/schema-controller.js
- test/internals/request-validate.test.js
Hi, I was using `@fastify/type-provider-typebox` as default compiler and I found that `schema.headers` in subroutes cannot be compiled because is not taking the parent options of the SchemaController correctly.
You can reproduce the error here: https://replit.com/@tinchoz49/ShimmeringGrowingQuote
Thanks
> fix: extend isCustomValidatorCompiler from parent controller

- fastify.js
- test/request-id.test.js
converts the requestIdHeader configuration value to lowercase at server initializiation
Case in discord, where dev passed the cloudflares `CF-RAY` headername to fastify, but didnt work. The dev needed to lowercase the headername to `cf-ray` to get it working. This PR ensures a better DX.
> fix: allow uppercase requestdHeader

- docs/Reference/TypeScript.md
This is a simple typo fix in the TypeScript docs. The name of the package that contains types for Node standard modules is `@types/node`.
See:
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
- https://www.npmjs.com/package/@types/node
> Fix typo in TypeScript docs ("@types/node", not "@node/types")

- test/types/type-provider.test-d.ts
- types/type-provider.d.ts
- types/utils.d.ts
As far as I understand, Fastify converts [request headers to lowercase](https://github.com/fastify/help/issues/71), while **Fastify type provider** seems to pass down to the type provider libraries the headers with the same casing provided in the route handler schemas.
Here is an example:
```ts
fastify.get(
"/",
{
schema: {
headers: {
type: "object",
properties: {
lowercase: { type: "string" },
UPPERCASE: { type: "number" },
},
required: ["lowercase", "UPPERCASE"],
} as const,
},
},
(req) => {
req.headers.lowercase; // Correct types and runtime value
req.headers.UPPERCASE; // Gets schema types but it's actually undefined and type should be, too
req.headers.uppercase; // Gets generic headers types but it actually holds the actual request header value
}
);
```
This PR is an attempt to align …
> fix: lowercase type-providers headers types

- test/types/reply.test-d.ts
- types/reply.d.ts
Closes #4883
As @aadito123 mentioned on the issue, there's a pitfall here: if someone wants the Reply type to be an object with keys as http codes like `{ 401: string, 409: string }`, the inference of the return type will be `string`. A possible workaround for this case would be `{ '4xx':  { 401: string, 409: string } }`.
> fix: ReplyTypeConstrainer array type inference

- fastify.d.ts
- test/types/fastify.test-d.ts
- types/schema.d.ts
[`FastifySchemaValidationError`](https://github.com/learnwiz/fastify/blob/4bde0e0b259b8df6495ae93c91e06615b61be9c6/types/schema.d.ts#L26) seems to originate from [`ErrorObject` from Ajv](https://github.com/ajv-validator/ajv/blob/main/lib/types/index.ts#L85).  
However, while property `params` in `FastifySchemaValidationError` has type `Record<string | string[]>`, possible values that are created in Ajv are wider than this; see [`LimitNumberError`](https://github.com/ajv-validator/ajv/blob/main/lib/vocabularies/validation/limitNumber.ts#L18-L22) and [`ConstError`](https://github.com/ajv-validator/ajv/blob/main/lib/vocabularies/validation/const.ts#L7). Note that `allowedValue` defined in `ConstError` could be literally any; see [JSON Schema Validation …
> make FastifySchemaValidationError.params wider

- fastify.js
- lib/pluginOverride.js
- lib/pluginUtils.js
- test/internals/plugin.test.js
- test/plugin.test.js
> fix: hasPlugin does not track parent plugins

- .github/workflows/benchmark-parser.yml
Impossible to test it properly without merging, unfortunately, as workflow depends on definition in main, but now it's 100% consistent with the benchmark that is passing, so fingers crossed.
Invoking benchmark script itself inside GA is passing on my fork.
> fix: Try to fix parser benchmark workflow

- lib/wrapThenable.js
- test/wrapThenable.test.js
> fix: do not double send the response if the request is destroyed but not aborted

- test/types/instance.test-d.ts
- types/instance.d.ts
Follow up for #4900 
Removes the types for variadic listen()
> types: Remove variadic listen types

- .github/dependabot.yml
I would like to see if `groups dependencies` reduce the amounts of noise.
Maybe we can change to daily check for one or two weeks to see if it feasible.
More on https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> chore: use group dependencies in dependabot

- .github/workflows/benchmark.yml
It fails everytime you add a new label:
```
Warning: Unexpected input(s) 'repo', 'issue_number', 'name', valid inputs are ['route', 'mediaType']
Run octokit/request-action@v[2](https://github.com/fastify/fastify/actions/runs/5922752207/job/16057202744?pr=4982#step:2:2).x
with:
route: DELETE /repos/{repo}/issues/{issue_number}/labels/{name}
repo: fastify/fastify
issue_number: 4982
name: benchmark
mediaType: {}
env:
GITHUB_TOKEN: ***
DELETE /repos/{repo}/issues/{issue_number}/labels/{name}
> repo: fastify/fastify
> issue_number: 4982
> name: benchmark
> mediaType: [object Object]
< 404 [3](https://github.com/fastify/fastify/actions/runs/5922752207/job/16057202744?pr=4982#step:2:3)[4](https://github.com/fastify/fastify/actions/runs/5922752207/job/16057202744?pr=4982#step:2:4)2ms
``` …
> chore: fix ci bench

- lib/pluginUtils.js
- test/internals/plugin.test.js
Refs https://github.com/nodejs/node/issues/49163
I am not sure if it is better to use `const cache = require.cache || {}` or a single if to block. 
> fix: require.cache is undefined breaks SEA

- docs/Guides/Getting-Started.md
Removed the mixing ESM and commom from the documentation example in our-db-connector.js
> docs: remove mixing ES6 and commomjs in the example

- test/types/instance.test-d.ts
- test/types/type-provider.test-d.ts
- types/route.d.ts
While using https://github.com/fastify/fastify-type-provider-json-schema-to-ts I noticed that the `errorHandler` callback request does not have inferred types from TypeProvider, unlike the global `setErrorHandler`.
As far as I can see this being tested else where and I am not entirely sure how to add a test here. I can however add a test to `fastify-type-provider-json-schema-to-ts` though. 
> fix: errorHandler callback should utilize TypeProvider

- test/types/request.test-d.ts
- types/request.d.ts
Resolves https://github.com/fastify/fastify/issues/4993
> fix: Set `FastifyRequest.id` type as a string

- docs/Guides/Database.md
There was a small typo on catch statement inside Postgrator migration example. 
The correct variable that should be used in `console.error` function is `err` instead of `error`.
> docs: typo on catch statement inside Postgrator migration example

- test/internals/reqIdGenFactory.test.js
When I wrote the test, I thought not much about the generated output. 1/3 of the test output is regarding this simple test.
> test: reduce output of reqIdGenFactory.test.js

- README.md
Hello 👋
I noticed that some documentation links in the readme have some line breaks in the middle (example at the end). It's not breaking anything but the readability. I was wondering where it comes from and it seems that it's coming from the markdown lint action that adds a line length limit.
Instead of trying to update the markdown linter config, this PR updates the links by using proper markdown instead of HTML, following the same formatting (**bold** with `inline code block`).
Because the result is shorter, it passes the current linter line limit without needing extra line breaks.
I decided to create a PR instead of an issue because the fix is relatively light. If there is a specific reason for using HTML links instead of markdown, don't hesitate to close it.
Before
After
> docs(readme): avoid line breaks in documentation links

- docs/Guides/Ecosystem.md
- docs/Guides/Getting-Started.md
- docs/Guides/Migration-Guide-V4.md
- docs/Reference/ContentTypeParser.md
> docs: minor improvements

- test/types/request.test-d.ts
- types/request.d.ts
> fix: add routeOptions.config to types

- docs/Reference/Hooks.md
As shown in the attached image, the onClose hook heading is included in the quotation.
https://fastify.dev/docs/latest/Reference/Hooks/#onclose
To fix this, I have added a blank line before the onClose hook heading.
> docs: Add blank line before onclose hook heading

- lib/contentTypeParser.js
- lib/schemas.js
`split` has optional second argument. Since only the first argument of the array is used, you can interrupt parsing the string after the first match.
> perf: optimize split params

- docs/Reference/Type-Providers.md
- test/types/type-provider.test-d.ts
- types/instance.d.ts
- types/route.d.ts
Skip explicitly providing as const when defining a schema with `json-schema-to-ts` as a type provider.
Now we can go from this:
```ts
const server = fastify().withTypeProvider<JsonSchemaToTsProvider>()
server.get('/route', {
schema: {
querystring: {
type: 'object',
properties: {
foo: { type: 'number' },
bar: { type: 'string' },
},
required: ['foo', 'bar']
}
} as const // <----- You had to specify it as const to get the literal types
}, (request, reply) => {
const { foo, bar } = request.query // type safe!
})
```
To this:
```ts
const server = fastify().withTypeProvider<JsonSchemaToTsProvider>()
server.get('/route', {
schema: {
querystring: {
type: 'object',
properties: {
foo: { type: 'number' },
bar: { type: 'string' },
},
required: ['foo', 'bar']
}
} // <--- We can now skip as const …
```
> chore: implicitly infer SchemaCompiler as readonly

- docs/Reference/Plugins.md
- docs/Reference/Reply.md
- lib/reply.js
This PR removes references to promisesaplus.com spec defintion for thenable. Discuessed in https://github.com/fastify/fastify/issues/5005
> docs: remove thenable promisesaplus spec references

- types/instance.d.ts
This PR "fixes" the type error reported at https://github.com/fastify/fastify/issues/5094. This error happens when the user's `tsconfig` has [`skipLibCheck: false`](https://www.typescriptlang.org/tsconfig#skipLibCheck) and an outdated version of `@types/node` or `typescript`.
Current fix only adds a `@ts-ignore` comment if the type is not available. This error should be harmless as the actual JS will only call `Symbol.asyncDispose` if its available.
I'm not sure how we should test this, as it would require to downgrade our typescript and @types/node versions, which would break other ts features that being used in fastify's types.
However, I downgraded them in my machine and can confirm the error was fixed.
and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CON …
> fix: build problems when `Symbol.asyncDispose` type is not available.

- test/types/route.test-d.ts
- types/route.d.ts
As mentioned in the [the documentation](https://fastify.dev/docs/latest/Reference/Routes/#constraints), routes may have [`version`](https://fastify.dev/docs/latest/Reference/Routes/#version-constraints), [`host`](https://fastify.dev/docs/latest/Reference/Routes/#host-constraints) or other custom constraints. This change only extends `RouteShorthandOptions` type with optional `version` and `host` attributes.
> feat: Improve RouteShorthandOptions['constraints'] type

- docs/Guides/Plugins-Guide.md
- lib/warnings.js
- package.json
- test/default-route.test.js
- test/internals/reply.test.js
- test/reply-trailers.test.js
This PR changes the deprecation warnings to be actual Node.js recognizable deprecation warnings. Whereas the errors we were emitting prior to this PR were plain warnings with "FastifyDeprecation" as the name, these are:
1. Emitted with "DeprecationWarning" as the name
2. Are recognized as deprecation warnings by Node.js
The benefit of doing this is that deprecations can be traced with `--trace-deprecation`, silenced with `--no-deprecation`, and caused to abort the process with `--throw-deprecation`.
This is made possible through https://github.com/fastify/process-warning/pull/87.
> refactor: migrate deprecation warnings to actual deprecation warnings

- test/logger/instantiation.test.js
closes https://github.com/fastify/fastify/security/code-scanning/4
> test(logger): restrict temp file permissions

- README.md
- docs/Guides/Ecosystem.md
- docs/Guides/Getting-Started.md
- docs/Guides/Style-Guide.md
- docs/Reference/Routes.md
- lib/errors.js
- test/constrained-routes.test.js
- test/http2/constraint.test.js
- test/internals/errors.test.js
- test/schema-examples.test.js
- test/types/route.test-d.ts
Also fixes https://github.com/fastify/fastify/security/code-scanning/3, https://github.com/fastify/fastify/security/code-scanning/5, and https://github.com/fastify/fastify/security/code-scanning/6
> chore: replace mention of fastify `.io` domain with `.dev`

- SECURITY.md
See https://github.com/openjs-foundation/security-collab-space/issues/36; if this PR is merged or rejected, that requirement is satisfied. Before writing this, I went through and marked a few more things as "Met" so the scores would be more accurate.
Fixes https://github.com/openjs-foundation/security-collab-space/issues/36.
> docs(security): add prose explaining OpenSSF CII Best Practices badge results

- test/types/request.test-d.ts
- types/request.d.ts
Fixes #5113 missing type on routeOptions.
> fix(types): add handler property to routeOptions

- README.md
Seems the paths changed at some point! This is why it was showing as failing even though it has clearly been passing.
> docs(readme): fix ci badge path

- docs/Reference/Warnings.md
- lib/pluginUtils.js
- lib/warnings.js
- test/hooks.test.js
- test/plugin.4.test.js
- test/register.test.js
> feat(plugins): mixing async and callback style now returns a warning

- docs/Reference/Errors.md
- lib/errors.js
- lib/pluginUtils.js
- test/internals/errors.test.js
- test/plugin.4.test.js
Closes #5112, opened as discussed in #5139
> fix(plugins): mixing async and callback style now returns an error

- docs/Guides/Ecosystem.md
This package received core status a long time ago but it was still missing from this list.
> docs: add @fastify/vite to core plugins list

- docs/Guides/Ecosystem.md
This PR adds `@scalar/fastify-api-reference` to the list of community plugins. This plugin renders modern OpenAPI/Swagger docs based on `@fastify/swagger`.
Read more about the Scalar API References here: https://github.com/scalar/scalar
And about the Fastify plugin here: https://github.com/scalar/scalar/tree/main/packages/fastify-api-reference
```ts
await fastify.register(require('@scalar/fastify-api-reference'), {
routePrefix: '/docs',
})
```
> docs: add @scalar/fastify-api-reference to community plugins list

- docs/Reference/Reply.md
Removed .routeOptions property reference from Reply.md because it was creating confusion whoever referring docs.
> docs: Remove routeOptions reference in Reply.md

- docs/Guides/Ecosystem.md
- Removed fastify-nodemailer from Ecosystem plugins list since it seems not to be maintained anymore (https://github.com/lependu/fastify-nodemailer/issues/107)
> docs: removed unmaintained fastify-nodemailer from ecosystem

- docs/Reference/Reply.md
Updates the docs to:
- Reflect the actual behaviour wherein it is no longer mandatory to set `Content-Type=application/octet-stream` to respond with a stream
- Mention within the immediate context that stream and buffer responses are treated as pre-serialized and skip any response serialization or validation
> docs: clarify handling of streams and buffers

- .gitpod.yml
- .npmignore
- README.md
- docs/Guides/Contributing.md
I added an initial gitpod config which will install via npm and add the eslint extension - I'd love to know if there is anything else people usually run when they first jump in to work on a new feature (for example a playground environment) so I can also run that.
I also added an "Open in Gitpod" and "Contribute with Gitpod" button in two places - LMK if there is anywhere I missed
> chore: gitpodify

- test/internals/errors.test.js
While working on #5193 I think tests for the error.md would be great to avoid merge errors.
> test: add tests for TOC of errors.md

- .github/workflows/ci.yml
- .github/workflows/integration.yml
- .github/workflows/package-manager-ci.yml
As discussed in #5195 we pin the version to 18.18.2 till we know why the release breaks our tests.
> ci: pin node 18 to 18.18.2

- .github/workflows/ci.yml
- .github/workflows/integration.yml
- .github/workflows/package-manager-ci.yml
- test/close-pipelining.test.js
- test/close.test.js
I guess in 18.19.0 the PR which has something to do with closeIdleConnections got backported and thus breaking our CI. 
> ci: fix broken ci by skipping tests if node v > 18.19.0

- test/types/hooks.test-d.ts
- types/hooks.d.ts
- types/route.d.ts
Closes #4859, without breaking `RouteShorthandOptions` in the same way #4655 did (see #4705 for details on that).
The idea is to use an intermediate type to infer the return type of the hook, and determine which hook handler interface to use based on that (sync or async).
A couple things I wanted to call out:
- this new meta hook type is intentionally not exported from the main `fastify.d.ts` file. It's really just an internal helper and shouldn't need to be exported.
- Not a huge fan of the `meta` name - suggestions welcome. I think it would make the most sense to rename the existing hooks `sync` and `async` and then just make the new type `<hook name>HookHandler` (what the sync hook currently is named), but that would be breaking.
and the [Code of …
> fix: allow async hooks in `RouteShorthandOptions` without breaking `request` and `reply` types

- lib/server.js
- test/server.test.js
Closes #5180
I tried to add a small test to reproduce it, it does covers the case but open to any suggestion to improve it.
> fix(#5180): close secondary bindings after primary is closed

- test/types/instance.test-d.ts
- types/instance.d.ts
I think `err` type definition in the first parameter of the callback function for `after` and `ready` methods are insufficient.
The one for `after` method can be nullish and the one for `ready` method is optional.
See also [an small example for Fastify & TS project](https://github.com/nokazn/fastify-ts-minimum-sample) if needed.
Thank you.
> types: nullish error types in callback function's parameter for `after` and `ready` method

- fastify.js
- test/fastify-instance.test.js
- test/hooks.on-ready.test.js
This PR closes #5049
It fixes the double run of `onReady` hooks when calling `Fastify#ready` more than once.
It introduces two new states `booting` (used to indicate `onReady` hooks are running) and `ready` (used to indicate `onReady` hooks have finished running).
> These additions can be subject to change, but I believe they are a good starting point.
> fix(#5049): Remove duplicated calls to onReady

- package.json
- test/types/request.test-d.ts
tiny PR to be merged so that https://github.com/pinojs/pino/pull/1858 doesn't break fastify types.
> chore: remove unused type assertion

- test/types/route.test-d.ts
- types/route.d.ts
In https://github.com/fastify/fastify/pull/5097, it provides a wrong typings of `route.constraints`.
The `constraints` options is a value that passed to a custom constraints which is initialized when the startup of `fastify`.
You cannot create a constraints through the route option.
> fix: route constraints

- README.md
I missed that we are `at-large` now since 2021
- https://github.com/openjs-foundation/project-status/issues/35
> chore: at-large project

- package.json
This was previously failing with the error: `Error: --watch requires coverage to be enabled`
I've also made the arguments use long parameter notation, to better match the other commands and support readability
> fix: `npm run test:watch`

- lib/reply.js
- test/reply-code.test.js
Fixes https://github.com/fastify/fastify-reply-from/issues/338.
This is quite a bad regression.
> fix: always consume stream payloads when responding to 204 with no body

- docs/Reference/Server.md
Coming from other frameworks this is somewhat surprising. This documents the behaviour and explains to catch 404 errors users need to set a not found handler.
> docs: update setErrorHandler to explain not found behaviour

- docs/Guides/Ecosystem.md
closes #5232 
We were also missing the `@fastify/routes-stats` plugin.
> docs(ecosystem): add missing plugins to core list

- lib/route.js
- package.json
Ref https://github.com/delvedor/find-my-way/pull/336
> chore: bump find-may-way to v8.0.0

- build/build-validation.js
- docs/Reference/Server.md
- fastify.d.ts
- fastify.js
- lib/configValidator.js
- lib/route.js
- test/internals/initialConfig.test.js
- test/types/instance.test-d.ts
- test/useSemicolonDelimiter.test.js
- types/instance.d.ts
fixes: https://github.com/fastify/fastify/issues/5237
This PR adds `useSemicolonDefault` with a default option of `true`
> feat: add use semicolon delimter config, default = true

- lib/route.js
- test/findRoute.test.js
- test/types/route.test-d.ts
- types/instance.d.ts
Follow Up #5230 
In the above mentioned PR, it expose the whole store within `find-my-way` which contains not even the schema but the whole `fastify` context which should not be able to modify or see.
We need to decide what should be exposed and minimize it.
> fix: restrict findRoute exposed property

- test/hooks.on-listen.test.js
The onListen hook test, which checks that the hook is non blocking, is flaky and breaking our CI. 
This should fix it.
> fix(test): flaky on-listen hook test

- lib/contentTypeParser.js
- test/async_hooks.test.js
The lack of an `.emitDestroy()` might causes a potential memory leak when used with odd implementations of `async_hooks` (including a false positive in why-is-node-running).
> fix: Always call resource.emitDestroy()

- docs/Reference/Decorators.md
This removes a repetition on `route` word (first as plain text, second time as a link to the routes documentation).
- [n/a] run `npm run test` and `npm run benchmark`
- [n/a] tests and/or benchmarks are included
> docs: remove word repetition on Decorators docs

- docs/Reference/Reply.md
- docs/Reference/Warnings.md
- lib/reply.js
- lib/warnings.js
- test/internals/reply.test.js
- test/types/reply.test-d.ts
- types/reply.d.ts
> refactor: deprecate `Reply#getResponseTime()` in favour of `Reply#elapsedTime`

- docs/Guides/Ecosystem.md
- docs/Guides/Getting-Started.md
- docs/Guides/Style-Guide.md
- package.json
> chore: remove `www.` from `fastify.dev` urls

- lib/hooks.js
- test/hooks.on-listen.test.js
This PR fixes an issue where the `onListen` application hooks don't run in some cases when they should:
1. When there is an `onListen` hook registered in a child encapsulation context, but the parent context does not have one
2. When there are multiple encapsulation contexts that are peers (i.e. at the same level / both children of the same parent), only the first will run
See example code:
```js
const Fastify = require('./fastify.js')
const fastify = Fastify({ logger: true })
fastify.addHook('onListen', (done) => {
console.log('i am called')
done()
})
fastify.register((instance, opts, done) => {
instance.addHook('onListen', (hookDone) => {
console.log('i am also called')
hookDone()
})
// create an encapsulation, and then create another immediately inside it
instance.register((instance2, …
```
> fix: ensure `onListen` hooks are called when they should be

- docs/Reference/Logging.md
More info here: https://sembr.org/
I updated the Pino docs link as the previous one was broken and took advantage to use Semantic Line Breaks for easier updates in the future without changing the formatting
> docs: Fix Pino docs link

- EXPENSE_POLICY.md
- SPONSORS.md
- package.json
> chore: add github sponsor

- docs/Guides/Ecosystem.md
Adds [fastify-sqlite-typed](https://github.com/yoav0gal/fastify-sqlite-typed) to the community plugins list
> docs(ecosystem): adds fastify-sqlite-typed to the community plugins list

- docs/Guides/Getting-Started.md
This commit updates the 'Getting Started' guide to include an ESM usage example, specifically demonstrating the export of routes using ESM syntax. A code snippet showing the addition of "type": "module" in a configuration example is also provided to assist users in setting up their projects for ESM.
This addresses the confusion mentioned in issue #5292 regarding ESM configuration in Fastify projects.
> docs: add ESM usage example in Getting Started

- docs/Reference/Errors.md
- docs/Reference/Hooks.md
- docs/Reference/Reply.md
- lib/errors.js
- lib/reply.js
- test/internals/errors.test.js
- test/web-api.test.js
> feat: Web Stream API

- docs/Guides/Ecosystem.md
Adds [fastify-hana](https://github.com/yoav0gal/fastify-hana) to the community plugins list
> docs(ecosystem): adds fastify-hana to the community plugins list

- lib/warnings.js
The deprecation read:
`You are using the deprecated "reply.getResponseTime()"" method. Use the "request.elapsedTime" property instead.`
This message reference the incorrect parent object and also had a typo of an extra quotation mark. This revision fixes this the content of this warning.
> docs: fix misattributed property parent in deprecation warning: request.elapsedTime

- docs/Guides/Serverless.md
Looks like a typo in the docs for Fastify on GCP.
Somewhat related but I don't want to mix with this PR - I'm using Firebase Functions which I think is *maybe* the same infra under the hood as Google Cloud Functions but I'm not totally sure on that and I've used a different syntax to make things work. Especially with regards to the use of webhooks which requires the raw body *and* JSON for parsing. So, I'm thinking I'll shoot out a new PR to add a new `Google Firebase Functions` section with what I've got that works. Is that ok?
> fix: typo in module exports

- docs/Reference/TypeScript.md
Fix wrong links/anchors from https://fastify.dev/docs/latest/Reference/TypeScript
> docs(ts): Fix links

- docs/Reference/Errors.md
- fastify.js
- lib/errors.js
- test/internals/errors.test.js
- test/set-error-handler.test.js
> fix: cb is not a function at fallbackErrorHandler

- docs/Guides/Serverless.md
This PR adds a new section to the Serverless Guide on the website that explains how to use Fastify as the wrapper around Firebase's own onRequest HTTP handler
> feat: add a Firebase Functions step by step guide

- lib/contentTypeParser.js
For the same reason as https://github.com/fastify/fastify-rate-limit/pull/353
There is a 50%+ improvement in the lookup performance of non-numeric keys when a map is used instead of an object — contentType is a string
> perf: use FifoMap to check contentType

- docs/Guides/Serverless.md
- lib/contentTypeParser.js
- test/content-type.test.js
From https://github.com/fastify/fastify/pull/4477#issuecomment-1378545312
We should not be allowing this in my opinion. Nothing good can come out of it:
```js
fastify.addContentTypeParser('   application/json   ', function (request, body, done) {
done(null, body)
})
fastify.addContentTypeParser('application/json   ', function (request, body, done) {
done(null, body)
})
fastify.addContentTypeParser('   application/json', function (request, body, done) {
done(null, body)
})
fastify.addContentTypeParser('application/JSON', function (request, body, done) {
done(null, body)
})
```
The Content-Type header is completely case insensitive for the MIME part, and whitespace insensitive when it comes to spaces around the whole value, we should take these facts into account when registering a parser …
> feat: make contentTypeParser's existingParser check more strict

- docs/Reference/ContentTypeParser.md
- lib/contentTypeParser.js
- lib/warnings.js
- test/content-parser.test.js
This PR target to `next` branch.
If we need to loosen the check for `main` or `v3`, we can easily backport to those branch.
1. Remove `Content-Type` parsing which also remove the ability to check `un-ordered` parameters.
2. Add `FastifySecurity` warning for `RegExp`. I use the word `Security` instead of `Warning` to bring attention to the user.
Please carefully review this PR, so we don't expose any security problem.
> feat: loosen content-type checking

- fastify.d.ts
- test/types/hooks.test-d.ts
Exports the types of the preClose hook.
> types: Export preClose hook types

- docs/Guides/Database.md
Looks like database connection is missing in the [migration](https://fastify.dev/docs/latest/Guides/Database/#migrations) `postgrator` code section. This piece of code is present in the [postgrator docs](https://github.com/rickbergfalk/postgrator?tab=readme-ov-file#usage). Without this, the execution was silently exiting without any log trace, and not running migration.  
> fix: database migration doc missing db connection code

- docs/Reference/TypeScript.md
https://github.com/fastify/fastify/issues/4241 and https://github.com/smartiniOnGitHub/fastify-healthcheck/issues/20 both seems to be closed. This note can be removed.
> docs: Remove ES module with NodeNext note

- docs/Reference/Type-Providers.md
- docs/Reference/TypeScript.md
- Add links behind each package name, so people can easily find and look-up the corresponding READMEs
- Add Zod to the TypeScript list as 3rd party
- Add Type Provider wrapper packages to the Type Provider page
- Make all links consistency, not using "GitHub" anymore
> docs: Add GitHub links to Type Providers + mention Zod

- lib/contentTypeParser.js
- test/content-parser.test.js
- test/content-type.test.js
- test/custom-parser.1.test.js
Relevant change: https://github.com/fastify/fastify/commit/ecfd79488dc4ce4cb6e4d02965668ac8faf748c9
Depends on: https://github.com/fastify/fastify/pull/5345, https://github.com/fastify/fastify/pull/5371
Why: other public methods only accept string or RegExp, now you might ask "Why not just call it and let it return false?", which is fair, but we could argue the same with [`.remove`](https://github.com/fastify/fastify/blob/f776447423fc1df7a6497abb76baea25b797560f/lib/contentTypeParser.js#L135-L149), why doesn't it just run and return false? So I think it's important to be consistent and only accept string or RegExp in all the methods 
> feat: hasParser, only accept string or RegExp

- fastify.js
- test/esm/errorCodes.test.mjs
In favor of: https://github.com/fastify/fastify/pull/5388
> fix: errorCodes import using ESM

- lib/contentTypeParser.js
@Uzlopak made a good point about how indexOf searches until the end of a string
[node's maxHeader size is 16kb](https://opensource.hcltechsw.com/connections-doc/v8-cr1/admin/install/changing_maximum_allowed_http_header_size.html), so potentially somebody could send malicious requests where contentType won't be found and we'd search ~16kb each time
It's not a huge issue, but this PR will make it more performant in those cases
[Note that slice won't create a new string](https://iliazeus.github.io/articles/js-string-optimizations-en/#sliced), [and when combined with a strict equality check, is as performant as indexOf](https://github.com/nodejs/performance/issues/159#issuecomment-2051717180)
> perf: limit search space for contentType

- .github/workflows/benchmark-parser.yml
- .github/workflows/benchmark.yml
We cannot only install production dependencies in these workflows as they depend on devDeps to run:
https://github.com/fastify/fastify/blob/13f9b6eb9083e5f5dcd8de5895adc81101603db4/.github/workflows/benchmark.yml#L36
https://github.com/fastify/fastify/blob/13f9b6eb9083e5f5dcd8de5895adc81101603db4/.github/workflows/benchmark.yml#L41
https://github.com/fastify/fastify/blob/13f9b6eb9083e5f5dcd8de5895adc81101603db4/package.json#L10
https://github.com/fastify/fastify/blob/13f9b6eb9083e5f5dcd8de5895adc81101603db4/package.json#L155-L170
> fix: benchmark CI

- .github/workflows/benchmark-parser.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/citgm.yml
Another issue discovered in the CI, `remove-label` jobs are failing due wrong information being sent to the REST API:
https://github.com/fastify/fastify/actions/runs/8772362238/job/24071203586?pr=5413#step:2:13
https://github.com/fastify/fastify/actions/runs/8772362236/job/24071226346?pr=5413#step:2:13
I believe it's choosing the wrong repo, it should be the base repo instead of the owner of the PR's repo
Reference: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> fix: `remove-label` job uses the wrong repo

- .github/workflows/citgm.yml
Hopefully the last fix...
Last 2 PRs [fixed](https://github.com/fastify/fastify/pull/5413#event-12551166195) the benchmark workflow, but CITGM's `remove-label` job is also [always](https://github.com/fastify/fastify/blob/c47b0330a6c3f546c7fc2535b53d641b20525ab0/.github/workflows/citgm.yml#L88) running whenever a label is set and failing because it can't find the label it's trying to remove — it should only run if `citgm-core-plugins` label is set to remove [that specific label](https://github.com/fastify/fastify/blob/c47b0330a6c3f546c7fc2535b53d641b20525ab0/.github/workflows/citgm.yml#L96-L103)
> fix: only run citgm if citgm-core-plugins label is set

- docs/Reference/Routes.md
- lib/handleRequest.js
- test/lock.test.js
- test/propfind.test.js
- test/proppatch.test.js
Adds webdav methods that require parsing, missing from this PR: https://github.com/fastify/fastify/pull/3836
> feat: adds webdav methods that require body & content type parsing

- docs/Reference/Hooks.md
- Fixes #5353 
The docs refer to `customErrorHandler` but don't say what it is - this links the `setErrorHandler` method.
> docs: improve onError docs by specifying what the error handler is

- .github/workflows/ci.yml
Related to https://github.com/fastify/.github/issues/37
> chore: exclude node 14 and 16 on macOS

- docs/Guides/Detecting-When-Clients-Abort.md
Closes https://github.com/fastify/help/issues/999.
The original documentation implied that other request properties may be used to detect an aborted request.
> docs(guides/abort):  suggest explicit use of the `aborted` property

- docs/Reference/Routes.md
- lib/handleRequest.js
- lib/httpMethods.js
- test/mkcalendar.test.js
- test/report.test.js
- types/utils.d.ts
Related to [#9](https://github.com/fastify/fastify/issues/9) and [PR #3836](https://github.com/fastify/fastify/pull/3836)
Includes support for `MKCALENDAR` and `REPORT` methods which are both part of the webDAV protocol.
I need to use these methods in a project that deals with contacts and calendars sync (CARDDAV / CALDAV).
> feat: add mkcalendar and report methods

- lib/error-handler.js
- lib/wrapThenable.js
- test/500s.test.js
> feat: handle synchronous errors in errorHandler

- fastify.js
- package.json
Removed in https://github.com/fastify/fastify/commit/f776447423fc1df7a6497abb76baea25b797560f
> chore: remove unused dependency and fix ci

- test/types/route.test-d.ts
- types/instance.d.ts
Carries over the work of https://github.com/fastify/fastify/pull/5444
> feat: (types) add shorthand types for MKCALENDAR and REPORT

- docs/Guides/Database.md
From: `Each file an migrations folder need`
To: `Each file in migrations folder need`
> docs(guides/database): correct typo

- docs/Reference/Routes.md
While looking at the documentation I found out a mismatch between the `costraints` example URL and the comment beside it, so I fixed it.
> docs(reference/routes): fix example on constraints

- lib/request.js
Hello, I have a suggestion. When looking up how trustProxy option in Fastify works in detail, I found out that the proxy-addr dependency used by Fastify, specifically the `.all()` function, checks if the trust argument is provided, and if it's not, then it just returns all adresses, skipping the trust checking logic alltogether, which can speed up things greatly, especially if there's a lot of X-Forwarded-For addresses. So, I made this PR, replacing the `return true` function with `undefined`, which has the same effect in the `.ips` property getter of `Request`, but because the proxy-addr default function doesn't support skipping trust argument, I replaced it with proxy-addr `.all()` function in the `.ip` property getter and did the same thing there as the proxy-addr default function …
> perf: Optimize resolving X-Forwarded-For addresses

- test/types/route.test-d.ts
- types/route.d.ts
> fix: `config` type in RouteShorthandOptions

- .github/workflows/benchmark-parser.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci-alternative-runtime.yml
- .github/workflows/ci.yml
- .github/workflows/integration-alternative-runtimes.yml
- .github/workflows/integration.yml
- .github/workflows/package-manager-ci.yml
The main reason is to remove node 18 from the alternative runtimes CI, which [keeps failing for PRs where normal node 18 passes](https://github.com/fastify/fastify/pull/5480); [but as @mcollina suggested](https://github.com/fastify/fastify/issues/5460), we can just remove node 18 support from v5 since it's already pretty divergent from v20+
> chore: remove node 18 from CI

- docs/Reference/Hooks.md
- fastify.js
- lib/handleRequest.js
- lib/wrapThenable.js
- package.json
- test/diagnostics-channel/404.test.js
- test/diagnostics-channel/async-delay-request.test.js
- test/diagnostics-channel/async-request.test.js
- test/diagnostics-channel/error-before-handler.test.js
- test/diagnostics-channel/error-request.test.js
- test/diagnostics-channel/error-status.test.js
- test/diagnostics-channel/init.test.js
- test/diagnostics-channel/sync-delay-request.test.js
- test/diagnostics-channel/sync-request-reply.test.js
- test/diagnostics-channel/sync-request.test.js
- test/internals/handleRequest.test.js
This adds support for emitting [diagnostics channel](https://nodejs.org/api/diagnostics_channel.html#class-tracingchannel) events for a request. It's an extension of #5105. 
The `dc-polyfill` package provides a polyfill of the `diagnostics_channel` module for older versions of Node.js. This is why the existing diagnostics channel call has been removed from a conditional in `fastify.js`. Note that `dc-polyfill` falls back to the existing diagnostics channel if present. That's why the tests are requiring diagnostics channel directly instead of the polyfill to show that it works as expected.
Here's some things I'm wondering about:
**main**
```
┌─────────┬──────┬──────┬───────┬───────┬────────┬─────────┬────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg    │ Stdev   │ Max    │ …
```
> feat: emit diagnostics_channel events upon routing request

- lib/decorate.js
- test/internals/decorator.test.js
> chore: remove unnecessary eslint override

- test/types/instance.test-d.ts
- types/instance.d.ts
> chore: readyListener can be async on server.ready()

- lib/request.js
- package.json
- test/404s.test.js
- test/close.test.js
- test/decorator.test.js
- test/esm/index.test.js
- test/inject.test.js
- test/maxRequestsPerSocket.test.js
- test/plugin.1.test.js
- test/plugin.2.test.js
- test/plugin.3.test.js
- test/plugin.4.test.js
- test/register.test.js
- test/schema-special-usage.test.js
- test/server.test.js
- test/stream.4.test.js
- test/web-api.test.js
(sans FSTDEP)
- Removed `form-data` package (were throwing util.isArray deprecation warn). Swapped out for native FormData since we now are >= v20
- Removed semver checks for unsupported versions of node
- Removed tests not applicable for Node >=v20
- t.mock (deprecated) -> t.mockRequire
- Removed `eslint no-prototype-builtins: 0`, and fixed when necessary
- Removed `new Function('module', 'return import(module)')` 'hack'
> chore: test deprecation cleanup

- lib/route.js
- test/has-route.test.js
> fix: hasRoute method comparison with case insensitive

- test/types/type-provider.test-d.ts
- types/route.d.ts
Fix for #5516
Fixed the test that should have caught this issue.
NOTE: this forces the project to require TypeScript 5.4 or greater
> fix: Type inferrence with auxilliary hook handlers

- docs/Reference/ContentTypeParser.md
for discussion in [5401](https://github.com/fastify/fastify/issues/5401) 
This PR includes an update to the documentation for addContentTypeParser
> docs: addContentTypeParser with fastify.register

- test/types/type-provider.test-d.ts
- types/route.d.ts
- types/utils.d.ts
Backport fix for #5516 
Uses a little cheat so that NoInfer does not need to be used, so older TS versions should still work.
> fix: (backport) Type inferrence with auxilliary hook handlers

- lib/server.js
- test/listen.5.test.js
I don't think we should permit multiple calls to `.listen`, but we should also properly cleanup the listener if `node` currently doesn't.
Fixes #5519 
> fix: server.listen listener is not cleanup properly

- docs/Guides/Write-Type-Provider.md
- test/types/register.test-d.ts
- test/types/type-provider.test-d.ts
- types/reply.d.ts
- types/type-provider.d.ts
Fix for discussion: https://github.com/fastify/fastify/discussions/5311
An update on a previous PR
This improved PR includes:
- Breaking changes with separate providers for both the validation and serialization stages
- Docs for the new TypeProvider interface
- A test
> feat: type definitions and documentation for separated type provider.

- lib/pluginUtils.js
- test/plugin.4.test.js
The checks against versions in all of our modules relies on this code. I need this plus a new alpha release.
> chore: support pre and alpha tags

- .npmignore
Fixes: https://github.com/fastify/fastify/issues/5536
I think we should bump a new release, 4 MB are too much
> fix(v4): update .npmignore

- lib/server.js
(Also fixed a typo and removed a Istanbul comment.)
> chore: rm < node19 support from secondaryServer.close()

- docs/Guides/Recommendations.md
The `http2` directive was introduced more than year ago, it would make sense to update the docs accordingly.
> docs: use `http2` directive in nginx config

- docs/Reference/Routes.md
- lib/handleRequest.js
- test/copy.test.js
- test/mkcol.test.js
- test/move.test.js
Already done in version 5, but not available in version 4 (and it's very useful !)
> feat(backport 4.x): add body parsing on copy move mkcol methods

- .github/workflows/ci-alternative-runtime.yml
We should not provide two track of `automerge` action.
It will leads to race-condition.
See https://github.com/fastify/fastify/pull/5554
Even if the linting failed on the normal track, it merges by the alternative runtime track
Depends on #5558
> ci: remove automerge from ci alternative runtimes

- docs/Reference/Hooks.md
- fastify.js
- lib/handleRequest.js
- lib/wrapThenable.js
- package.json
- test/diagnostics-channel/404.test.js
- test/diagnostics-channel/async-delay-request.test.js
- test/diagnostics-channel/async-request.test.js
- test/diagnostics-channel/error-before-handler.test.js
- test/diagnostics-channel/error-request.test.js
- test/diagnostics-channel/error-status.test.js
- test/diagnostics-channel/init.test.js
- test/diagnostics-channel/sync-delay-request.test.js
- test/diagnostics-channel/sync-request-reply.test.js
- test/diagnostics-channel/sync-request.test.js
Fastifyv5 engine targets means we no longer need the `dc-polyfill` package.
diagnostics_channel became stable @ v18.13.0.
tracingChannel class api was added in v18.19.0 and is still experimental, however, dc-polyfill uses the internal version if node >=18.19 so it does nothing for us in fastify v5.
(document tweak)
> chore: remove dc-polyfill

- .github/workflows/pull-request-title.yml
Allows `!` in title to indicate the PR is breaking change and shouldn't be backported.
> chore: allow ! in PR title

- docs/Guides/Ecosystem.md
Hi guys, I have this little plugin to add to the community plugins on your ecosystem page, it's very useful for me, so I want to share it with the fastify community.
I have my repository at [https://github.com/aaroncadillac/crudify-mongo](https://github.com/aaroncadillac/crudify-mongo) and it is properly documented and tested, and my plugin is available in npm packages.
Checklist
Thanks and happy code
> docs: Adding `crudify-mongo` plugin to community list

- docs/Reference/TypeScript.md
I made some small adjustments to the Typescript docs:
* I removed the type provider from the Typebox example. The example uses both a type provider and a generic which makes one of them obsolete. Also to my understanding this part of the docs is supposed to show how to use those libraries without type providers. There's a separate documentation of the type providers.
* I rephrased some sentences, just minor things.
> docs(reference/typescript): remove type provider from typebox example

- SPONSORS.md
As titled
- https://opencollective.com/handsontable-javascript-data-grid
If someone from Handsontable team would like to submit a better link or a logo to add it to the website, I will be more than happy to deploy it!
> chore(sponsor): add handsontable

- test/listen.1.test.js
This PR is for removing the warning listener from the node process in server listen tests ([ref](https://github.com/fastify/fastify/pull/5590#discussion_r1693983872))
> fix: removed warning listener from tests

- eslint.config.js
- package.json
This PR does the following: (fixes #5588)
- Updates `test:typescript` to include `--noEmit` to prevent the ouput of javascript file `import.js`
- Ignores `'test/types/import.js'` in `eslint.config.js` for existing cloned repositories with file created
> fix: test suite import.js emitting errors

- docs/Reference/Warnings.md
- lib/route.js
- lib/warnings.js
- test/http-methods/head.test.js
- test/route.7.test.js
Fixes #5596
`HEAD` route must register before `GET` route if `exposeHeadRoute` is enabled.
It can prevents the route b-tree rebuild.
> refactor: remove FSTDEP007

- lib/decorate.js
- lib/route.js
- lib/server.js
- lib/validation.js
- test/decorator.test.js
- test/internals/decorator.test.js
- test/internals/request-validate.test.js
> refactor: use `Object.hasOwn`

- docs/Reference/Warnings.md
- lib/reply.js
- lib/warnings.js
- test/reply-trailers.test.js
Remove `FSTDEP013` deprecation warning
> refactor: remove `FSTDEP013`

- lib/route.js
- test/route.8.test.js
- test/throw.test.js
Came across this small bug during unit tests in my project.
I have a unit test that catches various errors that lean on Fastify error codes, and I had a case where I expected to get the FST_ERR_DUPLICATED_ROUTE instance, but got raw Error instance:
```
const fastify = require('fastify')({
logger: true
})
fastify.get('/:param2', (request, reply) => {
reply.type('application/json').code(200)
return { hello: 'example' }
})
fastify.head('/:param1',  (request, reply) => {
reply.type('application/json').code(200)
return { hello: 'other' }
})
fastify.addHook('onReady', async function hook () {
console.log(fastify.printRoutes())
})
fastify.listen().then(console.log)
```
In this case, we expect to get `FST_ERR_DUPLICATED_ROUTE` error, because we're adding `HEAD` method of the same route after …
> fix: throwing "FST_ERR_DUPLICATED_ROUTE" error instead of raw error

- lib/reply.js
- test/web-api.test.js
We must add `Response.headers` before proceeding, otherwise early returns (ie: `204`) will miss them.
We can also remove special handling of `ReadableStream`: since the `Response` usage is fully finished, we can continue with `Response.body` as the payload and the possible types `null` or `ReadableStream` will be handled by existing cases.
Last but not least, we should add `304` handling to the same early return handling `204`, including the removal of `content-*` headers.
> **NOTE:** this should be back ported to other branches, at least v4 suffers from the same issue.
> fix: reorder handling of `Response` replies

- eslint.config.js
- package.json
The shortcomings that necessitated the workarounds when `neostandard` was introduced int #5509 have now all been fixed upstream, so a simpler setup can now be used.
(This is a short little simple PR before I get started contributing more substantially here again)
(Disclaimer: I'm the main author of `neostandard` so I wanted to clean up the mess I left behind)
> chore: simplify `neostandard` setup

- package.json
> chore: bump find-my-way to v9

- test/hooks.test.js
- test/types/hooks.test-d.ts
- types/hooks.d.ts
the `done` parameter does not exist in onRegister hooks
https://github.com/fastify/fastify/blob/07bc7cf7600e939b9d3a83338f888cfbe4a52b79/lib/pluginOverride.js#L69
> types: remove nonexistant done parameter from onRegister

- docs/Guides/Migration-Guide-V5.md
The naming was used before the PR review: https://github.com/fastify/fastify/pull/5567
> fix(docs): migration guide

- fastify.d.ts
- test/childLoggerFactory.test.js
- test/types/fastify.test-d.ts
- add childLoggerFactory option to FastifyHttpOptions type
- add test for childLoggerFactory option
fixes: #5664
> fix: add childLoggerFactory option to FastifyHttpOptions type

- docs/Guides/Ecosystem.md
These were all archived between May - June this year, so are not supported by v5.x.
> docs(guides/ecosystem): remove archived core plugins

- docs/Reference/Reply.md
Minor cleanup of Reply docs: Removed incorrect information stating that the elapsedTime getter will return 0 unless called in the onResponse hook, which is not the intended behaviour based on the discussion in #4575 and [existing tests](https://github.com/fastify/fastify/blob/b1b9a75cc08c00c27bae286ef85f71f259892176/test/internals/reply.test.js#L1508). I also removed a link that previously led to the getResponseTime section of the docs before it was removed in v5.
Cheers!
> docs(reply): cleanup and update to clarify elapsedTime behaviour

- lib/pluginOverride.js
- test/hooks.test.js
- test/types/hooks.test-d.ts
- types/hooks.d.ts
For #4967
To onRegister hooks we pass `this` and the instance, however there are 2 problems:
1) what `this` points to is documented neither in types nor the docs
2) the goal was probably to pass the parent, as the other passed parameter, `instance`, is the new fastify instance, but `this` actually points to the avvio instance as can be seen from here:
https://github.com/fastify/fastify/blob/501be899761e60dfc713ac0a415b518ba6595034/fastify.js#L446
This PR passes the parent as `this`
For more info, see: https://github.com/fastify/fastify/pull/5670#discussion_r1748862579
> fix: point this to parent at onRegister

- lib/contentTypeParser.js
- test/content-parser.test.js
so this actually correctly fixes #5740
[standards](https://httpwg.org/specs/rfc9110.html#media.type) say `Content-Type` is case insensitive, which is why we prevent the registration of `text/html` and `text/HTML` at the same time, but currently don't treat text/html and text/HTML as the same
> fix: make content-type case-insensitive

- docs/Reference/ContentTypeParser.md
- docs/Reference/Reply.md
- docs/Reference/Routes.md
- docs/Reference/Server.md
By reading the docs I found out that the `var` keyword is used in some snippets instead of `let` and `const`. As they are the recommended standard I took my time to change it.
> docs: Changed var for let and const

- lib/pluginUtils.js
Changed capture group `(...)` to non-capture group `(?:...)`, as nothing is done with the captured text, so the regex engine is doing extra work capturing and storing text only to end up not using it.
> perf(lib/pluginUtils): convert unused capture group to non-capture group

- lib/validation.js
`.exec()` returns an array of matches, which we never use. `.text()` returns a boolean indicating whether the string contains the pattern.
> refactor(lib/validation): replace regexp `.exec()` with `.test()`

- lib/validation.js
Not having a quantifier is the same as `{1}`. This is just giving the regex engine extra work.
This PR also replaces `[0-9]` with the shorter `\d` syntax, and consolidates two similar alternatives into one.
> refactor(lib/validation): remove redundant regex quantifier

- test/build/error-serializer.test.js
- test/build/version.test.js
- test/versioned-routes.test.js
- test/web-api.test.js
- test/wrapThenable.test.js
> test: migrate tests from tap to node:test and c8

- test/https/https.test.js
Hi,
In my previous PR #5714, I accidentally had one file with `assert.fail` receiving two arguments (which is deprecated) instead of one, so I just noticed that and wanted to fix it quickly. I assumed opening a issue for that minor thing is not needed, correct me if I'm wrong.
I made sure that the only place that it happened was `./test/https/https.test.js`.
> test: removed second argument from assert fail method in tests

- test/http2/closing.test.js
- test/http2/constraint.test.js
- test/http2/head.test.js
- test/http2/missing-http2-module.test.js
- test/http2/plain.test.js
- test/http2/secure-with-fallback.test.js
- test/http2/secure.test.js
- test/http2/unknown-http-method.test.js
Hi, 
These changes are related to the issue https://github.com/fastify/fastify/issues/5555
Changed `/test/http2` tests to use `node:test` instead of `tap`.
Basically, followed the same guidelines as my previous PR #5714.
> test: Migrate http2 test to node:test

- test/versioned-routes.test.js
The server tests in `test/versioned-routes.test.js` use sget and thus callback notation. This causes a race condition where the second callback (containing the `done()` call) runs before the first callback.
To fix, the second request was moved into the callback of the first request.
> test: Fix flaky tests in versioned-routes.test.js

- test/404s.test.js
Hi,
These changes are related to the issue https://github.com/fastify/fastify/issues/5555
Changed /test/404.test.js to use `node:test` instead of tap.
> test: Migrate 404 test to node:test

- lib/route.js
- test/request-error.test.js
- test/route.8.test.js
- test/types/route.test-d.ts
- types/request.d.ts
- types/utils.d.ts
While investigating #5762 I realized that there is an issue when passing lower case methods to the route fn. You could run the test "Will pass onSend hook to HEAD method if exposeHeadRoutes is true /2" on main branch and see that it fails.
Also makes the typings less strict regarding the method attribute as  `CONNECT` or `OPTION` could be added via `acceptHTTPMethod`, 
Also tries to fail faster. 
Requesting review by @climba03003  regarding the exposeHeadRequest logic.
Requesting review by @eomm regarding the acceptHTTPMethod aspect
> fix: exposeHeadRoute should pass "onSend" hook handlers provided to GET handler if method is not uppercased

- test/custom-http-server.test.js
porting of `custom-http-server.test.js` from tap to node:test
> test: migrated custom-http-server from tap to node:test

- test/server.test.js
`server.test.js` porting from `tap` to `node:test`
> test: port server.test.js to node:test

- test/als.test.js
- test/async-await.test.js
These changes are related to the issue https://github.com/fastify/fastify/issues/5555
Changed `als.test.js` and `async-await.test.js` to use `node:test` instead of `tap`.
> chore: Migrate async-local-storage and async-await test to node:test

- test/async-dispose.test.js
Proposal:
- migrated `async-dispose.test.js` file from `tap` to `node:test` 🔥
> test: migrated async-dispose.test.js from tap to node:test

- test/constrained-routes.test.js
Hi,
These changes are related to the issue https://github.com/fastify/fastify/issues/5555
Changed `test/constrained-routes.test.js` tests to use `node:test` instead of tap.
> test: migrate constrained routes test file to use node:test

- test/serialize-response.test.js
Refactor test to use node:test instead of tap
- Relevant to issue #5555 
- Updated /test/serialize-response.test.js to replace tap with node:test
> test: migrate serialize-response to node test runner

- test/reply-early-hints.test.js
Proposal:
- migrated `reply-early-hints.test.js` file from `tap` to `node:test` 🔥
> test: migrated reply-early-hints.test.js from tap to node:test

- test/request-timeout.test.js
Proposal:
- migrated `request-timeout.test.js` file from `tap` to `node:test` 🔥
> test: migrated request-timeout.test.js from tap to node:test

- .github/workflows/benchmark-parser.yml
- .github/workflows/benchmark.yml
The input name changed from `GITHUB_TOKEN` to `github-token` with [v3 of thollander/actions-comment-pull-request](https://github.com/thollander/actions-comment-pull-request/releases/tag/v3.0.0).
> ci(benchmark): fix github token input

- test/reply-code.test.js
Proposal:
- migrated `reply-code.test.js` file from `tap` to `node:test` 🔥
> test: migrated reply-code.test.js from tap to node:test

- test/allow-unsafe-regex.test.js
- test/buffer.test.js
- test/case-insensitive.test.js
- test/check.test.js
- test/conditional-pino.test.js
- test/http-methods/head.test.js
- test/request-timeout.test.js
- test/route.3.test.js
Convert asserts to strict asserts and remove console.log in tests
> fix: test asserts to strict asserts

- .gitattributes
Majority of the repos have these two rules on the same line.
To make maintenance easier going forward it'd be best to standardize files across the org.
> style(.gitattributes): standardize style across fastify repos

- test/post-empty-body.test.js
Proposal:
- migrated `post-empty-body.js` file from `tap` to `node:test` 🔥
> test: migrated post-empty-body.test.js from tap to node:test

- test/use-semicolon-delimiter.test.js
Proposal:
- migrated `use-semicolon-delimiter.js` file from `tap` to `node:test` 🔥
> test: migrated use-semicolon-delimiter.test.js from tap to node:test

- test/max-requests-per-socket.test.js
Proposal:
- migrated `max-requests-per-socker.test.js` file from tap to node:test 🔥
> test: migrated max-requests-per-socket.test.js from tap to node:test

- test/proto-poisoning.test.js
Proposal:
- migrated `proto-poisoning.test.js` from `tap` to `node:test` 🔥
> test: migrated proto-poisoning.test.js from tap to node:test

- test/content-type.test.js
- test/context-config.test.js
Porting of `content-type.test.js` and `context-config.test.js` from `tap` to `node:test`
> test: migrated content-type and context-config tests from tap to node:test

- test/trust-proxy.test.js
- test/type-provider.test.js
- test/url-rewriting.test.js
Mirgate tests from tap to node:test
- trust-proxy.test.js
- type-provider.test.js
- url-rewriting.test.js
<hr>
> test: migrate trust-proxy, type-provider, url-rewriting to node:test

- test/fluent-schema.test.js
Proposal:
- migrated `fluent-schema.test.js`  from `tap` to `node:test` 🔥
> test: migrated fluent-schema.test.js from tap to node:test

- test/header-overflow.test.js
- test/noop-set.test.js
- test/set-error-handler.test.js
Proposals:
- migrated `set-error-handler.js` from `tap` to `node:test` 🔥 ( see here: [afe854f](https://github.com/fastify/fastify/pull/5835/commits/afe854fb1a2bf4a6f46090f12be91a0fde8954e0))
- migrated `header-overflow.test.js` from `tap` to `node:test` 🔥 (see here: [20d43cd](https://github.com/fastify/fastify/pull/5835/commits/20d43cdbdf5cb60628fe7d410aff37bf9a62fc62))
- fix method `fail` on `noop-set.test.js`file  ( see here: [652a1fd](https://github.com/fastify/fastify/pull/5835/commits/652a1fd00322edc1863ae8f9799a9b1d82e0fb4a))
> test: migrated set-error-handler.test.js and header-overflow.test.js from tap to node:test

- test/pretty-print.test.js
Proposal:
- migrated `pretty-print.test.js` from `tap` to `node:test` 🔥
> test: migrated pretty-print.test.js from tap to node:test

- test/request-id.test.js
Proposal:
- migrated `request-id.test.js` from `tap` to `node:test` 🔥
> test: migrated request-id.test.js from tap to node:test

- test/router-options.test.js
Proposal:
- migrated `router-options.test.js` from `tap` to `node:test` 🔥
> test: migrated router-options.test.js from tap to node:test

- test/validation-error-handling.test.js
> test: migrated validation-error-handling from tap to node:test

- test/handler-context.test.js
Proposal:
-  migrated `handler-context.test.js` file from `tap` to `node:test` 🔥
> test: migrated handler-context.test.js from tap to node:test

- README.md
See https://github.com/fastify/fastify-accepts/pull/180
Also swapped out the workflow badge syntax for the [shorter syntax style](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge#using-the-branch-parameter).
> docs(readme): point ci badge at main branch

- README.md
Moved to shorted workflow badge syntax in https://github.com/fastify/fastify/pull/5873 but found it was actually deprecated.
The long form syntax is what should be used, doh!
Have kept the branch param from that PR though.
> docs(readme): revert to standard workflow badge syntax

- .github/workflows/ci.yml
- .github/workflows/coverage-win.yml
The current Windows CI is broken because the dns resolves in Windows is returning wrong values.
Refs: https://github.com/nodejs/node/issues/56137
This PR is pinning the `node@22` in `node@22.11` version. So, the revert can be made easily when https://github.com/nodejs/node/pull/56224 is landed in next release.
> ci: pin node version 22.11

- docs/Guides/Ecosystem.md
Updates the description for Apitally, a community plugin listed on the Ecosystem page in the docs. This is to reflect how Apitally has evolved since it was first added.
> docs(ecosystem): update apitally description

- docs/Reference/Request.md
- lib/request.js
- test/request-header-host.test.js
Fixes #5841
Since there's so many reason the Host header can be missing.
I would just simplify the logic as always fallback to empty string.
The document is updated to explain `hostname` and `port` is always depends on the `host` property.
> fix: crash when host header is missing by various of reason

- .github/workflows/coverage-nix.yml
- .github/workflows/coverage-win.yml
- package.json
- test/close-pipelining.test.js
- test/hooks.test.js
- test/post-empty-body.test.js
- test/trust-proxy.test.js
fixes our win coverage issue:
- https://github.com/fastify/fastify/actions/runs/12182503397/job/33981743111
```
Error: [Error [ERR_TEST_FAILURE]: connect ECONNREFUSED 127.0.0.1:50469] {
code: 'ERR_TEST_FAILURE',
failureType: 'testCodeFailure',
cause: Error: connect ECONNREFUSED 127.0.0.1:50469
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
errno: -4078,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 50469
}
}
FAILED: D:\a\fastify\fastify\test\post-empty-body.test.js
```
> chore: fix flaky test

- test/build-certificate.js
- test/reply-code.test.js
- test/reply-early-hints.test.js
See https://github.com/fastify/fastify-static/pull/407
> perf: use `node:` prefix to bypass require.cache call for builtins

- CONTRIBUTING.md
- README.md
This PR:
- reorder lists alphabetically as written here: https://github.com/fastify/fastify/blob/main/CONTRIBUTING.md#onboarding-collaborators
- move a few contributors to emeritus status to reflect this team: https://github.com/orgs/fastify/teams/emeritus
- applies what was said in this internal discussion https://github.com/orgs/fastify/discussions/51#discussioncomment-11471265
This will be reflected on the website whenever this PR is approved too.
> chore: org members reorder

- test/custom-parser.2.test.js
Proposal:
- migrated `custom-parser.2.test.js` from `tap` to `node:test` 🔥
> test: migrated custom-parser.2.test.js from tap to node:test

- lib/error-handler.js
annoyingly linting issues in upstream of neostandard makes our ci fail.
@voxpelli did try to fix this by pinning a dep in #5924 , but this didnt fix it apparantly
> fix(linting): fix linting error in error-handler.js

- lib/contentTypeParser.js
While looking at https://github.com/fastify/fastify/pull/5925, I realized we might be doing more payload validation than necessary
We set the default parsers with [`asString = true`](https://github.com/fastify/fastify/blob/36c38bc5ae250a52c8aa953c38919f599db4683b/lib/contentTypeParser.js#L35-L36), so the `body` will already be a string once it reaches the default json parser and we don't need the `== null`, `Buffer.isBuffer`, etc.
> fix: don't check for payload type in default json parser

- docs/Guides/Migration-Guide-V5.md
This wasn't included in the guide, but is a fairly important breaking change for applications that were using `req. hostname`.
- ~~run `npm run test` and `npm run benchmark`~~
- ~~tests and/or benchmarks are included~~
> docs: Include req.hostname change in upgrade guide

- .github/dependabot.yml
Copied from https://github.com/fastify/fastify/pull/5924#issuecomment-2577093391
I don't think we should have grouped unrelated dev dependencies in this repo for Dependabot updates. One breaks and it blocks the rest.
It makes sense to group packages that depend on each other like Eslint with any Eslint plugins, but not this.
> build(dependabot): regroup dev dependencies

- lib/contentTypeParser.js
- lib/headRoute.js
- lib/pluginUtils.js
- lib/validation.js
It's a small thing but we're never interested in what `done` returns and in most of the codebase we use:
```js
done()
return
```
For brevity, I've updated the remaining parts to also return directly and not return `done`
> chore: don't return the `done` function

- lib/contentTypeParser.js
- lib/validation.js
@mcollina came to the rescue
Let's not mix `result && typeof result.then === 'function'` and `typeof result?.then === 'function'` in the codebase as the former is still faster
> perf: don't use optional chaining for typeof .then checks

- docs/Reference/TypeScript.md
Since typescript-eslint v8, no special care is needed when dealing with `no-floating-promise` rule, everything just works by default.
> docs: the no floating promise guide is not needed anymore

- lib/pluginUtils.js
Regex is expensive to create and garbage collect, so this should help a tad rather than having to create a new regexp object every time a plugin version is checked.
> perf(lib/pluginutils): cache rc version regex

- docs/Reference/ContentTypeParser.md
- docs/Reference/Reply.md
This PR:
- Improves clarity and conciseness
- Moves an [unrelated sentence](https://github.com/fastify/fastify/pull/3159#discussion_r659017947) to the `reply` reference doc
> docs(reference/contenttypeparser): make more concise

- docs/Reference/Type-Providers.md
Got rid of two sentences about installing modules. Shouldn't need to teach developers how to suck eggs.
> docs(reference/type-providers): conciseness improvements

- docs/Reference/Errors.md
> docs(reference/errors): conciseness improvements

- docs/Reference/Logging.md
Not much to say, the original covers everything, just needed a tidy!
Have also added section headers to break the content up.
> docs(reference/logging): conciseness improvements

- docs/Reference/Request.md
This also standardizes the Request property/field list style to be like the Reply list style (capitalized first letter, ends in period).
> docs(reference/request): conciseness improvements

- docs/Reference/Validation-and-Serialization.md
Also closes #5459 by removing a reference to a non-existent section in another part of the docs.
> docs(reference/validation): conciseness improvements

- docs/Reference/Plugins.md
This PR also removes an unrelated sentence about `onClose` hooks, which is already present in the Hooks docs.
The code examples have been reviewed to check they do not use any mixed callback/promise APIs, [support of which was removed in Fastify v5](https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V5.md#plugins-cannot-mix-callbackpromise-api-anymore). None of them do (woo).
> docs(reference/plugins): conciseness improvements

- docs/Reference/Decorators.md
> docs(reference/decorators): conciseness improvements

- test/types/instance.test-d.ts
- types/instance.d.ts
Adds _supportedMethods_ to instance type.
Ref: https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/#removal-of-some-non-standard-http-methods
> fix(types): missing supportedMethods

- docs/Reference/ContentTypeParser.md
- docs/Reference/Hooks.md
- docs/Reference/Logging.md
- docs/Reference/Middleware.md
- docs/Reference/Reply.md
- docs/Reference/Request.md
- docs/Reference/Routes.md
- docs/Reference/Server.md
- docs/Reference/Validation-and-Serialization.md
This PR updates the notes and warnings across the reference documentation to use emojis and block quotes, [mimicking GitHub's note and warning highlighting](https://github.com/orgs/community/discussions/16925).
This should make these parts of the documentation stand out more. You can already see this in action on the [ContentTypeParser page](https://fastify.dev/docs/latest/Reference/ContentTypeParser/#content-type-parser), where this style draws your attention to the warning.
> docs(reference): mimic github notes and warning style

- docs/Reference/LTS.md
This PR fixes an issue where anchor tags were displayed as code blocks in the LTS documentation.
> docs(lts): fix anchor tag format

- docs/Reference/Server.md
The current information in the documentation is wrong. Fastify uses https://github.com/delvedor/find-my-way for routing which doesn't use `querystring` for parsing at all but uses [fast-querystring](https://www.npmjs.com/package/fast-querystring) by default.
> docs: wrong query string parser information

- docs/Reference/LTS.md
The sentence was trimmed by https://github.com/fastify/fastify/pull/5951
cc @Fdawgs
> chore: fix docs

- lib/server.js
- lib/warnings.js
- test/listen.5.test.js
I'm seeing multiple users that keep mixing async and callback.
This PR adds the generic `FSTWRN003` warning (which accepts the `subject` as input) in order to add more warnings to help the developer to find bad usage.
> feat: add listen async callback warning

- docs/Guides/Testing.md
Replace `--node-arg=--inspect-brk` by `--inspect-brk`.
The `--node-arg` is a [NODE TAP](https://node-tap.org/cli/#--node-arg%3D%3Carg%3E) and this package is not used anymore.
> docs: remove --node-arg prefix

- test/toolkit.js
- test/trust-proxy.test.js
Our `main` tests are not stable:
This PR clean up a bit the flaky test and adds a small utility to avoid the `pending` stuff to wait for multiple async functions
Unblock #6013
> test: fix flaky

- test/internals/content-type-parser.test.js
Toad-cache replaced tiny-lru in https://github.com/fastify/fastify/pull/4668
> test(content-type-parser): replace tiny-lru proxy with toad-cache

- test/types/type-provider.test-d.ts
- types/type-provider.d.ts
Fixes https://github.com/fastify/fastify/issues/6020
> fix: wrong reply return type

- .github/workflows/ci-alternative-runtime.yml
We added this CI workflow in https://github.com/fastify/fastify/pull/5332
As suggested: https://github.com/fastify/fastify/pull/5332#pullrequestreview-1906365087, I'm marking this run as "optional" because it is flaky.
Lately I need to run it at least twice to get a green:
- https://github.com/fastify/fastify/actions/runs/14129794841
- https://github.com/fastify/fastify/actions/runs/14041898978
- https://github.com/fastify/fastify/actions/runs/14042618758
TBH, I would evaluate to remove it because it seems to me that the prerequisites are not meet anymore: https://github.com/fastify/fastify/pull/5332#issuecomment-1967933779
NSOLID should just run the pipeline when a new commit is performed on this repo.
cc @RafaelGSS @riosje
> ci: continue-on-error on alternative runtime

- fastify.js
- test/fastify-instance.test.js
Disclaimer: this is committed with `--no-verify` because penultimate test fails locally with `EAFNOSUPPORT`.
Once support of Node.js older than v22.x is dropped, this should probably be rewritten using `Promise.withResolvers()`.
Without the patch, `assert.strictEqual` might hang and timeout instead of failing immediately. Didn't look into it closely, i guess combination of resolved promise and circular references might trigger a bug in `strictEqual()`?
> fix: clear `[kState].readyPromise` for garbage collection

- SPONSORS.md
Removing the sponsor as the subscription has been cancelled
(the next charge did not happen)
> chore: remove sponsort

- docs/Guides/Ecosystem.md
This PR adds an entry to the Ecosystem.md file with a brief description of fastify-lm and a link to its official GitHub repository. This will allow Fastify users to discover the plugin and easily access its documentation.
Changes made:
Added a new entry in Ecosystem.md with a description of fastify-lm and a link to its official GitHub repository.
Closes #6023
> docs: add fastify-lm to Ecosystem.md

- test/fastify-instance.test.js
- test/hooks.on-listen.test.js
- test/listen.2.test.js
Avoid `EAFNOSUPPORT` failures on systems without IPv6 support.
> test: skip IPv6 tests if its support is not present

- docs/Guides/Benchmarking.md
Replaced old GitHub link (kimmobrunfeldt/concurrently) with the new official repo (open-cli-tools/concurrently) since the original has been archived.
> docs: fix archived concurrently link to point to active repo

- lib/validation.js
- test/schema-validation.test.js
Follow-up from https://github.com/fastify/fastify/security/advisories/GHSA-mg2h-6x62-wpwc
> fix: treat space as a delimiter in content-type parsing

- eslint.config.js
- lib/decorate.js
- lib/logger-factory.js
- lib/logger-pino.js
- lib/reply.js
- lib/request.js
- test/issue-4959.test.js
- test/types/plugin.test-d.ts
- test/types/register.test-d.ts
- test/use-semicolon-delimiter.test.js
- Added "no `comma-dangle`" rule on eslint config file
- Ran `npm run lint:fix`  to remove remaining trailing commas
I get an error from coverage threshold on tests for `lib/server.js`  but, since it is happening on `main` branch too, I ignored the pre-commit hook. I can open a PR to add the missing test if needed.
Fixes: #6029 
> style: add "no comma-dangle" rule to eslint config and remove trailing commas

- package.json
This fixes an issue where the tests would fail to run if running on a system where there was just 1 CPU.
See https://github.com/mcollina/borp/issues/160
> fix: update borp to 0.20.0.

- test/close-pipelining.test.js
Saw this test failing several time in the CI.
> test: stabilize pipelining shutdown test with controlled close timing

- docs/Guides/Ecosystem.md
- remove `fastify-diagnostics-channel` as it has been archived.
> docs(ecosystem): remove `fastify-diagnostics-channel`

- fastify.js
- test/internals/hooks.test.js
Currently, we can't catch this:
```js
fastify.addHook("invalidHook", () => {});
try {
await fastify.ready()
} catch (error) {
// Unreachable
}
```
> fix: internal function _addHook failure should be turned into the rejection app.ready is waiting for

- docs/Reference/Server.md
- test/inject.test.js
- replaces usage of the removed `req.routerPath` with the updated `req.routeOptions.url` in `inject.test.js`
- updates the note in the documentation to reflect the change from `request.routerPath`, `routerMethod`, and `context.config` to `request.routeOptions.url`, `routeOptions.method`, and `routeOptions.config` within the custom "not found" handler.
> test: replace removed request properties and update docs

- .github/workflows/ci.yml
This is just an idea, but I think it would be interesting to be able to test Node.js release candidates, specially for semver-major versions
> ci: add support to test release candidates

- .github/workflows/ci-alternative-runtime.yml
The alternative NSolid runtime is making our CI red without reason.
Moving the boolean to job level, because the `nodesource/setup-nsolid@v1` is failing
Ref:
- #6034 
- https://github.com/fastify/fastify/actions/workflows/ci-alternative-runtime.yml
> fix(ci): ignore alternative runtime result

- test/types/request.test-d.ts
- types/request.d.ts
Ref.
- https://fastify.dev/docs/latest/Reference/Request/#request
- https://github.com/fastify/fastify/blob/7090d75d3769d6e05ddc577d465c2f6b9e0d62db/lib/request.js#L181-L192
> fix(types): add missing version to request.routeOptions

- docs/Guides/Ecosystem.md
- docs/Reference/ContentTypeParser.md
- docs/Reference/Hooks.md
- docs/Reference/Logging.md
- docs/Reference/Middleware.md
- docs/Reference/Reply.md
- docs/Reference/Request.md
- docs/Reference/Routes.md
- docs/Reference/Server.md
- docs/Reference/Validation-and-Serialization.md
Previous icon was not visible in Safari. See https://github.com/fastify/fastify/pull/6132#discussion_r2097602170
> docs: use cross-platform compatible info emoji

- test/hooks-async.test.js
This is a tentative to fix the hook-async flaky test
References:
- https://github.com/fastify/fastify/actions/runs/15452115950/job/43496716783?pr=6154
- https://github.com/fastify/fastify/actions/runs/15451905460/job/43495806687
> fix: hook async flaky

- .github/workflows/backport.yml
- .github/workflows/benchmark-parser.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci-alternative-runtime.yml
- .github/workflows/ci.yml
- .github/workflows/integration-alternative-runtimes.yml
- .github/workflows/integration.yml
- .github/workflows/links-check.yml
- .github/workflows/lock-threads.yml
- .github/workflows/md-lint.yml
- .github/workflows/package-manager-ci.yml
- .github/workflows/test-compare.yml
Closes https://github.com/fastify/fastify/security/code-scanning/33 and 15 other code scanning alerts.
Most first-party actions now use https://github.com/actions/publish-immutable-action, which negates the need for commit hashes, but this is not available for third-party actions yet.
> ci: pin third-party actions to commit-hash

- LICENSE
Swap out the date range with `-present`, borrowing [`@fastify/vite`'s style](https://github.com/fastify/fastify-vite/blob/main/LICENSE).
A large number of projects no longer use the range (or dates), and this should stop low-effort PRs, present company included.
See https://hynek.me/til/copyright-years/
> chore(license): replace date range

- docs/Reference/Server.md
- types/instance.d.ts
Better reflect that setErrorHandler handles thrown exceptions during a request lifecycle, instead of the very vague "whenever an error happens".
See open discussion [here](https://github.com/fastify/fastify/discussions/6226).
> docs: setErrorHandler description

- fastify.js
- lib/server.js
- test/server.test.js
> fix: handle abort signal in fastify.listen

- docs/Reference/Routes.md
Small doc change to include payload in the `preParsing` signature 
> docs(routes): add payload to preParsing signature

- docs/Reference/Routes.md
> docs: correct parameter name in frameworkErrors handler

- lib/contentTypeParser.js
- test/body-limit.test.js
- Removes the TODO and uses `asyncResource.bind`
- Makes sure we call `emitDestroy` in all error cases
> feat: optimize content type parser by using AsyncResource.bind()

- lib/error-handler.js
- lib/reply.js
- package.json
- Refactors `reply.send` to prioritize `this[kReplyIsError]`, which is a simple boolean check, over `instanceof Error`
https://github.com/fastify/fastify/blob/afd7f509daec4d43ef9dac9d3ea1c8a0cf1ea092/lib/reply.js#L138
This should run faster when we throw one of our errors, and if it's not the case, the boolean check should be pretty much instant so it's another small win
- Also simplifies the branching of the method
New benchmark, `benchmark:parser:error`:
PR:
```sh
[1] Running 30s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1] 
[1] 
[1] ┌─────────┬────────┬──────────┬──────────┬──────────┬─────────────┬────────────┬──────────┐
[1] │ Stat    │ 2.5%   │ 50%      │ 97.5%    │ 99%      │ Avg         │ Stdev      │ Max      │
[1] …
```
> chore: refactor reply.send and prioritize kReplyIsError

- types/logger.d.ts
Pino 9.8 changed its type definitions to be more correct (see https://github.com/pinojs/pino/pull/2223 and linked discussions), but that causes problems for projects that don't set "esModuleInterop: true" (see https://github.com/pinojs/pino/issues/2253).
Doing a namespace import (so fastify.d.ts can see pino's types) should address this.
No tests are included. I locally tested the issue by temporarily modifying package.json's `test:typescript` command to build with `--esModuleInterop false`. Running the `tsc` command multiple times under different combinations of compiler options seems potentially involved, but I can add that to this PR if there's interest.
> fix(types): Fix use of "esModuleInterop: false"

- lib/server.js
Replace function declaration with arrow function to properly reference the session object when closing timed-out HTTP/2 sessions.
I would sometimes get this error in my web application with fastify v5.5.0:
```
172444 |   const httpsOptions = options.https === true ? {} : options.https
172445 |
172446 |   if (options.http2) {
172447 |     const server = typeof httpsOptions === 'object' ? http2.createSecureServer(httpsOptions, httpHandler) : http2.createServer(options.http, httpHandler)
172448 |     server.on('session', (session) => session.setTimeout(options.http2SessionTimeout, function closeSession () {
172449 |       this.close()
^
TypeError: this.close is not a function. (In 'this.close()', 'this.close' is undefined)
```
> fix: correct session.close() context in http2 timeout handler

- .github/workflows/ci.yml
Added an extra conditional to the automerge job to check Dependabot PRs are coming from the same repo and not a fork.
Never seen this happen but Dependabot/GitHub developers aren't infallible and bugs can occur, so is an extra security layer.
> ci(ci): check dependabot prs originate from repo
