fastify/fastify

example.js
fastify.js
test/chainable.js

As titled.
```javascript
fastify
.get('/', schema, function (req, reply) {
reply(null, { hello: 'world' })
})
.post('/', schema, function (req, reply) {
reply(null, { hello: 'world' })
})
```

Chainable api support

---

fastify.js
lib/validation.js

In this first commit I've moved the `schema validation` in its own file.
I think we could split also `route` handling, `createNode` and `hanldeNode` in their own file.
Its ok for you? Any suggestion?

Split logic

---

README.md
fastify.js
package.json
test/logger.test.js

As titled, related to #8.
By default the logger is not enabled, if the user passes `{ logger: true }` or `{ logger: options }` it will be enabled for all the request.
If everything is ok for you, I can update the docs.
I've also updated the dependencies.

Logger support

---

.gitignore
.travis.yml
README.md
examples/example.js
examples/plugin.js
lib/tier-node.js
package.json
test/404s.test.js
test/async-await.js
test/async-await.test.js
test/delete.test.js
test/get.test.js
test/head.test.js
test/helper.js
test/input-validation.js
test/internals/reply.test.js
test/internals/tier-node.test.js
test/logger.test.js
test/promises.test.js
test/register.test.js
test/route.test.js
test/stream.test.js
test/throw.test.js

At the moment in master we can serve around 17k req / sec, with this change we can serve around 19.5k req / sec.
Is a ~15% improvement, that's good!
But this perf improvement implies an awful API, `reply.reply`.
Example:
```js
fastify
   .get('/', schema, function (req, reply) {
     reply.header('Content-Type', 'application-json').code(200)
     reply.reply(null, {hello: 'world'})
   })
```
@mcollina @davidmarkclements do you know any ninja trick to get this perf but have a nice looking API?
ps for the moment I disabled all the test, since all of them will fail.
__________
**TODO**:
Stream:
Reply:

Reply refactor

---

README.md
lib/validation.js
test/internals/validation.test.js

For your consideration
+ Adds support for omitting some of the meta data around the `querystring` schema definition, as it will always be an object
+ Adds tests for verifying the meta-data is correctly set as a `type` of `object` for both full schema and abbreviated
+ Adds docs to the README showing usage

feat(schema): add abbreviated querystring schema support

---

README.md

This PR updates the link to the Pino options documentation. It also changes it from a "here" link to a descriptive link.
Looking at the GH diff, it also seems some line endings got corrected.

Fix link to Pino options

---

README.md
lib/tier-node.js
package.json
test/custom-parser.test.js
test/internals/tier-node.test.js

*tl;dr*
3k req/sec more when body parsing 🎉 
___
I was doing some experiment with [fast-json-body](https://github.com/delvedor/fast-json-body) and I got way better performances than [body](https://www.npmjs.com/package/body), around ~100% more throughput.
So I tried to replace our actual json body parser, `body`, with `fast-json-body` but I got just 1k more request. As it is easy to imagine, the problem is the closure we are creating during the body parsing. So I used the same code of `fast-json-body` for parse the body, but I've update it in a way that we don't need a callback, the result was 3k req/sec more!

Fast json body

---

.editorconfig
docs/Routes.md
fastify.js
test/route.test.js

The `url` option in the `route` options is really specifying the `path`. This PR adds `path` as an alias for the current `url` name.

Add `path` alias for `url` in route options

---

docs/Server-Methods.md
fastify.js
test/listen.test.js

The current listen method does not allow the user to specify the address they would like the server to listen on. This PR fixes that problem.

Allow specifying address for listening

---

lib/reply.js
test/reply-error.test.js

The 0.19.0 version adds the boom library support. It's amazing!
I've noticed the output is very strange:
```
{
"data": {
"hello": "world"
},
"isBoom": true,
"isServer": true,
"output": {
"statusCode": 500,
"payload": {
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
},
"headers": {}
}
}
```
Maybe the http body could contain only the `output.payload` property.
I've also added the headers

Better boom library support

---

test/async-await.js
test/async-await.test.js

Since node v8 is out we can remove the *async/await* test for node v7.

Updated async await test for node v8

---

benchmarks/express-route-prefix.js
docs/Plugins.md
docs/Routes.md
examples/route-prefix.js
fastify.js
package.json
test/route-prefix.test.js

With this PR we introduce a system that allows the user to prefix all the routes inside a `register`, this could be useful when you need to maintain two different versions of the same api for example.
Talking about examples:
```js
const fastify = require('fastify')()
fastify.register(require('./routes-v1'), { prefix: '/v1' })
fastify.register(require('./routes-v2'), { prefix: '/v2' })
fastify.listen(3000)
``` 
```js
// routes-v1.js
module.exports = function (fastify, opts, next) {
fastify.get('/user', handler)
}
```
```js
// routes-v2.js
module.exports = function (fastify, opts, next) {
fastify.get('/user', handler)
}
```
The clients will have access to the routes:
- `/v1/user`
- `/v2/user`
Feedbacks? :)
cc @lucamaraschi @davidmarkclements

Route prefixing

---

benchmarks/koa.js

Generators have been deprecated for a while in `koa`. This PR switches the middleware to use `async/await` which improves koa's benchmark score about `~20%` on my machine.

Upgrade deprecated koa middleware signature

---

docs/Getting-Started.md
docs/Logging.md
docs/Reply.md
docs/Request.md
docs/Routes.md
docs/Testing.md
examples/example.js
examples/hooks.js
examples/https.js
examples/middleware.js
examples/plugin.js
examples/route-prefix.js
fastify.js
lib/handleRequest.js
lib/reply.js
test/404s.test.js
test/async-await.js
test/chainable.test.js
test/delete.test.js
test/get.test.js
test/head.test.js
test/helper.js
test/input-validation.js
test/internals/reply.test.js
test/output-validation.test.js
test/promises.test.js

In the [full route declaration](https://github.com/fastify/fastify/blob/master/docs/Routes.md#full-declaration) the user can pass any option, while in the [shorthand declaration](https://github.com/fastify/fastify/blob/master/docs/Routes.md#shorthand-declaration) can pass just the schema. With this pr we conform the behaviour of these apis.

Accept full options object in shorthand routes

---

README.md
docs/Hooks.md
docs/Lifecycle.md
docs/Plugins.md
docs/Routes.md
fastify.js
lib/handleRequest.js
test/beforeHandler.test.js
test/internals/handleRequest.test.js

Sometimes the *preHandler* hook is not easy to use when you need to call a specific function before the final handler, the user must work with `register` to create the correct encapsulation and the code could be hard to read.
Usage:
```js
fastify.get('/', {
beforeHandler: (req, reply, done) => {
// ...
done()
}
}, (req, reply) => {
reply.send({ hello: 'world' ])
})
``` 
As you can see from the code I'm using a closure to handle this, because I can't push at runtime the *beforeHandler* inside the *preHanlder* array otherwise I will change the *preHanlder* array forever causing tons of issues. `concat` won't work if *preHandler* is empty.
Have you got some better solution?
*Performances*:
There is almost no difference between use or not the *beforeHandler*, this change does not introduce a …

Before handler

---

benchmarks/bare.js
examples/asyncawait.js
examples/simple.js
fastify.js
lib/serializers.js

The more request data we log, the slower we go. So, I removed the headers by default, as those might pose a) a security risk and b) slow to encode and send.
This adds some percentage points to the benchmarks.

Log less request data

---

docs/Reply.md
lib/reply.js
test/internals/reply.test.js

This commit adds a `type` method to the `Reply` object. The `type`
method is a shortcut for `reply.header('Content-Type', 'the/type')`.

Add response type shortcut method

---

docs/Hooks.md
docs/Reply.md
docs/Routes.md
docs/Server-Methods.md
fastify.js
lib/handleRequest.js
test/beforeHandler.test.js
test/routes.test.js
test/throw.test.js

**The problem(s)**
- we can't push the `beforeHandler` function into the `preHandler` hooks, otherwise that change will be reflected for all routes
- we also can't push the `beforeHandler` inside `preHandler` at runtime because it's expensive.
- we can't accept an array of beforeHandlers
**Actual solution**
- we accept only one beforeHandler that creates a closure if executed https://github.com/fastify/fastify/pull/115
**Proposal**
- Wrap the route creation inside an [`after`](https://github.com/mcollina/avvio#after), in this way we can be sure that all the hooks will be registered before store them inside the `Store` object.
- During the route creation we duplicate the preHandler array and remove every reference, in this way we can push inside it without compromising the hooks for the …

Preload beforeHandler

---

lib/reply.js
test/internals/handleRequest.test.js
test/reply-error.test.js

If we return an error generated from `Reply` the `content-type` is not `application/json`, this pr fixes that.

Force 'content-type' in reply error

---

fastify.js
test/store-config.test.js
test/store-custom.test.js

In some circumstances, plugins should read some properties from route definition.
This PR allows that.

Allow custom object storing to Store instance for future use

---

README.md

I've written this in my repo but I'd like to have the fastify community contribution.
So, I'm glad if I can move "https://github.com/allevo/fastify-accepts-serializer" under fastify organization.
If no, please merge the PR.
I'll publish the package after the PR or the project movement.

Add fastify-accepts-serializer to README.md

---

lib/ContentTypeParser.js
test/custom-parser.test.js

If the request headers don't contain the `Content-Type` field and a custom ContentTypeParser is registered, this bug occurs.
`contentType.indexOf` throws and error because `contentType` is undefined.
Maybe the correct way is checking the variable `typeof`.
Let me know

undefined content type bug

---

test/listen.test.js

This PR adds a test to show the problem opened by https://github.com/fastify/fastify/issues/165 but not exampled.
travis should fail

Listen timeout when used with Promise.resolve()

---

docs/Getting-Started.md

Since that part of the doc shows how to use `register` and the `schema` option has already been explained few lines above, there is no need to add it here because it is not the focus of the section.

Fixes #188

---

fastify.js
lib/logger.js

It seems using symbols is preventing some type-based optimizations
to happen. Switching back to properties increases the throughput
by 10%.

Do not use symbols to track the context and startTime

---

docs/Decorators.md
docs/Plugins-Guide.md

The documentation is using arrow functions to in the examples for `decorateReply` and `decorateRequest`. The documentation also states that `this` is bound to the respective Fastify objects (request/reply) within the decorator functions. That is not true when using arrow functions. Therefore, this PR corrects the examples where it is relevant that `this` is bound correctly.

Fix scope in documentation examples

---

docs/Decorators.md

The previous fix for the scope in the decorators examples mistankenly
had the cautionary note within the examples themselves. This commit
moves them below the examples as they should have been from the start.

Move arrow function notes

---

README.md

This PR adds the `fastify-cookie` plugin to the Ecosystem section in the Readme. It also alphabetizes the Ecosystem section. I thought about creating a new "ecosystem.md" document and sectioning it like https://hapijs.com/plugins, but I wasn't sure about the classification of most plugins. I think this simple list is going to get unwieldy rather quickly, though.

Add fastify-cookie to ecosystem

---

README.md

Atom was very helpful in my last PR and added an extra `-` while re-organizing the ecosystem list. This PR fixes Atom's helpfulness that I overlooked.

Fix extra dash in ecosystem list (thanks Atom)

---

README.md

@cagataycali @dougwilson  thanks for helping out. Between turbofan and the changes you made the results looks very different now.

Updated benchmarks to Fastify 0.27.0 and Node 8.4.0.

---

fastify.js
test/listen.test.js
test/route.test.js

Handle all possible cases of double listen

---

docs/Routes.md
docs/Validation-And-Serialize.md
fastify.js
lib/handleRequest.js
lib/validation.js
package.json
test/input-validation.js
test/internals/handleRequest.test.js
test/internals/validation.test.js
test/options.test.js

`ajv` constructor has some parameter.
This PR allows to set those parameter per route.
A instance object is used for caching the `ajv` object. It's made in evil way.
The caching can be important to avoid a lot of `ajv` objects.
Maybe the `defaultAjvOptions` can be merged with the specified options.

Allow specify ajv options per route

---

fastify.d.ts

In TypeScript, when the compiler option of `noImplicitAny` is enabled, the following error occurs.
So I added a return type.
```
251     addHook(name: 'preHandler', hook: FastifyMiddleware)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/fastify/fastify.d.ts(251,5): error TS7010: 'addHook', which lacks return-type annotation, implicitly has an 'any' return type.
```

Add missing return type

---

package.json
test/plugin.test.js

Bumped avvio to 2.2.0 and added a regression test for https://github.com/fastify/fastify-mongodb/issues/8

Define hooks before routes synchronously even in a async context

---

lib/handleRequest.js
test/async-await.js

A route like this goes to timeout:
```js
fastify.get('/', async (req, reply) => {
await someKindOfAwesomeThing()
reply.code(204)
})
```

Fix 204 async. Add test

---

docs/Testing.md
fastify.js

Shot 4 is all in on async/await, which means we cannot use it if we want to keep supporting Node 4 and 6.

Note that we only support shot@3.

---

fastify.js
test/async-await.js
test/internals/logger.test.js
test/logger.test.js

This increase the throughput by 5-10% even if logging is disabled.
This happens because `logger.child({ req })` is our current bottleneck, because `req` is a big object and we `logger.child()`  serializes it to JSON as soon as it see it.
This change would add all the request details only on the `'incoming request'` log line.

Avoid serializing all the request for every log line

---

README.md

I missed this plugin on the initial scan as `apollo` didn't immediately correlate to GraphQL in my brain.  I'm so used to seeing GraphQL even though I use apollo-client

Make GraphQL support obvious

---

docs/Validation-And-Serialize.md

The document info about configuring `Joi` is incorrect. This pr fix that.

fix joi docs issue

---

docs/Middlewares.md

This was discussed in https://github.com/fastify/fastify/issues/319. I think it is a valuable clarification for the documentation and likely would have saved me some time getting set up!
Thanks!

chore: add documentation clarification for req and res in fastify middlewares.

---

fastify.d.ts
test/types/index.ts

Hi!
At the moment the TypeScript definition would fail on the `register` method because the type of the `options` parameter is defined as `RouteOptions` which is incorrect as in the `RouteOptions` type, you have to provide `url` and `method` and as the [documentation states](https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md#register) you can pass pretty much what you want in the option object, as well as a [`prefix` parameter](https://github.com/fastify/fastify/blob/master/docs/Routes.md#route-prefixing) which is not even allowed in `RouteOptions`.
This PR fixes it and adds a type parameter to the `Plugin` type so that the options you pass to the `register` function are set to the plugin function as well.
Also, the test file wasn't testing the `register` function at …

Fixed register TypeScript definition

---

README.md

This is the cause for the broken build of the website (ref https://github.com/fastify/website/issues/31).
The issue on the website has [a dedicated fix](https://github.com/fastify/website/pull/32) that makes the ecosystem parser slightly more flexible.
At the same time, I think the README here is broken and this PR addresses it.

Updated readme, Fixes broken plugin listing

---

docs/Logging.md
examples/example.js
fastify.js
package.json
test/logger.test.js

This removed the logger by default using https://www.npmjs.com/package/abstract-logging, but it turns it on if `{ logger: true }` or `{ logger: { } }` is passed.

No logger by default

---

docs/Logging.md
fastify.js
lib/logger.js
test/internals/logger.test.js

If a "request-id" header is present in the request it is used for req.id instead of a newly generated one.
This allows for request flow tracking across multiple services.
See #343

Use "request-id" header if present for req.id

---

docs/Hooks.md

Change the misleading parameter name of `preHandler` hook from `req` to `request` in doc file.

fix preHandler interface param: replace `req` with `request`

---

package.json
test/404s.test.js
test/ajv-options.test.js
test/async-await.js
test/custom-parser.test.js
test/decorator.test.js
test/delete.test.js
test/get.test.js
test/head.test.js
test/helper.js
test/hooks.test.js
test/https/https.test.js
test/input-validation.js
test/internals/reply.test.js
test/middleware.test.js
test/output-validation.test.js
test/plugin.test.js
test/promises.test.js
test/register.test.js
test/route.test.js
test/store-config.test.js
test/stream.test.js

Use [`simple-get`](https://www.npmjs.com/package/simple-get) instead.
Use `http` plain to test redirects in `test/internals/reply.test.js`
https://github.com/fastify/fastify/issues/268

Remove request devDeps

---

docs/Middlewares.md

This PR tries to clarify the compatibility of Express and Restify middlewares by extending the part about non compatible middlewares.

clarify express/restify middleware compatibility

---

docs/Reply.md

Noticed this typo in another patch but didn't want to conflate two issues so opening a separate PR. Apologies for the overhead.

Typo fix "strems" to "streams"

---

docs/Reply.md
lib/reply.js
test/async-await.js
test/reply-error.test.js

Fix for #401 
This can make it easier to handle errors using `async`/`await` and generate meaningful HTTP status codes/messages.

reject promise with statusCode and message

---

docs/Reply.md
lib/reply.js
test/reply-error.test.js

Compatibility fix for middleware using `err.status` instead of `err.statusCode`.
Example of middleware error using only `status`: https://github.com/MichielDeMey/express-jwt-permissions/blob/master/error.js#L10
Example of aliased `status` and `statusCode`: https://github.com/jshttp/http-errors/blob/master/index.js#L57
I'm not sure if there is a standard/convention for this property. Based on my limited experience it appears both are used in the wild.

err.status alias to err.statusCode

---

fastify.js
lib/handleRequest.js
lib/reply.js
lib/validation.js
test/context-config.test.js
test/internals/reply.test.js

The name `store` arrives from `find-my-way`, but here we are using it as Context object.
I think use this name is cleaner and clearer for the reader.
This could cause some regression if a plugin uses the `reply.store` property.

Renamed store in context

---

CONTRIBUTING.md

This PR updates the CONTRIBUTING.md document to set for some guidelines for managing pull requests. @fastify/fastify please review it and give your feedback. Should it be merged? Are there things that should be changed? Is this unnecessary?

Add pull-request guidelines to CONTRIBUTING.md

---

fastify.d.ts

This is supported in the library (https://github.com/fastify/fastify/pull/259) but typings were never updated

TS Typings: add socketPath as an option to the listen method

---

docs/Ecosystem.md

This is a PR for new version of the plusgin, that use the onSend Hook, and replace PR #232

 Add fastify-response-time reference in Ecosystem

---

fastify.d.ts

From the documentation, extendServerError should receive an error object:
fastify.extendServerError((err) => {
return {
timestamp: new Date()
}
})

Missing parameter in TypeScript definition

---

docs/Reply.md
fastify.d.ts
lib/reply.js
test/internals/reply.test.js

I just had the situation where I needed to access the default json serializer. This PR exposes the `serialize` function at the reply.

Expose the default json serializer

---

docs/Ecosystem.md

As the title says.
I have opted to put it in the community section because @SerayaEryn has already contributed a session plugin and I don't want step on their toes as a member.

Add fastify-server-session to community

---

docs/Getting-Started.md
docs/Plugins-Guide.md
docs/Routes.md

Fastify has different concepts that are not present in the other frameworks and our getting started section is failing to show them and give a gentle introduction to the framework.
This pr aims to fix that, please review it :)

Improve getting started

---

docs/TypeScript.md

This should serve as a start for TypeScript documentation. We could link to it in a PR/Issue template?

initial ts documentation

---

lib/handleRequest.js
lib/reply.js
test/internals/reply.test.js
test/reply-error.test.js

I noticed that Fastify does type checking ([`err instanceof Error`](https://github.com/fastify/fastify/blob/431713bd877701d0f584df5ec11f3bc1b7f43656/lib/reply.js#L62)) when a promise is rejected (async function throws). This is problematic when the thing thrown does not actually inherit from Error.
It's not entirely clear to me how to address this.
- Expose a `Reply.prototype.error()` method
- Add a parameter or option to `Reply.prototype.send()` to mark the payload as error
- Replace the non-Error `err` with a `new Error()` instance (losing the original object)
- Set a private (Symbol) property to mark the payload as an error.
Suggestions?

Test route handler rejection with non-Error

---

lib/handleRequest.js
test/internals/handleRequest.test.js

This PR ensures that a `request` object is passed to the `onSend` hook on 422 Unprocessable Entity and 415 Unsupported Media Type errors.
Fixes [#445](https://github.com/fastify/fastify/issues/445).

Pass request to the onsend hook on 422 and 415 errors

---

docs/Testing.md
lib/reply.js
test/hooks.test.js
test/inject.test.js

this pr show the problem in #465
> the typeof res.headers['content-length'] is not string, it is actually a number.
I have debug in `light-my-request` for a long time, at lastest I found it in `fastify/lib/reply.js`.

coverage content-length to string

---

README.md

We are currently loosing performance because of #291

Updated benchmarks as of 2017-11-16.

---

lib/reply.js
test/internals/reply.test.js

Currently, the `reply.redirect` method skips any registered hooks, e.g. `onSend`. This PR rectifies that situation.
~Unfortunately, there isn't any way to verify that the header in the added test gets set within the redirect. This is because there isn't any way to watch/inspect the redirects within `simple-get`.~ Doing too many things today. I wasn't thinking; this problem is solved.
```
Checking out "master"
Execute "npm run benchmark"
> fastify@0.35.2 benchmark /Users/jsumners/Projects/oss/fastify
> npx concurrently -k -s first "node ./examples/simple.js" "npx autocannon -c 100 -d 5 -p 10 localhost:3000/"
[0] server listening on 3000
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1]
[1] Stat         Avg    Stdev  Max
[1] Latency (ms) 74.81 …
```

Make reply.redirect honor registered hooks

---

docs/Testing.md

A fastify instance can only be booted once.

Do not encourage the server to be a singleton

---

lib/reply.js
package.json
test/stream.test.js

The updated version of pump no longer returns the last stream added to
the pipe.  Update fastify so values returned from functions are unchanged.
Completes #503.  Sorry if I did this wrong, should I do a pull request adding a commit to greenkeeper/pump-2.0.0 instead?

Update pump to latest version.

---

docs/Hooks.md
fastify.d.ts

From [docs](https://github.com/fastify/fastify/blob/master/docs/Hooks.md):
_If you are using the onSend hook you can update the payload, but not overwrite it, for example:_
_// this is valid_
```
fastify.addHook('onSend', (request, reply, payload, next) => {
payload.hello = 'world'
next()
})
```
_// this is not valid_
```
fastify.addHook('onSend', (request, reply, payload, next) => {
payload = { hello: 'world' }
next()
})
```
But how if payload is a primitive string? Sincerly I don't know any method to manipulate a string without to create a new one.
Reading the code [here](https://github.com/delvedor/fast-iterator/blob/master/index.js):
```
this._done = function (err, value) {
if (err) {
that.done.call(that.context, err, that.value)
holder.release(that)
return
}
if (value !== undefined) …
```

Update fastify.d.ts to include onSend hook

---

README.md
lib/handleRequest.js
lib/reply.js
test/async-await.js
test/logger.test.js

This removes setImmediate usage. Even thought this gives us 10% more throughput in a "happy path", under extreme load it **halves** it. This happens because the gc time goes at about 26% of our execution time, ultimately making this framework pointless.
I would like to thank @hueuniverse for finding this bad bug.
I have updated the results as well, after fixing https://github.com/fastify/benchmarks/issues/39.

Do not use setImmediate

---

docs/ContentTypeParser.md
lib/ContentTypeParser.js
test/custom-parser-async.js
test/custom-parser.test.js

Ref #525 
Need to update the ContentParser `done()` method. Originally it only took one argument `body`. Split into `error, data`, then promisify the method.

Update ContentParser API

---

lib/handleRequest.js
test/async-await.js

Fixes #548 
I did not implement my second suggestion from #548 because [this test](https://github.com/fastify/fastify/blob/67e111e8bc4e5f47d4aa93468a71bccdb8664037/test/async-await.js#L207-L230) made me realize that async functions can be mixed with callbacks, so it might be a bad idea for fastify call `reply.send()` when a handler resolves but the response hasn't been sent yet.

Don't let async handler send 204 response twice

---

docs/Reply.md
docs/Validation-and-Serialization.md

`fast-safe-stringify` isn't used anywhere so update the docs to indicate that `JSON.stringify()` is used instead.

Update docs that mention fast-safe-stringify

---

fastify.js
lib/ContentTypeParser.js
test/hooks.test.js

This ensures that the onSend hook will always receive a valid Request object.
Fixes #550

Always use a Request object when creating a Reply object

---

lib/handleRequest.js
lib/validation.js
test/internals/handleRequest.test.js

Does the same as before, but adds one more property **validation** that has the Ajv error as is. Without stringifying it.

Preserve validation errors from Ajv as an array

---

docs/Ecosystem.md

It seems this plugin was missing from the list.

Add fastify-static to Core plugins in Ecosystem.md

---

fastify.js

Since `middie` needs `req.originalUrl` to be compatible with Express middleware, setting `req.originalUrl` at the beginning of each request will make `req` have the same shape throughout all Fastify code.
See fastify/middie#16 for the original discussion on why this should be added.

Set req.originalUrl on each request

---

docs/Getting-Started.md

"Inside an async function, return await is useless. Since the return value of an async function is always wrapped in Promise.resolve, return await doesn’t actually do anything except add extra time before the overarching Promise resolves or rejects. This pattern is almost certainly due to programmer ignorance of the return semantics of async functions."
https://eslint.org/docs/rules/no-return-await

return await is useless

---

fastify.js
test/hooks.test.js

Fixes cases where only the generic `Request` and `Reply` objects would be created and passed to later hooks if the `onRequest` hook or some middleware failed.

Create Request and Reply objects with the right context

---

fastify.js
test/route.test.js

Currently, when (for some reason) you enter an invalid schema, the whole app will shutdown since the thrown error from Ajv is not handled anywhere. 
This should log the error and in case a request is made to that endpoint, it will continue logging an error.

Handle invalid schemas

---

fastify.js
lib/decorate.js
lib/handleRequest.js
lib/reply.js
package.json
test/500s.test.js
test/async-await.js
test/internals/handleRequest.test.js
test/internals/reply.test.js
test/reply-error.test.js

Hi folks!
During the past months we did a huge amount of work on the error handling, but we have never refactored the code, so it has become a mess.
What has been done in this pr:
- Public API
- Dropped `extendServerError` api.
It was an element of confusion and often was in conflict with the custom error handler.
- Dropped the support for Boom #542 
- Added async await support for the `setErrorHandler` api
- The error object can set the headers as well
- Internals
- `handleError` will serialize and send the error instead of `onSendEnd` (if needed)
- Heavy refactor
If we all agree with this changes I can proceed to update the docs.
Needless to say that this is a breaking change (hopefully one of the last).

Updated error handling

---

fastify.js
lib/ContentTypeParser.js
lib/handleRequest.js
lib/request.js
test/internals/handleRequest.test.js

By removing the `body` parameter from the `Request` constructor's parameters and setting `body` to `null` by default, the `Request` and `Reply` objects can be created at the beginning of `handleRequest`, which allows the rest of the code to be dramatically simplified.
The request body is now simply set by doing `request.body = parsedBody` after the body content is parsed.

Refactor handleRequest

---

docs/Ecosystem.md

Plugin to load lua scripts with [fastify-redis](https://github.com/fastify/fastify-redis) and [lured](https://github.com/enobufs/lured)

Adds fastify-lured to Ecosystem's community list

---

lib/reply.js
test/stream.test.js

Previously, `onSend` hooks were being skipped if a stream was passed to `reply.send()`.
This could be considered a breaking change since `reply.send()` no longer returns the `res` object when passed a stream.

Run onSend hooks when sending a stream

---

docs/Reply.md
fastify.js
lib/reply.js
test/internals/reply.test.js

Sometimes handlers for a route need to act like the route wasn't matched, so they need a way to forward the request to the 404 handler. This is mainly necessary for the `fastify-static` plugin and was suggested by @mcollina in [this comment](https://github.com/fastify/fastify-static/pull/27#discussion_r158830732).

Add reply.notFound() method

---

fastify.js
test/404s.test.js

Use `fast-iterator` to bind hooks to the fastify instance.
404 handlers are also now bound to the fastify instance.
Based on [my comment](https://github.com/fastify/fastify/pull/592#issuecomment-354476787) in #592.

Clean up binding hook and 404 handler context

---

test/404s.test.js

The problem was introduced in 25a65a7 by using the wrong fastify instance inside a `register()` call.
I'm not sure how the tests passed when I made that commit or even on CI. They only started failing locally for me when I updated my branch to include the latest changes on master. Anyway, this corrects the problem.

Fix incorrect test

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Most of the code was copied from the Hapi issue template. I think that should not be a problem. I added the `You have already researched for similiar issues?` section and added removed some sections.

add github issue template

---

docs/Error-Handling.md
fastify.js
lib/ContentTypeParser.js
lib/errorUtils.js
lib/handleRequest.js
lib/reply.js
test/reply-error.test.js

This PR includes inter alia issue https://github.com/fastify/fastify/issues/599 where the user was restricted with setting a status code when an error was passed. The current implementation was really hard to read.
I removed the support for none error values as errors ~~(truthy values can be still passed)~~ because it's widely known as an anti-pattern and the developer should use the `Error` object.
We shouldn't provide a space for anti-pattern. Due to this change, I could simplify the code.
When https://github.com/fastify/fastify/pull/591 is merged I will add this behavior to the docs.
If you are passing an error and with a status code smaller than 400, Fastify will automatically set it at 500.
References:
https://www.joyent.com/node-js/production/design/errors …

Simplify error handling

---

lib/ContentTypeParser.js
lib/hooks.js

Creating a new constructor and inheriting from the old one isn't necessary for `Hooks` and `ContentTypeParser`. Simply creating a new instance and cloning the values is all that's needed.
This also improves debugging, general code compatibility, and possibly performance since the hooks and `parsersList` will now be real arrays instead of array-like objects.

Simplify building Hooks and ContentTypeParser

---

docs/Reply.md
lib/reply.js
test/internals/reply.test.js

According to [RFC 7230 Section 3.3.2](https://tools.ietf.org/html/rfc7230#section-3.3.2), there are cases when a server must not send a `Content-Length` header (such as with a 204 response). This change makes Fastify follow the spec more closely by passing the payload through the `onSend` hooks as-is and not setting the `Content-Length` header on a response with an `undefined` payload.
Other benefits from this are a 20% perf boost for undefined payloads and better alignment with developer expectations (if I call `reply.send()` I expect `payload` to be `undefined` in the `onSend` hooks and no `Content-Type` header in the response).
<details>
<summary>undefined payload benchmark</summary>
**master**
```
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 2.11    7.88    325
[1] Req/Sec …
```

Improve handling undefined payloads

---

.gitignore
lib/reply.js
test/reply-error.test.js

This PR fixes https://github.com/fastify/fastify/issues/595 when the user responds with a value where no compatible serializer exists. The result is a hanging request with no errors. It's better to fail first instead to convert the payload somehow.

check for writeable payload value

---

docs/Server-Methods.md
fastify.js
test/404s.test.js

Running `preHandler` hooks for 404 handlers was missing (I'm assuming that was unintentional?). This PR adds that functionality and also adds tests to make sure all hooks and middlewares are run for 404 handlers.

Run preHandler hooks for 404 handlers

---

fastify.js
test/route-prefix.test.js

It used to be a class with a single `prefix` property that didn't have any extra functionality.
The prefix property as a string is all that's needed.
<details>
<summary>benchmark</summary>
**master**
```
[1] Stat         Avg     Stdev  Max
[1] Latency (ms) 3.11    11.01  360
[1] Req/Sec      31406.4 6013.7 35647
[1] Bytes/Sec    4.73 MB 897 kB 5.51 MB
[1]
[1] 157k requests in 5s, 23.4 MB read
...
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 3.01    10.83   371
[1] Req/Sec      32379.2 6412.03 37567
[1] Bytes/Sec    4.84 MB 964 kB  5.77 MB
[1]
[1] 162k requests in 5s, 24.1 MB read
```
**this PR**
```
[1] Stat         Avg    Stdev  Max
[1] Latency (ms) 3.16   11.16  371
[1] Req/Sec      30880  6228   35999
[1] Bytes/Sec    4.6 MB 912 kB 5.51 MB
[1]
[1] 154k requests in 5s, 23 MB …
```

Refactor RoutePrefix to be a string

---

fastify.d.ts
package.json
test/types/index.ts

Otherwise `this` would be of type `any` within hook callbacks.

Typescript: define the value of `this` within hooks

---

docs/Reply.md
test/internals/reply.test.js

This aligns the documentation and tests with the current functionality of passing a string to `reply.send()`.
New documentation:
```
If you pass a string to `send` without a `Content-Type`, it will be sent as plain text.
If you set the `Content-Type` header and pass a string to `send`, it will be serialized
with the custom serializer if one is set, otherwise it will be sent unmodified (unless
the `Content-Type` header is set to `application/json`, in which case it will be
JSON-serialized like an object — see the section above).
```
If anyone thinks the functionality should be changed, this would be a good chance to discuss it.

reply.send(string) documentation and test updates

---

docs/Routes.md
fastify.js
lib/handleRequest.js
test/fastify-options.test.js
test/helper.js
test/internals/handleRequest.test.js
test/jsonBodyLimit.test.js
test/route.test.js

Adds a `jsonBodyLimit` option that can be configured with the initial `fastify` call and at routes.
```js
const fastify = require('fastify')({ jsonBodyLimit: 1000 })
fastify.route({
method: 'POST'
url: '/form',
jsonBodyLimit: 10000, 
handler() { ... }
})
```
Default limit is `1 MiB`.

Add option to limit the size of request bodies for the default body parser

---

lib/reply.js

Log with `error` severity and log the error object.
Supersedes #634

Improve how stream errors are logged

---

docs/Plugins-Guide.md

Within `decorateRequest` handlers `this` is bound to the Fastify request object. Thus, there is no need to access the raw `IncomingRequest` to retrieve a specific header.

Fix decorateRequest example

---

docs/Routes.md
fastify.js
test/logger.test.js

With this pr we introduce a shine new feature ideated by @allevo.
We will have the possibility to set a custom log level for a plugin or even a single route, respecting the encapsulation model :)
The internals has been changed because to support this feature without loosing performances we must create the child logger directly with the new log level and not setting it afterwards, otherwise V8 will deoptimize the code and we lose about 10% req/sec.
Following a brief example:
```js
fastify.register(require('./routes/user'), { logLevel: 'warn' })
fastify.register(require('./routes/events'), { logLevel: 'debug' })
fastify.get('/', { logLevel: 'info' }, (req, reply) => {
reply.send({ hello: 'world' })
})
```
Related: https://github.com/fastify/fastify/issues/636
*master*
```
Running 5s test @ …
```

Plugin log level

---

lib/reply.js
package.json
test/stream.test.js

Added support for streams1 in reply.send()

---

lib/handleRequest.js
lib/reply.js
test/internals/handleRequest.test.js
test/internals/reply.test.js

Since all of the code for re-throwing system errors was reverted, issue #595 became a problem again. This fixes it.
This also fixes a bug where doing `reply.send(errorObject)` would throw if a `Content-Type` header was previously set because [the payload](https://github.com/fastify/fastify/blob/6c23c92e8261ed3eef4248861692a5c50194a93f/lib/reply.js#L217-L221) wouldn't get serialized in [`onSendEnd`](https://github.com/fastify/fastify/blob/6c23c92e8261ed3eef4248861692a5c50194a93f/lib/reply.js#L124-L167).

Fix 595 and a bug when sending an Error object

---

lib/handleRequest.js
test/helper.js

Several issues have been opened in the past because by default, Fastify responds with an error to POST requests without a body. People expect requests without a body to work without having to set a "catch all" content type parser. It's counter-intuitive to have to set a body parser to be able to handle requests without a body.
This change avoids running any content type parser if the request has no `Content-Type` header and no body. From [RFC 7230 Section 3.3](https://tools.ietf.org/html/rfc7230#section-3.3), we can determine if a request has a body by checking the `Transfer-Encoding` and `Content-Type` headers.
> The presence of a message body in a request is signaled by a Content-Length or Transfer-Encoding header field.
The rest of that section does use "SHOULD" a lot, but it looks …

Avoid body parsing for requests with no Content-Type and no body

---

docs/Plugins-Guide.md
docs/Request.md
docs/TypeScript.md
lib/ContentTypeParser.js
lib/handleRequest.js
lib/request.js
test/hooks-async.js
test/hooks.test.js
test/internals/all.test.js
test/internals/handleRequest.test.js
test/internals/logger.test.js
test/logger.test.js
test/middleware.test.js

Before release v1.0.0 I would like to propose the following changes to request object:
- rename `req` to `raw`
- add `rawBody` property
The first one becase doing `req.req` or `request.req` is awkward and counterintuitive.
The second because it could happen that a plugin or a user needs the raw body (maybe to perform some kind of forwarding).
cc @fastify/fastify

Updated request object

---

lib/handleRequest.js
test/helper.js
test/internals/handleRequest.test.js

According to [RFC 7231 Section 6.5.1](https://tools.ietf.org/html/rfc7231#section-6.5.1):
> 6.5.1.  400 Bad Request
>
>   The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
Therefore 400 (Bad Request) would be the right status code  to send because getting an error while parsing the body means that either the syntax was malformed or the payload was too big to be processed by `JSON.parse()` (although that will usually be caught by the `jsonBodyLimit` to respond with a 413 - Payload Too Large).
The [422 Unprocessable Entity](https://tools.ietf.org/html/rfc4918#section-11.2) status is mainly …

If parsing a JSON body fails, respond with 400 status instead of 422

---

docs/Plugins.md

This PR documents the potential for options collision when registering plugins. Upon investigating how to add direct support for namespaced options I determined that this would be easiest, least intrusive, solution.

Add documentation about options collision [skip-ci]

---

package.json
test/get.test.js

As [mentioned](https://github.com/fastify/fastify/pull/656#issuecomment-357352748) by @delvedor in #656.

Replace fast-safe-stringify with an inline function

---

docs/Request.md
fastify.d.ts
lib/request.js
test/types/index.ts

As titled. I like to have `request.id` as alias `request.raw.id`
Do you agree?
~~I don't know where to test it.
I'll update the docs asap.~~
I add the typescript definition too.

Add request.id

---

docs/Logging.md
fastify.js
test/logger.test.js

When we use a custom logger, it's not possible to provide serializers in configuration.
When we do not use a custom logger, we can only provide serializers which contains all of them, not only overwrite one (`res` for example).
This PR fixes those 2 cases.

Allow overwrite logger serializer, one by one

---

lib/reply.js
package.json
test/logger.test.js
test/reply-error.test.js

This PR adds the request to the logs in `handleError` as requested in issue #659.

Serialize req on error (fix #659)

---

docs/Getting-Started.md

Since 3417842968462474a0eeac1b3e2b1fde790ae33d, log for server listening at is already sent.
~~But, if do not set any address, it will display `Server listening at http://:::3000` which is not very comprehensive and we can't click on it! So I added `localhost` as address argument value in examples.~~
I also take some enhancements from Fastify website homepage: I think it's better to log an error than throw this error in case of listen error.
I will also be updated `fastify-website` home template whith those fixes if this PR is ok for you.

[doc] Fix listen already log server listening address in getting started

---

docs/Ecosystem.md

Adds the https://www.npmjs.com/package/fastify-no-icon module to the ecosystem list.

Add fastify-no-icon to ecosystem list

---

fastify.js
test/404s.test.js
test/500s.test.js
test/custom-parser.test.js
test/hooks.test.js
test/middleware.test.js
test/post.test.js
test/route.test.js

Truly this is a breaking change. But changing the `fastify` instance after the server is started is a bad practice.
Fix #594

Throw error for avoiding `fastify` changes after binding

---

docs/TypeScript.md
package.json

Me and @mcollina think that the types should stay inside the repo and shipped with the project.
We all discussed a lot in #649 about this, and this is our proposal.
Again, this is the best that thing we can offer, if someone does not agree with this, then he/she/them can start to contribute to the project and take care of this.
I've also moved the `@types` dependencies as dev dependencies, because it is not a good idea ship them directly as dependency. Then I added the `@types` dependencies inside the greenkeeper ignore, because every time there is a new release of the types for some unknown reason our CI will complain.
cc @fastify/fastify

TypeScript Documentation

---

docs/Getting-Started.md
docs/Server-Methods.md
fastify.js
test/listen.test.js

This is related to #665. This PR defaults the server to listen only on address `127.0.0.1`. With this PR, in order to listen on any other address the user must do:
```js
// Listen on all IPv4 interfaces
fastify.listen(8000, '0.0.0.0', (err) => {
if (err) throw err
})
```
This eliminates non-deterministic behavior from core (https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_server_listen_port_host_backlog_callback):
> If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
>
> Note: In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).
This is a breaking change because …

Default to listening on 127.0.0.1

---

fastify.js
test/route-prefix.test.js

Handles trailing slashes in the route `prefix` so that:
```js
fastify.register(function (fastify, opts, next) {
fastify.register(function (fastify, opts, next) {
fastify.get('/route', (req, reply) => {
reply.send({ hello: 'world' })
})
next()
}, { prefix: '/inner/' })
next()
}, { prefix: '/v1/' })
```
registers `/v1/inner/route` instead of `/v1//inner//route`.
See the discussion in #584.

Normalize route paths with a prefix that has a trailing slash

---

fastify.js
package.json
test/ignoreTrailingSlash.test.js

This PR adds support for ignoring trailing slashes as discussed in #584. This is an all or nothing setting. For example:
```js
const fastify = require('fastify')({
ignoreTrailingSlash: true
})
// maps to both "/test/" and "/test"
fastify.get('/test/', (req, reply) => {
reply.send('test')
})
```
Documentation is not included because we don't have any documentation that describes the factory function and the options it accepts. A PR should be opened to rectify that problem.

Add support for ignoring trailing slashes in routes

---

docs/Plugins-Guide.md

Only a few of these grammar issues made it hard to read, but I went ahead and fixed all that I could find in a quick scan.
This documentation is otherwise a fun and easy read!
BTW, here in the U.S. women have become pretty sensitive to the use of masculine terms when gender-neutral terms exist. I suspect saying "children" and "siblings" would better suit modern sensitivities than "sons" and "brothers." But that's not a grammar issue, so I didn't change that. Just a heads-up.

Grammar fixes for Plugins-Guide.md

---

fastify.js
test/404s.test.js

Looks like I missed this case when writing #676.

Handle prefix with trailing slash when setting not-found handler

---

README.md
docs/LTS.md

This PR adds a document to codify the LTS strategy outlined in #670. The included table should eventually look something like this:
| Version | Release Date | End Of LTS Date |
|:--------|:-------------|:----------------|
| 1.0.0 | 2018-02-01 | 2019-02-27 |
| 2.0.0 | 2018-08-31 | TBD |

Add LTS documentation (fix #670)

---

docs/Factory.md
docs/Server-Methods.md

This PR adds documentation for the options available when constructing new Fastify instances.
@fastify/fastify please review to make sure I didn't miss any options.

Add documentation for the options to the factory function

---

docs/Server-Methods.md
fastify.js
test/route-prefix.test.js

This PR adds a `basePath` property to instances. It resolves #686.

Add basePath property to instance (fix #686)

---

docs/Hooks.md
lib/reply.js
test/hooks-async.js
test/hooks.test.js
test/internals/handleRequest.test.js
test/internals/reply.test.js
test/reply-error.test.js

Serialization now happens before the `onSend` hooks, so the hooks receive the serialized payload.
This also adds a feature where an `onSend` hook can replace the payload with `null` to send a response with an empty body without having the `Content-Type` header get set to `0`. This was not possible before because `null` would either get serialized as JSON or be considered an unserialized value and cause an error to be thrown. (It would be preferable to do this by setting the payload to `undefined` in the hook, but `undefined` currently means that the payload was not changed.)
Fixes #672 
<details>
<summary>Benchmarks</summary>
**master**
```
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 3       10.65   354
[1] Req/Sec      32459.2 6549.24 37215
[1] Bytes/Sec    4.89 MB 984 kB  5.77 …
```

Serialize the payload before running onSend hooks

---

fastify.js
test/logger.test.js

This fixes the invalid URL that is logged when using IPv6 address.
Before:
```json
{ "msg": "Server listening at https://:::7777" }
```
After:
```json
{ "msg": "Server listening at https://[::]:7777" }
```

Fix formatting of IPv6 URL

---

fastify.js
test/middleware.test.js

This makes adding middleware to routes consistent with how hooks are added to routes.
Fixes #696

Add middleware to routes the same as hooks

---

fastify.js
test/fastify-instance.test.js

Supersedes #705 
As @mcollina said in #705, Fastify shouldn't export a function. This PR makes Fastify export a plain object as the root Fastify instance instead of a function.
Adding support for `supertest` can be done separately if it's not too much of a burden.
This makes no difference to benchmarks.

Make the root fastify instance a plain object

---

lib/reply.js
package.json
test/stream.test.js

I've improved the stream support to not close the destination stream directly if the payload errors, but rather pass it through our error pipeline.
Thanks to this, we can simplify https://github.com/fastify/fastify-static/blob/master/index.js#L34-L48, as the sendStream could be passed in directly

Support send

---

docs/Testing.md

Rewrite the documentation to explain the 2 methods of testing (http injection or with a running server) using minimal examples.
Suggested in [#715 (comment)](https://github.com/fastify/fastify/pull/715#pullrequestreview-92034255).

Simplify Testing docs

---

docs/Reply.md
lib/reply.js
test/404s.test.js
test/internals/reply.test.js

As titled. Does this needs a doc change? I think this fixes a bug in our current error handling logic.
(I need this for #724 to fully work)

Route 404 errors to the 404 handler

---

docs/Reply.md
docs/Validation-and-Serialization.md
test/context-config.test.js

Also add more information to the `reply.send` documentation.
Superscedes #718.

docs: Improve reply.serializer documentation

---

docs/Server-Methods.md
fastify.d.ts
lib/reply.js
test/500s.test.js
test/logger.test.js
test/reply-error.test.js
test/types/index.ts

Before
```js
fastify.setErrorHandler(function (error, reply) {})
```
After
```js
fastify.setErrorHandler(function (error, request, reply) {})
```
Fixes #744

Add `request` to custom error handler parameters

---

fastify.js
lib/handleRequest.js
lib/hookRunner.js
lib/reply.js
package.json
test/hooks.test.js
test/internals/handleRequest.test.js
test/internals/hookRunner.test.js
test/middleware.test.js

With this change we are able to register hooks and middlewares declared in a plugin *after* a route declaration in the same level.
The context update is postponed until `avvio` emits the `preReady` event (https://github.com/mcollina/avvio/pull/49).
I've also updated the hook runner since the context binding happens during the hook registration.
When using the hooks the benchmarks have improved by 1-2k req/sec.
Related: https://github.com/fastify/fastify/issues/748

Updated hook and middleware encapsulation

---

docs/Server-Methods.md
fastify.js
test/listen.test.js

Added backlog parameter to listen method

Added backlog parameter to listen method #767

---

fastify.js
test/404s.test.js

Use `app.once('preReady', ...)` just like route handlers so that plugin hooks and middleware get registered the same way.
Related: #748

Configure not-found handlers the same way as route handlers

---

fastify.js
lib/hooks.js
test/hooks.test.js
test/middleware.test.js

Make hooks/middleware always run in the order in which they are defined.
This also makes Fastify instance "levels" consistent by fixing this bug:
```js
const fastify = require('fastify')() // master branch
fastify.get('/', function handler (request, reply) {
reply.send(request.cookies)
})
fastify.register(function (instance, opts, next) {
instance.get('/encap', function (request, reply) {
reply.send(request.cookies)
})
next()
})
fastify.register(require('fastify-cookie'))
fastify.inject({
url: '/',
headers: { Cookie: 'foo=bar' }
}, (err, res) => {
console.log('/      -', res.payload) // {"foo":"bar"}
})
fastify.inject({
url: '/encap',
headers: { Cookie: 'foo=bar' }
}, (err, res) => {
console.log('/encap -', res.payload) // {}
})
```
With this change, the `preHandler` hook from …

Make hooks/middleware run in the order in which they are defined

---

docs/ContentTypeParser.md
docs/Factory.md
fastify.js
lib/ContentTypeParser.js
lib/handleRequest.js
package.json
test/custom-parser-async.js
test/custom-parser.test.js
test/helper.js
test/internals/handleRequest.test.js
test/jsonBodyLimit.test.js

Hi all!
With this pr we change how works our internal body parsers, some users asked us if we could provide a better content type parser API, not everybody wants to handle a stream and we are already doing that internally (with a very low overhead). This pr updates the `addContentTypeParser` API by adding an options object, if the user passes  `{ asString: true }` it will get the body as string, with `{ asBuffer: true }` it will get the body as buffer.
To avoid breaking the compatibility with the ecosystem if the option object is not provided the callback function will be the same as before `function (rawRequest, done)`, instead, if the options object is provided (with the above options) the function signature will be  `function (request, reply, body, done)`.
The only breaking change we …

WIP: Refactor content type parser

---

package.json
test/decorator.test.js

This is a work in progress. Thus far, only a failing test is added.
The issue is that plugins are actually loaded asynchronously via `avvio`. This internal handling creates a new call stack that does not get handled by the `try/catch` block as desired.
It may be that this has to be resolved in `avvio`. Any ideas @mcollina ?

Resolve issue #777 - unhandled exceptions when registering plugins

---

fastify.js
lib/handleRequest.js
lib/hookRunner.js
lib/reply.js
test/hooks.test.js
test/internals/hookRunner.test.js

The `onSend` hooks are a special case because they need extra logic for changing the payload. This extra logic is not needed for the other hooks and it makes the other hooks prone to a bug where the hook runner's internal state will be changed if a hook function returns a promise that resolves to a value other than `undefined`.
<details>
<summary>Example of the bug that this change prevents</summary>
```js
const fastify = require('./')()
fastify.addHook('preHandler', (request, reply) => {
return Promise.resolve() // OK
})
fastify.addHook('preHandler', (request, reply) => {
return Promise.resolve(true) // Causes crash
})
fastify.get('/', (request, reply) => {
reply.send('hello')
})
fastify.inject('/', (err, res) => {
console.log('Will not reach here')
})
```
```
(node:12944) …
```

Create a separate hook runner for onSend hooks

---

fastify.d.ts
test/types/index.ts

Add missing printRoutes ts definition on FastifyInstance

---

.gitattributes

The .editorconfig requires LF line endings and npm has some line endings bugs so this should make contributing easier for people on Windows.

Add .gitattributes to normalize line endings

---

docs/Ecosystem.md

----
To ensure it really works (other than usual tests and example) I just used it in a sample webapp: [fastify-example](https://github.com/smartiniOnGitHub/fastify-example)

Add fastify-favicon to community plugins list (#806)

---

fastify.d.ts
test/types/index.ts

Fix FastifyInstance::ready type definition

---

docs/ContentTypeParser.md
fastify.js
lib/ContentTypeParser.js
test/custom-parser.test.js

This PR allows custom parser plugins to specify a maximum body limit that supersedes the global limit. This allows for more granular control of payload sizes while retaining a catch-all limit.

Add support for per-parser body limits

---

fastify.d.ts
test/types/index.ts

Add FastifyInstance::after typescript definition

---

fastify.js

`loggerUtils.onResponseCallback` logs only if there's a logger
Bench:
*this branch:*
```
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1] 
[0] server listening on 3000
[1] Stat         Avg     Stdev  Max     
[1] Latency (ms) 8.3     27.44  511.66  
[1] Req/Sec      11710   2804.9 13896   
[1] Bytes/Sec    1.75 MB 411 kB 2.07 MB 
[1] 
[1] 59k requests in 5s, 8.72 MB read
[1] 112 errors (0 timeouts)
```
*master:*
```
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1] 
[0] server listening on 3000
[1] Stat         Avg     Stdev   Max     
[1] Latency (ms) 8.78    29.27   340.12  
[1] Req/Sec      11079.6 3750.94 14926   
[1] Bytes/Sec    1.64 MB 535 kB  2.22 MB 
[1] 
[1] 55k requests in 5s, 8.25 MB …
```

Avoid to log if the log is not set

---

docs/Server-Methods.md

Addresses the specific issue mentioned in #801.

Fix linking to factory function options from Server Methods

---

lib/validation.js
test/get.test.js

As titled, the rfc https://tools.ietf.org/html/rfc2616#section-4.2 defines the header key as case insensitive.
```
const schema = {
headers: {
UppErCaSe: { type: 'number' }
}
}
fastify.get('/', { schema }, myHandler)
```
The problem is when I curl with `uppercase: 3` header because nodejs force to use to lower case.
I'm working on to fix this.

Header name is case insensitive in the schema definition

---

fastify.js
test/hooks.test.js
test/reply-error.test.js

Fix code that checks the Node version that would break with Node 10 (handle version numbers with multiple digits).

Future-proof checking Node version

---

docs/Hooks.md
docs/Routes.md
fastify.d.ts
test/bodyLimit.test.js
test/helper.js
test/hooks.test.js
test/route.test.js
test/types/index.ts

#785 renamed the `jsonBodyLimit` option to `bodyLimit`. This changes the remaining instances of `jsonBodyLimit` to `bodyLimit`.

Update instances of "jsonBodyLimit" to "bodyLimit"

---

test/route.test.js

While making #828, I was surprised that [this test](https://github.com/fastify/fastify/pull/828/files#diff-b546326f3ba2fced1af5691d01a323b5R199) wasn't failing. Turns out an error was being thrown (which is what the test wanted), but it was the wrong error. A `bodyLimit` error should have been thrown but a "fastify already started" error was what was actually thrown.
This PR changes the tests in `test/routes.test.js` so that different tests use a different Fastify instance and fixes the `bodyLimit` option test.
It may be helpful to view the file changes [without whitespace](https://github.com/fastify/fastify/pull/831/files?w=1).

Use separate Fastify instances for route tests

---

docs/Reply.md
lib/reply.js
test/internals/reply.test.js

This is pushed with a failing test. I have done so because I think that test is wrong, but I want others opinion. The failing test is:
https://github.com/fastify/fastify/blob/6aaa14abbdd317280af68a032a618984d07c38a3/test/stream.test.js#L52-L74
It fails, because now the resulting header is:
```
+++ found
--- wanted
-"application/javascript"
+[
+  "application/octet-stream"
+  "application/javascript"
+]
```
The wrong bit about the test is that the response *should* be `application/octet-stream` since a stream has been sent. However, it could also be wrong that the content type has been set twice.
I feel like we are heading into a mine field with maintaining headers on the `Reply` object ourselves. See https://tools.ietf.org/html/rfc2616#section-4.2:
> Multiple message-header fields with …

Fix setting header multiple times and add utility methods (fix #834)

---

fastify.js
lib/reply.js

When I wrote #588 I stored the Fastify instance on the route Context as a hack because that was the only way to get a reference to the right 404 Context during a request (since when a route is defined, the associated 404 handler might not have been defined yet).
Now that the `'preReady'` event from `avvio` exists, it is possible to use that to get the right 404 Context to store on the route Context.

Store the 404 Context directly on the route Context

---

fastify.js
test/404s.test.js

Almost all of the new tests included in this change would have failed before this fix.
For example, using a 404 Error to invoke the default 404 handler from a route within a prefixed plugin wasn't working before:
```js
const fastify = require('fastify')()
fastify.register(function (instance, opts, next) {
instance.get('/path', function (request, reply) {
reply.send(Object.assign(new Error(), { status: 404 }))
})
next()
}, { prefix: '/v1' })
fastify.inject('/v1/path', (err, res) => {
// TypeError: Cannot read property 'handler' of null
})
```

Fix encapsulation of 404 handlers

---

fastify.d.ts
package.json
test/types/index.ts
test/types/tsconfig.json

This PR introduces a few updates to the TypeScript setup and typings.
Reviewing type changes can sometimes be confusing for me, so in attempt to make it easier to review I made each change in its own commit. If you have questions or would like any changes let me know.
I'll explain the changes in each commit in a more detail  below.
_**Note:** none of the changes should break any existing types, all the changes should be making existing types more correct and better defined._
The switch to a `tsconfig.json` was just made to get matching config settings when using an IDE.
Enabling strict mode is to fix and prevent problems when using this fastify from a within a project with strict mode enabled.
Once strict mode is enabled it wants types for all imports, so we add the types for `cors` as a …

Misc TypeScript fixes

---

docs/Reply.md

they old links were referring to a deleted branch

[docs] Fix broken links

---

docs/Getting-Started.md

I went through the documentation and noticed a typo.

Fix typo in getting started documentation

---

fastify.js
lib/reply.js
test/404s.test.js
test/internals/logger.test.js
test/internals/reply.test.js
test/logger.test.js

If a route is encapsulated, it may have more `onSend` hooks than the *notFound* handler associated with the route. This PR makes sure that if a route invokes the *notFound* handler, all of the route's `onSend` hooks will run.
Fixes #868

Run onSend hooks when an encapsulated handler invokes the notFound handler

---

fastify.js
test/reply-error.test.js

The `Content-Type: application/json` response header value should not contain quotes.

Remove unnecessary quotes in HTTP response header

---

lib/handleRequest.js
test/async-await.js

Hi,
* Log `error` when promise is fulfilled with undefined and no other message was sent through `reply.send`

log message when promise is fullfilled with undefined

---

docs/Hooks.md

Based on Fastify/Lobby Gitter discussion today 16:30, it turns out that if using the promise-returning variant of hook handlers, one should not call the `next` function provided within.
I made this limitation explicit in the documentation.

Segregate `async/await` and  `next` hook forms in documentation

---

test/404s.test.js
test/http2/unknwon-http-method.js

Add test for checking how `fastify` handles the unknown http methods

Add test for unknown method

---

lib/ContentTypeParser.js
test/custom-parser.test.js

Disallowing empty bodies was an optimization for parsing `application/json` requests (since JSON bodies are not valid if they are empty). However, now that the ContentTypeParser can be used to parse other content types, this has become a bug.
Fixes #894

Allow parsing empty request bodies

---

lib/validation.js
test/input-validation.test.js

When validating incoming headers both the schema header properties and the incoming header properties are converted to lower case, However the property names in the schema required array are not converted to lower case which cause validation to fail.
**schema**
```javascript
schema: {
headers: {
type: 'object',
required: ['FooBar'],
properties: {
FooBar: { type: 'string' }
}
}
}
```
**request**
```javascript
{
method: 'GET',
url: '/',
headers: {
'FooBar': 'Baz'
}
}
```
**error**
```json
{"statusCode":400,"error":"Bad Request","message":"headers should have required property 'FooBar'"}
```

makes input schema required headers validation case insensitive

---

docs/ContentTypeParser.md
docs/Reply.md
docs/Testing.md
lib/reply.js
test/helper.js
test/hooks.test.js
test/internals/reply.test.js

Fix #913 
I updated all docs to promote good practice.
This should be handled as minor change. The charset of JSON is `utf8`. The default charset of `text` isn't given but we can protect users against crazy misinterpretations. `utf8` [is widely adopted](https://w3techs.com/technologies/overview/character_encoding/all) and defacto standard and most supported charset.

enforce utf8 as default charset

---

docs/Routes.md
fastify.d.ts
test/context-config.test.js
test/types/index.ts

Add `reply.context.config` to documentation.
Add typescript definition too

Add config to docs

---

docs/Getting-Started.md

`fastify server.js` wouldn't start the server, according to `fastify-cli` correct command to start server is `fastify start server.js`.

Updated Getting-Started.md, fixed command for fastify start

---

docs/Ecosystem.md

Adding plugin for auto loading the routes fastify

---

fastify.d.ts
package.json
test/types/index.ts

@types/node v9 defines the parameter returned from the `address` function `AddressInfo | string`
Currently the test on master is broken
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v9/index.d.ts#L2829

Fix typescript address test

---

fastify.d.ts
test/types/index.ts

This PR adds the missing TypeScript definition for hook event `onRoute` and provides to the called function the fields `path` and `prefix` added to `opts` by the function `afterRouteAdded`.
https://github.com/fastify/fastify/blob/71dfd8be932e598c801ae664eacfc45739e9098f/fastify.js#L520-L521

Add TypeScript definition for onRoute hook

---

docs/ContentTypeParser.md
fastify.js
test/custom-parser.test.js

Support array syntax to handle multiple content types as the same

---

lib/reply.js
test/404s.test.js

support for error headers in 404 handler

---

fastify.js

According to the nodejs documentation the callback parameter of the listen method is attached to `listening` event that no takes any parameters.
This PR remove the error parameter (and increase the coverage)

Remove `error` parameter from node `listen` callback

---

README.md
docs/Getting-Started.md
docs/Server-Methods.md
examples/simple.js
fastify.d.ts
fastify.js
test/listen.test.js
test/types/index.ts

Full URL address can be passed in `fastify.listen()`. If listen() is a promise then address passed through resolve method or if it is a callback then passed along with an error. Fixed #875 
Note: Missing "listen on socket" test. Same as previously closed PR #926. Special thanks @allevo, @mcollina, @jsumners, @delvedor 
```js
fastify.listen(3000, '127.0.0.1')
.then(address) => /* do whatever */)
.catch(error) => /* error */);
```
or
```js
fastify.listen(3000, '127.0.0.1', (err, address) => /* do whatever */);
```

fix(): return url from listen method

---

docs/Reply.md
fastify.d.ts
lib/reply.js
test/internals/reply.test.js

This PR adds a `.status()` alias on the `Reply` object that maps to the `.code()` method. Using `status()` is more familiar to some people because it's the leading word of what is actually being set: the status code. In particular, it's more familiar to people coming from Express; see https://expressjs.com/en/4x/api.html#res.status .
Note: the test I added passes when I run `node test/internals/reply.test.js`. Trying to run `npm test` results in some TypeScript nonsense:
```sh
[jsumners@morla] ~/Projects/fastify <git:(status-code *)>
% npm test                                                                                                                   [s:1 l:8140]
> fastify@1.6.0 test /Users/jsumners/Projects/fastify
> npm run lint && npm run unit && npm run typescript
> …
```

Add .status() alias for .code()

---

docs/Decorators.md
lib/decorate.js
test/decorator.test.js
test/internals/decorator.test.js

This PR adds support for defining properties via decoration. I recall an issue sometime ago asking for this feature, but I cannot find it. I personally encountered a need to do this earlier today. I think the proposed implementation is a fair compromise between a barebones decoration API and one that has checks for special supported features.

Add support for decorating with a getter/setter object

---

fastify.js
test/listen.test.js

Continuing https://github.com/fastify/fastify/pull/964.
Add test and a fix for returning the sock path.
The `address` is the sock path and it is not prefixed with the protocol

Add test for retuning sock file path on listen

---

docs/Plugins-Guide.md

Seems like the doc has small issues in the example code.

fix syntax in doc

---

fastify.d.ts
test/listen.test.js
test/types/index.ts

After check source code of `listen` method:
```
function listen (port, address, backlog, cb) {
/* Deal with listen (port, cb) */
if (typeof address === 'function') {
cb = address
address = undefined
}
address = address || '127.0.0.1'
/* Deal with listen (port, address, cb) */
if (typeof backlog === 'function') {
cb = backlog
backlog = undefined
}
if (cb === undefined) return listenPromise(port, address, backlog)
...
```
We can use `listen` in six ways, correct me if I'm wrong.
* listen(port, cb)
* listen(port, address, cb)
* listen(port, address, backlog, cb)
* listen(port).then()
* listen(port, address).then()
* listen(port, address, backlog).then()
```
So I change the typings for the `listen` method according this.

fix listen ts types

---

docs/Ecosystem.md

Hi,
Fastify-swaggergen has been replaced by fastify-openapi-glue which supports swagger and openapi V3
This PR adjusts docs/Ecosystem.md to reflect that change
- [N/A] run `npm run test` and `npm run benchmark`
- [N/A ] tests and/or benchmarks are included
- [X ] documentation is changed or added
- [X ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

Rename swaggergen to openapi glue

---

docs/Server-Methods.md
fastify.js
test/404s.test.js

Hi! This is the first attempt to implement `beforeHandler` for custom `notFoundHandler`.
The original discussion is #713.
**Machine:** QEMU Virtual CPU version (cpu64-rhel6) 2.9Ghz 1 core | 1GB DDR3 2000Mhz
| Variant            |  Requests/sec (error) | diff |
| :----------------- | :------------------------- | :----------: |
| master with custom 404 | 6.600 | --- |
| custom 404 wo beforeHandler | 6.400 | ~= |
| custom 404 with beforeHandler | 5.400 | ~15% |

Feature/#713 beforeHandler for setNotFoundHandler

---

docs/Factory.md
docs/Logging.md
fastify.js
lib/logger.js
test/logger.test.js

Add `requestIdHeaderKey` to fastify configuration in order to support the request id header key customization.
I should update the documentation accordingly too.
The benchmark doesn't reveal changes.

Configure request id header key

---

package.json
test/inject.test.js

The injection using `form-data` module doesn't work properly.
A test is added.

Add test for checking multipart request using form-data module

---

lib/reply.js
test/internals/reply.test.js

If use `reply.res.writeHead` before `reply.send(stream)`, it will cause `response.headersSent` to be true, and `res.setHeader` will throw a error.

fix: if response.setHeader is used, will cause header write after send error

---

fastify.d.ts
test/types/index.ts

Added type definition for [`FastifyInstance.all`](https://github.com/fastify/fastify/blob/master/docs/Routes.md#shorthand-declaration).

Add type definition for FastifyInstance.all

---

docs/Validation-and-Serialization.md
fastify.d.ts
fastify.js
lib/schemas.js
test/shared-schemas.test.js

- Add method `getAllSchemas` that allows to retrieve fastify shared schemas.
This PR is needed to implement support for creating swagger models from fastify shared schemas
https://github.com/fastify/fastify-swagger/pull/88

Add method to get all shared schemas

---

README.md
docs/Server-Methods.md
fastify.js

On some systems (Win 10), localhost resolves to ::1 first, creating
a sub-par development experience when connecting to localhost by
introducing a 300-500ms delay on connection.
Fixes https://github.com/fastify/fastify/issues/1022.

Listen to localhost instead of 127.0.0.1.

---

lib/handleRequest.js
test/custom-parser.test.js
test/delete.test.js
test/helper.js
test/internals/handleRequest.test.js

The original discussion is #936.
#895 made possible to accept request without body and with valid `Content-Type` header **other than** `application/json`.
This change makes possible to do the same if the request method is `DELETE` and the `Content-Type` header is `application/json`.
The PR also separates how we handle the `OPTIONS` and `DELETE` methods based on https://github.com/fastify/fastify/issues/936#issuecomment-397460128.
Best of my knowledge these two RFC paragraph are the closest to our use case, but none of them regulates it explicitly:
*From [RFC 7231 Section 3.1.1.5](https://tools.ietf.org/html/rfc7231#section-3.1.1.5)*
> A sender that generates a message containing a payload body SHOULD
> generate a Content-Type header field in that message unless the
> intended media type …

Resolves issue #936

---

lib/schemas.js
test/shared-schemas.test.js

As titled.
The issue was caused by using the same `$id` key multiple times and `Ajv` was complaining about that (probably because of the cache).
Since we are using a custom schema resolver and only the full final object is passed to the compiler there is no need to also pass the `$id` key.
cc @SkeLLLa

Fixes #1043

---

docs/Reply.md
lib/reply.js
test/internals/reply.test.js

Fixed the bug in redirect exposed in #1049

---

lib/reply.js
test/404s.test.js
test/500s.test.js
test/internals/reply.test.js
test/reply-error.test.js
test/stream.test.js

As I have been making tests for my application, I noticed that default 404 and 500 messages set `content-type` header to only `application/json`, omitting the `charset=utf-8` part.
This seems odd to me, so I propose this pull request.
(possibly linked to #913)

Set UTF8 charset for default 404 and 500 responses

---

lib/reply.js

Use the same content type string in all `reply.js` file.

Refactor content type strings

---

docs/Factory.md
fastify.js
package.json
test/plugin.test.js

I've seen some people complaining that debugging _what_ plugin did not start is very hard.
This fixed it by adding a `pluginTimeout` option to `Fastify`, the errors will contain the name of the plugin as guessed by avvio.

Added pluginTimeout option.

---

package.json

This PR removes the following warning emitted during `npm test`:
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: ~3.0.1
YOUR TYPESCRIPT VERSION: 2.9.2
Please only submit bug reports when using the officially supported version.
=============
```

Update TypeScript to 3.0.1

---

lib/decorate.js
test/decorator.test.js

When I implemented #987 I was unaware that we had special internal functions for decorating the request and reply prototypes. I thought all decorations filtered through this function:
https://github.com/fastify/fastify/blob/d99cd61f246b9d505ae0e0a26819008b65a5afe1/lib/decorate.js#L3-L22
But that isn't the case. That function is essentially duplicated twice: once for request and once for reply. This PR fixes a problem where `instance.decorateRequest` and `instance.decorateReply` do not recognize the getter/setter config like they should be.
I think this code duplication should be removed in a future PR so that this sort of situation does not arise again.

Fix decorate{Request, Reply} not recognizing getter/setter config

---

fastify.js
test/inject.test.js

This was fixed by https://github.com/mcollina/avvio/pull/74.
Should we also update the docs about calling `after()` without a error parameter?

after should not cause inject() to be called

---

lib/handleRequest.js
lib/reply.js
lib/wrapThenable.js
test/async-await.js

Turns out we were not really handling promises well in the error handler. This reuse the same logic of the main handlers. This problems does not apply to the 404 because they go through the normal path anyway.

Handle promises in the error handler with the same logic of normal handlers

---

docs/Server.md
fastify.js
package.json
test/plugin.test.js

Fixes #1090 hopefully right this time 😄

Change default plugin timeout to 10 seconds instead of 0

---

docs/TypeScript.md
fastify.d.ts
test/types/index.ts

First off, this is a completely non-breaking change for typescript users. The main change here is that I converted the query, params, headers, and body types into generics that default to the existing type definitions. Since we can set the schema validators, I think it makes sense to also allow us to exactly type the pieces that can be validated since we will know exactly what their types should be. However, this should not be required which is why I defaulted these new generic types to their existing values, making this feature completely opt-in for typescript users.
Right now, overriding one of the generic types will be slightly verbose since typescript cannot infer generic parameters when one is overridden out of order, but generic parameter type inference is already on their roadmap …

added generic Query, Params, Headers, and Body types

---

README.md
package.json

Hi all,
This is just a small pr with even small changes that are hard to land in other places :P
- Use all the cores available for running the tests
- cagataycali is no longer a contributor
- letzdoit is no longer a sponsor

Updated README and tap runner

---

lib/contentTypeParser.js
test/helper.js
test/internals/contentTypeParser.test.js

Currently we have this logic for the `asString` type parser's `onData` callback:
```js
body += chunk.toString()
```
This may cause the body string to be wrong because some character may have multi length buffer, for example chinese character:
```js
console.log(Buffer.from('啊')) // <Buffer e5 95 8a>
```
Since a multi length buffer may be cut into two chunks, `chunk.toString()` will make a broken string with symbol `&#65533`.
Just concat chunks in the callback and convert the whole buffer into string when transfer end.
I'm not sure whether we can control the chunk size and then we could give a test to reproduce the bug. But if not, it seems hard to make a solid end to end test.

fix the logic of convert chunk segement into string

---

lib/validation.js

I have not added any unit test because we cannot really test latest joi as it requires Node 8+. It works on my machine.
cc @cemremengu 
Fixes #1158.

Fix support for latest Joi

---

fastify.js
lib/reply.js
lib/wrapThenable.js

log is a pino logger, the first argument is a mapping, so in order to give it an error object, we must give it an object with an `err` field, otherwise the error object itself is dissected as if it were a mapping.
This commit fixes places where this has been forgotten.
I only changed source files, not test files because it's not a big deal there.
`npm run benchmark` exits this way on my machine, on my branch just like on master:
```
[0] {"level":30,"time":1537595975197,"msg":"request completed","pid":30338,"hostname":"Ofavre-Home-T5500","reqId":38361,"res":{"statusCode":200},"responseTime":0.18976199626922607,"v":1}
[0] {"level":50,"time":1537595975197,"msg":"client error","pid":30338,"hostname":"Ofavre-Home-T5500","type":"Error","stack":"Error: write EPIPE\n    at WriteWrap.afterWrite …
```

Fix missing object wrapper for errors in pino log

---

docs/Server.md
fastify.js
test/route-prefix.test.js

Replace all `basePath` instances with `prefix` #1182

Change basePath to prefix

---

docs/Ecosystem.md

add `fastify-oas` plugin - an OpenAPI 3.0+ documentation generator.
add `fastify-metrics` plugin - Prometheus metrics exporter.

Add fastify-oas and fastify-metric to Ecosystem.md

---

README.md

fix broken link to Server#listen docs

Fix broken link to Server#listen docs

---

lib/contentTypeParser.js
test/content-length.test.js
test/helper.js
test/options.error-handler.test.js
test/patch.error-handler.test.js
test/put.error-handler.test.js

custom error handler can be able to handle contentTypeParser's errors

---

fastify.d.ts
test/types/index.ts

This PR just fixes the typings of the https property in `ServerOptionsAsSecure`. I added a scenario. to the typescript test file.

typings: fix allowHTTP1 flag for http2 servers

---

lib/contentTypeParser.js

Prevent losing stacktrace when onEnd is called in contentTypeParser

Prevent losing stacktrace onEnd

---

package.json
test/async-await.js
test/hooks-async.js

Remove devDependency `then-sleep` since it's updated 3 years ago (ok theres not much maintenance needed maybe for it), can be achieved natively in one line and gives deprecation error:
`native-or-bluebird is deprecated. please switch to any-promise`

Remove `then-sleep`

---

docs/Routes.md
docs/Validation-and-Serialization.md
fastify.d.ts
fastify.js
lib/handleRequest.js
test/internals/handleRequest.test.js
test/validation-error-handling.test.js

Attempts to provide a solution for #1202 
Here is the original `gitter` chat:
The OP wanted to have functionality similar to `express-validator` which is attaching validation result to request. 
~~However, I wanted to provide a more reusable and less distruptive/polluting way to the main content of request. Instead of filling a request body with validation checks, it makes sense for me to provide an external function for overriding what we already do.~~
~~I also thought putting `wrapValidationError` inside the schema object itself but then decided it will pollute the main information in schema definitions.~~
I will update the docs as well if you think this solves the problem here @fastify/fastify

Attach validation result to request

---

lib/reply.js
lib/symbols.js
lib/wrapThenable.js
test/hooks.test.js
test/internals/reply.test.js

I moved _prefixed properties in Reply.js to symbols.

Move all _ prefixed properties to Symbols

---

docs/Routes.md
fastify.js
test/route-prefix.test.js

This is an alternative to #1225 that creates much less breakage. Basically I'm registering two routes, one with and one without the ending slash. I'm up for adding a flag that have the more strict behavior that #1225 defines, if you think it's needed.
```js
'use strict'
const fastify = require('fastify')()
fastify.register(function (instance, options, next) {
// the route will be called for both '/english/' and '/english'
instance.get('/', (req, reply) => {
reply.send({ greet: 'hello' })
})
next()
}, { prefix: '/english' })
fastify.register(function (instance, options, next) {
// the handler will be called for both '/italian/' and '/italian'
instance.get('/', (req, reply) => {
reply.send({ greet: 'ciao' })
})
next()
}, { prefix: '/italian' })
fastify.listen(8000, function (err) {
if (err) …
```

Plugin double prefix

---

docs/Hooks.md
fastify.d.ts
fastify.js
lib/hooks.js
lib/reply.js
test/hooks.test.js
test/internals/handleRequest.test.js
test/internals/hooks.test.js
test/types/index.ts

Hi all!
This is an initial implementation of what discussed in https://github.com/fastify/fastify/issues/1224.
The documentation/typings are still missing, once we finalize the API and how it works, I'll add them.
Features:
- The `onError` hook lives inside the standard request pipeline and is executed every time `reply.send` is invoked with an Error object (but only after the `customErrorHandler` has finished its execution, in `next` we always have a default);
- `reply.send` will throw if called inside the `onError` hook;
- Changing headers is allowed.
Note:
- If you pass an error to the `next` function inside the `onError` hook, that error will be swallowed.
Feedbacks are welcome!
cc @watson

WIP: onError hook

---

docs/Ecosystem.md

Hi all, I created this plugin to have the ability to forward desired Fastify events (when enabled related hook) generate custom events and serialize then in the [Cloudevents](https://cloudevents.io/) standard format.
Hope it will be useful even to others.
Bye.

add fastify-cloudevents to Community plugins

---

docs/Logging.md
test/logger.test.js

Log redaction is a key new feature of pino v5, and it's better to highligh it.

Document log redaction

---

docs/Server.md
fastify.js
test/custom-querystring-parser.test.js

Implementation of what has been proposed in https://github.com/fastify/fastify/issues/1268.
We are also dropping the use of `url.parse`, so this change will be flagged as `semver-major`.
With this change, the querystring parsing is twice faster than before 🚀

Custom querystring

---

package.json

Needed because of #1281 and https://github.com/epoberezkin/ajv/issues/889.

chore: pin ajv to 6.5.5

---

docs/Ecosystem.md

Greetings everyone, 
I created this plugin that injects a Sequelize instance connected to the PostgreSQL database of CockroachDB along with optional pre-defined models within `fastify`. Defining models is optional and can be done post-injection by accessing `fastify.cockroachdb.instance`.
I recently required it for a project and thought that others might find it useful.
Thanks.

Add fastify-cockroachdb to Community plugins

---

README.md

Taken from latest https://github.com/fastify/benchmarks
Closes #1246

Update benchmarks to reflect latest measurements

---

docs/Ecosystem.md

Greetings everyone, 
I created this plugin that sets the error handler of `fastify` to forward errors to Sentry via their SDK and respond with a generic `500` error and `Internal Server Error` message. It also adds certain context parameters before reporting the error to Sentry, namely the `ip` and `path` of `req.raw` as a `User` context and `Tag` key-value respectively for more concise error grouping.
Once again, I recently required it for a project and thought that others might find it useful.
Thanks.

Added fastify-sentry to Community Plugins

---

fastify.d.ts
test/types/index.ts

fix: add querystringParser to ServerOptions

---

package.json

unpin ajv and use autocannon v3.2.0 which does not depend on the problematic table module.

update ajv and autocannon

---

docs/Ecosystem.md

Hi, I created a plugin for Fastify to allow all requests on a port using HTTP to redirect to HTTPS, or to respond the same way using HTTP(s) on only one port.
Hope it will be usefull to someone.
Bye

Adding fastify-http2https plugin to the community ecosystem

---

docs/Errors.md
docs/Reply.md
lib/errors.js
lib/reply.js
lib/symbols.js
lib/wrapThenable.js
test/skip-reply-send.js

Fixes https://github.com/fastify/fastify/issues/1330
To avoid conflicts, this is based on https://github.com/fastify/fastify/pull/1328, and it will need to be rebased once that lands.

Establish reply.sent = true as a proper way to skip async/await handling

---

docs/Reply.md
lib/reply.js
lib/wrapThenable.js
test/skip-reply-send.js
test/validation-error-handling.test.js

Backport of #1328 and #1330 to 1.x.
This needs to be landed manually to not lose commit history during squash.

Backport sent fixes

---

lib/schemas.js
test/input-validation.test.js

Hi,
this is the fix for #1353 issue, where `$schema` field is ignored and it is not `resolve`d.
I checked that there aren't other fields like that, and I didn't notice them.
I have run also benchmark (with some problems 😅), but looking the code I think that this change impact only the startup time right?
Do you need this fix starting from branch `1.x` also?
Thank you
---
Running banchmarks I get these error after some succesfull run, but maybe could be caused by PC?
```
{"level":50,"time":1545772614031,"msg":"client error","pid":14584,"hostname":"EOMM-XPS","err":{"type":"Error","message":"write ECANCELED","stack":"Error: write ECANCELED\n    at _errnoException (util.js:992:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)","code":"ECANCELED","errno":"ECANCELED","syscall":"wr …
```

fix: #1353 ignore evaluation of $schema field in json-schema

---

.travis.yml
README.md
package.json
tools/license-checker.sh

Fix https://github.com/fastify/fastify/issues/1356
The output si available here: https://travis-ci.org/fastify/fastify/jobs/472663107#L569
There's a summary also (see below).
Are there some cases on which the build fails? For example with Apache Licence?
The license is checker when the dependency is added but if the author doesn't make a breaking change on changing license, I'd like to have a check that fails.
For time being fastify has:
```
├─ MIT: 38
├─ ISC: 4
├─ BSD-3-Clause: 2
└─ BSD-2-Clause: 1
```

Add license-checker on CI

---

LICENSE

Update copyright year to 2019

---

fastify.js

I'm new to js, github and this is my first PR, so feel fre to change anything.
Closes #[1361](https://github.com/fastify/fastify/issues/1361)
**Problem**
Google chrome browser keep-alive socket connection to server, so after 2 min of any https request, or if client will close browser window - server socket [will timeout](https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback). 
After that error will be logged:
```
ERROR [2019-01-03 12:24:09.858 +0000] (11508 on PredatorRTW):
msg: "client error"
err: {
"type": "Error",
"message": "socket hang up",
"stack":
Error: socket hang up
at TLSSocket.onSocketClose (_tls_wrap.js:737:23)
at TLSSocket.emit (events.js:187:15)
at _handle.close (net.js:616:12)
at Socket.done (_tls_wrap.js:384:7)
at Object.onceWrapper (events.js:273:13)
at …
```

move ECONNRESET log from error to debug

---

lib/validation.js

Rewrites a vague code block to be more discrete. I think it would be better to use `Object.keys(headers).forEach(...)`. It also skips non-enumerable properties and imo is more readable than `for (var k in headers)` because `headers` can be misread as an array instead of the object it is.

Rewrite unnecessary lines in validation file

---

test/internals/handleRequest.test.js
test/wrapThenable.test.js

In continuation of the effort to increase the code coverage (#1335 ). 
- 1st commit: Having doubt about how I imported ../../lib/handleRequest again [here](https://github.com/flickz/fastify/blob/fix/improve-test-coverage/test/internals/handleRequest.test.js#L5) but couldn't figure out alternative way to do it. But let me know if you think there's another way I could have done it better.
- 2nd commit: Spent a lot of time trying to come with a test description :smile: but will really appreciate a better way to describe the test.
cc @Ethan-Arrowood

Test coverage further improvement

---

fastify.d.ts
test/types/index.ts

I had to update the `Reply` definition because with the previous syntax was not possible to define function overloads.
Closes https://github.com/fastify/fastify/pull/1341.

Updated reply.redirect declaration

---

lib/reply.js
package.json
test/stream.test.js

This change logs "premature close" stream errors with log level `warn` instead of `error`, as discussed in #1406.

log "premature close" stream errors as warnings

---

lib/reply.js

I think the list in #1407 will only grow in time so we should probably just emit a warning for all problems.

Set log level to warn for all sendStream errors

---

lib/handleRequest.js
test/internals/handleRequest.test.js

Add tests to exercise more lines. `preValidationCallback with finished response` test is a bit synthetic but it gets the work done.

Add tests to cover handleRequest

---

docs/Hooks.md
docs/Lifecycle.md
docs/Routes.md
fastify.d.ts
fastify.js
lib/hooks.js
lib/reply.js
test/hooks-async.js
test/hooks.test.js
test/router-options.test.js
test/types/index.ts

I've added preSerialization hook and route option. This fixes #1369.
One use-case for this is to being able to intercept serialization error before fast-json-stringify (which would hide all information since the error thrown has no context).

feat: Added preSerialization hook and route option.

---

docs/Validation-and-Serialization.md
lib/validation.js
test/validation-error-handling.test.js

Closes #1397 
Set `allErrors: true` in default AJV instance to catch all errors

Update default ajv instance to include all errors

---

test/404s.test.js
test/router-options.test.js

More tests to cover all hooks functionality. Fix a test name as well.

Cover all hooks functionality

---

fastify.js
lib/schemas.js
test/shared-schemas.test.js

This fixes #1419 
The pattern used in the code has been written reading the actual [draft standard](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3):
>    To specify such a subschema identifier, the "$id" keyword is set to a
>    URI reference with a plain name fragment (not a JSON Pointer
>    fragment).  This value MUST begin with the number sign that specifies
>    a fragment ("#"), then a letter ([A-Za-z]), followed by any number of
>    letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons
>    (":"), or periods (".").

fix: json schema $ref with $id set in definitions

---

docs/Server.md
fastify.d.ts
fastify.js
lib/contentTypeParser.js
lib/symbols.js
package.json
test/proto-poisoning.test.js

Protect against prototype poisoning

---

docs/Routes.md
docs/Server.md
fastify.d.ts
fastify.js
package.json
test/versioned-routes.test.js

This PR makes it possible to use custom versioning feature from `find-my-way`.
Which was introduced in scope of this PR: https://github.com/delvedor/find-my-way/pull/107.

update find-my-way to version 1.18.0;

---

lib/contentTypeParser.js
test/custom-parser.test.js

Latest minor broke our server, since it now generates new parser functions every time, the hasParser comparison fails. I only included a unit test so far to show the problem, I don't know how you want to address it so I'd happily take guidance on this one and make the changes, or feel free to merge the failing test and fix it if it's faster for you.

Add test for content-type overriding inside a plugin

---

lib/contentTypeParser.js
test/custom-parser.test.js

Forward port of #1434 from `1.x`.
cc @marsup

Add test for content-type overriding inside a plugin (#1434)

---

docs/TypeScript.md

This PR is a follow-up to [this](https://github.com/fastify/fastify-static/issues/66#issuecomment-460487639). It proposes changes to the plugin typescript docs section to include that we prefer including typings for officially maintained plugins within the respective repos. I also updated the example typings to use fastify.Plugin.

docs: enhance typescript plugin docs

---

docs/Testing.md
fastify.d.ts

Add `query` option after upgrade `light-my-request` to v3.2.0

Add `query` option

---

docs/Server.md
package.json
test/case-insensitive.test.js

As titled, the behavior of `caseSensitive` has changed, I've added two more tests to verify that.
*This should not be backported to v1.*

Updated find-my-way to v2

---

package.json

Locking this dependency, since they dropped support for Node v6.

Exclude tap-mocha-reporter from greenkeeper

---

test/http2/closing.js

I don't understand why the previous PR passed twice but it's still flaky from time to time.

Less flakyness maybe

---

fastify.js
test/decorator.test.js

This fixes #1456 
I have to check if the problem needs to be ported to v2, I'll check later after your feedback 😃
Thanks

fix: don't add twice a json schema to an encapsulated object in tree

---

docs/Ecosystem.md

Greetings everyone, 
I created this plugin that injects an Influx instance connected to the database of InfluxDB along with optional pre-defined schemas within `fastify`. Defining schemas is optional and the instance itself can be found at `fastify.influxdb.instance`.
Once again, I recently required it for a project and thought that others might find it useful.
Thanks.

Added fastify-influxdb to Community Plugins

---

lib/schemas.js
test/shared-schemas.test.js

Closes #1491 
This fix needs to be backported to v1.x

fix: unused shared schema to serializer

---

lib/reply.js

Remove the condition check which is always true

refactor: remove unnecessary condition

---

docs/Request.md
docs/Server.md
fastify.d.ts
fastify.js
lib/reply.js
lib/request.js
lib/wrapThenable.js
test/internals/reply.test.js
test/logger.test.js
test/trust-proxy.test.js
test/types/index.ts
test/wrapThenable.test.js

Add ip, ips, and hostname in `Request` object. Related to @delvedor's feedback at https://github.com/fastify/fastify/pull/1086#discussion_r211718687. All credits go to @nwoltman . Without his guidance, the work won't be possible. 
[benchmarks](https://gist.github.com/shwei/390c850ebc7a52650de5e33481f5fce3#file-fastify-3dc46f3-tables-comparing-master-vs-pass-ip-to-request-constructor-branches-L1)

Pass ip, ips, and hostname to Request object

---

docs/Reply.md
docs/Request.md
docs/Server.md
fastify.js
test/trust-proxy.test.js

To maintain backwards compatibility with Fastify v2, the default value for the new `modifyCoreObjects` option should be `true`.
This PR also updates the relevant documentation to be clearer about how the properties should be accessed and it also fixes some typos.
This is a followup to #1476.

Fix the default for the modifyCoreObjects option

---

docs/Ecosystem.md

Hello everyone, 
I created this plugin that injects a Mongoose instance connected to the database of MongoDB along with optional pre-defined schemas within `fastify`. Defining schemas is required and the instance itself can be found at `fastify.mongoose.instance`.
Once again, I recently required it for a project and thought that others might find it useful.
Thanks.

Added fastify-mongoose-driver to Community Plugins

---

docs/Errors.md

Adjusted the docs on errors as discussed in #1514

Docs: clarify error handling in non-async routes

---

docs/Ecosystem.md
docs/Plugins-Guide.md
docs/Plugins.md
package.json
test/plugin.test.js

Hey everyone,
You can find some updated documentation to reflect the changes made to the plugin registration API for the `options` parameter. It refers to the avvio [PR82](https://github.com/mcollina/avvio/pull/82). I believe it is clear enough but contributions are more than welcome!

Documentation update for avvio PR 82

---

docs/Server.md

Added some note related to serverless environments and removed "experimental status" from http2 (it's no longer experimental in Node.js core).

Updated docs

---

docs/Server.md
fastify.js
lib/errors.js
lib/initialConfigValidation.js
package.json
test/internals/initialConfig.test.js

Address https://github.com/fastify/fastify/issues/1444
@mcollina > I followed your advices and now initialConfig uses a schema to validate what must be exposed, I also documented the functionality.
Let me know if you want that I make some rework.
PS: sorry again for the burden of re-opening a PR, I currently have a poor cellular connection and it was easier for me to do like this in order to avoid commit pollution :smile_cat:

InitialConfig second draft

---

fastify.d.ts

```
import * as fastify from 'fastify';
const fastifyApp = fastify({
pluginTimeout: 900000,
});
```
to fix 
`Object literal may only specify known properties, and 'pluginTimeout' does not exist in type'.`

feat: add pluginTimeout options in d.ts

---

docs/Hooks.md
fastify.d.ts
fastify.js
lib/hooks.js
lib/symbols.js
test/hooks.test.js

This pr adds a brand new hook that will make super happy plugin developers!
It allows you to interact with Fastify encapsulation model and run your magic with it :)
Talk is cheap, here's the code:
```js
fastify.decorate('data', [])
fastify.register(async (instance, opts) => {
instance.data.push('hello')
console.log(instance.data) // ['hello']
instance.register(async (instance, opts) => {
instance.data.push('world')
console.log(instance.data) // ['hello', 'world']
})
})
fastify.register(async (instance, opts) => {
console.log(instance.data) // []
})
fastify.addHook('onRegister', (instance) => {
instance.data = instance.data.slice()
})
```
Feedbacks?
___
Edit: renamed `onEncapsulation` in `onPlugin`
Edit2: renamed `onPlugin` in `onRegister`

Feature: onRegister hook

---

docs/Ecosystem.md
docs/Routes.md
fastify.d.ts
fastify.js
test/route-prefix.test.js

Since 2.0 it is not possible to target only `/v1/test` with the multiple levels of nested prefixes. 
The code in this [sandbox](https://codesandbox.io/s/myxzv3m8ojl) would add only a single route `/v1/test` in v1. However in v2 it creates two routes `/v1/test` and `/v1/test/`.
This PR adds the option `prefixRootOnly` which behaves in the old way, adding only a single route.

Add option to match only prefix root with paths

---

docs/Server.md
docs/Validation-and-Serialization.md
fastify.d.ts
fastify.js
lib/symbols.js
test/post.test.js

Hi,
I would like to add a `getSchemaCompiler` method in order to get returned the function used by the `validation.js` to build the validation function.
That `this._schemaCompiler` have all the JSON schemas of the fastify instance and could let the devs to add some feature validation using the schemas they already set plus the resolved shared-schema.
I'm adding this method in order to solve issue #1376 
I have already build a plugin that accomplishes that task but it works only thanks to this line:
https://github.com/Eomm/fastify-schema-constraint/blob/dbec55b3da4dc88d8c4a1a7c1d337396cc4e9757/plugin.js#L84
I think that could give some new flexibility to the community 👍
Let me know what you think about this PR.
I'm not sure if there could be some side effect I don't spot

add: schemaCompiler property

---

docs/Server.md

This is a quickfix for documentation not describing how to use genReqId with the 'request-id' header is supplied.

Document `genReqId` being called even when 'request-id' header is supplied

---

docs/Hooks.md

Hey guys!
Just fixed a small typo :)

Fix typo in Hooks.md

---

docs/Server.md

Added a fourth option under server logging discussing a custom logger. Closes #1542.

Docs: Update Server#logger to discuss custom logger option

---

docs/Ecosystem.md

This plugin normalizes the Fastify request and reply to the Express version 4.x request and response. This allows middleware, like swagger-stats, that was originally written for Express to be be utilized within Fastify.

Added plugin fastify-normalize-request-reply

---

fastify.js
lib/validation.js

Adding a shared cache between all Ajv instances is going to speed up
external schemas compilation.
See #1597 for more details

use a cache for Ajv compiled schemas

---

docs/Getting-Started.md

The previous version of the documentation didn’t make it clear that the correct approach in containerized environments is to bind to `::` or `0.0.0.0`.

Minor host binding documentation rewrite

---

docs/Ecosystem.md

Fastify-feature-flags plugin provides users simple interface to configure their features. It supports multiple providers starting from simple one - env provider, which reads configuration from env variables. Also it supports more enterprise-ready solutions like unleash - feature flags service that allows more complex configuration. Also it provides generic interface that could be extended in order to create new feature config providers.
This plugin could be useful for A-B testing, rolling releases of features, etc.

Add fastify-feature-flags plugin

---

fastify.js
lib/errors.js
test/hooks-async.js

As titled.
> Wild idea: check at startup if is an async function and the arity, and if it is an async function with 3 arguments, throw an error.
Ref: https://github.com/fastify/fastify/issues/1593

Hooks: throw on incorrect async function

---

lib/contentTypeParser.js
package.json

As titled.
You can find the library code in https://github.com/fastify/secure-json-parse.
Main reasons:
- We need to support Node.js v6.
- The new Hapi licensing strategy may cause issues in the future.

Use secure-json-parse

---

docs/Logging.md

An anchor tag is broken in this page.
https://www.fastify.io/docs/latest/Logging/

docs: fix a broken anchor tag in Logging page

---

docs/Server.md
fastify.js
lib/configValidator.js
lib/reply.js
lib/symbols.js
test/internals/initialConfig.test.js
test/logger.test.js

This addresses issue #1624. Instead of attempting to pass along a limited set of information such that it can be logged at the end of the request, which would lead to a never ending "I need this info there" path, this PR adds an option to disable the initial and final request logs. The result is you can attach your own `onRequest` and `onResponse` hooks to log the information you need and not get double log messages due to the enforced logging in Fastify.

Add option to disable request start and end logging

---

docs/Ecosystem.md

fastify-objectionjs is a plugin for the Fastify framework that provides integration with [objectionjs ORM](https://vincit.github.io/objection.js/).

Add fastify-objectionjs plugin

---

package.json

As discussed in [PR-1618](https://github.com/fastify/fastify/pull/1618), this is the change for adding Tap to GreenKeeper ignore list.
Bye

add tap into greenkeeper ignore list

---

fastify.d.ts
test/types/index.ts

This PR fixes types for `register` method. For some reason it extended `RouteShorthandOptions` that contain some fields with declared types that can't be overridden. However any of those options are not directly used as plugin options. Such example could be find in https://github.com/mcollina/fastify-gql/pull/49 where `schema` should be string or graphql schema, however those type extension forcing it to be `RouteSchema`.
Also I left that options as "generic" for backward compatibility until major typescript refactoring will be merged https://github.com/fastify/fastify/pull/1569. There generic could be removed, cause it's not needed.

fix(types): fix register options

---

fastify.js
test/hooks.test.js

Working on https://github.com/fastify/fastify-websocket/pull/26 we discovered that if `onRoute` hook throws it is not caught anywhere. This PR fixes it.

Catches onRoute hooks errors

---

docs/TypeScript.md

I hope that this is part of the contributing guides. I don't know if you can just open up a Pull Request to fix this kind of issue.

Make some spelling and grammar corrections to TS.

---

docs/Reply.md

I've had some issues drawing the connection from `header` to nodes-`setHeader`, especially as the link to node.js
So hopefully this small comment will make things more clear for people browsing the docs searching how to modify a header

docs(reply): clarify settings headers

---

package.json
test/types/index.ts

Checklist
Ref #1678 and #1681
all branches CI was failing most likely due to a type update in the @types/node library. I've tracked down the error and updated our tests so it passes.
This PR required an additional change to one of the lines due to 1.x being on an older tsc linting set up
Can land as a patch

Fix http2SecureServer test (1.x branch)

---

package.json
test/types/index.ts

Ref #1678 all branches CI was failing most likely due to a type update in the @types/node library. I've tracked down the error and updated our tests so it passes. The commit should be added to 1.x and next as well (even though next will be getting the full TS refactor very soon).
Can land as a patch

Fix http2SecureServer test

---

package.json
test/types/index.ts

Ref #1678 and #1681 
all branches CI was failing most likely due to a type update in the @types/node library. I've tracked down the error and updated our tests so it passes.
Can land as a patch

Fix http2SecureServer test (next branch)

---

lib/route.js
test/route-prefix.test.js

This PR fixes [1672](https://github.com/fastify/fastify/issues/1672) issue.
The real issue was that an incomplete route (`/prefix//`) was added if `ignoreTrailingSlash === true` and `prefixTrailingSlash: "both"` (default behaviour).  On `/prefix//` route call, the fastify server just crashed.

Removes double call to afterRouteAdded when ignoreTrailingSlash === true

---

docs/Fluent-Schema.md
docs/Routes.md
docs/Validation-and-Serialization.md
lib/errors.js
lib/schemas.js
lib/validation.js
test/internals/validation.test.js

Alias schema.query to schema.querystring (#1690)

---

package.json

autocannon dropped node 6 and we use it in our tests
Closes #1674

greenkeeper ignore autocannon

---

lib/context.js
test/logger.test.js

If the `modifyCoreObject` option is false, the framework is incorrectly referencing `req.log` — which is not available. 
This PR changes the code to use `reply` instead of the raw response object coming from nodejs

fix: use reply instead of original res

---

docs/Server.md
fastify.d.ts
fastify.js
lib/context.js
lib/reply.js
lib/route.js
lib/symbols.js
test/internals/reply.test.js
test/types/index.ts

Closes #961 
Hi, I would like to share my first idea to implement a "default serializer" for a fastify (encapsulated) context.
There will be a new method to add a sync function:
```
// The sync function API is the same as `reply.serializer()`.
fastify.setReplySerializer((payload) => {
payload.foo = 'bar bar'
return JSON.stringify(payload)
})
```
Anyway, I would also add to the signature the response code since it could be useful.
The workflow will be:
1. use the reply.serializer if any
1. use the fastify.setReplySerializer if any
1. use the (actual) default validation.serialize
The main issue I found is that the:
- [`validation.serialize`](https://github.com/fastify/fastify/blob/901911c553bea62a21799ec7df34d5e36d2bacd0/lib/validation.js#L106) has a completely different signature
so it …

feature: custom serializator

---

docs/Fluent-Schema.md
lib/schemas.js
lib/validation.js
package.json
test/fluent-schema.js

Now Fastify can detect Fluent Schema objects and call internally `.valueOf`.
This vastly improves the user experience of validation handling.
Ref: https://github.com/fastify/fluent-schema/pull/38
/cc @aboutlo

Improve support for Fluent Schema

---

docs/Hooks.md

Based on #1593 
1) I noted that in some cases we use `next` and others `done`, can be interesting create a pattern.
2) Maybe create a section for each __hook__ sounds good for me, instead of showing the examples with all hooks.

docs(Hooks): Add payload inside example to prevent bugs

---

docs/Decorators.md
docs/Hooks.md
docs/Logging.md
docs/Plugins-Guide.md
docs/Plugins.md
docs/Routes.md
docs/Server.md
docs/Validation-and-Serialization.md

Based on #1739 conversation, to add a pattern inside your plugins/routes/hooks.
We use `next` inside your `examples/*.js` and in our `tests/*.js`
Maybe another PR to adjust it?
Most of people that use Fastify, uses the pattern following `express`(next). Change it can cause some doubt, right?
Personally `done` sounds good for me.

Change the `next` to `done` inside documentation

---

lib/schemas.js
test/route.test.js

This PR reverts the change that caused Joi schemas to not validate correctly when being used as route schemas instead of JSON schemas. 
I need this fix in place to finish an update to Fastify v2. The sooner it can be released the better for me.

Fix bug regarding Joi schemas (issue #1767)

---

fastify.js
test/hooks-async.test.js

change async hooks judgment, from warning to error

chore: change async hooks warning to error for next version

---

fastify.d.ts

using "object" forces manual casting to do string index lookups on headers object

better typing for headers object

---

lib/errors.js
test/internals/errors.test.js

This PR adds `Symbol.toStringTag` to Fastify error instances so silly packages like https://npm.im/lodash.iserror can figure out that they are instances of `Error`.

Add toStrinTag to errors

---

docs/Reply.md
fastify.d.ts
test/types/index.ts

Adds documentation and TypeScript type definition for property `reply.request`.
Additionally, adds missing punctuation mark in `.log` property description.
Relates to #1734

Add request property to reply documentation

---

lib/schemas.js
lib/validation.js
package.json

See https://github.com/fastify/fluent-schema/pull/40
Note: users will need to update their dependency tree.

Use .isFluentSchema instead of symbol to check for fluent-schema

---

docs/Serverless.md

in one example of the serverless documentation: (require.main === module) was inverted.
The description of that example is fine and usage in another example of same document is also fine.

fix inverted if-statement in example of serverless documentation

---

lib/validation.js
test/internals/validation.test.js

Originally reported this issue in fastify-swagger (https://github.com/fastify/fastify-swagger/issues/197), but my investigation lead me to fastify itself.
The issue was that header properties were being duplicated with both upper and lowercase, which caused issues like the one above with fastify-swagger.
I've included a test exemplifying the issue, which passes on this branch and would fail on the master branch.
```
test/404s.test.js ................................. 257/257
test/500s.test.js ................................... 29/29
test/async-await.test.js ............................ 63/63
test/bodyLimit.test.js ................................ 5/5
test/case-insensitive.test.js ....................... 18/18
test/chainable.test.js ................................ 3/3
(node:23006) …
```

Ensure that header properties are not duplicated in schema

---

docs/Errors.md
docs/Server.md
docs/Serverless.md
docs/TypeScript.md

fix order of parameters in typescript docs according to type definitions https://github.com/andriyor/fastify/blob/124e7eea7af4048b008abf9c495bb581ec25061b/fastify.d.ts#L364
fix typos in the documentation

Docs(typescript) and other typos

---

docs/Hooks.md

1. move L7 to L33, for it is a description for Request/Reply hooks.
2. change the number of Request/Reply hooks from seven to eight.
3. add a description for different types of hooks in L7.

docs(Hooks): modify description for Request/Reply hooks and the content

---

lib/fourOhFour.js
test/404s.test.js
test/logger.test.js
test/route-prefix.test.js

This avoids creating an `Error` in the default 404 route and improves the log message by adding the method and url that has been called. 
Closes #1823
I did a benchmark run with the following command: 
```
npx concurrently -k -s first \"node ./examples/simple.js\" \"npx autocannon -c 100 -d 5 -p 10 localhost:3000/notfound\"
```
Results `master` branch:
```
[1] ┌─────────┬──────┬──────┬────────┬────────┬──────────┬─────────┬───────────┐
[1] │ Stat    │ 2.5% │ 50%  │ 97.5%  │ 99%    │ Avg      │ Stdev   │ Max       │
[1] ├─────────┼──────┼──────┼────────┼────────┼──────────┼─────────┼───────────┤
[1] │ Latency │ 0 ms │ 0 ms │ 159 ms │ 206 ms │ 16.17 ms │ 50.8 ms │ 759.36 ms │
[1] └─────────┴──────┴──────┴────────┴────────┴──────────┴─────────┴───────────┘
[1] …
```

Improve default 404 route

---

test/stream.test.js

There was an incorrect test count on the premature close tests where it never actually tested whether `'close'` was emitted.
`'close'` is actually not emitted (Node bug?) and to fix these test we need to increment the test count and instead listen for `'aborted'`.
Refs: nodejs/node#27984
P.S. Sorry for the previous hasty PR. I've checked this properly now against both versions of Node.

fix: premature close test

---

package.json

Closes #1798 
Node 6 no longer supported

greenkeeper ignore @typescript-eslint/eslint-plugin

---

fastify.d.ts
test/types/index.ts

Typescript eslint https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md is reporting an error when creating an async/await hook function.
```js
server.addHook('preValidation', async (_request, _reply) => {
await Promise.resolve();
console.log('test');
});
```

Fix eslint "no-misused-promises" error in hooks

---

fastify.d.ts
test/types/index.ts

This PR just adds the type declaration of `FastifyReply#removeHeader` into fastify.d.ts.
Implementation is there: [lib/reply.js#L150](https://github.com/fastify/fastify/blob/78c867f46ad17265f019dd8e84148a21bc4c33b6/lib/reply.js#L150)

add FastifyReply#removeHeader method to fastify.d.ts

---

test/listen.test.js

To avoid side effects from other processes, avoid using a predictable
file name for the socket in the OS tmp directory.

randomize file name in test

---

CONTRIBUTING.md

Adding non-written rules to docs

Rules to contributing to plugins 

---

docs/Plugins.md
test/plugin.test.js

docs(Plugins): removed prefix from list with fastify-plugin

---

lib/schemas.js
package.json
test/internals/schemas.test.js

Fixes bug with invalid schema. The reason is that calling `getJsonSchemas` changes `store[schemaKey]` (adds `$id` field). But `resolve` returns `this.store[id]` and returned object could be changed at next `getJsonSchemas` call. It affects plugins like [fastify-swagger](https://github.com/fastify/fastify-swagger)
Fixes #1871

Don't change resolved schema

---

fastify.d.ts
test/types/index.ts

According to [avvio](https://github.com/mcollina/avvio/blob/3a386683994bfb274355edbb0d7d892e0e066e9a/plugin.js#L89) the `register()` function expects plugins to be either synchronous functions, asynchronous functions with a `callback` argument or asynchronous functions that return promises.
I stumbled upon this issue when using [apollo-server-fastify](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-fastify). The [`createHandler()`](https://github.com/apollographql/apollo-server/blob/2f4074252778e1946f5493513d249d26751036f2/packages/apollo-server-fastify/src/ApolloServer.ts#L82-L85) function returns an `async function` that's supposed be passed to `register` like this:
```js
server.register(apolloServer.createHandler());
```
TypeScript itself is fine with …

Fix Plugin type in fastify.d.ts

---

fastify.js
test/hooks-async.js

The onError hook has 3 parameters (request, reply, error) and it's currently triggering a warning saying that it has too many arguments.
This change adds `onError` the same condition branch as `onSend` and `preSerialization`.

Fix warning for onError hook

---

fastify.d.ts
lib/schemas.js
package.json
test/schemas.test.js
test/types/index.ts

Fixes #1881 
This doesn't fix the case:
```
fastify.route({
method: 'POST',
url: '/',
schema: {
response: {
'2xx': ajv.getSchema('urn:schema:response').schema
}
},
handler (req, reply) {
reply.send({ foo: 'bar' })
}
})
```
I'm still investigating.
Meanwhile, @jsumners, if you would like to suggest more test it would be really helpful

fix schema resolver for plain id

---

docs/Reply.md

doc fix: add .headers to reply docs

---

docs/Reply.md
lib/reply.js
test/internals/reply.test.js

The necessity is for this use case:
https://github.com/fastify/fastify-reply-from/blob/master/index.js#L119-L121
It is not possible for the user to access the status code set by plugins and not exposed.
In this way, the user can have control every time.

Reply status code

---

test/decorator.test.js

Add test for documenting behaviour "After can access to decorations registered into plugin"

Test: After can access to decorations registered into plugin

---

fastify.d.ts
test/types/index.ts

Adds missing typescript definition for server option `genReqId`.
This missing definition required us to define it in our project to build successfully.

Add type definition for genReqId option

---

fastify.d.ts
test/types/index.ts

Added missing types for Server Options

---

docs/Ecosystem.md

Hi!
I've created this plugin based on top of fastify-jwt that enables verification of Auth0 issued tokens with HS256 or RS256.
Hope this helps!

 Add fastify-auth0-verify plugin to Ecosystem

---

fastify.d.ts
package.json
test/types/route.test-d.ts
types/instance.d.ts
types/middleware.d.ts
types/request.d.ts
types/route.d.ts

While working on the new documentation I realized that when defining generic properties for routes can be extremely repetitive, and exhaustive when only defining one of the 4 available generics (Body, Querystring, Params, Headers). For example:
```typescript
import fastify, { 
RouteShorthandOptions, 
RequestBodyDefault, 
RequestParamsDefault, 
RequestHeadersDefault } from 'fastify'
const server = fastify()
type QuerystringType = {
username: string,
password: number
}
server.get<
RequestBodyDefault,
QuerystringType,
RequestParamsDefault, 
RequestHeadersDefault
>('/auth', async (request, reply) => {
const { username, password } = request.query
return `logged in!`
}) 
```
In this example we only need to modify the `Querystring` generic, but are required to pass in the preceding `Body` …

Update route generics to use object instead

---

docs/Hooks.md

Hi!
While working on a custom plugin I had problem understanding how to access route options in a `preSerialization` hook.
After talking to @mcollina I realize that adding a new hook (by setting `route.preSerialization`) from within a `onRoute` is perfectly legit and actually the intended way to go.
This documentation PR aims to makes this aspect more explicit.
Hope this helps!

Update onRoute documentation for plugin authors.

---

docs/Server.md
docs/Validation-and-Serialization.md
fastify.d.ts
fastify.js
lib/route.js
lib/schemas.js
lib/validation.js
package.json
test/fastify-instance.test.js
test/input-validation.test.js
test/schemas.test.js

- Implement support for custom Ajv options without breaking encapsulation when creating custom Ajv instance.
- Implement support for ajv plugins
```js
const fastify = require('fastify')({
ajv: {
customOptions: {
nullable: false // Refer to [ajv options](https://ajv.js.org/#options)
},
plugins: [
require('ajv-merge-patch')
[require('ajv-keywords'), 'instanceof'];
// Usage: [plugin, pluginOptions] - Plugin with options
// Usage: plugin - Plugin without options
]
}
})
```

Ajv update

---

fastify.d.ts
test/types/index.ts

Type changed only, Support multiple paths
```ts
/**
* Apply the given middleware to routes matching the given multiple path
*/
use(path: string[], middleware: Middleware<HttpServer, HttpRequest, HttpResponse>): void
```
for example
```js
// Multiple paths
fastify.use(['/css', '/js'], serveStatic(path.join(__dirname, '/assets')))
```

fix: add middleware type for multiple paths

---

docs/Hooks.md
fastify.js
test/hooks.test.js

This change lets plugins' developers increase the feature they can develop with the `onRegister` plugin.
I'm working on a plugin that would use this feature and improve how the user writes tests.

Opts on register

---

docs/TypeScript.md

Docs update for http2, https types support in plugins.
- [ + ] documentation is changed or added
- [ + ] commit message and code follows [Code of conduct]

Typescript types plugin example docs update

---

docs/TypeScript.md

Added docs comment for correct use of typings for https server:
"// For https pass http2.Http2SecureServer or http.SecureServer instead of Server."

minor docs update for https typings

---

docs/Ecosystem.md

Hello everyone, 
I created this plugin that injects a CASL utility class in fastify that enables one to add preHandler & preSerialization hooks to API endpoints, sanitizing any input and output of the path. It follows a simple definition language and ties in nicely with MongoDB models. Under the hood, it utilizes the [casl](https://github.com/stalniy/casl) library.
The tests provide 100% coverage although I admit they can be restructured to be a bit more readable and concise. Additionally, although a CI process has been defined it does not operate yet as CircleCI doesn't have the necessary permissions, this will be fixed today / tomorrow.
Thanks.

Added fastify-casl to Community Plugins

---

docs/Ecosystem.md

Hi, I've created a plugin to easily integrate with TypeORM.
I've based my setup on fastify-elasticsearch.
Any feedback is welcome 😄 .

Add fastify-typeorm-plugin to community plugins

---

.github/workflows/ci.yml

I'm removing the Windows / Node 6 combo from CI. A couple of reasons:
1. it's a flaky test with 50% chance of failing on that platform
2. Node 6 is long in the past
3. We are still testing Node 6 all across the other envs.
I'm happy to investigate in this if there is a strong need but otherwise I'm not convinced we should go and fix this.

Drop Windows-latest and Node 6 from CI as its failing.

---

README.md
docs/Fluent-Schema.md
docs/Hooks.md

fix - docs - hooks - error handling

---

docs/Ecosystem.md

Hacking fastify 🤟
This plugin lets you store the fastify instances in order to use them in tests and trigger those piece of code that usually couldn't be reached.

add fastify-explorer to ecosystem

---

docs/Hooks.md
fastify.js
lib/fourOhFour.js
lib/hooks.js
lib/route.js
test/hooks-async.test.js

In the past, the `this` of every hook was the same as the context where it has been registered, while the `this` of the route-specific hooks is the same as the plugin where the route is registered. This could lead to some confusion, as the `this` changes during time, while it's better to have it consistent.
This pr addresses this issue, take a look at the test to see the new behavior.
This should not break current application code, but it's safer to release it in a server major change.
Closes: https://github.com/fastify/fastify/issues/1587

Hook scope binding

---

docs/Hooks.md
fastify.js
lib/hooks.js
lib/route.js
lib/symbols.js
test/hooks.test.js

Back in https://github.com/fastify/fastify/pull/642 we have decided to not encapsulate `onRoute` and `onRegister`, almost two years after, the use of this hooks in our plugins has changed, and make this two hooks encapsulated is now the right choice.
Unfortunately, doing so will introduce a breaking change, since the behavior of those hooks will change slightly.
**`onRoute`**
The hook will be called asynchronously, in v1/v2 it's called as soon as a route is registered. This means that if you want to use it, you should register this hook as soon as possible in your code.
**`onRegister`**
Same as the `onRoute` hook, the only difference is that now the very first call will no longer be the framework itself, but the first registered plugin.
Fixes: #1970

Fix hook encapsulation

---

docs/Reply.md
docs/Request.md
docs/Server.md
lib/context.js
lib/handleRequest.js
lib/reply.js
lib/request.js
lib/route.js
lib/warnings.js
lib/wrapThenable.js
test/emit-warning.test.js
test/hooks-async.test.js
test/hooks.test.js
test/internals/handleRequest.test.js
test/internals/reply.test.js
test/middleware.test.js
test/reply-error.test.js
test/skip-reply-send.js
test/stream.test.js
types/reply.d.ts

The current API is not consistent, we have `request.req`, `request.raw` and `reply.res`.
I don't recall why we kept  `request.req`, but I think it's useless and also ugly to use, as people usually would write the shorthand version: `req.req`.
This pr removes completely `request.req` and renames `reply.res` to `reply.raw`.
We can choose to keep `.req` and `.res` as aliases, but since we are about to cut a major, I would prefer just to remove those and avoid maintaining an almost useless alias.
We can even choose to be more strict and have a function, such as `unwrap` that returns the Node.js core objects.
Note: this will not introduce any benefit, just a more explicit contract between our APIs and the user.
```js
fastify.get('/', (req, reply) => {
const res = reply.unwrap()
res.statusCode …
```

Drop request.req and rename reply.res to reply.raw

---

docs/Server.md
fastify.js
lib/fourOhFour.js
lib/request.js
lib/route.js
test/genReqId.test.js
test/internals/contentTypeParser.test.js
test/internals/handleRequest.test.js
test/internals/logger.test.js
test/logger.test.js
test/trust-proxy.test.js

As titled, with this pr we also stop enhancing the Node.js core request/response objects.
Once this one is merged, I'll work on https://github.com/fastify/fastify/issues/1551.
Closes: #2013

Removed modifyCoreObjects option

---

docs/Routes.md

docs(onResponse): fix parameter not sent in doc

---

docs/Logging.md
docs/Request.md
lib/context.js
lib/logger.js
lib/reply.js
lib/request.js
lib/route.js
test/internals/handleRequest.test.js

As titled. I've also added a few new getters in our `request` object, which not only improves the API, but also softens the breaking change.
Closes: #1551

Serialize Fastify objects instead of Node.js

---

lib/schemas.js
test/shared-schemas.test.js

Fixes #2021 
Reading the spec of [enum](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.2) I have added a check to avoid the shared schema "replace way" only when we are traversing a `type: string enum: [values]` JSON schema.
Because this is a valid use case:
```
{
type: 'object',
enum: [{hello:'C#'}]
}
```
That some users can write with shared schema:
```
{
type: 'object',
enum: ['helloJson#']
}
```

fix replace way enum

---

fastify.d.ts
test/types/index.ts

fixes #2030 for v2
using `T` instead of`Payload` as it's much more readable

add generic to typescript Reply.send payload

---

lib/schemas.js
test/route.test.js

This pull request fixes #2024.
I see it as a workaround because probably there is a better way to do it.
I'm not too familiar with the codebase, but maybe it's a good idea to create a deep clone of the original schema and then resolve it? This way any mutation won't modify the original schema.

Workaround for using one schema for multiple routes

---

docs/Testing.md

Added a reference to chainable methods on 'inject' function based on the update of 'light-my-request'

docs: inject chainable methods (#1917)

---

build/build-validation.js
docs/Server.md
fastify.js
lib/configValidator.js
lib/server.js
package.json
test/http2/closing.js
test/internals/initialConfig.test.js

This commit adds an option http2SessionTimeout to be able to gracefully
closing an http2 server. This is analogous to the 5000ms timeout of
keepalive connections.

http2: handle graceful close

---

lib/route.js
test/hooks.test.js

I had to modify the route urls for some reason. However, i noticed that not affecting the url changes in onRoute hook and made such a little fix.

fix: use opts of onRoute hook

---

docs/Server.md
fastify.d.ts
test/genReqId.test.js
test/logger.test.js
test/types/index.ts

This pull request adds a missing Typescript definition for the `ServerOptions.genReqId` function's request argument, which renders the function unusable for processing the request under Typescript.
I was trying to use the incoming request inside `genReqId` to parse the `x-apigateway-context` header and use the request id provided by the AWS API Gateway service, falling back to a newly generated UUID v4 if not present, but then realized that Typescript was complaining whenever I added the request argument.
According to both [the documentation](https://github.com/fastify/fastify/blob/master/docs/Server.md#genreqid) and [the codebase](https://github.com/fastify/fastify/blob/master/lib/reqIdGenFactory.js#L6), this function receives the incoming request as an argument, but its type definition …

Add missing TS definition for ServerOptions.genReqId function arg

---

docs/Errors.md
lib/errors.js
lib/hooks.js
test/hooks.test.js

Fixes: #2070 
The reason why the error was not thrown because `Promise.reject()` was empty and it didn't have any error like `Promise.reject(new Error)` so when result.then is called it when to `handleReject` with error undefined.

fix: throw hooks promise rejection (#2070)

---

fastify.d.ts
test/types/fastify.test-d.ts
test/types/logger.test-d.ts
types/utils.d.ts

Introducing a better typescript developer experience. Now using overloads, discriminant unions, and generic parameter inference the user no longer has to specify the type of their server in the generic parameters when instantiating. They simply have to use the correct server options and the interpreter will figure out which server type to return to them.
`{ http2: true, https: {} }` -> `http2.Http2SecureServer`
`{ http2: true }` -> `http.Http2Server`
`{ https: {} }` -> `https.Server`
`{} | undefined` -> `http.Server`

use overloads for stricter type inference

---

docs/Hooks.md
test/hooks-async.js
test/hooks.test.js

Add docs to stop processing hooks with async

---

docs/Ecosystem.md

As titled :)
This is yet another authentication plugin for Fastify, but its quite different from the others. I wrote some pretty decent docs that should help developers getting started with Fastify (and perhaps Node) to implement simple, but effective (and safe) authentication.
Thans!

Added fastify-esso plugin

---

build/build-validation.js
docs/Server.md
fastify.d.ts
fastify.js
lib/configValidator.js
lib/server.js
test/connectionTimeout.test.js
test/internals/initialConfig.test.js
test/keepAliveTimeout.test.js

* Implements #2058
* ~~Both `http` and `https` also have `server.keepAliveTimeout` setting (for `Keep-Alive` connections; 5 seconds by default), but I'm not sure if it makes sense to add option for that one~~
- Introduced `keepAliveTimeout` (HTTP/1 only; 5 seconds by default - same as in `http[s]`)
* ~~Current default (60 seconds) may lead to problems in serverless environments. See https://github.com/nodejs/node/issues/27556. So, maybe default should be 0 (no timeout at all), like it's done in `http[2s]` modules in recent versions of Node.js?~~
- Set to `0`
* ~~I'm not sure if it makes sense to apply `connectionTimeout` when `serverFactory` is in use~~
- Implemented this behavior and updated documentation

Add connectionTimeout option

---

lib/errors.js
lib/reply.js
test/reply-error.test.js

When setting an `undedined` status code in reply, it will throw a new custom error message.
Fixes #2078

Throws error if undefined status code is sent

---

fastify.d.ts
test/types/index.ts

Fix inaccurate type of `setErrorHandler`

---

docs/Server.md

There was a typo error in documentation in **disableRequestLogging** section.

Fixed typo res.res to reply.res

---

docs/Plugins-Guide.md

Noticed this when reading through docs on plugins.  I think the intention was for the util to be the same in every case, but in the first case it was assigning the value to the literal key property of request instead of the computed value of key using square brackets.
Since it's the first example it confused me, but made sense when I looked further down and noticed the second and third examples using square bracket notation. This makes them all the same.
```
request.key = value
request[key] = value
```

docs: use computed key when assigning property to request

---

fastify.d.ts
test/types/index.ts

In the not found handler, `this` refers to the current fastify instance. However, corresponding type declaration of `this` is absent.
https://github.com/fastify/fastify/blob/b44d859874a51558b207781533eb7208a7ce61bc/fastify.d.ts#L691
This pull request contains the fix and corresponding test.

types: add type of `this` to the not found handler

---

docs/TypeScript.md

The generic short-hand types follow order `<Query = DefaultQuery, Params = DefaultParams, Headers = DefaultHeaders, Body = DefaultBody>`
but the docs has them listed as `<Query, Params, Body, Headers>`. This caused one of the examples to be incorrect when it assigned `unknown` to the `Headers` type but explained that it was `unknown` on the `Body` type. The body was undefined which mean it would default to `DefaultBody` which is `any`

docs: fix header and body generic types

---

lib/route.js
test/http2/plain.js

http2: fix req.hostname not set

---

docs/Ecosystem.md

As titled :smiley: 
This plugin adds support for sending requests via [`axios`](https://github.com/axios/axios), a promise based HTTP client. 
I hope it will be useful for community!
Thanks

Added fastify-axios plugin to Ecosystem Community Plugins

---

docs/Reply.md

fixes #1592
The documentation is much more specific about
calling reply.redirect() where .code() has and has
not been called.

docs: Clarify reply.redirect status code docs

---

.github/workflows/ci.yml

I'm quite sad for all the failing checkout in this PR https://github.com/fastify/fastify/pull/2077/checks?check_run_id=475848653
I saw that there is a new version of this action... hope it will decrease our fail ci

ci: update checkout action

---

README.md

I stumbled on an `npm init` feature, if you do `npm init <name>` npm will execute the bin file of `create-<name>`.
Created http://npm.im/create-fastify to hook into that functionality, it just uses the generate cli function of fastify-cli.
So now if you do `npm init fastify` in a folder, it'll autogenerate a fastify project.
Before this can land we need to move https://github.com/davidmarkclements/create-fastify to https://github.com/fastify/create-fastify. 
As a form of request, I've also added myself to the list of core contributors.
Here's my case for making this request:
* fastify is literally the web framework of my dreams.
* I'm familiar with the internals
* I have a corpus of performance-related OSS and published analysis
* pino is a core part of fastify and I think we can do more …

quicker quick start + request to add to core contributors

---

docs/Reply.md

This is an attempt at fixing #1680.

docs: Clarify thrown values must be Errors

---

docs/Decorators.md

This resolves issue #2117.
In addition to resolving that issue, this PR refactors the decorators documentation completely by:
1. Removing all informal language
1. Moving anchors into correct position for editor code folding and proper browser anchor referencing
1. Grouping API methods into a coherent list
1. Moving relevant information into contiguous blocks instead of spread out over multiple sections

Update decorators documentation

---

lib/decorate.js
lib/errors.js
test/decorator.test.js
test/internals/decorator.test.js

Check if fastify has started when calling decorate* and throw an error if it has.
Fix #2116 .

feat(decorators): throw error if called after start

---

package.json
test/types/index.ts

this is a breaking test that illustrates #2148 . It should pass once the issue is fixed

test for issue #2148 where typedefs for query params object were wrong

---

.dependabot/config.yml
package.json

greenkpeer is shutting down, let's move to dependabot

Replace greenkeeper with dependabot

---

docs/Reply.md
lib/reply.js
test/internals/reply.test.js
types/reply.d.ts

This adds a `getHeaders()` method to Reply.
It returns a shallow copy of all current response headers, including those set via the raw `http.ServerResponse`. Headers set via Fastify take precedence over those set via `http.ServerResponse` to match the behavior of `res.writeHead()`.
See https://github.com/fastify/fastify-nextjs/issues/84 for an example of a use case that would benefit from this feature.
Some things to note:
-   I've opened this PR against the `next` branch because it relies on `http.ServerResponse`'s [`getHeaders()` method](https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_response_getheaders), which was added in Node 7.7.0. I'm not sure if there's a way to do this that's compatible with Node 6.x, but I'm open to suggestions!
-   Node's `getHeaders()` returns an …

Add a getHeaders() method to Reply

---

docs/Ecosystem.md

Hi!
This plugin allows use HTTP verbs, such as DELETE, PATCH, HEAD, PUT, OPTIONS in case the client doesn't support them.
I hope this plugin will be useful.

add fastify-method-override to ecosystem

---

types/instance.d.ts

I noticed that `fastify.inject` wasn't returning the right thing. Fixed it to use the correct types from light-my-request.

fix inject response types

---

docs/Hooks.md

As per this comment: 
https://github.com/fastify/fastify/issues/1593#issuecomment-608999111
I also took the liberty of adding some links that were missing in the page anchors menu.

Docs for managing errors in an async hook

---

docs/Ecosystem.md

This is a new PR for google cloud trace API plugin. Look at #2181 for the detail of why there is a new PR for the same thing.
I am adding a plugin that connects your application with Stackdriver Trace API for Fastify. It measures how long each event takes within one request and generates trace results.

Add google cloud trace API plugin

---

lib/errors.js
lib/reply.js
test/reply-error.test.js

Updates how we validate reply status code.
Now allowing only numbers in range between 100 and 600
Fixes: #2169

Fixes crash when using a non-standard error code

---

.github/workflows/package-manager-ci.yml
docs/LTS.md

A module updated to mkdirp in their tree and it has engine >= 10.x, so we need to install with `--ignore-engines` with yarn.
I've also done some cleanup in our LTS doc.

Fix package-manager CI

---

lib/reply.js
test/stream.test.js

- This PR fixes an issue where prematurely closed sockets would cause duplicate log lines
- This PR also reduces the log level of prematurely closed sockets from WARN to INFO (clients closing sockets is expected behaviour)
Fixes  fastify/fastify-static#116

Fix double logging + reduced log level for streams

---

docs/Middleware.md

I noticed these stray quotes broke this link when viewed [via the github user interface](https://github.com/fastify/fastify/blob/master/docs/Middleware.md).  This PR makes this one link behave as the others do in the doc. 
This is my first PR to this repo and I _think_ I'm doing it right, but if there's extra process or a different branch/repo I should be submitting this to please let me know.

Fix for Link in docs/Middleware

---

docs/Routes.md
docs/Server.md
docs/Validation-and-Serialization.md
lib/schema-compilers.js
lib/validation.js
test/input-validation.js
test/internals/handleRequest.test.js
test/internals/validation.test.js
test/route.test.js
test/schema-examples.test.js
test/schema-feature.test.js
test/schema-serialization.test.js
test/schema-validation.test.js
test/validation-error-handling.test.js
types/schema.d.ts

I would like to change the new API interface for *compilers, this would ease the migration from v2 to v3.
I thought it was a good idea to put the `schema` at the end... 😅
Edit:
the target is that the migration would be: "replace `setSchemaCompiler()` to `setValidatorCompiler()`"
cc #2140

change *compiler api

---

package.json

As titled. The update just includes the drop of Node v6 and  v8.

Updated find-my-way dependency

---

test/types/plugin.test-d.ts
types/instance.d.ts
types/register.d.ts

Fixes function signature type of `instance.after()`
Fixes register / close / after not being thenable
Fixes register / close / after not being chainable

fix: Chainable / thenable types & after signature

---

docs/TypeScript.md
docs/Validation-and-Serialization.md

This fixes the spelling of various words in the "TypeScript" and "Validation and Serialization" documentation.

docs: fix spelling errors

---

docs/Ecosystem.md

The current objectionjs plugin only imports the main Model class. However other useful classes such as transaction, fn, ref aren't being imported. You could either import the whole library or write individual internal plugins for every class. This plugin makes it easier to cherry-pick whatever class you want to use.
~run `npm run test` and `npm run benchmark`~
~tests and/or benchmarks are included~

plugin: add fastify-objectionjs-classes

---

lib/handleRequest.js
test/http2/head.test.js
test/internals/handleRequest.test.js

Fix HEAD requests hanging in Node version 10 and 13.5.0.
On these requests, the `preValidationCallback` and `preHandlerCallback`
were exiting prematurely because of `reply.raw.finished` being `true`
with the handler not having sent the response yet. Using `writableEnded`
where available and a combined check of the `writable` and `finished`
properties solved this problem.
Fix #1993

http2: fix HEAD requests hanging

---

lib/handleRequest.js
test/http2/head.js
test/http2/http2.test.js
test/internals/handleRequest.test.js

Fix HEAD requests hanging in Node version 10 and 13.5.0.
On these requests, the `preValidationCallback` and `preHandlerCallback`
were exiting prematurely because of `reply.raw.finished` being `true`
with the handler not having sent the response yet. Using `writableEnded`
where available and a combined check of the `writable` and `finished`
properties solved this problem.

http2: fix HEAD requests hanging (#2233)

---

.github/workflows/backport.yml

As titled!
This GitHub action should help us easily backport changes from `master` to `2.x` or `1.x`, you just need to add the correct backport label and it will work automagically!
If the can't be automatically backported, the GitHub bot will comment the failure on the pr.
I've already renamed our backport labels so the bot can understand them.
It's quite easy, as soon as someone opens a pr against `master`, and the change should be backported to `2.x` and/or `1.x`, you should add the corresponding backport label.
For example, if we need to backport something to both `2.x` and `1.x`, we will add:
- `backport 2.x`
- `backport 1.x`
And you are done! If there are no conflicts, the action will open a separate pr with the backport, and after the tests pass, you should manually merge it :)

Added github backport action

---

lib/handleRequest.js
test/internals/handleRequest.test.js

Add missing `raw` property in path when accessing `writableEnded`.
Explicitly set `writableEnded` only in Node versions greather than equal
to 12.9.0 in `preValidationCallback` test.

fix(internals): fix typo in handleRequest

---

fastify.js

See: https://github.com/fastify/fastify/issues/2036

Log clientError as trace to avoid dev confusion

---

docs/Server.md
fastify.js
test/reply-error.test.js

The custom clientError handler function has the signature `(err, socket, logger) => void`
The extra logger is injected to allow the custom clientHandler to have parity with the default `clientError` handler. The default `clientError` handler has access to `logger`, so the custom one should have access to `logger` as well.
---
`npm run bench` results are as follows. The tests were run a MacBook Pro laptop (Retina, 15-inch, Mid 2015).
```
> fastify@3.0.0-rc.1 bench /Users/chiku/code/fastify
> branchcmp -r 2 -g -s "npm run benchmark"
Current Branch is client-error-handler ba6508a
? What's your branches to compare? client-error-handler, master
? Please enter the command you want to execute in all branches! npm run benchmark
Checking out "client-error-handler"
Execute "npm run benchmark"
> …
```

Add option to configure clientErrorHandler (#2226)

---

docs/Reply.md
docs/Server.md
lib/handleRequest.js
lib/reply.js
test/404s.test.js

Fixes https://github.com/fastify/fastify/issues/2229

Fix: call preHandler on reply.callNotFound

---

docs/Validation-and-Serialization.md
package.json
test/validation-error-handling.test.js

Added docs example to demonstrate usage with ajv-errors & ajv-i18n.

doc: doc example to use ajv-errors

---

docs/Validation-and-Serialization.md
package.json
test/schema-examples.test.js
test/validation-error-handling.test.js

Port f12f4871a1053b6caaa8627921eb8096e2e9f9ab from #2254 to master
* docs: added example docs to show usage with ajv-errors
* doc: fix wordings
* docs: added example docs to show usage with ajv-i18n
* docs: feedback
* doc: fix doc for i18n
* add tests to verify ajv-errors & i18n examples from docs
* Update test/validation-error-handling.test.js
Co-authored-by: Manuel Spigolon <behemoth89@gmail.com>
* Update docs/Validation-and-Serialization.md
Co-authored-by: Matteo Collina <matteo.collina@gmail.com>
Co-authored-by: Manuel Spigolon <behemoth89@gmail.com>

doc: doc example to use ajv-errors (#2254)

---

docs/Reply.md
docs/Server.md
lib/handleRequest.js
lib/reply.js
test/404s.test.js

Backport ae6b57c94cbfcec10b66c4a19d8a62df540486c1 from #2256

[Backport 2.x] Fix: call preHandler on reply.callNotFound (#2256)

---

docs/Server.md

In reference to #2265, I have converted the absolute urls from Server.md to relative urls.

Remove absolute URL's from docs

---

docs/Server.md
fastify.js
test/request-error.test.js

This PR implements the new recommended approach (https://github.com/nodejs/node/issues/33302) on how to handle `ECONNRESET` during `clientError` events.
Fixes #2036.

Ignore clientError on reset connections. (#2036)

---

package.json
test/close.test.js

This PR bumps minimum avvio version in order to avoid fastify/avvio#110.
It also added test to address #2250.

test: Add test to verify async onClose hooks. (#2250)

---

docs/Ecosystem.md

Added [`fastify-now`](https://github.com/yonathan06/fastify-now) to community plugins
[`fastify-now`](https://github.com/yonathan06/fastify-now) allows you to Structure your endpoints in a folder and load them dynamically

add fastify-now to community plugins

---

docs/TypeScript.md
fastify.d.ts
fastify.js
package.json
test/types/fastify.test-d.ts
test/types/logger.test-d.ts
types/instance.d.ts
types/logger.d.ts
types/reply.d.ts

- Adds back definitions that were inadvertently removed in https://github.com/fastify/fastify/pull/1569
- Adds tests for server-option definitions
- Updates server-option definitions to match code and docs in master
- Fixes an error message for AJV plugin options 
- Adds a new `FastifyLoggerInstance` type 
- Removes `FastifyLoggerInstance` methods from `FastifyLoggerOptions`

Update TypeScript type definitions for server options

---

docs/TypeScript.md
fastify.d.ts
package.json
test/types/fastify.test-d.ts
test/types/logger.test-d.ts
types/hooks.d.ts
types/instance.d.ts
types/logger.d.ts
types/register.d.ts
types/request.d.ts
types/route.d.ts

Fix logger typings (per discussion in #2289)
- log() method of FastifyInstance and FastifyRequest now has correct type
- external logger is now checked for conformance to FastifyLoggerInstance interface
- adjust FastifyLoggerInstance to be compatible with pino.Logger
- logger type is now propagated to builder method declarations (addHook etc)
- add tests for external pino instance
- adjust custom logger test (it hasn't been conforming to FastifyLoggerInstance)
- update tests and add a couple of new ones
- update docs
Please see individual commits for more details.

TypeScript: fix logger typings #2289

---

docs/Server.md
fastify.d.ts
fastify.js
test/request-error.test.js

Bind error handler to instance (v2)

---

docs/Ecosystem.md

Updated `Ecosystem.md` to mention fastify-supporting plugin that fills an API-first validation gap.
Moved another plugin to ensure alphabetical order for all the entries.

Add openapi-validator-middleware plugin to the ecosystem docs

---

docs/TypeScript.md

Fixing typo incorrectly pointing at FastifytRegisterOptions found during doc search

docs: Fixing typo pointing at FastifytRegisterOptions

---

test/types/instance.test-d.ts
types/instance.d.ts

feat: specify this context for setErrorHandler

---

lib/hooks.js
test/hooks.on-ready.test.js

This test was failing in v3: the order was reverted

fix ready order execution

---

test/types/instance.test-d.ts
types/instance.d.ts

This change allows use of `Fastify.prototype.use` as is or with custom type augmentations.

Allow TS type augmentation for Fastify.prototype.use

---

fastify.d.ts
test/types/index.ts

fixes #2343
note: the current `ready` function was added by 655f28fcc36679b4538e0120eecb1f5524325298 that mentions a backport.
I adjusted the d.ts to match the implementation by removing 2 overloads, but I also had to remove corresponding tests.
you should check that 655f28fcc36679b4538e0120eecb1f5524325298 didn't break other runtime stuff

correct typings for ready()

---

docs/Validation-and-Serialization.md

Hello,
I propose this documentation change so as it is explicit `body` validation also happens during `PATCH` requests.

Add `PATCH` to `body` validation

---

test/internals/reply.test.js

In response to a short conversation on #2309 I have added a test for ND-JSON, a content type that has `json` in it's media type but should not be treated as JSON for serialization.

add test to verify ND-JSON content is not serialized as JSON

---

docs/Getting-Started.md

updated Getting-Started.md - added more detail making the process easier to understand

---

package.json
test/validation-error-handling.test.js

Due the security release of fast-json-stringify, the CI is always red

fix test per security release

---

docs/TypeScript.md
fastify.d.ts
test/types/reply.test-d.ts
test/types/request.test-d.ts
types/content-type-parser.d.ts
types/hooks.d.ts
types/instance.d.ts
types/logger.d.ts
types/plugin.d.ts
types/reply.d.ts
types/request.d.ts
types/route.d.ts
types/utils.d.ts

Fixes #2367. Follow https://github.com/fastify/fastify/blob/master/types/instance.d.ts#L65 where `RequestGeneric extends RequestGenericInterface = RequestGenericInterface` is the first generic parameter

Reorder generic parameter of FastifyRequest for ease of use

---

docs/Middleware.md

This PR fixes typo from Alternativies to Alternatives in Middleware document.

fix(typo) Correct typo: Alternativies to Alternatives

---

fastify.d.ts
test/types/plugin.test-d.ts
types/plugin.d.ts
types/register.d.ts

I usually write TS with [no-misused-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md) rule on since it provides such benefits as prohibiting passing `async` function where it is not expected (i.e. event listener on `EventEmitter` etc.)
The `fastify.register` didn't have a correct overload for a plugin function that returns a promise therefore that rule failed even though such use-case is supported.
This adds an overload to `FastifyPlugin` that returns a Promise, therefore, telling TS that `register` can handle such functions.
Unfortunately, I couldn't get TS to properly infer types for async versions of functions, therefore a need to explicitly specify type. Furthermore, since the type was explicitly …

add Promise version overload for FastifyPlugin

---

test/types/plugin.test-d.ts
types/plugin.d.ts

Hi all,
Here's a pull request for fixing this issue: https://github.com/fastify/help/issues/215
Test reports are shown below:
Please point out if there are any other issues related to this PR that I need to fix, or please review and approve it. Thanks!
Regards,
Jackson Hu

Fix a wrong TypeScript typing issue at register() function

---

test/types/instance.test-d.ts
types/instance.d.ts

Add missing type

---

lib/errors.js
lib/server.js
test/close.test.js

Fix https://github.com/fastify/fastify/issues/2411

reopened server show more detail error msg

---

fastify.js
lib/request.js
lib/route.js
test/internals/handleRequest.test.js
test/internals/request.test.js

In this PR I'm moving `ip`, `ips` and `hostname` to be getters instead of fields on the request as suggested my @mcollina in https://github.com/fastify/fastify/issues/2416
As part of that I extracted the tests on the request object from `handleRequest.test.js`, moved them to their own file and expanded them.
I've run the benchmarks and I can't see any significant change.

Move ip, ips and hostname to getters in request

---

fastify.js
test/inject.test.js

FIx https://github.com/fastify/fastify/issues/2344.

inject function return normal value with non-ready app

---

test/types/request.test-d.ts
types/request.d.ts

closes #2409 
There isn't any specific `validationError` object to create an interface from (or I missed it, and I'd be happy if you show me). Therefore I made it a generic record that contains the errors from `validation.js`.
The documentation also specifies the object as `validationErrors`, but I couldn't find a use for this property in the code (Is the scope of this PR to change the docs and the implementation?) .

Added validationError property to request

---

fastify.js
lib/fourOhFour.js
lib/request.js
lib/route.js
test/internals/contentTypeParser.test.js
test/internals/request.test.js

This is a follow up to https://github.com/fastify/fastify/pull/2418 where I also move headers to be a getter on Request.
As for that PR I'm not seeing consistently better performance on my machine, but I guess it's worth investigating on the dedicated one.

Move headers to be a getter on Request

---

fastify.d.ts
test/types/fastify.test-d.ts
test/types/plugin.test-d.ts

As far as Fastify implements `then()` method it can be marked as PromiseLike
Closes #2378

feat: make fastify() PromiseLike

---

test/types/instance.test-d.ts
types/instance.d.ts

this typings present in Fastify v2 and disappeared in Fastify v3

typings: add getSchema and getSchemas

---

fastify.d.ts
test/types/instance.test-d.ts
types/instance.d.ts

Improve server types

---

docs/Hooks.md
lib/route.js
test/hooks.test.js
test/types/hooks.test-d.ts
types/hooks.d.ts

In the onRoute hook, the argument has two key with the same value.
I think this was not the intended behaviour
cc @delvedor 
Ref https://github.com/Eomm/fastify-405/pull/25

add routePath in onRoute hook

---

lib/symbols.js
test/internals/validation.test.js

In schemas.js use the kSchemaVisited symbol var , while symbols.js not find it. 
https://github.com/fastify/fastify/blob/283a1bde631645dc65b6499a29b16ccb95c89823/lib/schemas.js#L4

add missing kSchemaVisited symbol var

---

lib/route.js
lib/schemas.js
test/schema-feature.test.js
test/schema-serialization.test.js

Fix #2462 
The issue:
the first route of a context trigger the creation of the default schema validator, then all the children will use the same so ajv is instantiated only once.
This PR adds a check that, if the validator is not customized by the user, the validator will be recreated every time the user changes the schemas in the fastify instance.

fix schema lock in

---

docs/Getting-Started.md

The first example has this option and I think the async/await example should have it as well.
Adding `logger` option to the `async`/`await` example:
> Do you prefer to use `async/await`? Fastify supports it out-of-the-box.<be>
> *(We also suggest using [make-promises-safe](https://github.com/mcollina/make-promises-safe) to avoid file descriptor > > and memory leaks.)*
> ```js
> const fastify = require('fastify')({
>   logger: true
> })
The first example I mentioned:
>### Your first server
> Let's write our first server:
> ```js
> // Require the framework and instantiate it
> const fastify = require('fastify')({
>   logger: true
> })

docs: add logger option in async/await example

---

docs/Hooks.md
lib/context.js
lib/hooks.js
lib/route.js
test/hooks.test.js
test/types/hooks.test-d.ts
types/hooks.d.ts
types/instance.d.ts
types/route.d.ts

Fixes: https://github.com/fastify/fastify/issues/2203
This is set as draft for now because no documentation neither tests have been properly written. Wanted to have feedback on the implementation.
In the end the use of it will be:
```js
fastify.addHook('onTimeout', (request, reply, done) => {
console.log('Hook Timeout')
done()
})
```
But in here the reply can't be mutated because the socket has already hanged-up. Any opinion on this?

feat: add hook onTimeout

---

README.md
package.json

Hey everyone!
I follow [this](https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md#onboarding-collaborators) document, but I checked some issues and sounds like have new requisites to add a member. So, if have something to do, or waiting for a while, let me know, please.
Based on the same document, I would like to join at `@fastify/core` + `@fastify/benchmarks` because makes sense to my actual work.

update(package.json): add rafaelgss as member

---

lib/contentTypeParser.js
package.json
test/content-parser.test.js

Hi,
this pull request lets `hasContentTypeParser` return true for native types  ('application/json' and 'text/plain') as discussed in https://github.com/fastify/fastify/issues/2448 .
+ Behavior now matches [Documentation](https://www.fastify.io/docs/latest/ContentTypeParser/#usage)
+ Unit test to confirm new behavior included.
+ Changes are not in the hot path.
Kind regards,
Hans

fix hasContentTypeParser to include native types

---

package.json
test/close-pipelining.test.js

fix: #2470 
```
$ npx tap -J test/close-*.test.js
PASS  test/close-pipelining.test.js 24 OK 15s
```
Looking at the doc, specifying `jobs` property seems to fix the issue : https://node-tap.org/docs/api/parallel-tests/#parallel-tests-from-the-api
Validated on my machine on W10

fix: test slowness on windows

---

test/types/hooks.test-d.ts
types/hooks.d.ts

fix: typings for hooks

---

.npmignore

As mentionned in https://github.com/fastify/help/issues/243
Deleting azure pipelines references in npmignore

feat: delete non existent files references

---

package.json

As suggested in the [ESM](https://nodejs.org/api/esm.html#esm_package_json_type_field) guidelines of nodejs it would be good to explicit the `type` of the module.

Add type commonjs

---

test/types/dummy-plugin.ts
test/types/plugin.test-d.ts
types/register.d.ts

Fixes: https://github.com/fastify/fastify/issues/2403
The issue was because dynamic import in Typescript always imports an object that have `.default` property instead of assigning the default export to "top" level. In fact the compiler outputs this JS
```js
fastify.register(Promise.resolve().then(() => __importStar(require("fastify-formbody"))));
```
for this ts
```ts
fastify.register(import("fastify-formbody"));
```
It compiles it like this because `import()` is implemented `using require()` and promises.
This PR works thanks to https://github.com/fastify/avvio/blob/76f83492819c0cbc64e6a255e92df11fe4f094fb/plugin.js#L245 that works if an object with `.default` property is passed.

Adds support for plugin dynamic imports in TS projects

---

docs/Hooks.md

Minor doc change: I noticed that the "Scope" and "Route level hooks" sections of the Hooks documentation were not linked in the ToC.

doc: add scope & route level to Hooks ToC

---

docs/Ecosystem.md

I did a mistake and put the `fastify-guard` plugin in the core plugin list. Sorry about that.
See: https://github.com/fastify/fastify/pull/2524

fix for fastify-guard plugin position

---

docs/Plugins.md

trivial typo f.e -> i.e
```
by a preceding plugin i.e. utilizing an existing database
```
sincere thanks for the great docs, I am reading through a second time now.
( read the contributing.md file and agree to it )

docs: Plugins.md

---

docs/Ecosystem.md

removed duplicated `fastify-guard` fix

remove: duplicated fastify-guard plugin

---

test/types/reply.test-d.ts
types/reply.d.ts
types/route.d.ts

Fix for https://github.com/fastify/fastify/issues/2529
This PR adds proper type tests for the`handler` and the `reply` types.
~At the moment, this PR fixes only one of the two problems pointed in that issue: the return type for the handler function.~
Both bugs are fixed.
~We still need a proper fix for the `send` method because this [line](https://github.com/fastify/fastify/blob/master/types/reply.d.ts#L30) isn't working: default `RouteGeneric['Reply']` value is never used, even if the `send` generic is not passed.~
I think this might be a TypeScript limitation and we need to find a better definition for this case. In my opinion, we don't even need that generic and we could write it like: `send(payload?: RouteGeneric['Reply']): FastifyReply<RawServer, RawRequest, RawReply, RouteGeneric, …

Passes generic to RouteHandler return type

---

docs/Ecosystem.md

:wave: as discussed here https://github.com/fastify/fastify-oauth2/issues/20#issuecomment-685764095 I'm adding [Grant](https://github.com/simov/grant) to the list of available plugins for Fastify.
Grant is an OAuth authentication/authorization plugin that supports both OAuth 2.0 and OAuth 1.0a providers, currently around 200+ that were tested officially, but any other provider implementing the OAuth spec can be configured to work with the plugin.
Grant relies on session to persist state during the OAuth flow:
```js
var fastify = require('fastify')
var cookie = require('fastify-cookie')
var session = require('fastify-session')
var grant = require('fastify-grant')
fastify()
.register(cookie)
.register(session, {secret: 'grant', cookie: {secure: false}})
.register(grant({/*configuration - …
```

Add Grant to the ecosystem of plugins

---

lib/reply.js
test/content-length.test.js

Fixes: #2543 
~I'm not totally sure that's the best approach to it because override the content-length if has one. Otherwise, what reasons to sent a custom `content-type` from handlers?~

Fix content length

---

fastify.d.ts
test/types/fastify.test-d.ts

These were accidentally removed in https://github.com/fastify/fastify/pull/2554
Also adds tests to make sure these Types are exported.

fix: fastify plugin types exports

---

docs/Decorators.md

Rationale behind this change: I'm seeing our developers instantiating decorated object fields with `''` because that's what they are seeing in current documentation, and I believe that defeats the whole point of avoiding the deoptimization.
Now I'm not sure if changing from null to object also causes deoptimization, but that's what I remember being instructed to use for dynamically set objects by @mcollina. If that doesn't help with deoptimization at all, and is just cleaner, I'd be happy to reword the documentation. Alternatively, would it be a better idea to instantiate such fields as `{}`?

Provide additional clarification for decorated fields

---

docs/Ecosystem.md

Hello everyone,
We are using Fastify for the microservice edge-gateway solution in ShopBack. Our system usually has a spike in traffic so we need to reduce the workload for downstream services, as well as prevent redundant operations. Then, we developed a plugin for caching the response and preventing the gateway to fire the same request at the spike time.
We think it is worth sharing this plugin with the Fastify community and we can together improve this.
Thanks.

Add fastify-response-caching to ecosystem

---

test/types/logger.test-d.ts
types/logger.d.ts

The `FastifyLoggerOptions` interface is missing a type definition for the `prettyPrint` option which `pino` supports when `pino-pretty` is installed.  The latest general [Logging docs](https://www.fastify.io/docs/latest/Logging/) already reference the `prettyPrint` option however without the type definition an error is shown when using TypeScript and passing the option to the logger when creating the Fastify instance. 

Add prettyPrint option to logger type definitions

---

docs/Reply.md
docs/TypeScript.md
fastify.d.ts
package.json
test/types/decorate-request-reply.test-d.ts

Fixes #2557 
Wasn't sure how we feel about shipping @types/node. I listed it as a peer dep instead. Our type definitions do actually depend on it so I'm not sure if it should be a proper dependency or not. The reason this sorta goes unnoticed is whenever a dev creates a TS + Node project its second nature to just `npm i -D typescript @types/node`. I'm assuming by listing this as a peer dep is at least another way to indicate to our TS users they need to install node types in order to use our types.

Improve dec merging dev experience

---

docs/Request.md
docs/Server.md
lib/request.js
test/http2/secure.test.js
test/https/https.test.js
test/trust-proxy.test.js
types/request.d.ts

Hey,
one thing I missed in fastify was a way to easily determine whether the used protocol is `http` or `https`.
So I added that feature analogous to `ip` and `hostname` with the `X-Forwarded-Proto`-header.

Added Attribute 'protocol' to Request

---

examples/simple.mjs
fastify.js
test/esm/index.test.js
test/esm/named-exports.mjs

Support for named export in Node v14.13.0

---

fastify.d.ts

Reverting `export *` syntax because it is breaking module augmentation for `FastifyReply`
For example, the following code fails:
```
import fastify from 'fastify';
declare module 'fastify' {
interface FastifyReply {
hello: string;
}
}
const server = fastfiy();
server.decorateReply('hello', 'world');
server.get('/hello', async (request, reply) => {
reply.send(reply.hello);
})
```
with error: `Property 'hello' does not exist on type 'FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.`
And after applying the fix, the code works as expected and returns `world`.

Reverting `export *` syntax

---

docs/Hooks.md
docs/Lifecycle.md

update document based on #2561 forward error to reply.send() instead of done() onRequest and preHandler from adding a hook. Please review, Thanks!

forward error to reply.send() instead of done() onRequest and preHandler

---

docs/Logging.md
docs/Request.md
docs/Routes.md
lib/logger.js
lib/request.js
lib/warnings.js
package.json
test/internals/request.test.js
test/logger.test.js
test/types/request.test-d.ts
types/request.d.ts

This fixes #2575, switching to use `request.socket` over the [deprecated `request.connection`](https://nodejs.org/api/http.html#http_request_connection).  It relies on https://github.com/fastify/light-my-request/pull/99, and updates `light-my-request` to 4.1.0.  I've also updated `request.test.js` to provide the required `socket` and/or `connection` properties as necessary.

Deprecated API usage (#2575)

---

fastify.js
test/internals/version.test.js
types/instance.d.ts

Fix: https://github.com/fastify/fastify/issues/2603
as discussed in https://github.com/fastify/fastify/pull/2604
edit: switching to conditional loading like mentioned in : https://github.com/fastify/fastify/pull/2605#issuecomment-704896395

feat: add conditional load of version

---

test/types/instance.test-d.ts
types/instance.d.ts

As discussed in https://github.com/fastify/fastify-express/pull/7, it's currently not possible to overload the `use` from here with a properly typed one. I _think_ just removing `use` from core makes sense since it'll throw an error during runtime anyways, but I might be wrong.

fix: remove `.use` from types

---

test/emit-warning.test.js

Missing test, helps with https://github.com/fastify/fastify/issues/2381

warning test on deprecate request.connection usage

---

test/types/register.test-d.ts
types/register.d.ts

test(types): add register test type

---

docs/Reply.md

This fixes the issue in #2633 of the the contents not the same link as the anchor for redirect.
It also standardizes everything to `.redirect)[code ,] dest)`.

Fix anchor and make standardize refs to redirect

---

docs/Hooks.md

As per issue #2639, this PR removes empty/redundant `return` lines at the end of several Hooks examples.

Removed empty 'return' lines at the end of Hooks examples

---

docs/Routes.md

The markdown file was renamed, causing the reference to result in a 404 error, and the referenced anchor doesn't exist either.

Fix reference to pino logLevel in docs

---

test/types/route.test-d.ts
types/route.d.ts

Ran into the `prefixTrailingSlash` option for a route having an incorrect type definition. The type definition erroneously said that it's supposed to be a `boolean`, but it's supposed to be one of `'slash'|'no-slash'|'both'`.

Fix defined type for route option "prefixTrailingSlash"

---

docs/Request.md
docs/Server.md
lib/request.js
test/internals/request.test.js

We're runnning our fastify server on **Azure Linux Web Apps** behind **Akamai** that (for some reason) adds 2 `x-forwarded-host` headers resulting in `request.hostname` to appear as `"host.com, host.com"` - which certainly feels incorrect.
In our own code we've handled this in a plugin prior to using `request.hostname` - but we felt the issue should be addressed here 😄 
This PR simply handles `x-forwarded-host` in the same fashion that `x-forwarded-proto` already is when `trustProxy` is `true`.

treat x-forwarded-host headers as x-forwarded-proto

---

docs/TypeScript.md

When a list item has more than one line, the subsequent lines after the first one should begin in the same column that the first line content began.
Example:
This is a very subtle/minimal change, but the way it was before can lead to users copying code from the documentation and having to re-adjust it. This may cause friction for the user, since he/she may not be happy by just copying and pasting the examples.
There are 2 examples taken from https://www.fastify.io/docs/latest/TypeScript:
- In this example for an under-indented markdown list item, it leads to the first indentation level being 1 space instead of 2 spaces:
- In this example for an over-indented markdown list item, all the lines have 1 extra space in the beginning of the line:
---
Edit: I built and ran the [website …

Fix Markdown list alignment

---

docs/Errors.md
fastify.js
lib/reply.js
lib/setErrorHeaders.js
test/reply-error.test.js
test/route-hooks.test.js

Seems like the fix suggested in #2602 did not change the behavior accurately. I added an extra isDefaultErrorHandler attribute to Context and checked for it before setting headers. 

Checked if error handler is default before setting headers

---

docs/Decorators.md
lib/decorate.js
lib/warnings.js
test/decorator.test.js

Like mentioned in https://github.com/fastify/fastify/issues/2598 . Emitting warning on `object` properties on `decorate`

feat: add warning on decorate

---

docs/Server.md
docs/Validation-and-Serialization.md
fastify.js
test/validation-error-handling.test.js

The `schemaErrorFormatter` function was not binded to the fastify instance and this may confuse the user that starts to be habit to have always the `this` like in hooks or `errorHandler` etc.
- [c] run `npm run test` and `npm run benchmark`

Schema error formatter bind to fastify instance

---

docs/Lifecycle.md

Improve #2687 
This PR add a "reply lifecycle" that aims to explain what is happening when devs write `reply.send(<something>)`.
The stars 🌟 would like to emphasize the possible entry point to this flow

docs: add reply lifecycle

---

docs/Decorators.md

Git is timestamped. One knows when a link was added. One can always go back and add an archive.org link later. Someone might even create and share a GitHub Action or something for it if there's a major need for it. Pre-emptively linking to archive.org is just rude.
Sure domain names doesn't live forever and people can by them own kill URL:s if they like to, but that's what the current world wide web delivers.
If one has a problem with that, then one can push towards eg. https://ipfs.io/, but lets not do it like this?
Also, a domain owner can always request retroactive removal from archive.org, so that URL sure can become invalid as well.
Twitter discussion: https://twitter.com/mathias/status/1331666134807048193

Politely link to source rather than archive.org

---

lib/hooks.js
test/hooks-async.test.js

Fixes #2707 and adds a test for the edge case

test async preSerialization with a failed response schema

---

test/types/instance.test-d.ts
types/instance.d.ts

Fixes https://github.com/fastify/fastify/issues/2711
_Please check the update carefully as I'm not so good at writing types_ 😅 

fix(2711): expose instance.errorHandler in types

---

docs/Ecosystem.md

Hello all!
I have renamed my plugin `fastify-errors-properties` to `fastify-http-errors-enhanced`.
This PR updates the ecosystem to match the new name.

Track renaming of fastify-errors-properties

---

fastify.d.ts
test/types/fastify.test-d.ts

Change the value type from return object of querystringParser to unknown.
Why: 
With the current definition it is not possible to return nested queries when using an external parser (e.g. qs).
Since the type of the return value is not important at this point, the `unknown` type can be used.
Example:
```typescript
type QuerystringParserOld = (str: string) => { [key: string]: string | string[] },
type QuerystringParserNew = (str: string) => { [key: string]: unknown },
// URL: /api?foo[a]=bar&foo[b]=fuzz&foo[c]=buzz
// is parsed into the following object:
const queryOld: ReturnType<QuerystringParserOld> = { foo: { a: 'bar', b: 'fuzz', c: 'buzz' } };
const queryNew: ReturnType<QuerystringParserNew> = { foo: { a: 'bar', b: 'fuzz', c: 'buzz' } };
```
With `queryOld` a type error is thrown and …

Update the type definition of querystringParser

---

docs/Encapsulation.md

A slight language correction to match the actual behavior.

Fix language in encapsulation doc

---

fastify.d.ts

Correct typo in type declaration file: change from 'factor function' to 'factory function'.

Correct typo in type declaration file: factory function

---

lib/hooks.js
lib/route.js
test/hooks.test.js
test/internals/hookRunner.test.js

fixes the issue described in #2692 

fix: throw in `onSend` causes fastify to not respond

---

docs/Fluent-Schema.md

Pluralise so we wont get a ReferenceError in the `bodyJsonSchema` code...(line 27)

Correct very small typo

---

GOVERNANCE.md
SECURITY.md
docs/Ecosystem.md
docs/Encapsulation.md
docs/Hooks.md
docs/Reply.md
docs/Server.md
docs/TypeScript.md

Fixed typos in several `md` files

docs: fix a few typos

---

package.json
test/http2/closing.test.js

There is not need of this polyfill module since the minimum node.js version supported by fastify is 10.16.x that has this feature included.

chore: remove events.once devDependencies

---

docs/TypeScript.md
fastify.js
test/404s.test.js
test/async-await.test.js
test/decorator.test.js
test/hooks-async.test.js
test/hooks.test.js
test/logger.test.js
test/plugin.test.js
test/types/instance.test-d.ts
test/validation-error-handling.test.js
test/versioned-routes.test.js
types/content-type-parser.d.ts

Corrected method names in documentation and fix a few typos.

Correct method names in documentation and fix a few typos

---

CONTRIBUTING.md
README.md
docs/ContentTypeParser.md
docs/Ecosystem.md
docs/Getting-Started.md
docs/Routes.md
docs/TypeScript.md
docs/Validation-and-Serialization.md
docs/Write-Plugin.md

Upgraded all `http` links to `https` that support the `https` protocol.
<details>
<summary>All upgraded links</summary>
Links
---
https://standardjs.com
https://json-schema.org
https://nearform.com
https://semver.org
https://bookshelfjs.org
https://lorenwest.github.io/node-config
https://nats.io
https://getpino.io/#/
https://npm.im/ajv
https://npm.im/fast-json-stringify
https://www.node-tap.org/
</details>

docs: upgrade all http links to https

---

fastify.d.ts
package.json
test/types/instance.test-d.ts

This is blocked until fastify-error module is updated (https://github.com/fastify/fastify-error/pull/9)

move validation type to core

---

lib/server.js
test/http2/closing.test.js

I guess when the graceful closing for http2 was [added](https://github.com/fastify/fastify/commit/d0c976e82549488ecd27c17421cd3b51264468de#diff-1b48bb429de959672dadab9c87c215e19177dd70e3bd932d131ce74294c44cd5R27), it was simply forgotten to add this line for https too.

Added (probably) missing line for http2 server

---

docs/Ecosystem.md

Hi!
I have created two new plugins, `fastify-openapi-docs` and `fastify-print-routes` that I would like to be listed in the Ecosystem page.
This PR adds them to the list.

Add fastify-openapi-docs and fastify-print-routes to the Ecosystem.

---

lib/wrapThenable.js
test/async-await.test.js

This is a fix for issue https://github.com/fastify/fastify/issues/2653
Test is a bit of copy-pasta, I'm not sure I understand exactly how it works so let me know if I should change anything, this is my first contribution. I'm also unsure how to interpret the output of the benchmark tests, let me know if there's a problem 🙃 

Do not trigger errorHandler when reply.sent === true (async handlers)

---

lib/reply.js
test/internals/reply.test.js

add support for running preSerialization hooks for custom reply serializers

---

lib/pluginUtils.js
test/plugin.test.js

Fixes #2760
The PR introduces now the name of the plugin that requests a specific decorator which is not available at the moment of registering the plugin. For now, only appends the name in the case that name exists.
For plugins that don't provide a name, the name cannot be printed. Assuming that the usage of the fastify-plugin is kinda mandatory, this shouldn't be an issue as it provides an auto-generated plugin name in case none is provided. In case this is not used, we depend on the handmade implementation by the developer.
We can always rely on the `name` property of the `Function` object but don't know how deep we want to go in that direction.
Any feedback is more than welcome!

feat: Add hint of which plugin is requesting specific decorator

---

lib/route.js
test/hooks.test.js
test/route-prefix.test.js
test/route.test.js

Alternative fix for https://github.com/fastify/fastify/issues/2767
Approach explained in https://github.com/fastify/fastify/issues/2767#issuecomment-755499855 

fix(2767): prevent calling onRoute while prefixing

---

lib/route.js
test/route.test.js

Unfortunately we where emitting a warning even if the `HEAD` route was defined.

avoid warning with exposeHeadRoute route option

---

docs/Ecosystem.md

Hi 👋🏻 ,
I would like to propose another plugin to add to the ecosystem (if you find it useful). It's a small wrapper for sampling process metrics like `cpu`, `eventLoopUtilization`, and so on. Its aim is to simplify the implementation of a custom reporter for health metrics.

Add fastify-doc plugin to ecosystem

---

lib/route.js
test/route.test.js

This PR fixes #2788, when `prefixTrailingSlash` is set to `'both'` fastify will generate two routes, one that has a trailing slash and the prefix and the other without the trailing slash it will also auto generate generate `HEAD` routes (if `exposeHeadRoute` is set to `true`) for both of the new endpoints which was the primary source of the duplication bug, setting `exposeHeadRoute` to `false` when attempting to add the second route seems to fix this issue.
if `prefixTrailingSlash` is set to `'no-slash'` then fastify will create a `GET` route and (if `exposeHeadRoute` is set to `true`) fastify will generate one `HEAD` route however it actually create a route where the prefix is concatenated twice, …

Fix(2788): by preventing invalid route creation

---

lib/route.js
test/context-config.test.js

If `exposeHeadRoutes` is set to `true` (introduced in https://github.com/fastify/fastify/pull/2700), the route `config` property will be wrongly altered. This PR fixes it.
I've discovered this when working on #2826.

Create shallow copy of the route context config

---

build/build-validation.js
docs/Server.md
fastify.js
lib/configValidator.js
test/context-config.test.js
test/hooks-async.test.js
test/hooks.test.js
test/internals/initialConfig.test.js
test/pretty-print.test.js
test/route-prefix.test.js
test/route.test.js
test/schema-feature.test.js
test/schema-serialization.test.js

Set exposeHeadRoutes: true by default

---

docs/Reply.md

In https://www.fastify.io/docs/latest/Reply/#raw we have a link that looks like:
This PR changes it to:

Docs: Fixes link preview to Reply

---

docs/Encapsulation.md

Encapsulation documentation uses decorators (`foo`, `bar`) that are available on different levels but uses all of these at these different levels.

docs: Fix encapsulation decorators example

---

test/types/reply.test-d.ts
types/reply.d.ts

fix reply.d.ts missing hijack funciton

fix: reply.d.ts missing hijack function

---

CODE_OF_CONDUCT.md

Brings Fastify's Code of Conduct into line with the [OpenJS Foundation's Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md).

docs(coc): bump from 1.4 to 2.0

---

docs/Server.md
test/types/instance.test-d.ts
types/instance.d.ts

`initialConfig` is missing from the `FastifyInstance` type.  The docs are also updated to list all of the fields available in `initialConfig`.
- [x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)

feat: add initialConfig to FastifyInstance

---

docs/Reply.md
test/internals/reply.test.js
test/types/reply.test-d.ts
types/reply.d.ts

I didn't change `FST_ERR_PROMISE_NOT_FULLFILLED`, assuming that'd be semver-major.

Fix promise parameter name

---

lib/reqIdGenFactory.js

Prefix the request id with a `req-` string and convert the auto incremented request id (of type number) to string using the base of 36.
✅ Closes: #2736

feat: Convert request id to string of base 36 and prefix it with `req-`

---

docs/Errors.md

Creating this as a draft first, as I had a quick question: is it worth converting the list of errors into a table composed of  `code` and `description` column headers? It would compress the data into an easier to reference format.

docs(errors): sort error list alphabetically ascending

---

docs/Style-Guide.md

docs(style-guide): add section regarding contraction usage; grammar fixes

---

build/build-validation.js
docs/Routes.md
docs/Server.md
fastify.d.ts
fastify.js
lib/configValidator.js
lib/route.js
lib/warnings.js
package.json
test/constrained-routes.test.js
test/internals/initialConfig.test.js
test/throw.test.js
test/types/fastify.test-d.ts
test/versioned-routes.test.js
types/route.d.ts

Closes https://github.com/fastify/fastify/issues/2498
This is the fastify side of https://github.com/delvedor/find-my-way/pull/170 which adds support for constraining routes to certain hostnames or using custom constraining strategies. 
It would need those bits of `find-my-way` to be merged and released before really being ready, but I'm opening this now for transparency and so anyone who wants to test can do so! Woop woop! 
No need to review quite yet, but if you want to use this feature, I'd love any help testing in your apps! To test, you'll have to import that branch of `find-my-way`, as well as this branch of `fastify`. `npm link` worked for me to do this.

Add support for constrained routes from newer find-my-way

---

docs/Routes.md

As #2682 landed to master Fastify uses [find-my-way@4.0.0](https://github.com/delvedor/find-my-way/releases/tag/v4.0.0) which now has support for path with colons. This PR add small note to docs regarding paths with colons

Docs: Add note about colon in path

---

docs/Request.md
docs/Server.md

add a docs tips to `ips` since it is not so seamless to find out (look the code, check per `proxyAddr.all`)

docs: ips order detail

---

docs/ContentTypeParser.md
lib/contentTypeParser.js
lib/errors.js
test/content-parser.test.js
test/custom-parser.test.js
types/content-type-parser.d.ts

Closes #2885.
Create the possibility to provide a RegExp to the `addContentTypeParser` API.
```js
fastify.addContentTypeParser(/^image\/.*/, function (request, payload, done) {
imageParser(payload, function (err, body) {
done(err, body)
})
})
```
In the current implementation, fastify first tries to match a content-type parser with a string value before trying to find a matching RegExp.
Additionally, I updated the documentation to demonstrate the user in which order fastify searches for a matching content type parser.
I can provide benchmark results if necessary.

Regexp support content type parser

---

docs/Server.md
fastify.js
test/pretty-print.test.js
test/types/instance.test-d.ts
types/instance.d.ts

This is useful when debugging require order issues, especially if using something that loads plugins for you like `fastify-autoload`

Expose the avvio pretty printer for printing the plugin tree

---

test/versioned-routes.test.js

Update tests to the newer constrained routes in order to remove warning. #2889 

tests: Update tests to newer constrained routes

---

.github/labeler.yml
.github/workflows/labeler.yml

[Update]:  fixes https://github.com/fastify/fastify/issues/2906
This PR is a partial solution for https://github.com/fastify/fastify/issues/2906
- `documentation` label for PRs touching only the `docs` folder
- `typescript` label for PRs touching only the `types` folder
Outcome: https://github.com/loredanacirstea/fastify/pulls
I tried some approaches for solving `fastify.d.ts`, but none worked. Such as:
- `any: [types/**/*, fastify.d.ts]`
- `./**/*.d.ts` & some other variations; `**/*.d.ts` is unparsable by .yml

Add workflow for labeling PRs by their content

---

lib/reply.js
test/stream.test.js

Currently streams are closed (if it is not closedby itself) only if there is an error in the response.
I think it should always be closed when the response ends.

fix: stream should always be destroyed when response is ended

---

test/types/logger.test-d.ts
types/logger.d.ts

fix: logger argument type

---

docs/Routes.md

docs: delete an extra word

---

test/types/instance.test-d.ts
types/instance.d.ts

This adds the typescript definition for the `setNotFoundHandler` given it supports optional `preHandler` and `preValidation` hooks.
The documentation: https://github.com/fastify/fastify/blob/0af94651ee311f9637bed97ab255b4f5173d5837/docs/Server.md#setnotfoundhandler
The JS code handling the optional hooks: https://github.com/fastify/fastify/blob/0af94651ee311f9637bed97ab255b4f5173d5837/lib/fourOhFour.js#L67

Fix typescript def for the setNotFoundHandler

---

docs/Server.md

If this link was working it seems that the page would have been linking to itself, so I've removed it completely.

Remove broken link from Server documentation

---

lib/reply.js
test/schema-serialization.test.js

fix: catch errors thrown by serializers in the default error handler

---

docs/Hooks.md
test/hooks-async.test.js
test/hooks.test.js

Add an example of `preValidation` usage in the documentation and also add a test for this behavior.
I've noticed that `preSerialization` has a good use-case in our documentation (See [here](https://www.fastify.io/docs/latest/Hooks/#preserialization)) and I think that would be great to have an example in `preValidation` hook as well.

docs: improve preValidation docs

---

docs/Server.md

Since Fastify version 3.14 it is possible to add content-types via a RegExp. I have added this feature to the Server docs.

fix content-type type

---

fastify.d.ts
test/types/content-type-parser.test-d.ts
test/types/instance.test-d.ts
types/content-type-parser.d.ts
types/instance.d.ts

Closes #2930
I have added types for the default json and the default plain text parser. I have also created types for the `onProtoPoisoning` and the `onConstructorPoisoning` options.

add types for default parser

---

docs/Ecosystem.md

Hi,
I've developed a plugin used to authenticate HTTP requests based on api key and signature. I thought that's a good idea to share it with the community.
Note: Sorry for my previous PR [#2957](https://github.com/fastify/fastify/pull/2957), I had a problem with my IDE when I commited then I've prefered to recreate a clean PR... my bad

docs(ecosystem): add fastify-api-key to community plugins

---

test/internals/initialConfig.test.js

do not print the FSTDEP009 warning in test but use assertion

---

lib/schema-compilers.js
test/schema-special-usage.test.js

I have found and fixed a bug in the new schema compilers logic that caused it to throw if the same schema was specified twice with the same id. I went ahead and fixed it.

Fix: schema compiler for schemas with the same ids.

---

docs/LTS.md

This is just a minor documentation fix I noticed while reading through the site.

fix: doc typo, added 'to'.

---

docs/Logging.md

I've added a bit of info on the docs on logging outside of route handlers as there was no example on how to do that.

Added info on logging from outside route handlers

---

docs/Ecosystem.md

Hi,
This PR aims to add `fastify-mailer` and `fastify-stripe` to the community plugin ecosystem list.
Regards.

Add fastify-mailer and fastify-stripe to the community ecosystem list.

---

docs/Server.md

Amended `printRoutes` documentation to reflect the `prettyPrint({ commonPrefix: false })` updates in `find-my-way`

adding reference to commonPrefix option in printRoutes documentation

---

SECURITY.md

I have updated the SECURITY.md to point to our brand new program: https://hackerone.com/fastify.

Point our SECURITY.md to the new hackerone program

---

docs/Ecosystem.md

docs: add fastify-hasura

---

test/types/instance.test-d.ts

Ref #3017 
I removed the assertion since it does not seem useful, `FastifyError` is an interface and in the test are being called as a function. 
@Ethan-Arrowood I'm asking review for you since you've implemented it a long time ago.

fix: remove invalid assertion

---

.taprc
test/build-certificate.js
test/http2/closing.test.js
test/http2/secure-with-fallback.test.js
test/http2/secure.test.js
test/https/custom-https-server.test.js
test/https/https.test.js
test/internals/initialConfig.test.js

Resolve: #3029
Duplicated and Closes #3031 
Changes:
- Remove the before script file
- Remove before script from tap
- Run build certificate inside the file it needed

test: move build certificate to the file it need only

---

README.md

Currently the examples show how to write a simple server but also leads to a double log because of this line : https://github.com/fastify/fastify/blob/ba43b314b156b39732dc614826806d4ef61700b8/lib/server.js#L130
and this snippet:
```js
fastify.listen(3000, (err, address) => {
if (err) throw err
fastify.log.info(`server listening on ${address}`) // This will be duplicated
})
```
In a sense it is good to show where to put logs when server starts but at the same time it will be strange as a first developer experience to see dupe log lines. I'm definitely not sure this is the best way to adress this problem but i think we should find a solution for this.

doc: fix example

---

docs/TypeScript.md
test/types/instance.test-d.ts
types/instance.d.ts

Again a quite strong type change, but I think an important one as well for type safety. This would mean that all decorators must be explicitly typed in the interface to go through without `as any` hacks. Looking for comments about this approach

Typed decorators

---

lib/reply.js
test/internals/reply.test.js

fix: https://github.com/fastify/fastify/issues/3030
@matteo said 
> it should be based on the same logic. We can avoid generating the wrapper object.
src: https://github.com/fastify/fastify/issues/3030#issuecomment-825156516
Issue is in a case of a proxyfied reply the nodeJs raw reply still has its own headers so this it's still needed:
https://github.com/fastify/fastify/blob/28febddefce64d91e2618fd14001211130a067ad/lib/reply.js#L204-L209
before:
```
[1] ┌─────────┬──────┬───────┬───────┬───────┬──────────┬─────────┬────────┐
[1] │ Stat    │ 2.5% │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max    │
[1] ├─────────┼──────┼───────┼───────┼───────┼──────────┼─────────┼────────┤
[1] │ Latency │ 7 ms │ 17 ms │ 30 ms │ 56 ms │ 18.04 ms │ 8.17 ms │ 158 ms │
[1] …
```

fix: reply hasHeader behavior

---

docs/Routes.md
docs/Validation-and-Serialization.md

Documentation update

---

lib/route.js
test/route.test.js

This merge is intended to fix the bug #3047.
in case of empty url in route - throw error

Fix: use case when route defined without a url

---

lib/reply.js
test/hooks.test.js

This PR fixes #3057, `onSendEnd` will now set `Content-length` header to the length of the payload if they're not already equal and if the http method isn't `HEAD`.

Fix Content-Length not being updated after onSend hook

---

docs/Routes.md
lib/errors.js
lib/wrapThenable.js
test/async-await.test.js
test/hooks.test.js

1. This is a follow up from https://github.com/fastify/fastify/issues/2664.
2. This PR fixes the following bug:
Using HTTP response codes which do not require body content (beside 204) using promise control flow.
```js
fastify.post('/', async (request, reply) => {
reply.code(202);
});
```
Previously this block would never resolve in case we did not explicitly call reply.send().
3. Changes introduced:
- Documentation states that async handler cannot resolve with "undefined", so fastify can support callback-style control flow. The example that was brought up in the referred issue was the following:
```js
fastify.post('/', async (request, reply) => {
setTimeout(() => {
reply.code(200).send('hello …
```

Allow async handler to resolve with undefined

---

fastify.d.ts
test/types/fastify.test-d.ts

Added the clientErrorHandler option in the fastify server definition, according to the official doc.
This is intended to solve the issue https://github.com/fastify/fastify/issues/3062

add clientErrorHandler in fastify ts definition

---

docs/LTS.md

This PR adds a call out note to the LTS documentation that informs readers of our policy on publishing security releases and how they can avoid automatically installing them.
Bonus: cleans up some line wrapping in the LTS doc.

Note about security releases and LTS

---

test/types/logger.test-d.ts
types/logger.d.ts

This merge is intended to fix the bug https://github.com/fastify/fastify/issues/3026
Now the req and res type in the log serializers are typed respectively FastifyRequest and FastifyReply.

serializer log req and res are now Fastify Objects in type definition

---

lib/reply.js
lib/symbols.js
lib/wrapThenable.js
test/internals/reply.test.js
test/wrapThenable.test.js

This PR simplifies "reply.sent" monitoring; instead of manually setting the kReplySent property all over the package (in more than 10 different places!), it relies on node's response.writableEnded (since fastify supports node versions prior to 12.9.0 which added "writableEnded", reponse.finished is used as a fallback).
When the user sets "reply.sent = true" or uses reply.hijack(), the kReplySentOverwritten property is now used.
You can see that all existing tests (except for one which I had to negligibly modify because it didn't use the proper object) are passing, therefore I believe no changes for the end users were introduced.

Simplify reply sent monitoring

---

examples/benchmark/hooks-benchmark-async-await.js
examples/benchmark/hooks-benchmark.js
examples/benchmark/simple.js

The https://github.com/fastify/fastify/pull/3048 moved the benchmark scripts, but the requires were not adapted to the new path, so they do not work in the current state. This PR fixes these paths.

Fix requires in the benchmark scripts

---

lib/handleRequest.js
lib/reply.js
test/internals/handleRequest.test.js
test/internals/reply.test.js

After another review, I noticed a problem with my previous PR https://github.com/fastify/fastify/pull/3072.
I figured out that when http2 is used and the request method is "HEAD", `response.finished` will be always true (my understanding after reading https://nodejs.org/api/http2.html#http2_response_finished was that it behaves the same way as `response.writableEnded`, since that is suggested as a replacement). This is problematic with Node.js versions prior to 12.9.0 where `response.writableEnded` does not exist.
https://github.com/fastify/fastify/pull/2233 was made to cope with this problem, but it relied on `response.writable`, which by my testing will stay true even after the response has …

Fix simplify reply sent monitoring

---

lib/decorate.js
lib/errors.js
test/decorator.test.js

Throws a meaningful error if a server decorator dependency is specified and it is not an array. The code assumes an array and will fail with misleading errors in case something else is provided.
Also fixes a few assertions in the `decorator.test.js` file where `t.ok` was mistakenly used to do an equality check. Replaced with `t.same`.

feat: error on wrong decorator dependency type

---

examples/simple-stream.js
lib/reply.js
test/hooks.test.js
test/internals/reply.test.js
test/route.test.js
test/stream.test.js

Resolves #3085, resolves fastify/fastify-reply-from#174
Adjusts the handling of response streams so that we no longer apply a default `content-type` header. As discussed on the original issue the current behaviour can cause issues with specific responses e.g. 204 - empty response.
This change will be included in v3 as well behind a option, but wanted to confirm the approach in v4 first. 

Remove content type coercion for response streams

---

docs/Reply.md
docs/Request.md
fastify.js
lib/pluginOverride.js
lib/reply.js
lib/request.js
test/decorator.test.js

This PR implements feature #3094 , which adds a new  `instance` property to the prototypes of the Request/Reply constructors.

Add `instance` property to req/rep prototypes

---

lib/handleRequest.js
lib/reply.js
lib/symbols.js
lib/wrapThenable.js
test/internals/handleRequest.test.js
test/internals/reply.test.js
test/wrapThenable.test.js

Fixes https://github.com/fastify/fastify/issues/3107

Revert sent refactoring

---

docs/Server.md
lib/request.js
package.json

Hi there! :wave:
Fastify has maintained its own fork of the `proxy-addr` module to address an issue in one of its dependencies. That issue has now been resolved in the original package and released in `proxy-addr@2.0.7`.
I mentioned this in https://github.com/fastify/proxy-addr/issues/9, and was asked to submit a PR here to go back to using the original `proxy-addr` package for consideration.
I couldn't find anywhere to put a changelog entry, but maybe the commit message is enough?
Tests all pass:
I verified that several tests fail with `proxy-addr@2.0.6`:
Benchmarks:

chore: go back to the original proxy-addr module instead of @fastify/proxy-addr

---

docs/Errors.md
fastify.js
lib/errors.js
lib/hooks.js
package.json
test/hooks.on-ready.test.js
test/plugin.test.js

Closes #2842
**Note**:
- This PR depends on the next major release of `avvio` until then is pointing out to `fastify/avvio#next` branch for dependency.

feat: Handle new `avvio` error codes

---

fastify.js
lib/fourOhFour.js
test/404s.test.js
test/logger.test.js

fix: handle invalid url

---

docs/Routes.md
test/async-await.test.js
test/hooks-async.test.js
test/hooks.test.js
test/reply-error.test.js
test/route-hooks.test.js
test/skip-reply-send.test.js

After studying the reasoning behind https://github.com/fastify/fastify/issues/3107, I found out that the reply.send() will behave like synchronous method most of the time, but in rare situations it will not fully complete before async function is resolved. Therefore, not awaiting the reply will introduce a race condition. This is already the case in current version, but since marking reply as sent is done manually, it was very hard to notice this problem. Now that the reply is marked as sent only after response is actually sent, such situation can occur more frequently.
I updated the docs to warn users to await (or return) for reply in their async handlers when using reply.send() manually. I also …

Clarification for "Simplify reply sent monitoring (#3072)"

---

docs/Reply.md
lib/reply.js
lib/symbols.js
lib/warnings.js
lib/wrapThenable.js
test/internals/reply.test.js
test/wrapThenable.test.js

This PR deprecates the ability to modify `reply.sent` property directly. Fastify already includes the `reply.hijack()` method that does exactly the same thing. I believe that using a method fits the Nodejs ecosystem much better than modifying the property directly.
Additionally kReplySentOverwritten symbol is renamed to kReplyHijacked to make it more understandable.

Deprecate modifying reply.sent property

---

.github/workflows/benchmark.yml

Finally, we are able to solve: #2497 #2152 #1931.
Sorry to be late with this, I've noticed with a delay the `pull_request_target` feature in GH Actions.
I've created a repository earlier to test the fork permissions and it's working fine:
- https://github.com/RafaelGSS/test-gh-pr-referral/pull/14 (By allowed collaborators)
- https://github.com/RafaelGSS/test-gh-pr-referral/pull/15 (By fork)
Also, I've used my fork of Fastify to test this PR before making this PR:
The above result is when I remove the `response` schema in https://github.com/fastify/fastify/blob/main/examples/benchmark/simple.js#L7. The idea was to have a slow PR to check the divergences.
There is an important note that could be solved later or in this PR:
- We'll run the benchmark in GH action using the free tier, which …

chore: add benchmark workflow to run by label

---

docs/Hooks.md

Just to make it more clear.
`onReady` hooks will execute every time when calling `.ready` and `.listen`

docs: update description for onReady hooks

---

test/types/hooks.test-d.ts
types/hooks.d.ts

TS2683: 'this' implicitly has type 'any' because it does not have a type
annotation.
An outer value of 'this' is shadowed by this container.

fix(types): add missing typings for `this` in encapsulated hooks

---

docs/ContentTypeParser.md

I was having issues with emojis (#3157) and the problem was that I was using `reply.header()` to change my Content-Type without also specifiying UTF-8.

Specify in docs that utf-8 will not be the default if you use your own Content-Type header

---

lib/handleRequest.js
test/reply-error.test.js

Closes #3160 
Sets `reply[kReplyIsError]` to `true` if the  thrown value in the  handler is not an error object.

Fix thrown non-Error values not being treated as errors

---

docs/Hooks.md

I found another place in the docs that needed to be slightly adjusted due to the new way that tracking reply.sent state is handled.

Fix responding from a hook doc

---

test/types/logger.test-d.ts
types/logger.d.ts

I see the discussion about it on #2715 and I think that if `stream` is a valid option in `fastify`. At least, we should make it possible to pass this options without problem.
The types is copy from `@types/pino` currently and I think that it support most of the case and well tested by the wide range of `pino` users.
I look forward to `pino@7`, it seems that it will provide official types and we won't have discrete behavior between Javascript and Typescript users in logger anymore.

chore: add stream type to logger

---

fastify.js

Otherwise, webpack loads the `package.json` of the user's application...
Fixes:
```
Trace: FastifyError [Error]: fastify-plugin: fastify-static - expected
'3.x' fastify version, '4.6.0'* is installed.
* version of user's application
```
Bug: #3110
Refs: #3113
Signed-off-by: Jesse Chan <jc@linux.com>

Use `path.join(__dirname, 'package.json')` to load version

---

docs/Ecosystem.md

My first plugin posted on Ecosystem.
The main different between this and `fastify-multipart` is their dependency.
`fastify-multipart` currently rely on `busboy` which is relatively inactive and it's overall architecture make it hard to integrate with `fastify-swagger`.
This plugin use `formidable` for multipart parsing and provide an easier way to handle files and integration.

docs: add fastify-formdiable

---

fastify.js
lib/pluginUtils.js
test/internals/version.test.js

Reverts fastify/fastify#3113
Apparently this is significantly harder than it looks and there is not a better way to do this that will not break webpack.

Revert "fix: #3110 version resolution"
